fields-on-correct-type.js:43
 43:   fragment unknownSelection on UnknownType { # only error for unknown type
       ^ GraphQL fragment. Type `UnknownType` not found in schema

fields-on-correct-type.js:62
 62:     meowVolume # field not defined
         ^^^^^^^^^^ GraphQL field `meowVolume`. Field not found in type `Dog`

fields-on-correct-type.js:69
 69:     unknown_field { # error only here
         ^^^^^^^^^^^^^ GraphQL field `unknown_field`. Field not found in type `Dog`

fields-on-correct-type.js:79
 79:       unknown_field # field not defined
           ^^^^^^^^^^^^^ GraphQL field `unknown_field`. Field not found in type `Pet`

fields-on-correct-type.js:88
 88:       meowVolume # field not defined
           ^^^^^^^^^^ GraphQL field `meowVolume`. Field not found in type `Dog`

fields-on-correct-type.js:96
 96:     volume : mooVolume # field not defined
                  ^^^^^^^^^ GraphQL field `mooVolume`. Field not found in type `Dog`

fields-on-correct-type.js:103
103:     barkVolume : kawVolume # field not defined
                      ^^^^^^^^^ GraphQL field `kawVolume`. Field not found in type `Dog`

fields-on-correct-type.js:110
110:     tailLength # field not defined
         ^^^^^^^^^^ GraphQL field `tailLength`. Field not found in type `Pet`

fields-on-correct-type.js:117
117:     nickname # field not defined
         ^^^^^^^^ GraphQL field `nickname`. Field not found in type `Pet`

fields-on-correct-type.js:131
131:     directField # direct selection on union
         ^^^^^^^^^^^ GraphQL field `directField`. Selection on union `CatOrDog` can only contain fragment spreads

fields-on-correct-type.js:138
138:     name # direct selection on union
         ^^^^ GraphQL field `name`. Selection on union `CatOrDog` can only contain fragment spreads

fragments-on-composite-types.js:44
 44:   fragment scalarFragment on Boolean { # error
       ^ GraphQL fragment. Fragment cannot condition on non composite type `Boolean`

fragments-on-composite-types.js:51
 51:   fragment scalarFragment on FurColor { # error
       ^ GraphQL fragment. Fragment cannot condition on non composite type `FurColor`

fragments-on-composite-types.js:58
 58:   fragment inputFragment on ComplexInput { # error
       ^ GraphQL fragment. Fragment cannot condition on non composite type `ComplexInput`

fragments-on-composite-types.js:66
 66:     ... on String {
         ^ GraphQL inline fragment. Fragment cannot condition on non composite type `String`

scalar-leafs.js:13
 13:     human # error
         ^^^^^ GraphQL field `human`. Field of object type `Human` requires selection

scalar-leafs.js:20
 20:     human { pets } # error
                 ^^^^ GraphQL field `pets`. Field of object type `Pet` requires selection

scalar-leafs.js:34
 34:     barks { sinceWhen } # error
               ^^^^^^^^^^^^^ Selection set. Cannot select on non-object type `Boolean`

scalar-leafs.js:41
 41:     furColor { inHexdec } # error
                  ^^^^^^^^^^^^ Selection set. Cannot select on non-object type `FurColor`

scalar-leafs.js:48
 48:     doesKnowCommand(dogCommand: SIT) { sinceWhen } # error
                                          ^^^^^^^^^^^^^ Selection set. Cannot select on non-object type `Boolean`

scalar-leafs.js:55
 55:     name @include(if: true) { isAlsoHumanName } # error
                                 ^^^^^^^^^^^^^^^^^^^ Selection set. Cannot select on non-object type `String`

scalar-leafs.js:62
 62:     doesKnowCommand(dogCommand: SIT) @include(if: true) { sinceWhen } # error
                                                             ^^^^^^^^^^^^^ Selection set. Cannot select on non-object type `Boolean`


Found 22 errors
