
A.js:13:19,27: call of method foo
Error:
A.js:13:19,27: string
This type is incompatible with
A.js:13:10,15: number

A.js:21:20,29: string
This type is incompatible with
A.js:21:11,16: number

B.js:7:20,31: call of method foo
Error:
B.js:7:20,31: string
This type is incompatible with
B.js:7:11,16: number

B.js:10:20,22: function call
Error:
A.js:8:25,26: object literal
This type is incompatible with
global object

B.js:10:20,22: function call
Error:
B.js:10:20,22: string
This type is incompatible with
B.js:10:11,16: number

B.js:12:19,29: call of method foo
Error:
B.js:12:19,29: string
This type is incompatible with
B.js:12:10,15: number

non_objects.js:3:1,32: Object.assign
Error:
non_objects.js:3:1,32: prop `a` of object literal
Property cannot be assigned on
non_objects.js:3:15,19: string

non_objects.js:4:1,30: Object.assign
Error:
non_objects.js:4:1,30: prop `a` of object literal
Property cannot be assigned on
non_objects.js:4:15,17: number

non_objects.js:5:1,30: Object.assign
Expected object instead of
non_objects.js:5:27,29: number

Found 9 errors
