// flow-typed signature: 23db36e496d940a846d575a45c31d235
// flow-typed version: <<STUB>>/colors_v1.1.2/flow_v0.54.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'colors'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'colors' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'colors/examples/normal-usage' {
  declare module.exports: any;
}

declare module 'colors/examples/safe-string' {
  declare module.exports: any;
}

declare module 'colors/lib/colors' {
  declare module.exports: any;
}

declare module 'colors/lib/custom/trap' {
  declare module.exports: any;
}

declare module 'colors/lib/custom/zalgo' {
  declare module.exports: any;
}

declare module 'colors/lib/extendStringPrototype' {
  declare module.exports: any;
}

declare module 'colors/lib/index' {
  declare module.exports: any;
}

declare module 'colors/lib/maps/america' {
  declare module.exports: any;
}

declare module 'colors/lib/maps/rainbow' {
  declare module.exports: any;
}

declare module 'colors/lib/maps/random' {
  declare module.exports: any;
}

declare module 'colors/lib/maps/zebra' {
  declare module.exports: any;
}

declare module 'colors/lib/styles' {
  declare module.exports: any;
}

declare module 'colors/lib/system/supports-colors' {
  declare module.exports: any;
}

declare module 'colors/safe' {
  declare module.exports: any;
}

declare module 'colors/themes/generic-logging' {
  declare module.exports: any;
}

// Filename aliases
declare module 'colors/examples/normal-usage.js' {
  declare module.exports: $Exports<'colors/examples/normal-usage'>;
}
declare module 'colors/examples/safe-string.js' {
  declare module.exports: $Exports<'colors/examples/safe-string'>;
}
declare module 'colors/lib/colors.js' {
  declare module.exports: $Exports<'colors/lib/colors'>;
}
declare module 'colors/lib/custom/trap.js' {
  declare module.exports: $Exports<'colors/lib/custom/trap'>;
}
declare module 'colors/lib/custom/zalgo.js' {
  declare module.exports: $Exports<'colors/lib/custom/zalgo'>;
}
declare module 'colors/lib/extendStringPrototype.js' {
  declare module.exports: $Exports<'colors/lib/extendStringPrototype'>;
}
declare module 'colors/lib/index.js' {
  declare module.exports: $Exports<'colors/lib/index'>;
}
declare module 'colors/lib/maps/america.js' {
  declare module.exports: $Exports<'colors/lib/maps/america'>;
}
declare module 'colors/lib/maps/rainbow.js' {
  declare module.exports: $Exports<'colors/lib/maps/rainbow'>;
}
declare module 'colors/lib/maps/random.js' {
  declare module.exports: $Exports<'colors/lib/maps/random'>;
}
declare module 'colors/lib/maps/zebra.js' {
  declare module.exports: $Exports<'colors/lib/maps/zebra'>;
}
declare module 'colors/lib/styles.js' {
  declare module.exports: $Exports<'colors/lib/styles'>;
}
declare module 'colors/lib/system/supports-colors.js' {
  declare module.exports: $Exports<'colors/lib/system/supports-colors'>;
}
declare module 'colors/safe.js' {
  declare module.exports: $Exports<'colors/safe'>;
}
declare module 'colors/themes/generic-logging.js' {
  declare module.exports: $Exports<'colors/themes/generic-logging'>;
}
