// flow-typed signature: 0ecfe69cb754eca0089f2646ebeac556
// flow-typed version: <<STUB>>/flow-remove-types_v^1.2.1/flow_v0.54.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'flow-remove-types'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'flow-remove-types' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'flow-remove-types/register' {
  declare module.exports: any;
}

// Filename aliases
declare module 'flow-remove-types/index' {
  declare module.exports: $Exports<'flow-remove-types'>;
}
declare module 'flow-remove-types/index.js' {
  declare module.exports: $Exports<'flow-remove-types'>;
}
declare module 'flow-remove-types/register.js' {
  declare module.exports: $Exports<'flow-remove-types/register'>;
}
