iter.js:7
  7: for (var k in a) {
                   ^ array literal. The right-hand side of a `for...in` statement must be an object, null or undefined.

iter.js:8
  8:     foo(a[k]);
             ^^^^ access of computed property/element. Element cannot be accessed with
  8:     foo(a[k]);
               ^ string

iter.js:22
 22: for (var n in (d = a)) {
                        ^ array literal. The right-hand side of a `for...in` statement must be an object, null or undefined.

iter.js:23
 23:     foo(d[n]);
             ^^^^ access of computed property/element. Element cannot be accessed with
 23:     foo(d[n]);
               ^ string


Found 4 errors
