
Closure.js:20:1,22: function call
Error:
Closure.js:20:14,21: number
This type is incompatible with
Closure.js:6:25,30: string

Closure.js:38:3,23: function call
Error:
Closure.js:38:16,22: number
This type is incompatible with
Closure.js:6:25,30: string

Closure.js:57:1,22: function call
Error:
Closure.js:57:14,21: number
This type is incompatible with
Closure.js:6:25,30: string

Closure.js:77:3,23: function call
Error:
Closure.js:77:16,22: number
This type is incompatible with
Closure.js:6:25,30: string

cond_havoc.js:12:10,10: string
This type is incompatible with
cond_havoc.js:6:28,33: number

const.js:20:38,42: null
This type is incompatible with
const.js:20:29,34: number

const.js:20:38,42: undefined
This type is incompatible with
const.js:20:29,34: number

const.js:38:38,42: boolean
This type is incompatible with
const.js:38:29,34: number

const.js:38:38,42: string
This type is incompatible with
const.js:38:29,34: number

const.js:40:38,42: boolean
This type is incompatible with
const.js:40:29,34: string

const.js:40:38,42: number
This type is incompatible with
const.js:40:29,34: string

const.js:42:39,43: number
This type is incompatible with
const.js:42:29,35: boolean

const.js:42:39,43: string
This type is incompatible with
const.js:42:29,35: boolean

Found 13 errors
