Error --------------------------------------------------------- Closure.js:20:14

Cannot call `takes_string` with `global_x` bound to `_` because:
 - number [1] is incompatible with string [2].
 - number [3] is incompatible with string [2].


Error --------------------------------------------------------- Closure.js:38:16

Cannot call `takes_string` with `local_x` bound to `_` because:
 - number [1] is incompatible with string [2].
 - number [3] is incompatible with string [2].


Error --------------------------------------------------------- Closure.js:57:14

Cannot call `takes_string` with `global_y` bound to `_` because:
 - number [1] is incompatible with string [2].
 - number [3] is incompatible with string [2].


Error --------------------------------------------------------- Closure.js:77:16

Cannot call `takes_string` with `local_y` bound to `_` because:
 - number [1] is incompatible with string [2].
 - number [3] is incompatible with string [2].


Error ------------------------------------------------------ cond_havoc.js:12:10

Cannot return `x` because string [1] is incompatible with number [2].


Error ----------------------------------------------------------- const.js:20:38

Cannot assign `var_x` to `y` because:
 - null [1] is incompatible with number [2].
 - null or undefined [3] is incompatible with number [2].



Found 11 errors
