Error -------------------------------------------------------------- test.js:4:5

Cannot call `foo` because no arguments are expected by function [1].


Error -------------------------------------------------------------- test.js:6:3

Cannot call `foo` because no arguments are expected by function [1].


Error -------------------------------------------------------------- test.js:9:1

Cannot call `foo` because no arguments are expected by function [1].


Error ------------------------------------------------------------ test.js:11:16

Cannot call `foo.call` because no arguments are expected by function [1].


Error ------------------------------------------------------------- test.js:12:5

Cannot call `foo.call` because no arguments are expected by function [1].


Error ------------------------------------------------------------ test.js:13:16

Cannot call `foo.call` because no arguments are expected by function [1].


Error ------------------------------------------------------------ test.js:15:18

Cannot call `foo.apply` because no arguments are expected by function [1].


Error ------------------------------------------------------------- test.js:16:5

Cannot call `foo.apply` because no arguments are expected by function [1].


Error ------------------------------------------------------------ test.js:18:16

Cannot call `foo.bind` because no arguments are expected by function [1].


Error ------------------------------------------------------------- test.js:19:5

Cannot call `foo.bind` because no arguments are expected by function [1].


Error ------------------------------------------------------------ test.js:20:16

Cannot call `foo.bind` because no arguments are expected by function [1].


Error ------------------------------------------------------------- test.js:22:9

Cannot call `foo` because no arguments are expected by function [1].


Error ------------------------------------------------------------- test.js:23:5

Cannot call `foo` because no arguments are expected by function [1].


Error ------------------------------------------------------------- test.js:24:9

Cannot call `foo` because no arguments are expected by function [1].



Found 14 errors
