===== signature-verification error should not be reported, just the parsing error: =====
No errors!

The Flow server is currently in filesystem lazy mode and is only checking 0/4 files.
To learn more, visit flow.org/en/docs/lang/lazy-modes


===== suppressed errors should not be reported after focus-checking fileA.js: =====
No errors!

The Flow server is currently in filesystem lazy mode and is only checking 2/4 files.
To learn more, visit flow.org/en/docs/lang/lazy-modes


===== suppressed errors should not be reported after focus-checking fileB.js: =====
No errors!

The Flow server is currently in filesystem lazy mode and is only checking 4/4 files.
To learn more, visit flow.org/en/docs/lang/lazy-modes
