Error ------------------------------------------------------------ init.js:34:20

Cannot assign `x` to `y` because possibly uninitialized variable [1] is
incompatible with number [2].


Error ------------------------------------------------------------ init.js:44:20

Cannot assign `x` to `y` because possibly uninitialized variable [1] is
incompatible with number [2].


Error ------------------------------------------------------------ init.js:54:20

Cannot assign `x` to `y` because possibly uninitialized variable [1] is
incompatible with number [2].


Error ------------------------------------------------------------ init.js:66:20

Cannot assign `x` to `y` because possibly uninitialized variable [1] is
incompatible with number [2].


Error ----------------------------------------------------------- init.js:118:18

Cannot assign `x` to `y` because uninitialized variable [1] is incompatible with
number [2].


Error ----------------------------------------------------------- init.js:131:18

Cannot assign `x` to `y` because possibly uninitialized variable [1] is
incompatible with number [2].


Error ----------------------------------------------------------- init.js:140:18

Cannot assign `x` to `y` because possibly uninitialized variable [1] is
incompatible with number [2].


Error ----------------------------------------------------------- init.js:153:18

Cannot assign `x` to `y` because possibly uninitialized variable [1] is
incompatible with number [2].


Error ----------------------------------------------------------- return.js:28:3

Unreachable code.


Error ----------------------------------------------------------- return.js:64:3

Unreachable code.


Error ------------------------------------------------------------- test.js:18:5

Cannot call `x` because string [1] is not a function.


Error ------------------------------------------------------------- test.js:19:5

Cannot call `y` because a callable signature is missing in object literal [1].


Error ------------------------------------------------------------- test.js:41:5

Unreachable code.



Found 13 errors
