test.js:2
  2:   foo(x: Out): Out { return x; }
              ^^^ Out. contravariant position (expected `Out` to occur only covariantly)

test.js:3
  3:   bar(y: In): In { return y; }
                   ^^ In. covariant position (expected `In` to occur only contravariantly)

test.js:10
 10:   v1: Variance<A,B>,
                    ^ A. This type is incompatible with
 13:   (v1: Variance<B,A>); // error on both targs (A ~/~> B)
                     ^ B

test.js:13
 13:   (v1: Variance<B,A>); // error on both targs (A ~/~> B)
                       ^ A. This type is incompatible with
 10:   v1: Variance<A,B>,
                      ^ B


Found 4 errors
