Error ------------------------------------------------------------ test2.js:4:15

Cannot get `this.p` because property `p` is missing in object literal.


Error ------------------------------------------------------------- test3.js:4:8

Cannot call `this.m` because property `m` is missing in global object.


Error ------------------------------------------------------------- test3.js:4:8

Cannot call `this.m` because property `m` is missing in object literal.


Error ------------------------------------------------------------- test3.js:4:8

Cannot call `this.m` because property `m` is missing in object literal.



Found 4 errors
