-----------------------------
restart server
-----------------------------

-----------------------------
root
-----------------------------


Coverage results from 13 file(s):

other_folder/i.js: 20.00% (2 of 10 expressions)
other_folder/h.js: 100.00% (6 of 6 expressions)
match_coverage/coverage.js: 24.39% (10 of 41 expressions)
folder/subfolder/j.js: 100.00% (5 of 5 expressions)
folder/e.js: 20.00% (1 of 5 expressions)
folder/d.js: 40.00% (2 of 5 expressions)
folder/c.js: 100.00% (4 of 4 expressions)
f.js: 20.00% (1 of 5 expressions)
cycle/cycle3.js: 31.25% (5 of 16 expressions)
cycle/cycle2.js: 43.75% (7 of 16 expressions)
cycle/cycle1.js: 38.46% (5 of 13 expressions)
b.js: 100.00% (5 of 5 expressions)
a.js: 60.00% (3 of 5 expressions)

-----------------------------------
Aggregate coverage statistics
-----------------------------------
Files                : 13
Expressions          :
  Covered            : 56
  Total              : 136
  Covered Percentage : 41.18%

-----------------------------
folder
-----------------------------


Coverage results from 4 file(s):

folder/subfolder/j.js: 100.00% (5 of 5 expressions)
folder/e.js: 20.00% (1 of 5 expressions)
folder/d.js: 40.00% (2 of 5 expressions)
folder/c.js: 100.00% (4 of 4 expressions)

-----------------------------------
Aggregate coverage statistics
-----------------------------------
Files                : 4
Expressions          :
  Covered            : 12
  Total              : 19
  Covered Percentage : 63.16%

-----------------------------
cycle
-----------------------------


Coverage results from 3 file(s):

cycle/cycle3.js: 31.25% (5 of 16 expressions)
cycle/cycle2.js: 43.75% (7 of 16 expressions)
cycle/cycle1.js: 38.46% (5 of 13 expressions)

-----------------------------------
Aggregate coverage statistics
-----------------------------------
Files                : 3
Expressions          :
  Covered            : 17
  Total              : 45
  Covered Percentage : 37.78%

-----------------------------
match_coverage
-----------------------------


Coverage results from 1 file(s):

match_coverage/coverage.js: 24.39% (10 of 41 expressions)

-----------------------------------
Aggregate coverage statistics
-----------------------------------
Files                : 1
Expressions          :
  Covered            : 10
  Total              : 41
  Covered Percentage : 24.39%

-----------------------------
other_folder
-----------------------------


Coverage results from 2 file(s):

other_folder/i.js: 20.00% (2 of 10 expressions)
other_folder/h.js: 100.00% (6 of 6 expressions)

-----------------------------------
Aggregate coverage statistics
-----------------------------------
Files                : 2
Expressions          :
  Covered            : 8
  Total              : 16
  Covered Percentage : 50.00%

-----------------------------
folder/subfolder
-----------------------------


Coverage results from 1 file(s):

folder/subfolder/j.js: 100.00% (5 of 5 expressions)

-----------------------------------
Aggregate coverage statistics
-----------------------------------
Files                : 1
Expressions          :
  Covered            : 5
  Total              : 5
  Covered Percentage : 100.00%

-----------------------------
file list
-----------------------------


Coverage results from 3 file(s):

folder/subfolder/j.js: 100.00% (5 of 5 expressions)
folder/d.js: 40.00% (2 of 5 expressions)
a.js: 60.00% (3 of 5 expressions)

-----------------------------------
Aggregate coverage statistics
-----------------------------------
Files                : 3
Expressions          :
  Covered            : 10
  Total              : 15
  Covered Percentage : 66.67%

-----------------------------
file and dir list
-----------------------------


Coverage results from 5 file(s):

folder/subfolder/j.js: 100.00% (5 of 5 expressions)
folder/e.js: 20.00% (1 of 5 expressions)
folder/d.js: 40.00% (2 of 5 expressions)
folder/c.js: 100.00% (4 of 4 expressions)
a.js: 60.00% (3 of 5 expressions)

-----------------------------------
Aggregate coverage statistics
-----------------------------------
Files                : 5
Expressions          :
  Covered            : 15
  Total              : 24
  Covered Percentage : 62.50%

-----------------------------
files
-----------------------------


Coverage results from 3 file(s):

folder/subfolder/j.js: 100.00% (5 of 5 expressions)
folder/d.js: 40.00% (2 of 5 expressions)
a.js: 60.00% (3 of 5 expressions)

-----------------------------------
Aggregate coverage statistics
-----------------------------------
Files                : 3
Expressions          :
  Covered            : 10
  Total              : 15
  Covered Percentage : 66.67%

-----------------------------
json
-----------------------------

{
  "files":[
    {"file":"a.js","percentage":60.00,"covered":3,"total":5},
    {"file":"folder/d.js","percentage":40.00,"covered":2,"total":5},
    {"file":"folder/subfolder/j.js","percentage":100.00,"covered":5,"total":5}
  ],
  "statistics":{
    "files_in_directory":3,
    "covered_expressions":10,
    "total_expressions":15,
    "percentage":66.67
  }
}
-----------------------------
trust
-----------------------------


Coverage results from 13 file(s):

other_folder/i.js: 20.00% trusted (2 of 10 expressions), 20.00% covered (2 of 10 expressions)
other_folder/h.js: 66.67% trusted (4 of 6 expressions), 100.00% covered (6 of 6 expressions)
match_coverage/coverage.js: 14.63% trusted (6 of 41 expressions), 24.39% covered (10 of 41 expressions)
folder/subfolder/j.js: 20.00% trusted (1 of 5 expressions), 100.00% covered (5 of 5 expressions)
folder/e.js: 20.00% trusted (1 of 5 expressions), 20.00% covered (1 of 5 expressions)
folder/d.js: 20.00% trusted (1 of 5 expressions), 40.00% covered (2 of 5 expressions)
folder/c.js: 100.00% trusted (4 of 4 expressions), 100.00% covered (4 of 4 expressions)
f.js: 20.00% trusted (1 of 5 expressions), 20.00% covered (1 of 5 expressions)
cycle/cycle3.js: 6.25% trusted (1 of 16 expressions), 31.25% covered (5 of 16 expressions)
cycle/cycle2.js: 12.50% trusted (2 of 16 expressions), 43.75% covered (7 of 16 expressions)
cycle/cycle1.js: 7.69% trusted (1 of 13 expressions), 38.46% covered (5 of 13 expressions)
b.js: 80.00% trusted (4 of 5 expressions), 100.00% covered (5 of 5 expressions)
a.js: 60.00% trusted (3 of 5 expressions), 60.00% covered (3 of 5 expressions)

-----------------------------------
Aggregate coverage statistics
-----------------------------------
Files                : 13
Expressions          :
  Trusted            : 31
  Covered            : 56
  Total              : 136
  Trust Percentage   : 22.79%
  Covered Percentage : 41.18%

{
  "files":[
    {
      "file":"a.js",
      "trusted_percentage":60.00,
      "percentage":60.00,
      "trusted":3,
      "covered":3,
      "total":5
    },
    {
      "file":"b.js",
      "trusted_percentage":80.00,
      "percentage":100.00,
      "trusted":4,
      "covered":5,
      "total":5
    },
    {
      "file":"cycle/cycle1.js",
      "trusted_percentage":7.69,
      "percentage":38.46,
      "trusted":1,
      "covered":5,
      "total":13
    },
    {
      "file":"cycle/cycle2.js",
      "trusted_percentage":12.50,
      "percentage":43.75,
      "trusted":2,
      "covered":7,
      "total":16
    },
    {
      "file":"cycle/cycle3.js",
      "trusted_percentage":6.25,
      "percentage":31.25,
      "trusted":1,
      "covered":5,
      "total":16
    },
    {
      "file":"f.js",
      "trusted_percentage":20.00,
      "percentage":20.00,
      "trusted":1,
      "covered":1,
      "total":5
    },
    {
      "file":"folder/c.js",
      "trusted_percentage":100.00,
      "percentage":100.00,
      "trusted":4,
      "covered":4,
      "total":4
    },
    {
      "file":"folder/d.js",
      "trusted_percentage":20.00,
      "percentage":40.00,
      "trusted":1,
      "covered":2,
      "total":5
    },
    {
      "file":"folder/e.js",
      "trusted_percentage":20.00,
      "percentage":20.00,
      "trusted":1,
      "covered":1,
      "total":5
    },
    {
      "file":"folder/subfolder/j.js",
      "trusted_percentage":20.00,
      "percentage":100.00,
      "trusted":1,
      "covered":5,
      "total":5
    },
    {
      "file":"match_coverage/coverage.js",
      "trusted_percentage":14.63,
      "percentage":24.39,
      "trusted":6,
      "covered":10,
      "total":41
    },
    {
      "file":"other_folder/h.js",
      "trusted_percentage":66.67,
      "percentage":100.00,
      "trusted":4,
      "covered":6,
      "total":6
    },
    {
      "file":"other_folder/i.js",
      "trusted_percentage":20.00,
      "percentage":20.00,
      "trusted":2,
      "covered":2,
      "total":10
    }
  ],
  "statistics":{
    "files_in_directory":13,
    "trusted_expressions":31,
    "covered_expressions":56,
    "total_expressions":136,
    "trusted_percentage":22.79,
    "percentage":41.18
  }
}
