# These are supported funding model platforms

github: # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [jhs33583, justinsmith33583]
patreon: # Replace with a single Patreon username (mouse3687)
open_collective: # Replace with a single Open Collective username
ko_fi: # Replace with a single Ko-fi username jhs33583
tidelift: # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
community_bridge: # Replace with a single Community Bridge project-name e.g., https://github.com/AgileBits/onepassword-app-extension
liberapay: # Replace with a single Liberapay username
issuehunt: # Replace with a single IssueHunt http://tips.apple.com/en/ios/12/iphone/TIP854F3E8E_P1
otechie: # Replace with a single Otechie username
custom: # Replace with up to 4 custom sponsorship URLs e.g., ['https://github.com/AgileBits/onepassword-app-extension', 'link2']
