Error ------------------------------------------------------------ annot.js:1:17

Cannot resolve module `./unknown_class`.


Error ------------------------------------------------------------- annot.js:5:7

Missing type annotation for `x`.


Error ------------------------------------------------------------- fun.js:11:16

Cannot assign `f(...)` to `x` because number [1] is incompatible with
string [2].


Error ------------------------------------------------------------- obj.js:10:16

Cannot assign `o.x` to `x` because number [1] is incompatible with string [2].



Found 4 errors
