Error ------------------------------------------------------------------------------------------- disabled/test.js:11:31

Cannot assign `Disabled.noThis` to `extracted` because in the `this` parameter: function [1] cannot be unbound from the
context [2] where it was defined. [method-unbinding]

   disabled/test.js:11:31
   11| const extracted: () => void = Disabled.noThis; // error: legacy method unbinding
                                     ^^^^^^^^^^^^^^^

References:
   disabled/test.js:4:3
    4|   static noThis(): void {}
         ^^^^^^^^^^^^^^^^^^^^^^^^ [1]
   disabled/test.js:3:7
    3| class Disabled {
             ^^^^^^^^ [2]


Error --------------------------------------------------------------------------------------------- enabled/test.js:6:18

Missing an annotation on implicit `this` parameter of method `usesThis`. [missing-this-annot]

   6|   static usesThis(): typeof Enabled { // error: need to annotate this
                       ^^



Found 2 errors
