variable_declaration.js:8:8
Flags: --strip-root --pretty
{
  "documentation":"this is foo!",
  "type":"number",
  "reasons":[],
  "loc":{
    "source":"variable_declaration.js",
    "type":"SourceFile",
    "start":{"line":8,"column":7,"offset":53},
    "end":{"line":8,"column":9,"offset":56}
  },
  "path":"variable_declaration.js",
  "line":8,
  "endline":8,
  "start":7,
  "end":9
}

variable_declaration.js:11:4
Flags: --strip-root --pretty
{
  "documentation":"this is foo!",
  "type":"number",
  "reasons":[],
  "loc":{
    "source":"variable_declaration.js",
    "type":"SourceFile",
    "start":{"line":11,"column":3,"offset":70},
    "end":{"line":11,"column":5,"offset":73}
  },
  "path":"variable_declaration.js",
  "line":11,
  "endline":11,
  "start":3,
  "end":5
}

variable_declaration.js:19:4
Flags: --strip-root --pretty
{
  "documentation":"this is bar!",
  "type":"void",
  "reasons":[],
  "loc":{
    "source":"variable_declaration.js",
    "type":"SourceFile",
    "start":{"line":19,"column":3,"offset":128},
    "end":{"line":19,"column":5,"offset":131}
  },
  "path":"variable_declaration.js",
  "line":19,
  "endline":19,
  "start":3,
  "end":5
}

variable_declaration.js:27:4
Flags: --strip-root --pretty
{
  "documentation":"this is baz!",
  "type":"void",
  "reasons":[],
  "loc":{
    "source":"variable_declaration.js",
    "type":"SourceFile",
    "start":{"line":27,"column":3,"offset":183},
    "end":{"line":27,"column":5,"offset":186}
  },
  "path":"variable_declaration.js",
  "line":27,
  "endline":27,
  "start":3,
  "end":5
}

variable_declaration.js:35:5
Flags: --strip-root --pretty
{
  "documentation":"this is alpha!",
  "type":"number",
  "reasons":[],
  "loc":{
    "source":"variable_declaration.js",
    "type":"SourceFile",
    "start":{"line":35,"column":3,"offset":240},
    "end":{"line":35,"column":7,"offset":245}
  },
  "path":"variable_declaration.js",
  "line":35,
  "endline":35,
  "start":3,
  "end":7
}

variable_declaration.js:43:4
Flags: --strip-root --pretty
{
  "documentation":"this is beta!",
  "type":"void",
  "reasons":[],
  "loc":{
    "source":"variable_declaration.js",
    "type":"SourceFile",
    "start":{"line":43,"column":3,"offset":292},
    "end":{"line":43,"column":6,"offset":296}
  },
  "path":"variable_declaration.js",
  "line":43,
  "endline":43,
  "start":3,
  "end":6
}

variable_declaration.js:48:4
Flags: --strip-root --pretty
{
  "documentation":"this is beta!",
  "type":"number",
  "reasons":[],
  "loc":{
    "source":"variable_declaration.js",
    "type":"SourceFile",
    "start":{"line":48,"column":3,"offset":319},
    "end":{"line":48,"column":6,"offset":323}
  },
  "path":"variable_declaration.js",
  "line":48,
  "endline":48,
  "start":3,
  "end":6
}

class_declaration.js:8:14
Flags: --strip-root --pretty
{
  "documentation":"this is Foo!",
  "type":"class Foo",
  "reasons":[],
  "loc":{
    "source":"class_declaration.js",
    "type":"SourceFile",
    "start":{"line":8,"column":13,"offset":59},
    "end":{"line":8,"column":15,"offset":62}
  },
  "path":"class_declaration.js",
  "line":8,
  "endline":8,
  "start":13,
  "end":15
}

function_declaration.js:8:4
Flags: --strip-root --pretty
{
  "documentation":"this is foo!",
  "type":"() => void",
  "reasons":[],
  "loc":{
    "source":"function_declaration.js",
    "type":"SourceFile",
    "start":{"line":8,"column":3,"offset":54},
    "end":{"line":8,"column":5,"offset":57}
  },
  "path":"function_declaration.js",
  "line":8,
  "endline":8,
  "start":3,
  "end":5
}

declare.js:8:4
Flags: --strip-root --pretty
{
  "documentation":"declaration of foo",
  "type":"empty",
  "reasons":[],
  "loc":{
    "source":"declare.js",
    "type":"SourceFile",
    "start":{"line":8,"column":3,"offset":59},
    "end":{"line":8,"column":5,"offset":62}
  },
  "path":"declare.js",
  "line":8,
  "endline":8,
  "start":3,
  "end":5
}

declare.js:16:6
Flags: --strip-root --pretty
{
  "documentation":"declaration of Bar",
  "type":"class Bar",
  "reasons":[],
  "loc":{
    "source":"declare.js",
    "type":"SourceFile",
    "start":{"line":16,"column":5,"offset":127},
    "end":{"line":16,"column":7,"offset":130}
  },
  "path":"declare.js",
  "line":16,
  "endline":16,
  "start":5,
  "end":7
}

declare.js:24:4
Flags: --strip-root --pretty
{
  "documentation":"declaration of baz",
  "type":"(any) => any",
  "reasons":[],
  "loc":{
    "source":"declare.js",
    "type":"SourceFile",
    "start":{"line":24,"column":3,"offset":208},
    "end":{"line":24,"column":5,"offset":211}
  },
  "path":"declare.js",
  "line":24,
  "endline":24,
  "start":3,
  "end":5
}

objects-requires.js:9:6
Flags: --strip-root --pretty
{
  "documentation":"foo is an identifier property",
  "type":"number",
  "reasons":[],
  "loc":{
    "source":"objects-requires.js",
    "type":"SourceFile",
    "start":{"line":9,"column":5,"offset":193},
    "end":{"line":9,"column":7,"offset":196}
  },
  "path":"objects-requires.js",
  "line":9,
  "endline":9,
  "start":5,
  "end":7
}

objects-requires.js:11:6
Flags: --strip-root --pretty
{
  "documentation":"bar is a getter property",
  "type":"number",
  "reasons":[],
  "loc":{
    "source":"objects-requires.js",
    "type":"SourceFile",
    "start":{"line":11,"column":5,"offset":212},
    "end":{"line":11,"column":7,"offset":215}
  },
  "path":"objects-requires.js",
  "line":11,
  "endline":11,
  "start":5,
  "end":7
}

objects-requires.js:13:6
Flags: --strip-root --pretty
{
  "documentation":"baz is an identifier property with variance",
  "type":"number",
  "reasons":[],
  "loc":{
    "source":"objects-requires.js",
    "type":"SourceFile",
    "start":{"line":13,"column":5,"offset":231},
    "end":{"line":13,"column":7,"offset":234}
  },
  "path":"objects-requires.js",
  "line":13,
  "endline":13,
  "start":5,
  "end":7
}

objects-requires.js:15:6
Flags: --strip-root --pretty
{
  "documentation":"qux is a literal property",
  "type":"number",
  "reasons":[],
  "loc":{
    "source":"objects-requires.js",
    "type":"SourceFile",
    "start":{"line":15,"column":5,"offset":250},
    "end":{"line":15,"column":7,"offset":253}
  },
  "path":"objects-requires.js",
  "line":15,
  "endline":15,
  "start":5,
  "end":7
}

objects-requires.js:21:6
Flags: --strip-root --pretty
{
  "documentation":"foo is an identifier property",
  "type":"number",
  "reasons":[],
  "loc":{
    "source":"objects-requires.js",
    "type":"SourceFile",
    "start":{"line":21,"column":5,"offset":330},
    "end":{"line":21,"column":7,"offset":333}
  },
  "path":"objects-requires.js",
  "line":21,
  "endline":21,
  "start":5,
  "end":7
}

objects-requires.js:23:6
Flags: --strip-root --pretty
{
  "documentation":"bar is a getter property",
  "type":"number",
  "reasons":[],
  "loc":{
    "source":"objects-requires.js",
    "type":"SourceFile",
    "start":{"line":23,"column":5,"offset":349},
    "end":{"line":23,"column":7,"offset":352}
  },
  "path":"objects-requires.js",
  "line":23,
  "endline":23,
  "start":5,
  "end":7
}

objects-requires.js:25:6
Flags: --strip-root --pretty
{
  "documentation":"baz is an identifier property with variance",
  "type":"number",
  "reasons":[],
  "loc":{
    "source":"objects-requires.js",
    "type":"SourceFile",
    "start":{"line":25,"column":5,"offset":368},
    "end":{"line":25,"column":7,"offset":371}
  },
  "path":"objects-requires.js",
  "line":25,
  "endline":25,
  "start":5,
  "end":7
}

objects-requires.js:27:6
Flags: --strip-root --pretty
{
  "documentation":"qux is a literal property",
  "type":"number",
  "reasons":[],
  "loc":{
    "source":"objects-requires.js",
    "type":"SourceFile",
    "start":{"line":27,"column":5,"offset":387},
    "end":{"line":27,"column":7,"offset":390}
  },
  "path":"objects-requires.js",
  "line":27,
  "endline":27,
  "start":5,
  "end":7
}

objects-requires.js:32:6
Flags: --strip-root --pretty
{
  "documentation":"foo is an identifier property",
  "type":"1",
  "reasons":[],
  "loc":{
    "source":"objects-requires.js",
    "type":"SourceFile",
    "start":{"line":32,"column":5,"offset":453},
    "end":{"line":32,"column":7,"offset":456}
  },
  "path":"objects-requires.js",
  "line":32,
  "endline":32,
  "start":5,
  "end":7
}

objects-requires.js:34:6
Flags: --strip-root --pretty
{
  "documentation":"bar is a getter property",
  "type":"2",
  "reasons":[],
  "loc":{
    "source":"objects-requires.js",
    "type":"SourceFile",
    "start":{"line":34,"column":5,"offset":469},
    "end":{"line":34,"column":7,"offset":472}
  },
  "path":"objects-requires.js",
  "line":34,
  "endline":34,
  "start":5,
  "end":7
}

objects-requires.js:36:6
Flags: --strip-root --pretty
{
  "documentation":"baz is an identifier property with variance",
  "type":"3",
  "reasons":[],
  "loc":{
    "source":"objects-requires.js",
    "type":"SourceFile",
    "start":{"line":36,"column":5,"offset":485},
    "end":{"line":36,"column":7,"offset":488}
  },
  "path":"objects-requires.js",
  "line":36,
  "endline":36,
  "start":5,
  "end":7
}

objects-requires.js:38:6
Flags: --strip-root --pretty
{
  "documentation":"qux is a literal property",
  "type":"4",
  "reasons":[],
  "loc":{
    "source":"objects-requires.js",
    "type":"SourceFile",
    "start":{"line":38,"column":5,"offset":501},
    "end":{"line":38,"column":7,"offset":504}
  },
  "path":"objects-requires.js",
  "line":38,
  "endline":38,
  "start":5,
  "end":7
}

objects-requires.js:42:7
Flags: --strip-root --pretty
{
  "documentation":"this is a static property",
  "type":"1",
  "reasons":[],
  "loc":{
    "source":"objects-requires.js",
    "type":"SourceFile",
    "start":{"line":42,"column":5,"offset":521},
    "end":{"line":42,"column":14,"offset":531}
  },
  "path":"objects-requires.js",
  "line":42,
  "endline":42,
  "start":5,
  "end":14
}

objects-requires.js:44:7
Flags: --strip-root --pretty
{
  "documentation":"this is a static method",
  "type":"() => void",
  "reasons":[],
  "loc":{
    "source":"objects-requires.js",
    "type":"SourceFile",
    "start":{"line":44,"column":5,"offset":544},
    "end":{"line":44,"column":16,"offset":556}
  },
  "path":"objects-requires.js",
  "line":44,
  "endline":44,
  "start":5,
  "end":16
}

objects-requires.js:47:12
Flags: --strip-root --pretty
{
  "documentation":"this is an instance property",
  "type":"2",
  "reasons":[],
  "loc":{
    "source":"objects-requires.js",
    "type":"SourceFile",
    "start":{"line":47,"column":9,"offset":601},
    "end":{"line":47,"column":20,"offset":613}
  },
  "path":"objects-requires.js",
  "line":47,
  "endline":47,
  "start":9,
  "end":20
}

objects-requires.js:49:12
Flags: --strip-root --pretty
{
  "documentation":"this is an instance method",
  "type":"() => void",
  "reasons":[],
  "loc":{
    "source":"objects-requires.js",
    "type":"SourceFile",
    "start":{"line":49,"column":9,"offset":636},
    "end":{"line":49,"column":22,"offset":650}
  },
  "path":"objects-requires.js",
  "line":49,
  "endline":49,
  "start":9,
  "end":22
}

objects-requires.js:51:12
Flags: --strip-root --pretty
{
  "documentation":"property with variance",
  "type":"3",
  "reasons":[],
  "loc":{
    "source":"objects-requires.js",
    "type":"SourceFile",
    "start":{"line":51,"column":9,"offset":675},
    "end":{"line":51,"column":20,"offset":687}
  },
  "path":"objects-requires.js",
  "line":51,
  "endline":51,
  "start":9,
  "end":20
}

objects.js:84:5
Flags: --strip-root --pretty
{
  "documentation":"identifier property of an object literal",
  "type":"number",
  "reasons":[],
  "loc":{
    "source":"objects.js",
    "type":"SourceFile",
    "start":{"line":84,"column":5,"offset":1354},
    "end":{"line":84,"column":5,"offset":1355}
  },
  "path":"objects.js",
  "line":84,
  "endline":84,
  "start":5,
  "end":5
}

objects.js:86:5
Flags: --strip-root --pretty
{
  "documentation":"literal property of an object literal",
  "type":"number",
  "reasons":[],
  "loc":{
    "source":"objects.js",
    "type":"SourceFile",
    "start":{"line":86,"column":5,"offset":1367},
    "end":{"line":86,"column":5,"offset":1368}
  },
  "path":"objects.js",
  "line":86,
  "endline":86,
  "start":5,
  "end":5
}

objects.js:88:5
Flags: --strip-root --pretty
{
  "documentation":"computed property of an object literal",
  "type":"number",
  "reasons":[],
  "loc":{
    "source":"objects.js",
    "type":"SourceFile",
    "start":{"line":88,"column":5,"offset":1380},
    "end":{"line":88,"column":5,"offset":1381}
  },
  "path":"objects.js",
  "line":88,
  "endline":88,
  "start":5,
  "end":5
}

objects.js:90:5
Flags: --strip-root --pretty
{
  "documentation":"annotated getter property of an object literal",
  "type":"number",
  "reasons":[],
  "loc":{
    "source":"objects.js",
    "type":"SourceFile",
    "start":{"line":90,"column":5,"offset":1393},
    "end":{"line":90,"column":5,"offset":1394}
  },
  "path":"objects.js",
  "line":90,
  "endline":90,
  "start":5,
  "end":5
}

objects.js:94:5
Flags: --strip-root --pretty
{
  "documentation":"method property of an object literal",
  "type":"() => void",
  "reasons":[],
  "loc":{
    "source":"objects.js",
    "type":"SourceFile",
    "start":{"line":94,"column":5,"offset":1478},
    "end":{"line":94,"column":5,"offset":1479}
  },
  "path":"objects.js",
  "line":94,
  "endline":94,
  "start":5,
  "end":5
}

objects.js:96:5
Flags: --strip-root --pretty
{
  "documentation":"async method property of an object literal",
  "type":"() => Promise<void>",
  "reasons":[],
  "loc":{
    "source":"objects.js",
    "type":"SourceFile",
    "start":{"line":96,"column":5,"offset":1491},
    "end":{"line":96,"column":5,"offset":1492}
  },
  "path":"objects.js",
  "line":96,
  "endline":96,
  "start":5,
  "end":5
}

requires.js:5:4
Flags: --strip-root --pretty
{
  "documentation":"foo is a function",
  "type":"(x: number, y: number) => number",
  "reasons":[],
  "loc":{
    "source":"requires.js",
    "type":"SourceFile",
    "start":{"line":5,"column":3,"offset":67},
    "end":{"line":5,"column":5,"offset":70}
  },
  "path":"requires.js",
  "line":5,
  "endline":5,
  "start":3,
  "end":5
}

requires.js:7:4
Flags: --strip-root --pretty
{
  "documentation":"Bar is a class",
  "type":"class Bar",
  "reasons":[],
  "loc":{
    "source":"requires.js",
    "type":"SourceFile",
    "start":{"line":7,"column":3,"offset":79},
    "end":{"line":7,"column":5,"offset":82}
  },
  "path":"requires.js",
  "line":7,
  "endline":7,
  "start":3,
  "end":5
}

requires.js:9:4
Flags: --strip-root --pretty
{
  "documentation":"baz is a variable",
  "type":"number",
  "reasons":[],
  "loc":{
    "source":"requires.js",
    "type":"SourceFile",
    "start":{"line":9,"column":3,"offset":91},
    "end":{"line":9,"column":5,"offset":94}
  },
  "path":"requires.js",
  "line":9,
  "endline":9,
  "start":3,
  "end":5
}

imports.js:5:4
Flags: --strip-root --pretty
{
  "documentation":"foo is a function",
  "type":"(x: number, y: number) => number",
  "reasons":[],
  "loc":{
    "source":"imports.js",
    "type":"SourceFile",
    "start":{"line":5,"column":3,"offset":57},
    "end":{"line":5,"column":5,"offset":60}
  },
  "path":"imports.js",
  "line":5,
  "endline":5,
  "start":3,
  "end":5
}

imports.js:7:4
Flags: --strip-root --pretty
{
  "documentation":"Bar is a class",
  "type":"class Bar",
  "reasons":[],
  "loc":{
    "source":"imports.js",
    "type":"SourceFile",
    "start":{"line":7,"column":3,"offset":69},
    "end":{"line":7,"column":5,"offset":72}
  },
  "path":"imports.js",
  "line":7,
  "endline":7,
  "start":3,
  "end":5
}

imports.js:9:4
Flags: --strip-root --pretty
{
  "documentation":"baz is a variable",
  "type":"number",
  "reasons":[],
  "loc":{
    "source":"imports.js",
    "type":"SourceFile",
    "start":{"line":9,"column":3,"offset":81},
    "end":{"line":9,"column":5,"offset":84}
  },
  "path":"imports.js",
  "line":9,
  "endline":9,
  "start":3,
  "end":5
}

