copyProperties.js:6
  6:     (copyProperties()); // error, unknown global
          ^^^^^^^^^^^^^^ identifier `copyProperties`. Could not resolve name

copyProperties.js:31
 31:     (copyProperties({ foo: 'a' }): { foo: number }); // err, num !~> string
                                ^^^ string. This type is incompatible with
 31:     (copyProperties({ foo: 'a' }): { foo: number }); // err, num !~> string
                                               ^^^^^^ number

mergeInto.js:6
  6:     (mergeInto()); // error, unknown global
          ^^^^^^^^^ identifier `mergeInto`. Could not resolve name

test.js:6
  6:     var x: string = this.x;
                         ^^^^^^ number. This type is incompatible with
  6:     var x: string = this.x;
                ^^^^^^ string

test.js:7
  7:     this.y = "";
              ^ property `y`. Property not found in
  4: class Foo extends mixin(Bar) {
           ^^^ Foo


Found 5 errors
