>>> rest.js (#changes: 1)
// @flow

declare function foo<Args: $ReadOnlyArray<mixed>>(
    f: (...Args) => mixed,
  ): (...Args) => void;

declare var x: (string, number) => void;

(foo<[string, number]>(x))('a', 1); // should annotate with [string, number] to not cause new flow errors

>>> test.js (#changes: 2)
// @flow

declare function id<T>(x:T): T;
declare function singletonArray<T>(T): Array<T>;

const arr1 = singletonArray<number | string>("s"); // annotate
arr1.push(3);
const set1 = new Set<number | string>(["a"]); // annotate
set1.add(3);

const arr2 = singletonArray("s"); // don't annotate
const set2 = new Set(["a"]); // don't annotate

>>> Launching report...

Stats:
  Files changed:                            2
  Number of annotations added:              3
  Total size of annotations:                9

Errors:
  Missing annot./normalizer error:          0
  Validation Error:                         0
  Import Error:
    Loc source none:                        0
    Indeterminate module type:              0
    No matching export:                     0
  Serializer error:                         0
  Unsupported error kind:                   0

Warnings:
  Skipping arrow function:                  0
  Large type added:                         0
  Location unhandled:                       0
  Empty NoUpper:                            0
  Empty SomeKnownUpper:                     0

