
break.js:6:24,24: boolean
This type is incompatible with
break.js:6:15,20: number

break.js:8:20,20: string
This type is incompatible with
break.js:8:11,16: number

break.js:8:20,20: undefined
This type is incompatible with
break.js:8:11,16: number

break.js:16:24,24: boolean
This type is incompatible with
break.js:16:15,20: number

break.js:19:24,24: boolean
This type is incompatible with
break.js:19:15,20: number

break.js:19:24,24: string
This type is incompatible with
break.js:19:15,20: number

break.js:23:20,20: boolean
This type is incompatible with
break.js:23:11,16: number

break.js:23:20,20: null
This type is incompatible with
break.js:23:11,16: number

break.js:23:20,20: string
This type is incompatible with
break.js:23:11,16: number

break.js:29:24,24: string
This type is incompatible with
break.js:29:15,20: number

break.js:33:20,20: string
This type is incompatible with
break.js:33:11,16: number

Found 11 errors
