
=== Codemod annotate-exports ===

>>> ./fileA.js
// @flow

import type {T} from "react-redux";const {foo} = require('react-redux');

module.exports = (foo(): T);

>>> ./fileB.js
// @flow

import type {T} from 'react-redux';
const {foo} = require('react-redux');

module.exports = (foo(): T);

>>> Launching report...

Stats:
  Files changed:                            2
  Number of annotations added:              2
  Total size of annotations:                2
  Number of sig. ver. errors:               2
  Number of annotations required:           2
  Number of annotations skipped:            0

Errors:
  Missing annot./normalizer error:          0
  Validation Error:                         0
  Import Error:
    Loc source none:                        0
    Parsing heaps get ast error:            0
    Indeterminate module type:              0
    No matching export:                     0
  Serializer error:                         0
  Unsupported error kind:                   0

Warnings:
  Skipping arrow function:                  0
  Large type added:                         0
  Location unhandled:                       0
  Empty NoUpper:                            0
  Empty SomeKnownUpper:                     0


=== Autofix exports ===

>>> ./fileA.js
// @flow

import type {T} from "react-redux";const {foo} = require('react-redux');

module.exports = (foo(): T);

>>> ./fileB.js
// @flow

import type {T} from 'react-redux';
const {foo} = require('react-redux');

module.exports = (foo(): T);


=== Diff between codemod-ed & autofix-ed ===
