func-0.js
// @flow

function foo(x: number, y: string): string {
  return x + y;
}

foo(1, "");
func-1.js
// @flow

function foo(x: number, y: ((z: number) => number)): number {
  return x + y(x);
}

foo(1, (z: number): number => z + 1);
func-2.js
// @flow

function foo(x: number, y: number): void {
  function bar(z: number, w: number): number {
    return x + z + y + w;
  }
  bar(x, y);
}

foo(1, 1);
func-3.js
// @flow
function throws_arg(): empty {
  throw 42;
}
Found 0 errors
