>>> file.js (#changes: 1)
// @flow

let x: $ReadOnlyArray<string | number> = [];

x = [1];

if (0 < 1) {
    x = [""];
}

>>> Launching report...

Stats:
  Files changed:                            1
  Number of annotations added:              1
  Total size of annotations:                5
  Number of vars with write errors:         1
  Number of possibly renamable vars:        1
  Number of annotations skipped:            0

Errors:
  Missing annot./normalizer error:          0
  Validation Error:                         0
  Import Error:
    Loc source none:                        0
    Parsing heaps get ast error:            0
    Indeterminate module type:              0
    No matching export:                     0
  Serializer error:                         0
  Unsupported error kind:                   0

Warnings:
  Skipping arrow function:                  0
  Large type added:                         0
  Location unhandled:                       0
  Empty NoUpper:                            0
  Empty SomeKnownUpper:                     0

