Error ------------------------------------------------------------- basic.js:6:2

Cannot cast `compose(...)(...)` to empty because string is incompatible with
empty.


Error ------------------------------------------------------------- basic.js:8:2

Cannot cast `composeReverse(...)(...)` to empty because string is incompatible
with empty.


Error ------------------------------------------------------------ basic.js:10:2

Cannot cast `compose(...)(...)` to empty because number is incompatible with
empty.


Error ------------------------------------------------------------ basic.js:11:8

Cannot perform arithmetic operation because string is not a number.


Error ------------------------------------------------------------ basic.js:15:2

Cannot cast `composeReverse(...)(...)` to empty because string is incompatible
with empty.


Error ------------------------------------------------------- recompose.js:23:19

Cannot call `Math.round` with `props.p` bound to `x` because string is
incompatible with number.


Error ------------------------------------------------------------ spread.js:8:2

Cannot cast `compose(...)(...)` to empty because number is incompatible with
empty.


Error ------------------------------------------------------------ spread.js:8:2

Cannot cast `compose(...)(...)` to empty because number is incompatible with
empty.


Error ----------------------------------------------------------- spread.js:12:2

Cannot cast `compose(...)(...)` to empty because number is incompatible with
empty.


Error ----------------------------------------------------------- spread.js:12:2

Cannot cast `compose(...)(...)` to empty because string is incompatible with
empty.


Error ----------------------------------------------------------- spread.js:13:6

Cannot call `compose` with compose intermediate value bound to the first
parameter because string is incompatible with number.


Error ----------------------------------------------------------- spread.js:16:2

Cannot cast `compose(...)(...)` to empty because number is incompatible with
empty.


Error ----------------------------------------------------------- spread.js:16:2

Cannot cast `compose(...)(...)` to empty because string is incompatible with
empty.


Error ----------------------------------------------------------- spread.js:17:6

Cannot call `compose` with compose intermediate value bound to the first
parameter because string is incompatible with number.


Error ----------------------------------------------------------- spread.js:21:2

Cannot call `compose` because property `p` is missing in `Number`.


Error ----------------------------------------------------------- spread.js:21:2

Cannot cast `compose(...)(...)` to empty because number is incompatible with
empty.


Error ----------------------------------------------------------- spread.js:21:2

Cannot cast `compose(...)(...)` to empty because object literal is incompatible
with empty.


Error ----------------------------------------------------------- spread.js:21:2

Cannot cast `compose(...)(...)` to empty because object literal is incompatible
with empty.


Error ----------------------------------------------------------- spread.js:21:2

Cannot cast `compose(...)(...)` to empty because object literal is incompatible
with empty.


Error ----------------------------------------------------------- spread.js:21:2

Cannot cast `compose(...)(...)` to empty because object literal is incompatible
with empty.


Error ----------------------------------------------------------- spread.js:27:2

Cannot cast `compose(...)(...)` to empty because `X2` is incompatible with
empty.


Error ----------------------------------------------------------- spread.js:27:2

Cannot cast `compose(...)(...)` to empty because `X2` is incompatible with
empty.



Found 22 errors
