// flow-typed signature: 6738cc101d3ea267944b3dc29832214d
// flow-typed version: <<STUB>>/vscode-textmate_v^6.0.0/flow_v0.176.3

/**
 * This is an autogenerated libdef stub for:
 *
 *   'vscode-textmate'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'vscode-textmate' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'vscode-textmate/release/main' {
  declare module.exports: any;
}

// Filename aliases
declare module 'vscode-textmate/release/main.js' {
  declare module.exports: $Exports<'vscode-textmate/release/main'>;
}
