// flow-typed signature: 89b005fc2f085af7e8a140a1fee559a2
// flow-typed version: <<STUB>>/vscode-oniguruma_v^1.6.2/flow_v0.176.3

/**
 * This is an autogenerated libdef stub for:
 *
 *   'vscode-oniguruma'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'vscode-oniguruma' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'vscode-oniguruma/release/main' {
  declare module.exports: any;
}

// Filename aliases
declare module 'vscode-oniguruma/release/main.js' {
  declare module.exports: $Exports<'vscode-oniguruma/release/main'>;
}
