
unary.js:8:11,11: string
This type is incompatible with
unary.js:8:10,11: number

unary.js:12:3,3: string
This type is incompatible with
unary.js:12:3,5: number

unary.js:12:3,5: number
This type is incompatible with
unary.js:11:16,21: string

unary.js:13:3,5: number
This type is incompatible with
unary.js:11:16,21: string

unary.js:14:3,5: number
This type is incompatible with
unary.js:11:16,21: string

unary.js:15:3,5: number
This type is incompatible with
unary.js:11:16,21: string

unary.js:19:11,11: string
This type is incompatible with
unary.js:19:10,11: number

Found 7 errors
