Error -------------------------------------------------------------- fun.js:3:19

Cannot use `T` in an input position because `T` is expected to occur only in
output positions.


Error -------------------------------------------------------------- fun.js:4:24

Cannot use `T` in an output position because `T` is expected to occur only in
input positions.


Error -------------------------------------------------------------- fun.js:7:25

Cannot use `T` in an output position because `T` is expected to occur only in
input positions.


Error ------------------------------------------------------------- fun.js:10:30

Cannot use `T` in an input position because `T` is expected to occur only in
output positions.


Error -------------------------------------------------------------- obj.js:2:25

Cannot use `T` in an input/output position because `T` is expected to occur only
in input positions.


Error -------------------------------------------------------------- obj.js:3:25

Cannot use `T` in an input/output position because `T` is expected to occur only
in output positions.


Error -------------------------------------------------------------- obj.js:5:29

Cannot use `T` in an output position because `T` is expected to occur only in
input positions.


Error -------------------------------------------------------------- obj.js:8:34

Cannot use `T` in an input position because `T` is expected to occur only in
output positions.


Error ------------------------------------------------------------- obj.js:11:29

Cannot use `T` in an input position because `T` is expected to occur only in
output positions.


Error ------------------------------------------------------------- obj.js:12:34

Cannot use `T` in an output position because `T` is expected to occur only in
input positions.


Error ------------------------------------------------------------- obj.js:15:29

Cannot use `T` in an output position because `T` is expected to occur only in
input positions.


Error ------------------------------------------------------------- obj.js:19:28

Cannot use `T` in an input position because `T` is expected to occur only in
output positions.



Found 12 errors
