Error -------------------------------------------- createclass-callsite.js:20:10

Cannot create `Hello` element because property `name` is missing in props but
exists in propTypes of React component.


Error -------------------------------------------- createclass-callsite.js:21:10

Cannot create `HelloLocal` element because property `name` is missing in props
but exists in propTypes of React component.


Error ------------------------------------- es6class-proptypes-callsite.js:20:10

Cannot create `Hello` element because property `name` is missing in props but
exists in object type.


Error ------------------------------------- es6class-proptypes-callsite.js:21:10

Cannot create `HelloLocal` element because property `name` is missing in props
but exists in object type.


Error ----------------------------------------- es6class-types-callsite.js:18:10

Cannot create `Hello` element because property `name` is missing in props but
exists in `Props`.


Error ----------------------------------------- es6class-types-callsite.js:19:10

Cannot create `HelloLocal` element because property `name` is missing in props
but exists in `Props`.



Found 6 errors
