#!/bin/bash

FLAG=true


while getopts ":b:" opt; do
    case $opt in
        b)
            ../../../facebook/flow convert --r "$OPTARG"
            ;;
        \?)
            echo "'./runtests' will test a handcrafted example"
            echo "'./runtests -b <path>' will run flow convert on all the files in <path>"
            ;;
        :)
            echo "Option -$OPTARG requires an argument." >&2
            exit 1
            ;;
    esac
    FLAG=false
done


if $FLAG
then
    printf "\n\n***************** RUNNING FLOW CONVERT *********************\n\n"
    ../../../facebook/flow convert --r .
    printf "\n\n***************** RUNNING FLOW CHECK *********************\n\n"
    ../../../facebook/flow check hand_crafted
fi
