Error ------------------------------------------------------------ test.js:12:18

Cannot assign `buffer.INSPECT_MAX_BYTES` to `b` because number [1] is
incompatible with boolean [2].


Error ------------------------------------------------------------ test.js:22:23

Cannot resolve module `./buffer`.


Error ------------------------------------------------------------ test.js:25:23

Cannot resolve module `./buffer.js`.



Found 3 errors
