
const.js:4:1,1: x
const cannot be reassigned
const.js:1:7,7: const x

const.js:5:1,1: x
const cannot be reassigned
const.js:1:7,7: const x

const.js:6:1,1: x
const cannot be reassigned
const.js:1:7,7: const x

const.js:7:1,1: x
const cannot be reassigned
const.js:1:7,7: const x

const.js:8:1,1: x
const cannot be reassigned
const.js:1:7,7: const x

const.js:9:1,1: x
const cannot be reassigned
const.js:1:7,7: const x

const.js:10:1,1: x
const cannot be reassigned
const.js:1:7,7: const x

const.js:11:1,1: x
const cannot be reassigned
const.js:1:7,7: const x

const.js:12:1,1: x
const cannot be reassigned
const.js:1:7,7: const x

const.js:13:1,1: x
const cannot be reassigned
const.js:1:7,7: const x

const.js:14:1,1: x
const cannot be reassigned
const.js:1:7,7: const x

const.js:15:1,1: x
const cannot be reassigned
const.js:1:7,7: const x

const.js:21:2,4: string
This type is incompatible with
const.js:21:7,12: number

const.js:22:2,4: string
This type is incompatible with
const.js:22:7,12: number

const.js:26:4,6: string
This type is incompatible with
const.js:26:9,14: number

rebinding.js:16:8,8: A
name is already bound
rebinding.js:15:8,8: type A

rebinding.js:21:9,9: A
name is already bound
rebinding.js:20:8,8: type A

rebinding.js:26:7,7: A
name is already bound
rebinding.js:25:8,8: type A

rebinding.js:31:9,9: A
name is already bound
rebinding.js:30:8,8: type A

rebinding.js:36:7,7: A
name is already bound
rebinding.js:35:8,8: type A

rebinding.js:41:3,3: A
type alias referenced from value position
rebinding.js:40:8,8: type A

rebinding.js:48:8,8: A
name is already bound
rebinding.js:47:9,9: class A

rebinding.js:53:9,9: A
name is already bound
rebinding.js:52:9,9: class A

rebinding.js:58:7,7: A
name is already bound
rebinding.js:57:9,9: class A

rebinding.js:63:9,9: A
name is already bound
rebinding.js:62:9,9: class A

rebinding.js:68:7,7: A
name is already bound
rebinding.js:67:9,9: class A

rebinding.js:75:8,8: A
name is already bound
rebinding.js:74:7,7: let A

rebinding.js:80:9,9: A
name is already bound
rebinding.js:79:7,7: let A

rebinding.js:85:7,7: A
name is already bound
rebinding.js:84:7,7: let A

rebinding.js:90:9,9: A
name is already bound
rebinding.js:89:7,7: let A

rebinding.js:95:7,7: A
name is already bound
rebinding.js:94:7,7: let A

rebinding.js:102:8,8: A
name is already bound
rebinding.js:101:9,9: const A

rebinding.js:107:9,9: A
name is already bound
rebinding.js:106:9,9: const A

rebinding.js:112:7,7: A
name is already bound
rebinding.js:111:9,9: const A

rebinding.js:117:9,9: A
name is already bound
rebinding.js:116:9,9: const A

rebinding.js:122:7,7: A
name is already bound
rebinding.js:121:9,9: const A

rebinding.js:127:3,3: A
const cannot be reassigned
rebinding.js:126:9,9: const A

rebinding.js:134:8,8: A
name is already bound
rebinding.js:133:7,7: var A

rebinding.js:139:9,9: A
name is already bound
rebinding.js:138:7,7: var A

rebinding.js:144:7,7: A
name is already bound
rebinding.js:143:7,7: var A

rebinding.js:149:9,9: A
name is already bound
rebinding.js:148:7,7: var A

rebinding.js:167:5,19: a
name is already bound
rebinding.js:166:5,19: function a

rebinding.js:177:11,11: x
name is already bound
rebinding.js:175:9,9: let x

rebinding.js:186:12,12: x
name is already bound
rebinding.js:184:9,9: let x

rebinding.js:193:34,34: x
name is already bound
rebinding.js:193:31,31: param x

rebinding.js:195:7,7: x
name is already bound
rebinding.js:194:37,37: param x

scope.js:6:13,14: string
This type is incompatible with
scope.js:3:10,15: number

scope.js:16:15,16: string
This type is incompatible with
scope.js:12:10,15: number

scope.js:19:11,11: a
name is already bound
scope.js:15:11,11: let a

scope.js:30:6,6: a
let referenced before declaration, or after skipped initializer
scope.js:36:11,11: let a

scope.js:33:14,14: a
let referenced before declaration, or after skipped initializer
scope.js:36:11,11: let a

scope.js:39:7,7: a
let referenced before declaration, or after skipped initializer
scope.js:36:11,11: let a

scope.js:42:22,22: a
let referenced before declaration, or after skipped initializer
scope.js:36:11,11: let a

scope.js:45:3,3: assignment of identifier `a`
Could not resolve name

scope.js:66:16,17: string
This type is incompatible with
scope.js:65:10,15: number

scope.js:76:12,12: string
This type is incompatible with
scope.js:75:10,15: number

scope.js:86:12,12: string
This type is incompatible with
scope.js:85:10,15: number

scope.js:93:6,11: number
This type is incompatible with
scope.js:92:14,19: string

scope.js:103:12,14: string
This type is incompatible with
scope.js:101:29,34: number

scope.js:105:19,19: identifier `b`
Could not resolve name

tdz.js:25:11,11: x
let referenced before declaration, or after skipped initializer
tdz.js:26:7,7: let x

tdz.js:25:15,15: c
const referenced before declaration, or after skipped initializer
tdz.js:27:9,9: const c

tdz.js:31:3,3: x
let referenced before declaration, or after skipped initializer
tdz.js:32:7,7: let x

tdz.js:34:5,5: y
let referenced before declaration, or after skipped initializer
tdz.js:35:9,9: let y

tdz.js:41:13,13: x
let referenced before declaration, or after skipped initializer
tdz.js:43:7,7: let x

tdz.js:41:17,17: c
const referenced before declaration, or after skipped initializer
tdz.js:44:9,9: const c

tdz.js:78:8,8: identifier `C`
Could not resolve name

tdz.js:80:13,13: C
class referenced before declaration, or after skipped initializer
tdz.js:82:7,7: class C

tdz.js:94:5,13: undefined
This type is incompatible with
tdz.js:94:8,13: number

Found 69 errors
