
date.js:2:16,26: call of method `getTime`
Error:
date.js:2:16,26: number
This type is incompatible with
date.js:2:7,12: string

date.js:18:1,12: constructor call
Error:
date.js:18:10,11: object literal
This type is incompatible with
[LIB] core.js:264:25,39: union: number | string
Member 1:
[LIB] core.js:264:25,30: number
Error:
date.js:18:10,11: object literal
This type is incompatible with
[LIB] core.js:264:25,30: number
Member 2:
[LIB] core.js:264:34,39: string
Error:
date.js:18:10,11: object literal
This type is incompatible with
[LIB] core.js:264:34,39: string

date.js:19:1,19: constructor call
Error:
date.js:19:16,18: string
This type is incompatible with
[LIB] core.js:264:50,55: number

date.js:20:1,23: constructor call
Error:
date.js:20:19,22: string
This type is incompatible with
[LIB] core.js:264:64,69: number

date.js:21:1,27: constructor call
Error:
date.js:21:23,26: string
This type is incompatible with
[LIB] core.js:264:79,84: number

date.js:22:1,31: constructor call
Error:
date.js:22:27,30: string
This type is incompatible with
[LIB] core.js:264:96,101: number

date.js:23:1,35: constructor call
Error:
date.js:23:31,34: string
This type is incompatible with
[LIB] core.js:264:113,118: number

date.js:24:1,40: constructor call
Error:
date.js:24:35,39: string
This type is incompatible with
[LIB] core.js:264:135,140: number

Found 8 errors
