
bound.js:4:10,15: null
This type is incompatible with
bound.js:47:13,18: string

bound.js:4:10,15: undefined
This type is incompatible with
bound.js:47:13,18: string

bound.js:4:10,15: null
This type is incompatible with
bound.js:53:15,20: string

bound.js:4:10,15: undefined
This type is incompatible with
bound.js:53:15,20: string

bound.js:9:22,22: null
This type is incompatible with
bound.js:9:13,18: string

bound.js:9:22,22: undefined
This type is incompatible with
bound.js:9:13,18: string

heap.js:5:22,24: null
This type is incompatible with
heap.js:5:13,18: string

heap.js:5:22,24: undefined
This type is incompatible with
heap.js:5:13,18: string

heap.js:40:24,26: null
This type is incompatible with
heap.js:40:15,20: string

heap.js:40:24,26: undefined
This type is incompatible with
heap.js:40:15,20: string

heap.js:47:13,16: null
This type is incompatible with
heap.js:48:15,20: string

heap.js:55:22,24: null
This type is incompatible with
heap.js:55:13,18: string

heap.js:55:22,24: undefined
This type is incompatible with
heap.js:55:13,18: string

heap.js:59:17,22: null
This type is incompatible with
heap.js:62:15,20: string

heap.js:59:17,22: undefined
This type is incompatible with
heap.js:62:15,20: string

lex.js:1:34,39: number
This type is incompatible with
lex.js:6:8,13: string

lex.js:9:35,40: number
This type is incompatible with
lex.js:15:8,13: string

lex.js:18:32,37: number
This type is incompatible with
lex.js:25:8,13: string

lex.js:28:38,43: number
This type is incompatible with
lex.js:35:8,13: string

local.js:5:22,22: null
This type is incompatible with
local.js:5:13,18: string

local.js:5:22,22: undefined
This type is incompatible with
local.js:5:13,18: string

local.js:45:14,19: null
This type is incompatible with
local.js:47:13,18: string

local.js:45:14,19: undefined
This type is incompatible with
local.js:47:13,18: string

local.js:51:14,19: null
This type is incompatible with
local.js:54:15,20: string

local.js:51:14,19: undefined
This type is incompatible with
local.js:54:15,20: string

null_tests.js:101:7,12: null
This type is incompatible with
null_tests.js:147:16,21: string

null_tests.js:101:7,12: undefined
This type is incompatible with
null_tests.js:147:16,21: string

Found 27 errors
