Error --------------------------------------------------- subdir/sublevel.js:5:2

Cannot cast `name` to string literal `node_modules/testproj2` because string
literal `subdir/custom_resolve_dir/testproj2` is incompatible with string
literal `node_modules/testproj2`.


Error ---------------------------------------------------------- toplevel.js:6:2

Cannot cast `name` to string literal `custom_resolve_dir/testproj` because
string literal `node_modules/testproj` is incompatible with string literal
`custom_resolve_dir/testproj`.



Found 2 errors
