Without --include-suppressed:
Found 0 errors
With --include-suppressed:
Error ------------------------------------------------------------------------------------------ <BUILTINS>/dom.js:156:3

Getters and setters can have side effects and are unsafe. [unsafe-getters-setters]

   156|   get innerHTML(): string;
          ^^^^^^^^^^^^^^^^^^^^^^^


Error ------------------------------------------------------------------------------------------ <BUILTINS>/dom.js:157:3

Getters and setters can have side effects and are unsafe. [unsafe-getters-setters]

   157|   set innerHTML(value: string | TrustedHTML): void;
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^


Error ----------------------------------------------------------------------------------------- <BUILTINS>/dom.js:1734:3

Getters and setters can have side effects and are unsafe. [unsafe-getters-setters]

   1734|   get innerHTML(): string;
           ^^^^^^^^^^^^^^^^^^^^^^^


Error ----------------------------------------------------------------------------------------- <BUILTINS>/dom.js:1735:3

Getters and setters can have side effects and are unsafe. [unsafe-getters-setters]

   1735|   set innerHTML(value: string | TrustedHTML): void;
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^


Error ----------------------------------------------------------------------------------------- <BUILTINS>/dom.js:1741:3

Getters and setters can have side effects and are unsafe. [unsafe-getters-setters]

   1741|   get outerHTML(): string;
           ^^^^^^^^^^^^^^^^^^^^^^^


Error ----------------------------------------------------------------------------------------- <BUILTINS>/dom.js:1742:3

Getters and setters can have side effects and are unsafe. [unsafe-getters-setters]

   1742|   set outerHTML(value: string | TrustedHTML): void;
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^


Error ----------------------------------------------------------------------------------------- <BUILTINS>/dom.js:2071:3

Getters and setters can have side effects and are unsafe. [unsafe-getters-setters]

   2071|   get innerHTML(): string;
           ^^^^^^^^^^^^^^^^^^^^^^^


Error ----------------------------------------------------------------------------------------- <BUILTINS>/dom.js:2072:3

Getters and setters can have side effects and are unsafe. [unsafe-getters-setters]

   2072|   set innerHTML(value: string | TrustedHTML): void;
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^


Error ----------------------------------------------------------------------------------------- <BUILTINS>/dom.js:3439:3

Getters and setters can have side effects and are unsafe. [unsafe-getters-setters]

   3439|   get srcdoc(): string;
           ^^^^^^^^^^^^^^^^^^^^


Error ----------------------------------------------------------------------------------------- <BUILTINS>/dom.js:3440:3

Getters and setters can have side effects and are unsafe. [unsafe-getters-setters]

   3440|   set srcdoc(value: string | TrustedHTML): void;
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^


Error ----------------------------------------------------------------------------------------- <BUILTINS>/dom.js:3951:3

Getters and setters can have side effects and are unsafe. [unsafe-getters-setters]

   3951|   get src(): string;
           ^^^^^^^^^^^^^^^^^


Error ----------------------------------------------------------------------------------------- <BUILTINS>/dom.js:3952:3

Getters and setters can have side effects and are unsafe. [unsafe-getters-setters]

   3952|   set src(value: string | TrustedScriptURL): void;
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^


Error ----------------------------------------------------------------------------------------- <BUILTINS>/dom.js:3953:3

Getters and setters can have side effects and are unsafe. [unsafe-getters-setters]

   3953|   get text(): string;
           ^^^^^^^^^^^^^^^^^^


Error ----------------------------------------------------------------------------------------- <BUILTINS>/dom.js:3954:3

Getters and setters can have side effects and are unsafe. [unsafe-getters-setters]

   3954|   set text(value: string | TrustedScript): void;
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^


Error ----------------------------------------------------------------------------------------------------- test.js:10:5

Sketchy null check on number [1] which is potentially 0. Perhaps you meant to check for null or undefined [2]?
[sketchy-null-number]

   test.js:10:5
   10| if (b){} //warning included by --include-suppressed (reported as an error)
           ^

References:
   test.js:8:9
    8| var b: ?number = 0;
               ^^^^^^ [1]
   test.js:8:8
    8| var b: ?number = 0;
              ^^^^^^^ [2]


Error ----------------------------------------------------------------------------------------------------- test.js:15:5

Sketchy null check on number [1] which is potentially 0. Perhaps you meant to check for null or undefined [2]?
[sketchy-null-number]

   test.js:15:5
   15| if (c){} //error included by --include-suppressed
           ^

References:
   test.js:13:9
   13| var c: ?number = 0;
               ^^^^^^ [1]
   test.js:13:8
   13| var c: ?number = 0;
              ^^^^^^^ [2]



Found 16 errors
