declare.js:3:18 = {
  "end":20,
  "endline":3,
  "line":3,
  "loc":{
    "end":{"column":20,"line":3,"offset":30},
    "source":"declare.js",
    "start":{"column":18,"line":3,"offset":27},
    "type":"SourceFile"
  },
  "path":"declare.js",
  "reasons":[],
  "start":18,
  "types":{"evaluated":null,"unevaluated":{"type":"() => void"}}
}
declare.js:5:18 = {
  "end":20,
  "endline":5,
  "line":5,
  "loc":{
    "end":{"column":20,"line":5,"offset":61},
    "source":"declare.js",
    "start":{"column":18,"line":5,"offset":58},
    "type":"SourceFile"
  },
  "path":"declare.js",
  "reasons":[],
  "start":18,
  "types":{"evaluated":null,"unevaluated":{"type":"(() => string) & (() => number)"}}
}
declare.js:6:18 = {
  "end":20,
  "endline":6,
  "line":6,
  "loc":{
    "end":{"column":20,"line":6,"offset":93},
    "source":"declare.js",
    "start":{"column":18,"line":6,"offset":90},
    "type":"SourceFile"
  },
  "path":"declare.js",
  "reasons":[],
  "start":18,
  "types":{"evaluated":null,"unevaluated":{"type":"(() => string) & (() => number)"}}
}
declare.js:8:18 = {
  "end":0,
  "endline":0,
  "line":0,
  "loc":{
    "end":{"column":0,"line":0,"offset":0},
    "source":null,
    "start":{"column":1,"line":0,"offset":0},
    "type":null
  },
  "path":"",
  "reasons":[],
  "start":1,
  "types":null
}
declare.js:9:18 = {
  "end":0,
  "endline":0,
  "line":0,
  "loc":{
    "end":{"column":0,"line":0,"offset":0},
    "source":null,
    "start":{"column":1,"line":0,"offset":0},
    "type":null
  },
  "path":"",
  "reasons":[],
  "start":1,
  "types":null
}
function.js:4:3 = {
  "end":5,
  "endline":4,
  "line":4,
  "loc":{
    "end":{"column":5,"line":4,"offset":27},
    "source":"function.js",
    "start":{"column":3,"line":4,"offset":24},
    "type":"SourceFile"
  },
  "path":"function.js",
  "reasons":[],
  "start":3,
  "types":{"evaluated":null,"unevaluated":{"type":"() => void"}}
}
function.js:8:3 = {
  "end":5,
  "endline":8,
  "line":8,
  "loc":{
    "end":{"column":5,"line":8,"offset":60},
    "source":"function.js",
    "start":{"column":3,"line":8,"offset":57},
    "type":"SourceFile"
  },
  "path":"function.js",
  "reasons":[],
  "start":3,
  "types":{"evaluated":null,"unevaluated":{"type":"() => void"}}
}
function.js:12:3 = {
  "end":3,
  "endline":12,
  "line":12,
  "loc":{
    "end":{"column":3,"line":12,"offset":102},
    "source":"function.js",
    "start":{"column":3,"line":12,"offset":101},
    "type":"SourceFile"
  },
  "path":"function.js",
  "reasons":[],
  "start":3,
  "types":{"evaluated":null,"unevaluated":{"type":"<T>(x: T) => T"}}
}
function.js:16:3 = {
  "end":3,
  "endline":16,
  "line":16,
  "loc":{
    "end":{"column":3,"line":16,"offset":148},
    "source":"function.js",
    "start":{"column":3,"line":16,"offset":147},
    "type":"SourceFile"
  },
  "path":"function.js",
  "reasons":[],
  "start":3,
  "types":{"evaluated":null,"unevaluated":{"type":"<T>(x: T) => T"}}
}
default.js:4:16 = {
  "end":16,
  "endline":4,
  "line":4,
  "loc":{
    "end":{"column":16,"line":4,"offset":37},
    "source":"default.js",
    "start":{"column":16,"line":4,"offset":36},
    "type":"SourceFile"
  },
  "path":"default.js",
  "reasons":[],
  "start":16,
  "types":{"evaluated":null,"unevaluated":{"type":"number"}}
}
default.js:5:17 = {
  "end":17,
  "endline":5,
  "line":5,
  "loc":{
    "end":{"column":17,"line":5,"offset":59},
    "source":"default.js",
    "start":{"column":17,"line":5,"offset":58},
    "type":"SourceFile"
  },
  "path":"default.js",
  "reasons":[],
  "start":17,
  "types":{"evaluated":null,"unevaluated":{"type":"number"}}
}
function-poly-0.js:3:10 = {
  "end":10,
  "endline":3,
  "line":3,
  "loc":{
    "end":{"column":10,"line":3,"offset":20},
    "source":"function-poly-0.js",
    "start":{"column":10,"line":3,"offset":19},
    "type":"SourceFile"
  },
  "path":"function-poly-0.js",
  "reasons":[],
  "start":10,
  "types":{"evaluated":null,"unevaluated":{"type":"<T>(x: T) => T"}}
}
function-poly-0.js:3:30 = {
  "end":33,
  "endline":3,
  "line":3,
  "loc":{
    "end":{"column":33,"line":3,"offset":43},
    "source":"function-poly-0.js",
    "start":{"column":33,"line":3,"offset":42},
    "type":"SourceFile"
  },
  "path":"function-poly-0.js",
  "reasons":[],
  "start":33,
  "types":{"evaluated":null,"unevaluated":{"type":"T"}}
}
function-poly-0.js:4:7 = {
  "end":7,
  "endline":4,
  "line":4,
  "loc":{
    "end":{"column":7,"line":4,"offset":54},
    "source":"function-poly-0.js",
    "start":{"column":7,"line":4,"offset":53},
    "type":"SourceFile"
  },
  "path":"function-poly-0.js",
  "reasons":[],
  "start":7,
  "types":{"evaluated":null,"unevaluated":{"type":"number"}}
}
function-poly-1.js:3:10 = {
  "end":10,
  "endline":3,
  "line":3,
  "loc":{
    "end":{"column":10,"line":3,"offset":20},
    "source":"function-poly-1.js",
    "start":{"column":10,"line":3,"offset":19},
    "type":"SourceFile"
  },
  "path":"function-poly-1.js",
  "reasons":[],
  "start":10,
  "types":{"evaluated":null,"unevaluated":{"type":"<T>(x: T) => T"}}
}
function-poly-1.js:3:3 = {
  "end":33,
  "endline":3,
  "line":3,
  "loc":{
    "end":{"column":33,"line":3,"offset":43},
    "source":"function-poly-1.js",
    "start":{"column":33,"line":3,"offset":42},
    "type":"SourceFile"
  },
  "path":"function-poly-1.js",
  "reasons":[],
  "start":33,
  "types":{"evaluated":null,"unevaluated":{"type":"T"}}
}
function-poly-1.js:4:7 = {
  "end":7,
  "endline":4,
  "line":4,
  "loc":{
    "end":{"column":7,"line":4,"offset":54},
    "source":"function-poly-1.js",
    "start":{"column":7,"line":4,"offset":53},
    "type":"SourceFile"
  },
  "path":"function-poly-1.js",
  "reasons":[],
  "start":7,
  "types":{"evaluated":null,"unevaluated":{"type":"number"}}
}
function-poly-2.js:3:10 = {
  "end":14,
  "endline":3,
  "line":3,
  "loc":{
    "end":{"column":14,"line":3,"offset":24},
    "source":"function-poly-2.js",
    "start":{"column":10,"line":3,"offset":19},
    "type":"SourceFile"
  },
  "path":"function-poly-2.js",
  "reasons":[],
  "start":10,
  "types":{"evaluated":null,"unevaluated":{"type":"<TOuter>(y: TOuter) => void"}}
}
function-poly-2.js:4:12 = {
  "end":16,
  "endline":4,
  "line":4,
  "loc":{
    "end":{"column":16,"line":4,"offset":62},
    "source":"function-poly-2.js",
    "start":{"column":12,"line":4,"offset":57},
    "type":"SourceFile"
  },
  "path":"function-poly-2.js",
  "reasons":[],
  "start":12,
  "types":{"evaluated":null,"unevaluated":{"type":"<T>(x: T, z: TOuter | T) => T"}}
}
function-poly-2.js:5:5 = {
  "end":5,
  "endline":5,
  "line":5,
  "loc":{
    "end":{"column":5,"line":5,"offset":97},
    "source":"function-poly-2.js",
    "start":{"column":5,"line":5,"offset":96},
    "type":"SourceFile"
  },
  "path":"function-poly-2.js",
  "reasons":[],
  "start":5,
  "types":{"evaluated":null,"unevaluated":{"type":"TOuter"}}
}
function-poly-2.js:6:5 = {
  "end":9,
  "endline":6,
  "line":6,
  "loc":{
    "end":{"column":9,"line":6,"offset":108},
    "source":"function-poly-2.js",
    "start":{"column":5,"line":6,"offset":103},
    "type":"SourceFile"
  },
  "path":"function-poly-2.js",
  "reasons":[],
  "start":5,
  "types":{"evaluated":null,"unevaluated":{"type":"(x: T, z: TOuter | T) => T"}}
}
function-poly-2.js:7:12 = {
  "end":12,
  "endline":7,
  "line":7,
  "loc":{
    "end":{"column":12,"line":7,"offset":128},
    "source":"function-poly-2.js",
    "start":{"column":12,"line":7,"offset":127},
    "type":"SourceFile"
  },
  "path":"function-poly-2.js",
  "reasons":[],
  "start":12,
  "types":{"evaluated":null,"unevaluated":{"type":"T"}}
}
function-poly-2.js:9:13 = {
  "end":17,
  "endline":9,
  "line":9,
  "loc":{
    "end":{"column":17,"line":9,"offset":151},
    "source":"function-poly-2.js",
    "start":{"column":13,"line":9,"offset":146},
    "type":"SourceFile"
  },
  "path":"function-poly-2.js",
  "reasons":[],
  "start":13,
  "types":{
    "evaluated":null,
    "unevaluated":{"type":"(x: number, z: TOuter | number) => number"}
  }
}
function-poly-2.js:11:12 = {
  "end":17,
  "endline":11,
  "line":11,
  "loc":{
    "end":{"column":17,"line":11,"offset":177},
    "source":"function-poly-2.js",
    "start":{"column":12,"line":11,"offset":171},
    "type":"SourceFile"
  },
  "path":"function-poly-2.js",
  "reasons":[],
  "start":12,
  "types":{"evaluated":null,"unevaluated":{"type":"<T>(x: T) => T"}}
}
function-poly-4.js:3:11 = {
  "end":12,
  "endline":3,
  "line":3,
  "loc":{
    "end":{"column":12,"line":3,"offset":22},
    "source":"function-poly-4.js",
    "start":{"column":10,"line":3,"offset":19},
    "type":"SourceFile"
  },
  "path":"function-poly-4.js",
  "reasons":[],
  "start":10,
  "types":{"evaluated":null,"unevaluated":{"type":"<T>(x: T) => {f: T}"}}
}
function-poly-4.js:7:7 = {
  "end":9,
  "endline":7,
  "line":7,
  "loc":{
    "end":{"column":9,"line":7,"offset":73},
    "source":"function-poly-4.js",
    "start":{"column":7,"line":7,"offset":70},
    "type":"SourceFile"
  },
  "path":"function-poly-4.js",
  "reasons":[],
  "start":7,
  "types":{"evaluated":null,"unevaluated":{"type":"<T>(x: T) => {f: T}"}}
}
function-poly-4.js:9:7 = {
  "end":9,
  "endline":9,
  "line":9,
  "loc":{
    "end":{"column":9,"line":9,"offset":119},
    "source":"function-poly-4.js",
    "start":{"column":7,"line":9,"offset":116},
    "type":"SourceFile"
  },
  "path":"function-poly-4.js",
  "reasons":[],
  "start":7,
  "types":{"evaluated":null,"unevaluated":{"type":"{m<T>(x: T): {f: T}}"}}
}
function-poly-5.js:3:10 = {
  "end":12,
  "endline":3,
  "line":3,
  "loc":{
    "end":{"column":12,"line":3,"offset":22},
    "source":"function-poly-5.js",
    "start":{"column":10,"line":3,"offset":19},
    "type":"SourceFile"
  },
  "path":"function-poly-5.js",
  "reasons":[],
  "start":10,
  "types":{
    "evaluated":null,
    "unevaluated":{"type":"<T: number | string>(x: T) => number"}
  }
}
function-poly-6.js:7:6 = {
  "end":8,
  "endline":7,
  "line":7,
  "loc":{
    "end":{"column":8,"line":7,"offset":84},
    "source":"function-poly-6.js",
    "start":{"column":6,"line":7,"offset":81},
    "type":"SourceFile"
  },
  "path":"function-poly-6.js",
  "reasons":[],
  "start":6,
  "types":null
}
