Error ------------------------------------------------------------------------------------------------------ test.js:4:2

Property `instance` is missing in `{props: {}, ...}` [1]. [prop-missing]

   test.js:4:2
   4| <noinstance ref={ref} />; // Error: the intrinsic has no `instance`
       ^^^^^^^^^^

References:
   lib/jsx.js:2:15
   2|   noinstance: {props: {}, ...},
                    ^^^^^^^^^^^^^^^^ [1]



Found 1 error
