Error -------------------------------------------------------------- test.js:3:2

Experimental decorator usage. Decorators are an early stage proposal that may
change. Additionally, Flow does not account for the type implications of
decorators at this time.


Error -------------------------------------------------------------- test.js:5:4

Experimental decorator usage. Decorators are an early stage proposal that may
change. Additionally, Flow does not account for the type implications of
decorators at this time.


Error -------------------------------------------------------------- test.js:8:4

Experimental decorator usage. Decorators are an early stage proposal that may
change. Additionally, Flow does not account for the type implications of
decorators at this time.



Found 3 errors
