dictionary.js:3:7 = const d1: {
  "": null,
  " ": null,
  "'": null,
  "1": null,
  _: null,
  "a b": null,
  "a'b": null,
  ab: null,
  get x(): null,
  set y(string): void
}
dictionary.js:3:7,3:8
dictionary.js:19:7 = const d2: {
  "": null,
  " ": null,
  '"': null,
  "1": null,
  _: null,
  "a b": null,
  'a"b': null,
  ab: null,
  get x(): null,
  set y(string): void
}
dictionary.js:19:7,19:8
jsx.js:7:12 = "div"
jsx.js:7:12,7:14
jsx.js:7:16 = (property) style: string
jsx.js:7:16,7:20
jsx.js:7:23 = const props: {data: A, name: string, ...}

'A' defined at jsx.js:4:20

jsx.js:7:23,7:27
jsx.js:7:29 = (property) data: A

'A' defined at jsx.js:4:20

jsx.js:7:29,7:32
jsx.js:7:35 = "literal"
jsx.js:7:35,7:36
jsx.js:7:48 = true
jsx.js:7:48,7:53
jsx.js:7:59 = const props: {data: A, name: string, ...}

'A' defined at jsx.js:4:20

jsx.js:7:59,7:63
jsx.js:8:17 = const props: {data: A, name: string, ...}

'A' defined at jsx.js:4:20

jsx.js:8:17,8:21
jsx.js:8:23 = (property) name: string
jsx.js:8:23,8:26
jsx.js:8:30 = "div"
jsx.js:8:30,8:32
jsx.js:11:17 = const str: string
jsx.js:11:17,11:19
jsx.js:18:12 = const o: {r: typeof C}

'C' defined at jsx.js:13:6

jsx.js:18:12,18:12
jsx.js:18:14 = class C

'C' defined at jsx.js:13:6

jsx.js:18:14,18:14
jsx.js:18:12 = const o: {r: typeof C}

'C' defined at jsx.js:13:6

jsx.js:18:22,18:22
jsx.js:18:24 = class C

'C' defined at jsx.js:13:6

jsx.js:18:24,18:24
literals.js:6:7 = const s: "A"
literals.js:6:7,6:7
literals.js:7:7 = const n: 1
literals.js:7:7,7:7
literals.js:8:7 = const f: 1.01
literals.js:8:7,8:7
literals.js:9:7 = const b: true
literals.js:9:7,9:7
literals.js:10:7 = const u: boolean | number | string
literals.js:10:7,10:7
literals.js:13:6 = type S = "A"

'S' defined at literals.js:13:5

literals.js:13:6,13:6
literals.js:14:6 = type N = 1

'N' defined at literals.js:14:5

literals.js:14:6,14:6
literals.js:15:6 = type F = 1.01

'F' defined at literals.js:15:5

literals.js:15:6,15:6
literals.js:16:6 = type B = true

'B' defined at literals.js:16:5

literals.js:16:6,16:6
literals.js:17:6 = type U = "A" | 1 | 1.01 | true

'U' defined at literals.js:17:5

literals.js:17:6,17:6
literals.js:19:7 = const f1: (x: "A" | "B") => "A" | "B"
literals.js:19:7,19:8
literals.js:21:7 = const o1: {f: string}
literals.js:21:7,21:8
literals.js:22:7 = const o2: {f: "f"}
literals.js:22:7,22:8
literals.js:24:7 = const f2: (x: "A" | "B") => "A" | "B"
literals.js:24:7,24:8
literals.js:28:7 = const numLitArray: Array<number>
literals.js:28:7,28:17
literals.js:31:7 = const a_n: A<number>

'A' defined at literals.js:30:6

literals.js:31:7,31:9
literals.js:32:7 = const a_1: A<1>

'A' defined at literals.js:30:6

literals.js:32:7,32:9
new-array.js:3:15 = 
 Returns a new JavaScript array with its length property set to that number.
 (Note: this implies an array of arrayLength empty slots, not slots with actual undefined
 values. See [sparse arrays](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Indexed_collections#sparse_arrays)).
constructor Array(arrayLength?: number): void
new-array.js:3:13,3:17
object-resolution.js:5:2 = const ro: {readonly p: number}
object-resolution.js:5:1,5:2
object-resolution.js:10:2 = const diff: Omit<O2, "p">

'O2' defined at object-resolution.js:8:5
'Omit' defined at (lib) core.js:3350:5

object-resolution.js:10:1,10:4
object-resolution.js:13:5 = const spread: {p: number, q: string, ...}
object-resolution.js:13:5,13:10
object.js:3:17 = const obj: {a?: {b: ?{c: null | {d: number, ...}, ...}, ...}, ...}
object.js:3:15,3:17
object.js:3:21 = (property) a: void | {b: ?{c: null | {d: number, ...}, ...}, ...}
object.js:3:21,3:21
object.js:3:26 = (property) b: ?{c: null | {d: number, ...}, ...}
object.js:3:26,3:26
object.js:3:31 = (property) c: null | {d: number, ...}
object.js:3:31,3:31
object.js:3:42 = (property) d: number
object.js:3:42,3:42
object.js:6:5 = const obj: {a?: {b: ?{c: null | {d: number, ...}, ...}, ...}, ...}
object.js:6:3,6:5
object.js:6:7 = (property) a: void | {b: ?{c: null | {d: number, ...}, ...}, ...}
object.js:6:7,6:7
object.js:7:10 = (property) a: {b: ?{c: null | {d: number, ...}, ...}, ...}

Refined at object.js:6:2

object.js:7:10,7:10
object.js:7:12 = (property) b: ?{c: null | {d: number, ...}, ...}
object.js:7:12,7:12
object.js:8:14 = (property) b: {c: null | {d: number, ...}, ...}

Refined at object.js:7:5

object.js:8:14,8:14
object.js:8:16 = (property) c: null | {d: number, ...}
object.js:8:16,8:16
object.js:9:18 = (property) c: {d: number, ...}

Refined at object.js:8:7

object.js:9:18,9:18
object.js:9:34 = (property) d: number

Refined at object.js:9:9

object.js:9:34,9:34
object.js:15:3 = (method) m(n: string): string
object.js:15:3,15:3
object.js:16:3 = (property) n: (k: number) => number
object.js:16:3,16:3
object.js:19:3 = let myobj: {m(n: string): string, n: (k: number) => number}
object.js:19:1,19:5
object.js:19:7 = (method) m(n: string): string
object.js:19:7,19:7
object.js:20:7 = (method) m(n: string): string
object.js:20:7,20:7
object.js:21:7 = (property) n: (k: number) => number
object.js:21:7,21:7
object.js:22:7 = (property) n: (k: number) => number
object.js:22:7,22:7
object.js:35:1 = const litobj: {
  b: 0b111,
  d: 11,
  f: "ff",
  g: 'g"g',
  h: 'h"h',
  i: "i'i",
  j: "'",
  x: 0x111,
  ...
}
object.js:35:1,35:6
object.js:37:7
Flags:
const frozenObject1: {readonly A: "a", readonly B: "b"}
object.js:37:7,37:19

object.js:40:7
Flags:
const frozenObject2: {readonly A: "a", readonly B: {C: string}}
object.js:40:7,40:19

object.js:43:5
Flags:
(method) constructor(this: typeof Object.prototype, ...empty): any (implicit)
object.js:43:5,43:15

object.js:46:5
Flags:
(method) constructor(this: typeof Object.prototype, ...empty): any (implicit)
object.js:46:5,46:15

optional_chaining.js:16:7 = const n: number | void
optional_chaining.js:16:7,16:7
optional_chaining.js:16:11 = const foo: ?Foo

'Foo' defined at optional_chaining.js:3:6

optional_chaining.js:16:11,16:13
optional_chaining.js:16:16 = (property) Foo.bar: void | Bar

'Bar' defined at optional_chaining.js:7:6

optional_chaining.js:16:16,16:18
optional_chaining.js:16:20 = (property) Bar.baz: void | Baz

'Baz' defined at optional_chaining.js:11:6

optional_chaining.js:16:20,16:22
optional_chaining.js:16:24 = (property) Baz.qux: number | void
optional_chaining.js:16:24,16:26
identifier.js:5:4
Flags:
const fooBar: number
identifier.js:5:4,5:9

identifier.js:8:9
Flags:
const fooBar: number
identifier.js:8:4,8:9

identifier.js:11:10
Flags:
const fooBar: number
identifier.js:11:4,11:9

identifier.js:14:10
Flags:
const fooBar: number
identifier.js:14:4,14:9

reduce_recursive.js:16:25
Flags:
(parameter) row: Obj

'Obj' defined at reduce_recursive.js:6:12

reduce_recursive.js:16:25,16:27

spread.js:4:11
Flags:
const z: {...T, ...S, prop: number}
spread.js:4:11,4:11

object_members.js:7:3
Flags:
(property) p: number
object_members.js:7:3,7:3

object_members.js:9:3
Flags:
(method) m(): number
object_members.js:9:3,9:3

object_members.js:13:7
Flags:
(getter) g: number
object_members.js:13:7,13:7

object_members.js:17:7
Flags:
(setter) s: number
object_members.js:17:7,17:7

object_members.js:19:3
Flags:
(property) 'quoted': number
object_members.js:19:3,19:10

object_members.js:21:3
Flags:
(property) 3: string
object_members.js:21:3,21:3

object_members.js:23:7
Flags:
(property) spread: number
object_members.js:23:7,23:12

object_members.js:28:29
Flags:
(property) inner: 1
object_members.js:28:29,28:33

