/**
 * Copyright (c) 2013-present, Facebook, Inc.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 */

declare class StyleSheet {
  disabled: boolean;
  href: string;
  media: MediaList;
  ownerNode: Node;
  parentStyleSheet: ?StyleSheet;
  title: string;
  type: string;
}

declare class StyleSheetList {
  @@iterator(): Iterator<StyleSheet>;
  length: number;
  [index: number]: StyleSheet;
}

declare class MediaList {
  @@iterator(): Iterator<string>;
  mediaText: string;
  length: number;
  item(index: number): ?string;
  deleteMedium(oldMedium: string): void;
  appendMedium(newMedium: string): void;
  [index: number]: string;
}

declare class CSSStyleSheet extends StyleSheet {
  cssRules: CSSRuleList;
  ownerRule: ?CSSRule;
  deleteRule(index: number): void;
  insertRule(rule: string, index: number): void;
}

declare class CSSRule {
  cssText: string;
  parentRule: ?CSSRule;
  parentStyleSheet: ?CSSStyleSheet;
  type: number;
  static STYLE_RULE: number;
  static MEDIA_RULE: number;
  static FONT_FACE_RULE: number;
  static PAGE_RULE: number;
  static IMPORT_RULE: number;
  static CHARSET_RULE: number;
  static UNKNOWN_RULE: number;
  static KEYFRAMES_RULE: number;
  static KEYFRAME_RULE: number;
  static NAMESPACE_RULE: number;
  static COUNTER_STYLE_RULE: number;
  static SUPPORTS_RULE: number;
  static DOCUMENT_RULE: number;
  static FONT_FEATURE_VALUES_RULE: number;
  static VIEWPORT_RULE: number;
  static REGION_STYLE_RULE: number;
}

declare class CSSRuleList {
  @@iterator(): Iterator<CSSRule>;
  length: number;
  item(index: number): ?CSSRule;
  [index: number]: CSSRule;
}

declare class CSSStyleDeclaration {
  @@iterator(): Iterator<string>;
  /* DOM CSS Properties */
  alignContent: string | null;
  alignItems: string | null;
  alignSelf: string | null;
  all: string | null;
  animation: string | null;
  animationDelay: string | null;
  animationDirection: string | null;
  animationDuration: string | null;
  animationFillMode: string | null;
  animationIterationCount: string | null;
  animationName: string | null;
  animationPlayState: string | null;
  animationTimingFunction: string | null;
  backdropFilter: string | null;
  webkitBackdropFilter: string | null;
  backfaceVisibility: string | null;
  background: string | null;
  backgroundAttachment: string | null;
  backgroundBlendMode: string | null;
  backgroundClip: string | null;
  backgroundColor: string | null;
  backgroundImage: string | null;
  backgroundOrigin: string | null;
  backgroundPosition: string | null;
  backgroundPositionX: string | null;
  backgroundPositionY: string | null;
  backgroundRepeat: string | null;
  backgroundSize: string | null;
  blockSize: string | null;
  border: string | null;
  borderBlockEnd: string | null;
  borderBlockEndColor: string | null;
  borderBlockEndStyle: string | null;
  borderBlockEndWidth: string | null;
  borderBlockStart: string | null;
  borderBlockStartColor: string | null;
  borderBlockStartStyle: string | null;
  borderBlockStartWidth: string | null;
  borderBottom: string | null;
  borderBottomColor: string | null;
  borderBottomLeftRadius: string | null;
  borderBottomRightRadius: string | null;
  borderBottomStyle: string | null;
  borderBottomWidth: string | null;
  borderCollapse: string | null;
  borderColor: string | null;
  borderImage: string | null;
  borderImageOutset: string | null;
  borderImageRepeat: string | null;
  borderImageSlice: string | null;
  borderImageSource: string | null;
  borderImageWidth: string | null;
  borderInlineEnd: string | null;
  borderInlineEndColor: string | null;
  borderInlineEndStyle: string | null;
  borderInlineEndWidth: string | null;
  borderInlineStart: string | null;
  borderInlineStartColor: string | null;
  borderInlineStartStyle: string | null;
  borderInlineStartWidth: string | null;
  borderLeft: string | null;
  borderLeftColor: string | null;
  borderLeftStyle: string | null;
  borderLeftWidth: string | null;
  borderRadius: string | null;
  borderRight: string | null;
  borderRightColor: string | null;
  borderRightStyle: string | null;
  borderRightWidth: string | null;
  borderSpacing: string | null;
  borderStyle: string | null;
  borderTop: string | null;
  borderTopColor: string | null;
  borderTopLeftRadius: string | null;
  borderTopRightRadius: string | null;
  borderTopStyle: string | null;
  borderTopWidth: string | null;
  borderWidth: string | null;
  bottom: string | null;
  boxDecorationBreak: string | null;
  boxShadow: string | null;
  boxSizing: string | null;
  breakAfter: string | null;
  breakBefore: string | null;
  breakInside: string | null;
  captionSide: string | null;
  clear: string | null;
  clip: string | null;
  clipPath: string | null;
  color: string | null;
  columns: string | null;
  columnCount: string | null;
  columnFill: string | null;
  columnGap: string | null;
  columnRule: string | null;
  columnRuleColor: string | null;
  columnRuleStyle: string | null;
  columnRuleWidth: string | null;
  columnSpan: string | null;
  columnWidth: string | null;
  contain: string | null;
  content: string | null;
  counterIncrement: string | null;
  counterReset: string | null;
  cursor: string | null;
  direction: string | null;
  display: string | null;
  emptyCells: string | null;
  filter: string | null;
  flex: string | null;
  flexBasis: string | null;
  flexDirection: string | null;
  flexFlow: string | null;
  flexGrow: string | null;
  flexShrink: string | null;
  flexWrap: string | null;
  float: string | null;
  font: string | null;
  fontFamily: string | null;
  fontFeatureSettings: string | null;
  fontKerning: string | null;
  fontLanguageOverride: string | null;
  fontSize: string | null;
  fontSizeAdjust: string | null;
  fontStretch: string | null;
  fontStyle: string | null;
  fontSynthesis: string | null;
  fontVariant: string | null;
  fontVariantAlternates: string | null;
  fontVariantCaps: string | null;
  fontVariantEastAsian: string | null;
  fontVariantLigatures: string | null;
  fontVariantNumeric: string | null;
  fontVariantPosition: string | null;
  fontWeight: string | null;
  grad: string | null;
  grid: string | null;
  gridArea: string | null;
  gridAutoColumns: string | null;
  gridAutoFlow: string | null;
  gridAutoPosition: string | null;
  gridAutoRows: string | null;
  gridColumn: string | null;
  gridColumnStart: string | null;
  gridColumnEnd: string | null;
  gridRow: string | null;
  gridRowStart: string | null;
  gridRowEnd: string | null;
  gridTemplate: string | null;
  gridTemplateAreas: string | null;
  gridTemplateRows: string | null;
  gridTemplateColumns: string | null;
  height: string | null;
  hyphens: string | null;
  imageRendering: string | null;
  imageResolution: string | null;
  imageOrientation: string | null;
  imeMode: string | null;
  inherit: string | null;
  initial: string | null;
  inlineSize: string | null;
  isolation: string | null;
  justifyContent: string | null;
  left: string | null;
  letterSpacing: string | null;
  lineBreak: string | null;
  lineHeight: string | null;
  listStyle: string | null;
  listStyleImage: string | null;
  listStylePosition: string | null;
  listStyleType: string | null;
  margin: string | null;
  marginBlockEnd: string | null;
  marginBlockStart: string | null;
  marginBottom: string | null;
  marginInlineEnd: string | null;
  marginInlineStart: string | null;
  marginLeft: string | null;
  marginRight: string | null;
  marginTop: string | null;
  marks: string | null;
  mask: string | null;
  maskType: string | null;
  maxBlockSize: string | null;
  maxHeight: string | null;
  maxInlineSize: string | null;
  maxWidth: string | null;
  minBlockSize: string | null;
  minHeight: string | null;
  minInlineSize: string | null;
  minWidth: string | null;
  mixBlendMode: string | null;
  mozTransform: string | null;
  mozTransformOrigin: string | null;
  mozTransitionDelay: string | null;
  mozTransitionDuration: string | null;
  mozTransitionProperty: string | null;
  mozTransitionTimingFunction: string | null;
  objectFit: string | null;
  objectPosition: string | null;
  offsetBlockEnd: string | null;
  offsetBlockStart: string | null;
  offsetInlineEnd: string | null;
  offsetInlineStart: string | null;
  opacity: string | null;
  order: string | null;
  orphans: string | null;
  outline: string | null;
  outlineColor: string | null;
  outlineOffset: string | null;
  outlineStyle: string | null;
  outlineWidth: string | null;
  overflow: string | null;
  overflowWrap: string | null;
  overflowX: string | null;
  overflowY: string | null;
  padding: string | null;
  paddingBlockEnd: string | null;
  paddingBlockStart: string | null;
  paddingBottom: string | null;
  paddingInlineEnd: string | null;
  paddingInlineStart: string | null;
  paddingLeft: string | null;
  paddingRight: string | null;
  paddingTop: string | null;
  pageBreakAfter: string | null;
  pageBreakBefore: string | null;
  pageBreakInside: string | null;
  perspective: string | null;
  perspectiveOrigin: string | null;
  pointerEvents: string | null;
  position: string | null;
  quotes: string | null;
  rad: string | null;
  resize: string | null;
  right: string | null;
  rubyAlign: string | null;
  rubyMerge: string | null;
  rubyPosition: string | null;
  scrollBehavior: string | null;
  scrollSnapCoordinate: string | null;
  scrollSnapDestination: string | null;
  scrollSnapPointsX: string | null;
  scrollSnapPointsY: string | null;
  scrollSnapType: string | null;
  shapeImageThreshold: string | null;
  shapeMargin: string | null;
  shapeOutside: string | null;
  tableLayout: string | null;
  tabSize: string | null;
  textAlign: string | null;
  textAlignLast: string | null;
  textCombineUpright: string | null;
  textDecoration: string | null;
  textDecorationColor: string | null;
  textDecorationLine: string | null;
  textDecorationStyle: string | null;
  textIndent: string | null;
  textOrientation: string | null;
  textOverflow: string | null;
  textRendering: string | null;
  textShadow: string | null;
  textTransform: string | null;
  textUnderlinePosition: string | null;
  top: string | null;
  touchAction: string | null;
  transform: string | null;
  transformOrigin: string | null;
  transformStyle: string | null;
  transition: string | null;
  transitionDelay: string | null;
  transitionDuration: string | null;
  transitionProperty: string | null;
  transitionTimingFunction: string | null;
  turn: string | null;
  unicodeBidi: string | null;
  unicodeRange: string | null;
  verticalAlign: string | null;
  visibility: string | null;
  webkitOverflowScrolling: string | null;
  webkitTransform: string | null;
  webkitTransformOrigin: string | null;
  webkitTransitionDelay: string | null;
  webkitTransitionDuration: string | null;
  webkitTransitionProperty: string | null;
  webkitTransitionTimingFunction: string | null;
  whiteSpace: string | null;
  widows: string | null;
  width: string | null;
  willChange: string | null;
  wordBreak: string | null;
  wordSpacing: string | null;
  wordWrap: string | null;
  writingMode: string | null;
  zIndex: string | null;

  cssFloat: string;
  cssText: string;
  getPropertyPriority(property: string): string;
  getPropertyValue(property:string): string;
  item(index: number): string;
  [index: number]: string;
  length: number;
  parentRule: CSSRule;
  removeProperty(property: string): string;
  setProperty(property: string, value: ?string, priority: ?string): void;
  setPropertyPriority(property: string, priority: string): void;
}

declare class TransitionEvent extends Event {
  elapsedTime: number; // readonly
  pseudoElement: string; // readonly
  propertyName: string; // readonly
}
