test.js:8:11
Flags:
const a: number
test.js:8:11,8:11

test.js:17:15
Flags:
const a: string
test.js:17:15,17:15

test.js:26:12
Flags:
const a: number
test.js:26:12,26:12

test.js:36:5
Flags:
const foo: 1
test.js:36:5,36:7

test.js:46:6
Flags:
const foo: 1
test.js:46:6,46:8

test.js:57:5
Flags:
const O: {bar: 1, foo: 1}
test.js:57:5,57:5

test.js:59:7
Flags:
1
test.js:59:7,59:9

test.js:69:6
Flags:
const O: {bar: 1, foo: 1}
test.js:69:6,69:6

test.js:71:8
Flags:
1
test.js:71:8,71:10

test.js:79:16
Flags:
const a: Readonly<[1, 2]>
test.js:79:16,79:16

test.js:90:16
Flags:
const a: Readonly<[number, number]>
test.js:90:16,90:16

