Error ------------------------------------------------------------ test2.js:7:14

Cannot assign `new C()` to `y` because `C` is incompatible with `B`.


Error ------------------------------------------------------------ test3.js:6:41

Cannot assign `c` to `a` because in type argument `Z`, boolean is incompatible
with array type.


Error ------------------------------------------------------------ test4.js:7:20

Cannot call `foo` with object literal bound to `x` because property `f` is
missing in object literal but exists in `O`.


Error ----------------------------------------------------------- test4.js:13:12

Cannot call `foo` with object literal bound to `x` because property `f` is
missing in object literal but exists in `O`.



Found 4 errors
