
Stop any already-running server.

Quick start.

Expect no errors.
No errors!

The Flow server is currently in lazy mode and is only checking 0/3 source files (+ 2/2 libdefs).
To learn more, visit flow.org/en/docs/lang/lazy-modes

Change @flow file with dependency on a @flow file in a cycle, expect no error.
No errors!

The Flow server is currently in lazy mode and is only checking 1/3 source files (+ 2/2 libdefs).
To learn more, visit flow.org/en/docs/lang/lazy-modes

Done!
