component.js:1:11
Flags:
React$AbstractComponent<{+foo: number}, mixed, React$Node>
= React$AbstractComponent<{+foo: number}, mixed, React$Node>
component.js:1:11,1:13

component.js:3:11
Flags:
React$AbstractComponent<{+bar: string}, mixed, number>
= React$AbstractComponent<{+bar: string}, mixed, number>
component.js:3:11,3:13

render_types.js:1:6
Flags:
type X = renders null
render_types.js:1:6,1:6

render_types.js:3:6
Flags:
type Y = renders (null | number)
render_types.js:3:6,3:6

