Error --------------------------------------------------- delegate_yield.js:3:19

Cannot assign `yield` to `x` because number is incompatible with undefined.


Error --------------------------------------------------- delegate_yield.js:17:6

Cannot cast `x` to undefined because number is incompatible with undefined.


Error -------------------------------------------------- delegate_yield.js:25:17

Cannot assign `yield* inner()` to `x` because number is incompatible with
undefined.


Error -------------------------------------------------------- generator.js:23:6

Cannot cast `line` to undefined because string is incompatible with undefined.


Error ------------------------------------------------------------ return.js:6:4

Cannot cast `result.value` to undefined because number is incompatible with
undefined.


Error ------------------------------------------------------------ return.js:6:4

Cannot cast `result.value` to undefined because string is incompatible with
undefined.


Error ----------------------------------------------------------- return.js:20:6

Cannot cast `result.value` to string because number is incompatible with string.


Error ----------------------------------------------------------- return.js:20:6

Cannot cast `result.value` to string because undefined is incompatible with
string.


Error ------------------------------------------------------------ throw.js:12:8

Cannot cast `value` to undefined because number is incompatible with undefined.


Error ------------------------------------------------------------ throw.js:29:8

Cannot cast `value` to undefined because number is incompatible with undefined.



Found 10 errors
