Error: buffer/buffer.js:57
 57: buffer = Buffer.from([0x62, 0x75, 0x66, 0x66, 0x65, 0x72], (a:number) => a + 1, {}); // error
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ call of method `from`. Function cannot be called on any member of intersection type
 57: buffer = Buffer.from([0x62, 0x75, 0x66, 0x66, 0x65, 0x72], (a:number) => a + 1, {}); // error
              ^^^^^^^^^^^ intersection
  Member 1:
  108:   static from(value: Buffer): Buffer;
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ function type. See lib: <BUILTINS>/node.js:108
  Error:
   57: buffer = Buffer.from([0x62, 0x75, 0x66, 0x66, 0x65, 0x72], (a:number) => a + 1, {}); // error
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ array literal. This type is incompatible with the expected param type of
  108:   static from(value: Buffer): Buffer;
                            ^^^^^^ Buffer. See lib: <BUILTINS>/node.js:108
  Member 2:
  109:   static from(value: string, encoding?: buffer$Encoding): Buffer;
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ function type. See lib: <BUILTINS>/node.js:109
  Error:
   57: buffer = Buffer.from([0x62, 0x75, 0x66, 0x66, 0x65, 0x72], (a:number) => a + 1, {}); // error
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ array literal. This type is incompatible with the expected param type of
  109:   static from(value: string, encoding?: buffer$Encoding): Buffer;
                            ^^^^^^ string. See lib: <BUILTINS>/node.js:109
  Member 3:
  110:   static from(value: ArrayBuffer, byteOffset?: number, length?: number): Buffer;
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ function type. See lib: <BUILTINS>/node.js:110
  Error:
   57: buffer = Buffer.from([0x62, 0x75, 0x66, 0x66, 0x65, 0x72], (a:number) => a + 1, {}); // error
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ array literal. This type is incompatible with the expected param type of
  110:   static from(value: ArrayBuffer, byteOffset?: number, length?: number): Buffer;
                            ^^^^^^^^^^^ ArrayBuffer. See lib: <BUILTINS>/node.js:110
  Member 4:
  111:   static from(value: Iterable<number>): this;
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ function type. See lib: <BUILTINS>/node.js:111
  Error:
   57: buffer = Buffer.from([0x62, 0x75, 0x66, 0x66, 0x65, 0x72], (a:number) => a + 1, {}); // error
                                                                  ^^^^^^^^^^^^^^^^^^^ unused function argument
    111:   static from(value: Iterable<number>): this;
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ function type expects no more than 1 argument. See lib: <BUILTINS>/node.js:111

Error: child_process/execSync.js:8
  8: (execSync('ls', {timeout: '250'})); // error, no signatures match
      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ function call. Function cannot be called on any member of intersection type
  8: (execSync('ls', {timeout: '250'})); // error, no signatures match
      ^^^^^^^^ intersection
  Member 1:
                                  v
  260:   declare function execSync(
  261:     command: string,
  262:     options: {encoding: buffer$NonBufferEncoding} & child_process$execSyncOpts
  263:   ): string;
         --------^ function type. See lib: <BUILTINS>/node.js:260
  Error:
    8: (execSync('ls', {timeout: '250'})); // error, no signatures match
                       ^^^^^^^^^^^^^^^^ object literal. This type is incompatible with the expected param type of
  262:     options: {encoding: buffer$NonBufferEncoding} & child_process$execSyncOpts
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ object type. See lib: <BUILTINS>/node.js:262
    Property `encoding` is incompatible:
      262:     options: {encoding: buffer$NonBufferEncoding} & child_process$execSyncOpts
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ property `encoding`. Property not found in. See lib: <BUILTINS>/node.js:262
        8: (execSync('ls', {timeout: '250'})); // error, no signatures match
                           ^^^^^^^^^^^^^^^^ object literal
  Member 2:
                                  v
  265:   declare function execSync(
  266:     command: string,
  267:     options?: child_process$execSyncOpts
  268:   ): Buffer;
         --------^ function type. See lib: <BUILTINS>/node.js:265
  Error:
    8: (execSync('ls', {timeout: '250'})); // error, no signatures match
                       ^^^^^^^^^^^^^^^^ object literal. This type is incompatible with the expected param type of
  267:     options?: child_process$execSyncOpts
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^ object type. See lib: <BUILTINS>/node.js:267
    Property `timeout` is incompatible:
        8: (execSync('ls', {timeout: '250'})); // error, no signatures match
                                     ^^^^^ string. This type is incompatible with
      149:   timeout?: number;
                       ^^^^^^ number. See lib: <BUILTINS>/node.js:149

Error: crypto/crypto.js:12
 12:       (hmac.read(): number); // 4 errors: null, void, string, Buffer
            ^^^^^^^^^^^ Buffer. This type is incompatible with
 12:       (hmac.read(): number); // 4 errors: null, void, string, Buffer
                         ^^^^^^ number

Error: crypto/crypto.js:12
 12:       (hmac.read(): number); // 4 errors: null, void, string, Buffer
            ^^^^^^^^^^^ null. This type is incompatible with
 12:       (hmac.read(): number); // 4 errors: null, void, string, Buffer
                         ^^^^^^ number

Error: crypto/crypto.js:12
 12:       (hmac.read(): number); // 4 errors: null, void, string, Buffer
            ^^^^^^^^^^^ string. This type is incompatible with
 12:       (hmac.read(): number); // 4 errors: null, void, string, Buffer
                         ^^^^^^ number

Error: crypto/crypto.js:12
 12:       (hmac.read(): number); // 4 errors: null, void, string, Buffer
            ^^^^^^^^^^^ undefined. This type is incompatible with
 12:       (hmac.read(): number); // 4 errors: null, void, string, Buffer
                         ^^^^^^ number

Error: crypto/crypto.js:16
 16:     hmac.write(123); // 2 errors: not a string or a Buffer
                    ^^^ number. This type is incompatible with the expected param type of
1475:     chunk: Buffer | string,
                 ^^^^^^^^^^^^^^^ union: Buffer | string. See lib: <BUILTINS>/node.js:1475
  Member 1:
  1475:     chunk: Buffer | string,
                   ^^^^^^ Buffer. See lib: <BUILTINS>/node.js:1475
  Error:
   16:     hmac.write(123); // 2 errors: not a string or a Buffer
                      ^^^ number. This type is incompatible with
  1475:     chunk: Buffer | string,
                   ^^^^^^ Buffer. See lib: <BUILTINS>/node.js:1475
  Member 2:
  1475:     chunk: Buffer | string,
                            ^^^^^^ string. See lib: <BUILTINS>/node.js:1475
  Error:
   16:     hmac.write(123); // 2 errors: not a string or a Buffer
                      ^^^ number. This type is incompatible with
  1475:     chunk: Buffer | string,
                            ^^^^^^ string. See lib: <BUILTINS>/node.js:1475

Error: crypto/crypto.js:26
 26:     hmac.update('foo', 'bogus'); // 1 error
                            ^^^^^^^ string. This type is incompatible with the expected param type of
                                                      v----------------------------
439:   update(data: string | Buffer, input_encoding?: 'utf8' | 'ascii' | 'latin1' |
440:   'binary'): crypto$Hmac;
       -------^ string enum. See lib: <BUILTINS>/node.js:439

Error: crypto/crypto.js:29
 29:     hmac.update(buf, 'bogus'); // 1 error
                          ^^^^^^^ string. This type is incompatible with the expected param type of
                                                      v----------------------------
439:   update(data: string | Buffer, input_encoding?: 'utf8' | 'ascii' | 'latin1' |
440:   'binary'): crypto$Hmac;
       -------^ string enum. See lib: <BUILTINS>/node.js:439

Error: crypto/crypto.js:36
 36:     (hmac.digest('hex'): void); // 1 error
          ^^^^^^^^^^^^^^^^^^ string. This type is incompatible with
 36:     (hmac.digest('hex'): void); // 1 error
                              ^^^^ undefined

Error: crypto/crypto.js:37
 37:     (hmac.digest(): void); // 1 error
          ^^^^^^^^^^^^^ Buffer. This type is incompatible with
 37:     (hmac.digest(): void); // 1 error
                         ^^^^ undefined

Error: fs/fs.js:13
     v-----------------------------------------------------------
 13: fs.readFile("file.exp", { encoding: "blah" }, (_, data) => {
 14:   (data : string);
 15: });
     -^ call of method `readFile`. Could not decide which case to select
 13: fs.readFile("file.exp", { encoding: "blah" }, (_, data) => {
     ^^^^^^^^^^^ intersection type
  Case 3 may work:
                                  v
  907:   declare function readFile(
  908:     path: string | Buffer | URL | number,
  909:     options: { encoding: string; flag?: string },
  910:     callback: (err: ?ErrnoError, data: string) => void
  911:   ): void;
         ------^ function type. See lib: <BUILTINS>/node.js:907
  But if it doesn't, case 4 looks promising too:
                                  v
  912:   declare function readFile(
  913:     path: string | Buffer | URL | number,
  914:     options: { flag?: string },
  915:     callback: (err: ?ErrnoError, data: Buffer) => void
  916:   ): void;
         ------^ function type. See lib: <BUILTINS>/node.js:912
  Please provide additional annotation(s) to determine whether case 3 works (or consider merging it with case 4):
   13: fs.readFile("file.exp", { encoding: "blah" }, (_, data) => {
                                                      ^ parameter `_`
   13: fs.readFile("file.exp", { encoding: "blah" }, (_, data) => {
                                                         ^^^^ parameter `data`

Error: fs/fs.js:28
 28: (fs.readFileSync("file.exp") : string); // error
      ^^^^^^^^^^^^^^^^^^^^^^^^^^^ Buffer. This type is incompatible with
 28: (fs.readFileSync("file.exp") : string); // error
                                    ^^^^^^ string

Error: fs/fs.js:31
 31: (fs.readFileSync("file.exp", "blah") : Buffer); // error
      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ string. This type is incompatible with
 31: (fs.readFileSync("file.exp", "blah") : Buffer); // error
                                            ^^^^^^ Buffer

Error: fs/fs.js:34
 34: (fs.readFileSync("file.exp", { encoding: "blah" }) : Buffer); // error
      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ string. This type is incompatible with
 34: (fs.readFileSync("file.exp", { encoding: "blah" }) : Buffer); // error
                                                          ^^^^^^ Buffer

Error: fs/fs.js:37
 37: (fs.readFileSync("file.exp", {}) : string); // error
      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ Buffer. This type is incompatible with
 37: (fs.readFileSync("file.exp", {}) : string); // error
                                        ^^^^^^ string

Error: http/server.js:67
 67: server.listen(() => {}, {});
     ^^^^^^^^^^^^^^^^^^^^^^^^^^^ call of method `listen`. Function cannot be called on any member of intersection type
 67: server.listen(() => {}, {});
     ^^^^^^^^^^^^^ intersection
  Member 1:
  1091:     listen(port?: number, hostname?: string, backlog?: number, callback?: Function): Server;
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ function type. See lib: <BUILTINS>/node.js:1091
  Error:
   67: server.listen(() => {}, {});
                     ^^^^^^^^ function. This type is incompatible with the expected param type of
  1091:     listen(port?: number, hostname?: string, backlog?: number, callback?: Function): Server;
                          ^^^^^^ number. See lib: <BUILTINS>/node.js:1091
  Member 2:
  1093:     listen(port?: number, backlog?: number, callback?: Function): Server;
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ function type. See lib: <BUILTINS>/node.js:1093
  Error:
   67: server.listen(() => {}, {});
                     ^^^^^^^^ function. This type is incompatible with the expected param type of
  1093:     listen(port?: number, backlog?: number, callback?: Function): Server;
                          ^^^^^^ number. See lib: <BUILTINS>/node.js:1093
  Member 3:
  1094:     listen(port?: number, hostname?: string, callback?: Function): Server;
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ function type. See lib: <BUILTINS>/node.js:1094
  Error:
   67: server.listen(() => {}, {});
                     ^^^^^^^^ function. This type is incompatible with the expected param type of
  1094:     listen(port?: number, hostname?: string, callback?: Function): Server;
                          ^^^^^^ number. See lib: <BUILTINS>/node.js:1094
  Member 4:
  1095:     listen(port?: number, callback?: Function): Server;
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ function type. See lib: <BUILTINS>/node.js:1095
  Error:
   67: server.listen(() => {}, {});
                     ^^^^^^^^ function. This type is incompatible with the expected param type of
  1095:     listen(port?: number, callback?: Function): Server;
                          ^^^^^^ number. See lib: <BUILTINS>/node.js:1095
  Member 5:
  1096:     listen(path: string, callback?: Function): Server;
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ function type. See lib: <BUILTINS>/node.js:1096
  Error:
   67: server.listen(() => {}, {});
                     ^^^^^^^^ function. This type is incompatible with the expected param type of
  1096:     listen(path: string, callback?: Function): Server;
                         ^^^^^^ string. See lib: <BUILTINS>/node.js:1096
  Member 6:
  1097:     listen(handle: Object, callback?: Function): Server;
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ function type. See lib: <BUILTINS>/node.js:1097
  Error:
   67: server.listen(() => {}, {});
                               ^^ object literal. This type is incompatible with the expected param type of
  1097:     listen(handle: Object, callback?: Function): Server;
                                              ^^^^^^^^ function type. See lib: <BUILTINS>/node.js:1097
    Callable property is incompatible:
      1097:     listen(handle: Object, callback?: Function): Server;
                                                  ^^^^^^^^ function type. Callable signature not found in. See lib: <BUILTINS>/node.js:1097
       67: server.listen(() => {}, {});
                                   ^^ object literal

Error: http/server.js:68
 68: server.listen(function() {}, {});
     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ call of method `listen`. Function cannot be called on any member of intersection type
 68: server.listen(function() {}, {});
     ^^^^^^^^^^^^^ intersection
  Member 1:
  1091:     listen(port?: number, hostname?: string, backlog?: number, callback?: Function): Server;
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ function type. See lib: <BUILTINS>/node.js:1091
  Error:
   68: server.listen(function() {}, {});
                     ^^^^^^^^^^ function. This type is incompatible with the expected param type of
  1091:     listen(port?: number, hostname?: string, backlog?: number, callback?: Function): Server;
                          ^^^^^^ number. See lib: <BUILTINS>/node.js:1091
  Member 2:
  1093:     listen(port?: number, backlog?: number, callback?: Function): Server;
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ function type. See lib: <BUILTINS>/node.js:1093
  Error:
   68: server.listen(function() {}, {});
                     ^^^^^^^^^^ function. This type is incompatible with the expected param type of
  1093:     listen(port?: number, backlog?: number, callback?: Function): Server;
                          ^^^^^^ number. See lib: <BUILTINS>/node.js:1093
  Member 3:
  1094:     listen(port?: number, hostname?: string, callback?: Function): Server;
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ function type. See lib: <BUILTINS>/node.js:1094
  Error:
   68: server.listen(function() {}, {});
                     ^^^^^^^^^^ function. This type is incompatible with the expected param type of
  1094:     listen(port?: number, hostname?: string, callback?: Function): Server;
                          ^^^^^^ number. See lib: <BUILTINS>/node.js:1094
  Member 4:
  1095:     listen(port?: number, callback?: Function): Server;
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ function type. See lib: <BUILTINS>/node.js:1095
  Error:
   68: server.listen(function() {}, {});
                     ^^^^^^^^^^ function. This type is incompatible with the expected param type of
  1095:     listen(port?: number, callback?: Function): Server;
                          ^^^^^^ number. See lib: <BUILTINS>/node.js:1095
  Member 5:
  1096:     listen(path: string, callback?: Function): Server;
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ function type. See lib: <BUILTINS>/node.js:1096
  Error:
   68: server.listen(function() {}, {});
                     ^^^^^^^^^^ function. This type is incompatible with the expected param type of
  1096:     listen(path: string, callback?: Function): Server;
                         ^^^^^^ string. See lib: <BUILTINS>/node.js:1096
  Member 6:
  1097:     listen(handle: Object, callback?: Function): Server;
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ function type. See lib: <BUILTINS>/node.js:1097
  Error:
   68: server.listen(function() {}, {});
                                    ^^ object literal. This type is incompatible with the expected param type of
  1097:     listen(handle: Object, callback?: Function): Server;
                                              ^^^^^^^^ function type. See lib: <BUILTINS>/node.js:1097
    Callable property is incompatible:
      1097:     listen(handle: Object, callback?: Function): Server;
                                                  ^^^^^^^^ function type. Callable signature not found in. See lib: <BUILTINS>/node.js:1097
       68: server.listen(function() {}, {});
                                        ^^ object literal

Error: http/server.js:69
 69: server.listen({}, () => {}, 'localhost', 123);
     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ call of method `listen`. Function cannot be called on any member of intersection type
 69: server.listen({}, () => {}, 'localhost', 123);
     ^^^^^^^^^^^^^ intersection
  Member 1:
  1091:     listen(port?: number, hostname?: string, backlog?: number, callback?: Function): Server;
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ function type. See lib: <BUILTINS>/node.js:1091
  Error:
   69: server.listen({}, () => {}, 'localhost', 123);
                     ^^ object literal. This type is incompatible with the expected param type of
  1091:     listen(port?: number, hostname?: string, backlog?: number, callback?: Function): Server;
                          ^^^^^^ number. See lib: <BUILTINS>/node.js:1091
  Member 2:
  1093:     listen(port?: number, backlog?: number, callback?: Function): Server;
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ function type. See lib: <BUILTINS>/node.js:1093
  Error:
   69: server.listen({}, () => {}, 'localhost', 123);
                     ^^ object literal. This type is incompatible with the expected param type of
  1093:     listen(port?: number, backlog?: number, callback?: Function): Server;
                          ^^^^^^ number. See lib: <BUILTINS>/node.js:1093
  Member 3:
  1094:     listen(port?: number, hostname?: string, callback?: Function): Server;
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ function type. See lib: <BUILTINS>/node.js:1094
  Error:
   69: server.listen({}, () => {}, 'localhost', 123);
                     ^^ object literal. This type is incompatible with the expected param type of
  1094:     listen(port?: number, hostname?: string, callback?: Function): Server;
                          ^^^^^^ number. See lib: <BUILTINS>/node.js:1094
  Member 4:
  1095:     listen(port?: number, callback?: Function): Server;
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ function type. See lib: <BUILTINS>/node.js:1095
  Error:
   69: server.listen({}, () => {}, 'localhost', 123);
                     ^^ object literal. This type is incompatible with the expected param type of
  1095:     listen(port?: number, callback?: Function): Server;
                          ^^^^^^ number. See lib: <BUILTINS>/node.js:1095
  Member 5:
  1096:     listen(path: string, callback?: Function): Server;
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ function type. See lib: <BUILTINS>/node.js:1096
  Error:
   69: server.listen({}, () => {}, 'localhost', 123);
                     ^^ object literal. This type is incompatible with the expected param type of
  1096:     listen(path: string, callback?: Function): Server;
                         ^^^^^^ string. See lib: <BUILTINS>/node.js:1096
  Member 6:
  1097:     listen(handle: Object, callback?: Function): Server;
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ function type. See lib: <BUILTINS>/node.js:1097
  Error:
   69: server.listen({}, () => {}, 'localhost', 123);
                                   ^^^^^^^^^^^ unused function argument
    1097:     listen(handle: Object, callback?: Function): Server;
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ function type expects no more than 2 arguments. See lib: <BUILTINS>/node.js:1097

Error: http/server.js:70
 70: server.listen({}, function() {}, 'localhost', 123);
     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ call of method `listen`. Function cannot be called on any member of intersection type
 70: server.listen({}, function() {}, 'localhost', 123);
     ^^^^^^^^^^^^^ intersection
  Member 1:
  1091:     listen(port?: number, hostname?: string, backlog?: number, callback?: Function): Server;
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ function type. See lib: <BUILTINS>/node.js:1091
  Error:
   70: server.listen({}, function() {}, 'localhost', 123);
                     ^^ object literal. This type is incompatible with the expected param type of
  1091:     listen(port?: number, hostname?: string, backlog?: number, callback?: Function): Server;
                          ^^^^^^ number. See lib: <BUILTINS>/node.js:1091
  Member 2:
  1093:     listen(port?: number, backlog?: number, callback?: Function): Server;
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ function type. See lib: <BUILTINS>/node.js:1093
  Error:
   70: server.listen({}, function() {}, 'localhost', 123);
                     ^^ object literal. This type is incompatible with the expected param type of
  1093:     listen(port?: number, backlog?: number, callback?: Function): Server;
                          ^^^^^^ number. See lib: <BUILTINS>/node.js:1093
  Member 3:
  1094:     listen(port?: number, hostname?: string, callback?: Function): Server;
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ function type. See lib: <BUILTINS>/node.js:1094
  Error:
   70: server.listen({}, function() {}, 'localhost', 123);
                     ^^ object literal. This type is incompatible with the expected param type of
  1094:     listen(port?: number, hostname?: string, callback?: Function): Server;
                          ^^^^^^ number. See lib: <BUILTINS>/node.js:1094
  Member 4:
  1095:     listen(port?: number, callback?: Function): Server;
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ function type. See lib: <BUILTINS>/node.js:1095
  Error:
   70: server.listen({}, function() {}, 'localhost', 123);
                     ^^ object literal. This type is incompatible with the expected param type of
  1095:     listen(port?: number, callback?: Function): Server;
                          ^^^^^^ number. See lib: <BUILTINS>/node.js:1095
  Member 5:
  1096:     listen(path: string, callback?: Function): Server;
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ function type. See lib: <BUILTINS>/node.js:1096
  Error:
   70: server.listen({}, function() {}, 'localhost', 123);
                     ^^ object literal. This type is incompatible with the expected param type of
  1096:     listen(path: string, callback?: Function): Server;
                         ^^^^^^ string. See lib: <BUILTINS>/node.js:1096
  Member 6:
  1097:     listen(handle: Object, callback?: Function): Server;
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ function type. See lib: <BUILTINS>/node.js:1097
  Error:
   70: server.listen({}, function() {}, 'localhost', 123);
                                        ^^^^^^^^^^^ unused function argument
    1097:     listen(handle: Object, callback?: Function): Server;
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ function type expects no more than 2 arguments. See lib: <BUILTINS>/node.js:1097

Error: http/server.js:71
 71: server.listen({}, () => {}, 123);
     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ call of method `listen`. Function cannot be called on any member of intersection type
 71: server.listen({}, () => {}, 123);
     ^^^^^^^^^^^^^ intersection
  Member 1:
  1091:     listen(port?: number, hostname?: string, backlog?: number, callback?: Function): Server;
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ function type. See lib: <BUILTINS>/node.js:1091
  Error:
   71: server.listen({}, () => {}, 123);
                     ^^ object literal. This type is incompatible with the expected param type of
  1091:     listen(port?: number, hostname?: string, backlog?: number, callback?: Function): Server;
                          ^^^^^^ number. See lib: <BUILTINS>/node.js:1091
  Member 2:
  1093:     listen(port?: number, backlog?: number, callback?: Function): Server;
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ function type. See lib: <BUILTINS>/node.js:1093
  Error:
   71: server.listen({}, () => {}, 123);
                     ^^ object literal. This type is incompatible with the expected param type of
  1093:     listen(port?: number, backlog?: number, callback?: Function): Server;
                          ^^^^^^ number. See lib: <BUILTINS>/node.js:1093
  Member 3:
  1094:     listen(port?: number, hostname?: string, callback?: Function): Server;
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ function type. See lib: <BUILTINS>/node.js:1094
  Error:
   71: server.listen({}, () => {}, 123);
                     ^^ object literal. This type is incompatible with the expected param type of
  1094:     listen(port?: number, hostname?: string, callback?: Function): Server;
                          ^^^^^^ number. See lib: <BUILTINS>/node.js:1094
  Member 4:
  1095:     listen(port?: number, callback?: Function): Server;
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ function type. See lib: <BUILTINS>/node.js:1095
  Error:
   71: server.listen({}, () => {}, 123);
                     ^^ object literal. This type is incompatible with the expected param type of
  1095:     listen(port?: number, callback?: Function): Server;
                          ^^^^^^ number. See lib: <BUILTINS>/node.js:1095
  Member 5:
  1096:     listen(path: string, callback?: Function): Server;
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ function type. See lib: <BUILTINS>/node.js:1096
  Error:
   71: server.listen({}, () => {}, 123);
                     ^^ object literal. This type is incompatible with the expected param type of
  1096:     listen(path: string, callback?: Function): Server;
                         ^^^^^^ string. See lib: <BUILTINS>/node.js:1096
  Member 6:
  1097:     listen(handle: Object, callback?: Function): Server;
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ function type. See lib: <BUILTINS>/node.js:1097
  Error:
   71: server.listen({}, () => {}, 123);
                                   ^^^ unused function argument
    1097:     listen(handle: Object, callback?: Function): Server;
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ function type expects no more than 2 arguments. See lib: <BUILTINS>/node.js:1097

Error: http/server.js:72
 72: server.listen({}, function() {}, 123);
     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ call of method `listen`. Function cannot be called on any member of intersection type
 72: server.listen({}, function() {}, 123);
     ^^^^^^^^^^^^^ intersection
  Member 1:
  1091:     listen(port?: number, hostname?: string, backlog?: number, callback?: Function): Server;
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ function type. See lib: <BUILTINS>/node.js:1091
  Error:
   72: server.listen({}, function() {}, 123);
                     ^^ object literal. This type is incompatible with the expected param type of
  1091:     listen(port?: number, hostname?: string, backlog?: number, callback?: Function): Server;
                          ^^^^^^ number. See lib: <BUILTINS>/node.js:1091
  Member 2:
  1093:     listen(port?: number, backlog?: number, callback?: Function): Server;
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ function type. See lib: <BUILTINS>/node.js:1093
  Error:
   72: server.listen({}, function() {}, 123);
                     ^^ object literal. This type is incompatible with the expected param type of
  1093:     listen(port?: number, backlog?: number, callback?: Function): Server;
                          ^^^^^^ number. See lib: <BUILTINS>/node.js:1093
  Member 3:
  1094:     listen(port?: number, hostname?: string, callback?: Function): Server;
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ function type. See lib: <BUILTINS>/node.js:1094
  Error:
   72: server.listen({}, function() {}, 123);
                     ^^ object literal. This type is incompatible with the expected param type of
  1094:     listen(port?: number, hostname?: string, callback?: Function): Server;
                          ^^^^^^ number. See lib: <BUILTINS>/node.js:1094
  Member 4:
  1095:     listen(port?: number, callback?: Function): Server;
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ function type. See lib: <BUILTINS>/node.js:1095
  Error:
   72: server.listen({}, function() {}, 123);
                     ^^ object literal. This type is incompatible with the expected param type of
  1095:     listen(port?: number, callback?: Function): Server;
                          ^^^^^^ number. See lib: <BUILTINS>/node.js:1095
  Member 5:
  1096:     listen(path: string, callback?: Function): Server;
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ function type. See lib: <BUILTINS>/node.js:1096
  Error:
   72: server.listen({}, function() {}, 123);
                     ^^ object literal. This type is incompatible with the expected param type of
  1096:     listen(path: string, callback?: Function): Server;
                         ^^^^^^ string. See lib: <BUILTINS>/node.js:1096
  Member 6:
  1097:     listen(handle: Object, callback?: Function): Server;
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ function type. See lib: <BUILTINS>/node.js:1097
  Error:
   72: server.listen({}, function() {}, 123);
                                        ^^^ unused function argument
    1097:     listen(handle: Object, callback?: Function): Server;
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ function type expects no more than 2 arguments. See lib: <BUILTINS>/node.js:1097

Error: http/server.js:73
 73: server.listen(() => {}, 123);
     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^ call of method `listen`. Function cannot be called on any member of intersection type
 73: server.listen(() => {}, 123);
     ^^^^^^^^^^^^^ intersection
  Member 1:
  1091:     listen(port?: number, hostname?: string, backlog?: number, callback?: Function): Server;
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ function type. See lib: <BUILTINS>/node.js:1091
  Error:
   73: server.listen(() => {}, 123);
                     ^^^^^^^^ function. This type is incompatible with the expected param type of
  1091:     listen(port?: number, hostname?: string, backlog?: number, callback?: Function): Server;
                          ^^^^^^ number. See lib: <BUILTINS>/node.js:1091
  Member 2:
  1093:     listen(port?: number, backlog?: number, callback?: Function): Server;
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ function type. See lib: <BUILTINS>/node.js:1093
  Error:
   73: server.listen(() => {}, 123);
                     ^^^^^^^^ function. This type is incompatible with the expected param type of
  1093:     listen(port?: number, backlog?: number, callback?: Function): Server;
                          ^^^^^^ number. See lib: <BUILTINS>/node.js:1093
  Member 3:
  1094:     listen(port?: number, hostname?: string, callback?: Function): Server;
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ function type. See lib: <BUILTINS>/node.js:1094
  Error:
   73: server.listen(() => {}, 123);
                     ^^^^^^^^ function. This type is incompatible with the expected param type of
  1094:     listen(port?: number, hostname?: string, callback?: Function): Server;
                          ^^^^^^ number. See lib: <BUILTINS>/node.js:1094
  Member 4:
  1095:     listen(port?: number, callback?: Function): Server;
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ function type. See lib: <BUILTINS>/node.js:1095
  Error:
   73: server.listen(() => {}, 123);
                     ^^^^^^^^ function. This type is incompatible with the expected param type of
  1095:     listen(port?: number, callback?: Function): Server;
                          ^^^^^^ number. See lib: <BUILTINS>/node.js:1095
  Member 5:
  1096:     listen(path: string, callback?: Function): Server;
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ function type. See lib: <BUILTINS>/node.js:1096
  Error:
   73: server.listen(() => {}, 123);
                     ^^^^^^^^ function. This type is incompatible with the expected param type of
  1096:     listen(path: string, callback?: Function): Server;
                         ^^^^^^ string. See lib: <BUILTINS>/node.js:1096
  Member 6:
  1097:     listen(handle: Object, callback?: Function): Server;
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ function type. See lib: <BUILTINS>/node.js:1097
  Error:
   73: server.listen(() => {}, 123);
                               ^^^ number. This type is incompatible with the expected param type of
  1097:     listen(handle: Object, callback?: Function): Server;
                                              ^^^^^^^^ function type. See lib: <BUILTINS>/node.js:1097

Error: http/server.js:74
 74: server.listen(function() {}, 123);
     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ call of method `listen`. Function cannot be called on any member of intersection type
 74: server.listen(function() {}, 123);
     ^^^^^^^^^^^^^ intersection
  Member 1:
  1091:     listen(port?: number, hostname?: string, backlog?: number, callback?: Function): Server;
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ function type. See lib: <BUILTINS>/node.js:1091
  Error:
   74: server.listen(function() {}, 123);
                     ^^^^^^^^^^ function. This type is incompatible with the expected param type of
  1091:     listen(port?: number, hostname?: string, backlog?: number, callback?: Function): Server;
                          ^^^^^^ number. See lib: <BUILTINS>/node.js:1091
  Member 2:
  1093:     listen(port?: number, backlog?: number, callback?: Function): Server;
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ function type. See lib: <BUILTINS>/node.js:1093
  Error:
   74: server.listen(function() {}, 123);
                     ^^^^^^^^^^ function. This type is incompatible with the expected param type of
  1093:     listen(port?: number, backlog?: number, callback?: Function): Server;
                          ^^^^^^ number. See lib: <BUILTINS>/node.js:1093
  Member 3:
  1094:     listen(port?: number, hostname?: string, callback?: Function): Server;
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ function type. See lib: <BUILTINS>/node.js:1094
  Error:
   74: server.listen(function() {}, 123);
                     ^^^^^^^^^^ function. This type is incompatible with the expected param type of
  1094:     listen(port?: number, hostname?: string, callback?: Function): Server;
                          ^^^^^^ number. See lib: <BUILTINS>/node.js:1094
  Member 4:
  1095:     listen(port?: number, callback?: Function): Server;
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ function type. See lib: <BUILTINS>/node.js:1095
  Error:
   74: server.listen(function() {}, 123);
                     ^^^^^^^^^^ function. This type is incompatible with the expected param type of
  1095:     listen(port?: number, callback?: Function): Server;
                          ^^^^^^ number. See lib: <BUILTINS>/node.js:1095
  Member 5:
  1096:     listen(path: string, callback?: Function): Server;
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ function type. See lib: <BUILTINS>/node.js:1096
  Error:
   74: server.listen(function() {}, 123);
                     ^^^^^^^^^^ function. This type is incompatible with the expected param type of
  1096:     listen(path: string, callback?: Function): Server;
                         ^^^^^^ string. See lib: <BUILTINS>/node.js:1096
  Member 6:
  1097:     listen(handle: Object, callback?: Function): Server;
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ function type. See lib: <BUILTINS>/node.js:1097
  Error:
   74: server.listen(function() {}, 123);
                                    ^^^ number. This type is incompatible with the expected param type of
  1097:     listen(handle: Object, callback?: Function): Server;
                                              ^^^^^^^^ function type. See lib: <BUILTINS>/node.js:1097

Error: http/server.js:75
 75: server.listen(() => {}, 'localhost', 123);
     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ call of method `listen`. Function cannot be called on any member of intersection type
 75: server.listen(() => {}, 'localhost', 123);
     ^^^^^^^^^^^^^ intersection
  Member 1:
  1091:     listen(port?: number, hostname?: string, backlog?: number, callback?: Function): Server;
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ function type. See lib: <BUILTINS>/node.js:1091
  Error:
   75: server.listen(() => {}, 'localhost', 123);
                     ^^^^^^^^ function. This type is incompatible with the expected param type of
  1091:     listen(port?: number, hostname?: string, backlog?: number, callback?: Function): Server;
                          ^^^^^^ number. See lib: <BUILTINS>/node.js:1091
  Member 2:
  1093:     listen(port?: number, backlog?: number, callback?: Function): Server;
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ function type. See lib: <BUILTINS>/node.js:1093
  Error:
   75: server.listen(() => {}, 'localhost', 123);
                     ^^^^^^^^ function. This type is incompatible with the expected param type of
  1093:     listen(port?: number, backlog?: number, callback?: Function): Server;
                          ^^^^^^ number. See lib: <BUILTINS>/node.js:1093
  Member 3:
  1094:     listen(port?: number, hostname?: string, callback?: Function): Server;
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ function type. See lib: <BUILTINS>/node.js:1094
  Error:
   75: server.listen(() => {}, 'localhost', 123);
                     ^^^^^^^^ function. This type is incompatible with the expected param type of
  1094:     listen(port?: number, hostname?: string, callback?: Function): Server;
                          ^^^^^^ number. See lib: <BUILTINS>/node.js:1094
  Member 4:
  1095:     listen(port?: number, callback?: Function): Server;
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ function type. See lib: <BUILTINS>/node.js:1095
  Error:
   75: server.listen(() => {}, 'localhost', 123);
                     ^^^^^^^^ function. This type is incompatible with the expected param type of
  1095:     listen(port?: number, callback?: Function): Server;
                          ^^^^^^ number. See lib: <BUILTINS>/node.js:1095
  Member 5:
  1096:     listen(path: string, callback?: Function): Server;
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ function type. See lib: <BUILTINS>/node.js:1096
  Error:
   75: server.listen(() => {}, 'localhost', 123);
                     ^^^^^^^^ function. This type is incompatible with the expected param type of
  1096:     listen(path: string, callback?: Function): Server;
                         ^^^^^^ string. See lib: <BUILTINS>/node.js:1096
  Member 6:
  1097:     listen(handle: Object, callback?: Function): Server;
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ function type. See lib: <BUILTINS>/node.js:1097
  Error:
   75: server.listen(() => {}, 'localhost', 123);
                               ^^^^^^^^^^^ string. This type is incompatible with the expected param type of
  1097:     listen(handle: Object, callback?: Function): Server;
                                              ^^^^^^^^ function type. See lib: <BUILTINS>/node.js:1097

Error: http/server.js:76
 76: server.listen(function() {}, 'localhost', 123);
     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ call of method `listen`. Function cannot be called on any member of intersection type
 76: server.listen(function() {}, 'localhost', 123);
     ^^^^^^^^^^^^^ intersection
  Member 1:
  1091:     listen(port?: number, hostname?: string, backlog?: number, callback?: Function): Server;
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ function type. See lib: <BUILTINS>/node.js:1091
  Error:
   76: server.listen(function() {}, 'localhost', 123);
                     ^^^^^^^^^^ function. This type is incompatible with the expected param type of
  1091:     listen(port?: number, hostname?: string, backlog?: number, callback?: Function): Server;
                          ^^^^^^ number. See lib: <BUILTINS>/node.js:1091
  Member 2:
  1093:     listen(port?: number, backlog?: number, callback?: Function): Server;
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ function type. See lib: <BUILTINS>/node.js:1093
  Error:
   76: server.listen(function() {}, 'localhost', 123);
                     ^^^^^^^^^^ function. This type is incompatible with the expected param type of
  1093:     listen(port?: number, backlog?: number, callback?: Function): Server;
                          ^^^^^^ number. See lib: <BUILTINS>/node.js:1093
  Member 3:
  1094:     listen(port?: number, hostname?: string, callback?: Function): Server;
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ function type. See lib: <BUILTINS>/node.js:1094
  Error:
   76: server.listen(function() {}, 'localhost', 123);
                     ^^^^^^^^^^ function. This type is incompatible with the expected param type of
  1094:     listen(port?: number, hostname?: string, callback?: Function): Server;
                          ^^^^^^ number. See lib: <BUILTINS>/node.js:1094
  Member 4:
  1095:     listen(port?: number, callback?: Function): Server;
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ function type. See lib: <BUILTINS>/node.js:1095
  Error:
   76: server.listen(function() {}, 'localhost', 123);
                     ^^^^^^^^^^ function. This type is incompatible with the expected param type of
  1095:     listen(port?: number, callback?: Function): Server;
                          ^^^^^^ number. See lib: <BUILTINS>/node.js:1095
  Member 5:
  1096:     listen(path: string, callback?: Function): Server;
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ function type. See lib: <BUILTINS>/node.js:1096
  Error:
   76: server.listen(function() {}, 'localhost', 123);
                     ^^^^^^^^^^ function. This type is incompatible with the expected param type of
  1096:     listen(path: string, callback?: Function): Server;
                         ^^^^^^ string. See lib: <BUILTINS>/node.js:1096
  Member 6:
  1097:     listen(handle: Object, callback?: Function): Server;
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ function type. See lib: <BUILTINS>/node.js:1097
  Error:
   76: server.listen(function() {}, 'localhost', 123);
                                    ^^^^^^^^^^^ string. This type is incompatible with the expected param type of
  1097:     listen(handle: Object, callback?: Function): Server;
                                              ^^^^^^^^ function type. See lib: <BUILTINS>/node.js:1097

Error: http/server.js:77
 77: server.listen(() => {}, 'localhost');
     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ call of method `listen`. Function cannot be called on any member of intersection type
 77: server.listen(() => {}, 'localhost');
     ^^^^^^^^^^^^^ intersection
  Member 1:
  1091:     listen(port?: number, hostname?: string, backlog?: number, callback?: Function): Server;
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ function type. See lib: <BUILTINS>/node.js:1091
  Error:
   77: server.listen(() => {}, 'localhost');
                     ^^^^^^^^ function. This type is incompatible with the expected param type of
  1091:     listen(port?: number, hostname?: string, backlog?: number, callback?: Function): Server;
                          ^^^^^^ number. See lib: <BUILTINS>/node.js:1091
  Member 2:
  1093:     listen(port?: number, backlog?: number, callback?: Function): Server;
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ function type. See lib: <BUILTINS>/node.js:1093
  Error:
   77: server.listen(() => {}, 'localhost');
                     ^^^^^^^^ function. This type is incompatible with the expected param type of
  1093:     listen(port?: number, backlog?: number, callback?: Function): Server;
                          ^^^^^^ number. See lib: <BUILTINS>/node.js:1093
  Member 3:
  1094:     listen(port?: number, hostname?: string, callback?: Function): Server;
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ function type. See lib: <BUILTINS>/node.js:1094
  Error:
   77: server.listen(() => {}, 'localhost');
                     ^^^^^^^^ function. This type is incompatible with the expected param type of
  1094:     listen(port?: number, hostname?: string, callback?: Function): Server;
                          ^^^^^^ number. See lib: <BUILTINS>/node.js:1094
  Member 4:
  1095:     listen(port?: number, callback?: Function): Server;
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ function type. See lib: <BUILTINS>/node.js:1095
  Error:
   77: server.listen(() => {}, 'localhost');
                     ^^^^^^^^ function. This type is incompatible with the expected param type of
  1095:     listen(port?: number, callback?: Function): Server;
                          ^^^^^^ number. See lib: <BUILTINS>/node.js:1095
  Member 5:
  1096:     listen(path: string, callback?: Function): Server;
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ function type. See lib: <BUILTINS>/node.js:1096
  Error:
   77: server.listen(() => {}, 'localhost');
                     ^^^^^^^^ function. This type is incompatible with the expected param type of
  1096:     listen(path: string, callback?: Function): Server;
                         ^^^^^^ string. See lib: <BUILTINS>/node.js:1096
  Member 6:
  1097:     listen(handle: Object, callback?: Function): Server;
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ function type. See lib: <BUILTINS>/node.js:1097
  Error:
   77: server.listen(() => {}, 'localhost');
                               ^^^^^^^^^^^ string. This type is incompatible with the expected param type of
  1097:     listen(handle: Object, callback?: Function): Server;
                                              ^^^^^^^^ function type. See lib: <BUILTINS>/node.js:1097

Error: http/server.js:78
 78: server.listen(function() {}, 'localhost');
     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ call of method `listen`. Function cannot be called on any member of intersection type
 78: server.listen(function() {}, 'localhost');
     ^^^^^^^^^^^^^ intersection
  Member 1:
  1091:     listen(port?: number, hostname?: string, backlog?: number, callback?: Function): Server;
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ function type. See lib: <BUILTINS>/node.js:1091
  Error:
   78: server.listen(function() {}, 'localhost');
                     ^^^^^^^^^^ function. This type is incompatible with the expected param type of
  1091:     listen(port?: number, hostname?: string, backlog?: number, callback?: Function): Server;
                          ^^^^^^ number. See lib: <BUILTINS>/node.js:1091
  Member 2:
  1093:     listen(port?: number, backlog?: number, callback?: Function): Server;
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ function type. See lib: <BUILTINS>/node.js:1093
  Error:
   78: server.listen(function() {}, 'localhost');
                     ^^^^^^^^^^ function. This type is incompatible with the expected param type of
  1093:     listen(port?: number, backlog?: number, callback?: Function): Server;
                          ^^^^^^ number. See lib: <BUILTINS>/node.js:1093
  Member 3:
  1094:     listen(port?: number, hostname?: string, callback?: Function): Server;
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ function type. See lib: <BUILTINS>/node.js:1094
  Error:
   78: server.listen(function() {}, 'localhost');
                     ^^^^^^^^^^ function. This type is incompatible with the expected param type of
  1094:     listen(port?: number, hostname?: string, callback?: Function): Server;
                          ^^^^^^ number. See lib: <BUILTINS>/node.js:1094
  Member 4:
  1095:     listen(port?: number, callback?: Function): Server;
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ function type. See lib: <BUILTINS>/node.js:1095
  Error:
   78: server.listen(function() {}, 'localhost');
                     ^^^^^^^^^^ function. This type is incompatible with the expected param type of
  1095:     listen(port?: number, callback?: Function): Server;
                          ^^^^^^ number. See lib: <BUILTINS>/node.js:1095
  Member 5:
  1096:     listen(path: string, callback?: Function): Server;
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ function type. See lib: <BUILTINS>/node.js:1096
  Error:
   78: server.listen(function() {}, 'localhost');
                     ^^^^^^^^^^ function. This type is incompatible with the expected param type of
  1096:     listen(path: string, callback?: Function): Server;
                         ^^^^^^ string. See lib: <BUILTINS>/node.js:1096
  Member 6:
  1097:     listen(handle: Object, callback?: Function): Server;
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ function type. See lib: <BUILTINS>/node.js:1097
  Error:
   78: server.listen(function() {}, 'localhost');
                                    ^^^^^^^^^^^ string. This type is incompatible with the expected param type of
  1097:     listen(handle: Object, callback?: Function): Server;
                                              ^^^^^^^^ function type. See lib: <BUILTINS>/node.js:1097

Error: http/server.js:79
 79: server.listen(8080, () => {}, 'localhost', 123);
     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ call of method `listen`. Function cannot be called on any member of intersection type
 79: server.listen(8080, () => {}, 'localhost', 123);
     ^^^^^^^^^^^^^ intersection
  Member 1:
  1091:     listen(port?: number, hostname?: string, backlog?: number, callback?: Function): Server;
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ function type. See lib: <BUILTINS>/node.js:1091
  Error:
   79: server.listen(8080, () => {}, 'localhost', 123);
                           ^^^^^^^^ function. This type is incompatible with the expected param type of
  1091:     listen(port?: number, hostname?: string, backlog?: number, callback?: Function): Server;
                                             ^^^^^^ string. See lib: <BUILTINS>/node.js:1091
  Member 2:
  1093:     listen(port?: number, backlog?: number, callback?: Function): Server;
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ function type. See lib: <BUILTINS>/node.js:1093
  Error:
   79: server.listen(8080, () => {}, 'localhost', 123);
                           ^^^^^^^^ function. This type is incompatible with the expected param type of
  1093:     listen(port?: number, backlog?: number, callback?: Function): Server;
                                            ^^^^^^ number. See lib: <BUILTINS>/node.js:1093
  Member 3:
  1094:     listen(port?: number, hostname?: string, callback?: Function): Server;
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ function type. See lib: <BUILTINS>/node.js:1094
  Error:
   79: server.listen(8080, () => {}, 'localhost', 123);
                           ^^^^^^^^ function. This type is incompatible with the expected param type of
  1094:     listen(port?: number, hostname?: string, callback?: Function): Server;
                                             ^^^^^^ string. See lib: <BUILTINS>/node.js:1094
  Member 4:
  1095:     listen(port?: number, callback?: Function): Server;
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ function type. See lib: <BUILTINS>/node.js:1095
  Error:
   79: server.listen(8080, () => {}, 'localhost', 123);
                                     ^^^^^^^^^^^ unused function argument
    1095:     listen(port?: number, callback?: Function): Server;
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ function type expects no more than 2 arguments. See lib: <BUILTINS>/node.js:1095
  Member 5:
  1096:     listen(path: string, callback?: Function): Server;
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ function type. See lib: <BUILTINS>/node.js:1096
  Error:
   79: server.listen(8080, () => {}, 'localhost', 123);
                     ^^^^ number. This type is incompatible with the expected param type of
  1096:     listen(path: string, callback?: Function): Server;
                         ^^^^^^ string. See lib: <BUILTINS>/node.js:1096
  Member 6:
  1097:     listen(handle: Object, callback?: Function): Server;
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ function type. See lib: <BUILTINS>/node.js:1097
  Error:
   79: server.listen(8080, () => {}, 'localhost', 123);
                     ^^^^ number. This type is incompatible with the expected param type of
  1097:     listen(handle: Object, callback?: Function): Server;
                           ^^^^^^ object type. See lib: <BUILTINS>/node.js:1097

Error: http/server.js:80
 80: server.listen(8080, function() {}, 'localhost', 123);
     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ call of method `listen`. Function cannot be called on any member of intersection type
 80: server.listen(8080, function() {}, 'localhost', 123);
     ^^^^^^^^^^^^^ intersection
  Member 1:
  1091:     listen(port?: number, hostname?: string, backlog?: number, callback?: Function): Server;
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ function type. See lib: <BUILTINS>/node.js:1091
  Error:
   80: server.listen(8080, function() {}, 'localhost', 123);
                           ^^^^^^^^^^ function. This type is incompatible with the expected param type of
  1091:     listen(port?: number, hostname?: string, backlog?: number, callback?: Function): Server;
                                             ^^^^^^ string. See lib: <BUILTINS>/node.js:1091
  Member 2:
  1093:     listen(port?: number, backlog?: number, callback?: Function): Server;
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ function type. See lib: <BUILTINS>/node.js:1093
  Error:
   80: server.listen(8080, function() {}, 'localhost', 123);
                           ^^^^^^^^^^ function. This type is incompatible with the expected param type of
  1093:     listen(port?: number, backlog?: number, callback?: Function): Server;
                                            ^^^^^^ number. See lib: <BUILTINS>/node.js:1093
  Member 3:
  1094:     listen(port?: number, hostname?: string, callback?: Function): Server;
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ function type. See lib: <BUILTINS>/node.js:1094
  Error:
   80: server.listen(8080, function() {}, 'localhost', 123);
                           ^^^^^^^^^^ function. This type is incompatible with the expected param type of
  1094:     listen(port?: number, hostname?: string, callback?: Function): Server;
                                             ^^^^^^ string. See lib: <BUILTINS>/node.js:1094
  Member 4:
  1095:     listen(port?: number, callback?: Function): Server;
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ function type. See lib: <BUILTINS>/node.js:1095
  Error:
   80: server.listen(8080, function() {}, 'localhost', 123);
                                          ^^^^^^^^^^^ unused function argument
    1095:     listen(port?: number, callback?: Function): Server;
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ function type expects no more than 2 arguments. See lib: <BUILTINS>/node.js:1095
  Member 5:
  1096:     listen(path: string, callback?: Function): Server;
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ function type. See lib: <BUILTINS>/node.js:1096
  Error:
   80: server.listen(8080, function() {}, 'localhost', 123);
                     ^^^^ number. This type is incompatible with the expected param type of
  1096:     listen(path: string, callback?: Function): Server;
                         ^^^^^^ string. See lib: <BUILTINS>/node.js:1096
  Member 6:
  1097:     listen(handle: Object, callback?: Function): Server;
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ function type. See lib: <BUILTINS>/node.js:1097
  Error:
   80: server.listen(8080, function() {}, 'localhost', 123);
                     ^^^^ number. This type is incompatible with the expected param type of
  1097:     listen(handle: Object, callback?: Function): Server;
                           ^^^^^^ object type. See lib: <BUILTINS>/node.js:1097

Error: http/server.js:81
 81: server.listen(8080, () => {}, 123);
     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ call of method `listen`. Function cannot be called on any member of intersection type
 81: server.listen(8080, () => {}, 123);
     ^^^^^^^^^^^^^ intersection
  Member 1:
  1091:     listen(port?: number, hostname?: string, backlog?: number, callback?: Function): Server;
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ function type. See lib: <BUILTINS>/node.js:1091
  Error:
   81: server.listen(8080, () => {}, 123);
                           ^^^^^^^^ function. This type is incompatible with the expected param type of
  1091:     listen(port?: number, hostname?: string, backlog?: number, callback?: Function): Server;
                                             ^^^^^^ string. See lib: <BUILTINS>/node.js:1091
  Member 2:
  1093:     listen(port?: number, backlog?: number, callback?: Function): Server;
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ function type. See lib: <BUILTINS>/node.js:1093
  Error:
   81: server.listen(8080, () => {}, 123);
                           ^^^^^^^^ function. This type is incompatible with the expected param type of
  1093:     listen(port?: number, backlog?: number, callback?: Function): Server;
                                            ^^^^^^ number. See lib: <BUILTINS>/node.js:1093
  Member 3:
  1094:     listen(port?: number, hostname?: string, callback?: Function): Server;
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ function type. See lib: <BUILTINS>/node.js:1094
  Error:
   81: server.listen(8080, () => {}, 123);
                           ^^^^^^^^ function. This type is incompatible with the expected param type of
  1094:     listen(port?: number, hostname?: string, callback?: Function): Server;
                                             ^^^^^^ string. See lib: <BUILTINS>/node.js:1094
  Member 4:
  1095:     listen(port?: number, callback?: Function): Server;
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ function type. See lib: <BUILTINS>/node.js:1095
  Error:
   81: server.listen(8080, () => {}, 123);
                                     ^^^ unused function argument
    1095:     listen(port?: number, callback?: Function): Server;
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ function type expects no more than 2 arguments. See lib: <BUILTINS>/node.js:1095
  Member 5:
  1096:     listen(path: string, callback?: Function): Server;
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ function type. See lib: <BUILTINS>/node.js:1096
  Error:
   81: server.listen(8080, () => {}, 123);
                     ^^^^ number. This type is incompatible with the expected param type of
  1096:     listen(path: string, callback?: Function): Server;
                         ^^^^^^ string. See lib: <BUILTINS>/node.js:1096
  Member 6:
  1097:     listen(handle: Object, callback?: Function): Server;
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ function type. See lib: <BUILTINS>/node.js:1097
  Error:
   81: server.listen(8080, () => {}, 123);
                     ^^^^ number. This type is incompatible with the expected param type of
  1097:     listen(handle: Object, callback?: Function): Server;
                           ^^^^^^ object type. See lib: <BUILTINS>/node.js:1097

Error: http/server.js:82
 82: server.listen(8080, function() {}, 123);
     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ call of method `listen`. Function cannot be called on any member of intersection type
 82: server.listen(8080, function() {}, 123);
     ^^^^^^^^^^^^^ intersection
  Member 1:
  1091:     listen(port?: number, hostname?: string, backlog?: number, callback?: Function): Server;
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ function type. See lib: <BUILTINS>/node.js:1091
  Error:
   82: server.listen(8080, function() {}, 123);
                           ^^^^^^^^^^ function. This type is incompatible with the expected param type of
  1091:     listen(port?: number, hostname?: string, backlog?: number, callback?: Function): Server;
                                             ^^^^^^ string. See lib: <BUILTINS>/node.js:1091
  Member 2:
  1093:     listen(port?: number, backlog?: number, callback?: Function): Server;
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ function type. See lib: <BUILTINS>/node.js:1093
  Error:
   82: server.listen(8080, function() {}, 123);
                           ^^^^^^^^^^ function. This type is incompatible with the expected param type of
  1093:     listen(port?: number, backlog?: number, callback?: Function): Server;
                                            ^^^^^^ number. See lib: <BUILTINS>/node.js:1093
  Member 3:
  1094:     listen(port?: number, hostname?: string, callback?: Function): Server;
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ function type. See lib: <BUILTINS>/node.js:1094
  Error:
   82: server.listen(8080, function() {}, 123);
                           ^^^^^^^^^^ function. This type is incompatible with the expected param type of
  1094:     listen(port?: number, hostname?: string, callback?: Function): Server;
                                             ^^^^^^ string. See lib: <BUILTINS>/node.js:1094
  Member 4:
  1095:     listen(port?: number, callback?: Function): Server;
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ function type. See lib: <BUILTINS>/node.js:1095
  Error:
   82: server.listen(8080, function() {}, 123);
                                          ^^^ unused function argument
    1095:     listen(port?: number, callback?: Function): Server;
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ function type expects no more than 2 arguments. See lib: <BUILTINS>/node.js:1095
  Member 5:
  1096:     listen(path: string, callback?: Function): Server;
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ function type. See lib: <BUILTINS>/node.js:1096
  Error:
   82: server.listen(8080, function() {}, 123);
                     ^^^^ number. This type is incompatible with the expected param type of
  1096:     listen(path: string, callback?: Function): Server;
                         ^^^^^^ string. See lib: <BUILTINS>/node.js:1096
  Member 6:
  1097:     listen(handle: Object, callback?: Function): Server;
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ function type. See lib: <BUILTINS>/node.js:1097
  Error:
   82: server.listen(8080, function() {}, 123);
                     ^^^^ number. This type is incompatible with the expected param type of
  1097:     listen(handle: Object, callback?: Function): Server;
                           ^^^^^^ object type. See lib: <BUILTINS>/node.js:1097

Error: http/server.js:83
 83: server.listen(8080, () => {}, 'localhost');
     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ call of method `listen`. Function cannot be called on any member of intersection type
 83: server.listen(8080, () => {}, 'localhost');
     ^^^^^^^^^^^^^ intersection
  Member 1:
  1091:     listen(port?: number, hostname?: string, backlog?: number, callback?: Function): Server;
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ function type. See lib: <BUILTINS>/node.js:1091
  Error:
   83: server.listen(8080, () => {}, 'localhost');
                           ^^^^^^^^ function. This type is incompatible with the expected param type of
  1091:     listen(port?: number, hostname?: string, backlog?: number, callback?: Function): Server;
                                             ^^^^^^ string. See lib: <BUILTINS>/node.js:1091
  Member 2:
  1093:     listen(port?: number, backlog?: number, callback?: Function): Server;
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ function type. See lib: <BUILTINS>/node.js:1093
  Error:
   83: server.listen(8080, () => {}, 'localhost');
                           ^^^^^^^^ function. This type is incompatible with the expected param type of
  1093:     listen(port?: number, backlog?: number, callback?: Function): Server;
                                            ^^^^^^ number. See lib: <BUILTINS>/node.js:1093
  Member 3:
  1094:     listen(port?: number, hostname?: string, callback?: Function): Server;
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ function type. See lib: <BUILTINS>/node.js:1094
  Error:
   83: server.listen(8080, () => {}, 'localhost');
                           ^^^^^^^^ function. This type is incompatible with the expected param type of
  1094:     listen(port?: number, hostname?: string, callback?: Function): Server;
                                             ^^^^^^ string. See lib: <BUILTINS>/node.js:1094
  Member 4:
  1095:     listen(port?: number, callback?: Function): Server;
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ function type. See lib: <BUILTINS>/node.js:1095
  Error:
   83: server.listen(8080, () => {}, 'localhost');
                                     ^^^^^^^^^^^ unused function argument
    1095:     listen(port?: number, callback?: Function): Server;
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ function type expects no more than 2 arguments. See lib: <BUILTINS>/node.js:1095
  Member 5:
  1096:     listen(path: string, callback?: Function): Server;
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ function type. See lib: <BUILTINS>/node.js:1096
  Error:
   83: server.listen(8080, () => {}, 'localhost');
                     ^^^^ number. This type is incompatible with the expected param type of
  1096:     listen(path: string, callback?: Function): Server;
                         ^^^^^^ string. See lib: <BUILTINS>/node.js:1096
  Member 6:
  1097:     listen(handle: Object, callback?: Function): Server;
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ function type. See lib: <BUILTINS>/node.js:1097
  Error:
   83: server.listen(8080, () => {}, 'localhost');
                     ^^^^ number. This type is incompatible with the expected param type of
  1097:     listen(handle: Object, callback?: Function): Server;
                           ^^^^^^ object type. See lib: <BUILTINS>/node.js:1097

Error: http/server.js:84
 84: server.listen(8080, function() {}, 'localhost');
     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ call of method `listen`. Function cannot be called on any member of intersection type
 84: server.listen(8080, function() {}, 'localhost');
     ^^^^^^^^^^^^^ intersection
  Member 1:
  1091:     listen(port?: number, hostname?: string, backlog?: number, callback?: Function): Server;
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ function type. See lib: <BUILTINS>/node.js:1091
  Error:
   84: server.listen(8080, function() {}, 'localhost');
                           ^^^^^^^^^^ function. This type is incompatible with the expected param type of
  1091:     listen(port?: number, hostname?: string, backlog?: number, callback?: Function): Server;
                                             ^^^^^^ string. See lib: <BUILTINS>/node.js:1091
  Member 2:
  1093:     listen(port?: number, backlog?: number, callback?: Function): Server;
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ function type. See lib: <BUILTINS>/node.js:1093
  Error:
   84: server.listen(8080, function() {}, 'localhost');
                           ^^^^^^^^^^ function. This type is incompatible with the expected param type of
  1093:     listen(port?: number, backlog?: number, callback?: Function): Server;
                                            ^^^^^^ number. See lib: <BUILTINS>/node.js:1093
  Member 3:
  1094:     listen(port?: number, hostname?: string, callback?: Function): Server;
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ function type. See lib: <BUILTINS>/node.js:1094
  Error:
   84: server.listen(8080, function() {}, 'localhost');
                           ^^^^^^^^^^ function. This type is incompatible with the expected param type of
  1094:     listen(port?: number, hostname?: string, callback?: Function): Server;
                                             ^^^^^^ string. See lib: <BUILTINS>/node.js:1094
  Member 4:
  1095:     listen(port?: number, callback?: Function): Server;
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ function type. See lib: <BUILTINS>/node.js:1095
  Error:
   84: server.listen(8080, function() {}, 'localhost');
                                          ^^^^^^^^^^^ unused function argument
    1095:     listen(port?: number, callback?: Function): Server;
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ function type expects no more than 2 arguments. See lib: <BUILTINS>/node.js:1095
  Member 5:
  1096:     listen(path: string, callback?: Function): Server;
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ function type. See lib: <BUILTINS>/node.js:1096
  Error:
   84: server.listen(8080, function() {}, 'localhost');
                     ^^^^ number. This type is incompatible with the expected param type of
  1096:     listen(path: string, callback?: Function): Server;
                         ^^^^^^ string. See lib: <BUILTINS>/node.js:1096
  Member 6:
  1097:     listen(handle: Object, callback?: Function): Server;
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ function type. See lib: <BUILTINS>/node.js:1097
  Error:
   84: server.listen(8080, function() {}, 'localhost');
                     ^^^^ number. This type is incompatible with the expected param type of
  1097:     listen(handle: Object, callback?: Function): Server;
                           ^^^^^^ object type. See lib: <BUILTINS>/node.js:1097

Error: https/server.js:67
 67: server.listen(() => {}, {});
     ^^^^^^^^^^^^^^^^^^^^^^^^^^^ call of method `listen`. Function cannot be called on any member of intersection type
 67: server.listen(() => {}, {});
     ^^^^^^^^^^^^^ intersection
  Member 1:
  1129:     listen(port?: number, hostname?: string, backlog?: number, callback?: Function): Server;
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ function type. See lib: <BUILTINS>/node.js:1129
  Error:
   67: server.listen(() => {}, {});
                     ^^^^^^^^ function. This type is incompatible with the expected param type of
  1129:     listen(port?: number, hostname?: string, backlog?: number, callback?: Function): Server;
                          ^^^^^^ number. See lib: <BUILTINS>/node.js:1129
  Member 2:
  1131:     listen(port?: number, backlog?: number, callback?: Function): Server;
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ function type. See lib: <BUILTINS>/node.js:1131
  Error:
   67: server.listen(() => {}, {});
                     ^^^^^^^^ function. This type is incompatible with the expected param type of
  1131:     listen(port?: number, backlog?: number, callback?: Function): Server;
                          ^^^^^^ number. See lib: <BUILTINS>/node.js:1131
  Member 3:
  1132:     listen(port?: number, hostname?: string, callback?: Function): Server;
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ function type. See lib: <BUILTINS>/node.js:1132
  Error:
   67: server.listen(() => {}, {});
                     ^^^^^^^^ function. This type is incompatible with the expected param type of
  1132:     listen(port?: number, hostname?: string, callback?: Function): Server;
                          ^^^^^^ number. See lib: <BUILTINS>/node.js:1132
  Member 4:
  1133:     listen(port?: number, callback?: Function): Server;
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ function type. See lib: <BUILTINS>/node.js:1133
  Error:
   67: server.listen(() => {}, {});
                     ^^^^^^^^ function. This type is incompatible with the expected param type of
  1133:     listen(port?: number, callback?: Function): Server;
                          ^^^^^^ number. See lib: <BUILTINS>/node.js:1133
  Member 5:
  1134:     listen(path: string, callback?: Function): Server;
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ function type. See lib: <BUILTINS>/node.js:1134
  Error:
   67: server.listen(() => {}, {});
                     ^^^^^^^^ function. This type is incompatible with the expected param type of
  1134:     listen(path: string, callback?: Function): Server;
                         ^^^^^^ string. See lib: <BUILTINS>/node.js:1134
  Member 6:
  1135:     listen(handle: Object, callback?: Function): Server;
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ function type. See lib: <BUILTINS>/node.js:1135
  Error:
   67: server.listen(() => {}, {});
                               ^^ object literal. This type is incompatible with the expected param type of
  1135:     listen(handle: Object, callback?: Function): Server;
                                              ^^^^^^^^ function type. See lib: <BUILTINS>/node.js:1135
    Callable property is incompatible:
      1135:     listen(handle: Object, callback?: Function): Server;
                                                  ^^^^^^^^ function type. Callable signature not found in. See lib: <BUILTINS>/node.js:1135
       67: server.listen(() => {}, {});
                                   ^^ object literal

Error: https/server.js:68
 68: server.listen(function() {}, {});
     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ call of method `listen`. Function cannot be called on any member of intersection type
 68: server.listen(function() {}, {});
     ^^^^^^^^^^^^^ intersection
  Member 1:
  1129:     listen(port?: number, hostname?: string, backlog?: number, callback?: Function): Server;
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ function type. See lib: <BUILTINS>/node.js:1129
  Error:
   68: server.listen(function() {}, {});
                     ^^^^^^^^^^ function. This type is incompatible with the expected param type of
  1129:     listen(port?: number, hostname?: string, backlog?: number, callback?: Function): Server;
                          ^^^^^^ number. See lib: <BUILTINS>/node.js:1129
  Member 2:
  1131:     listen(port?: number, backlog?: number, callback?: Function): Server;
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ function type. See lib: <BUILTINS>/node.js:1131
  Error:
   68: server.listen(function() {}, {});
                     ^^^^^^^^^^ function. This type is incompatible with the expected param type of
  1131:     listen(port?: number, backlog?: number, callback?: Function): Server;
                          ^^^^^^ number. See lib: <BUILTINS>/node.js:1131
  Member 3:
  1132:     listen(port?: number, hostname?: string, callback?: Function): Server;
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ function type. See lib: <BUILTINS>/node.js:1132
  Error:
   68: server.listen(function() {}, {});
                     ^^^^^^^^^^ function. This type is incompatible with the expected param type of
  1132:     listen(port?: number, hostname?: string, callback?: Function): Server;
                          ^^^^^^ number. See lib: <BUILTINS>/node.js:1132
  Member 4:
  1133:     listen(port?: number, callback?: Function): Server;
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ function type. See lib: <BUILTINS>/node.js:1133
  Error:
   68: server.listen(function() {}, {});
                     ^^^^^^^^^^ function. This type is incompatible with the expected param type of
  1133:     listen(port?: number, callback?: Function): Server;
                          ^^^^^^ number. See lib: <BUILTINS>/node.js:1133
  Member 5:
  1134:     listen(path: string, callback?: Function): Server;
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ function type. See lib: <BUILTINS>/node.js:1134
  Error:
   68: server.listen(function() {}, {});
                     ^^^^^^^^^^ function. This type is incompatible with the expected param type of
  1134:     listen(path: string, callback?: Function): Server;
                         ^^^^^^ string. See lib: <BUILTINS>/node.js:1134
  Member 6:
  1135:     listen(handle: Object, callback?: Function): Server;
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ function type. See lib: <BUILTINS>/node.js:1135
  Error:
   68: server.listen(function() {}, {});
                                    ^^ object literal. This type is incompatible with the expected param type of
  1135:     listen(handle: Object, callback?: Function): Server;
                                              ^^^^^^^^ function type. See lib: <BUILTINS>/node.js:1135
    Callable property is incompatible:
      1135:     listen(handle: Object, callback?: Function): Server;
                                                  ^^^^^^^^ function type. Callable signature not found in. See lib: <BUILTINS>/node.js:1135
       68: server.listen(function() {}, {});
                                        ^^ object literal

Error: https/server.js:69
 69: server.listen({}, () => {}, 'localhost', 123);
     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ call of method `listen`. Function cannot be called on any member of intersection type
 69: server.listen({}, () => {}, 'localhost', 123);
     ^^^^^^^^^^^^^ intersection
  Member 1:
  1129:     listen(port?: number, hostname?: string, backlog?: number, callback?: Function): Server;
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ function type. See lib: <BUILTINS>/node.js:1129
  Error:
   69: server.listen({}, () => {}, 'localhost', 123);
                     ^^ object literal. This type is incompatible with the expected param type of
  1129:     listen(port?: number, hostname?: string, backlog?: number, callback?: Function): Server;
                          ^^^^^^ number. See lib: <BUILTINS>/node.js:1129
  Member 2:
  1131:     listen(port?: number, backlog?: number, callback?: Function): Server;
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ function type. See lib: <BUILTINS>/node.js:1131
  Error:
   69: server.listen({}, () => {}, 'localhost', 123);
                     ^^ object literal. This type is incompatible with the expected param type of
  1131:     listen(port?: number, backlog?: number, callback?: Function): Server;
                          ^^^^^^ number. See lib: <BUILTINS>/node.js:1131
  Member 3:
  1132:     listen(port?: number, hostname?: string, callback?: Function): Server;
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ function type. See lib: <BUILTINS>/node.js:1132
  Error:
   69: server.listen({}, () => {}, 'localhost', 123);
                     ^^ object literal. This type is incompatible with the expected param type of
  1132:     listen(port?: number, hostname?: string, callback?: Function): Server;
                          ^^^^^^ number. See lib: <BUILTINS>/node.js:1132
  Member 4:
  1133:     listen(port?: number, callback?: Function): Server;
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ function type. See lib: <BUILTINS>/node.js:1133
  Error:
   69: server.listen({}, () => {}, 'localhost', 123);
                     ^^ object literal. This type is incompatible with the expected param type of
  1133:     listen(port?: number, callback?: Function): Server;
                          ^^^^^^ number. See lib: <BUILTINS>/node.js:1133
  Member 5:
  1134:     listen(path: string, callback?: Function): Server;
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ function type. See lib: <BUILTINS>/node.js:1134
  Error:
   69: server.listen({}, () => {}, 'localhost', 123);
                     ^^ object literal. This type is incompatible with the expected param type of
  1134:     listen(path: string, callback?: Function): Server;
                         ^^^^^^ string. See lib: <BUILTINS>/node.js:1134
  Member 6:
  1135:     listen(handle: Object, callback?: Function): Server;
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ function type. See lib: <BUILTINS>/node.js:1135
  Error:
   69: server.listen({}, () => {}, 'localhost', 123);
                                   ^^^^^^^^^^^ unused function argument
    1135:     listen(handle: Object, callback?: Function): Server;
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ function type expects no more than 2 arguments. See lib: <BUILTINS>/node.js:1135

Error: https/server.js:70
 70: server.listen({}, function() {}, 'localhost', 123);
     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ call of method `listen`. Function cannot be called on any member of intersection type
 70: server.listen({}, function() {}, 'localhost', 123);
     ^^^^^^^^^^^^^ intersection
  Member 1:
  1129:     listen(port?: number, hostname?: string, backlog?: number, callback?: Function): Server;
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ function type. See lib: <BUILTINS>/node.js:1129
  Error:
   70: server.listen({}, function() {}, 'localhost', 123);
                     ^^ object literal. This type is incompatible with the expected param type of
  1129:     listen(port?: number, hostname?: string, backlog?: number, callback?: Function): Server;
                          ^^^^^^ number. See lib: <BUILTINS>/node.js:1129
  Member 2:
  1131:     listen(port?: number, backlog?: number, callback?: Function): Server;
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ function type. See lib: <BUILTINS>/node.js:1131
  Error:
   70: server.listen({}, function() {}, 'localhost', 123);
                     ^^ object literal. This type is incompatible with the expected param type of
  1131:     listen(port?: number, backlog?: number, callback?: Function): Server;
                          ^^^^^^ number. See lib: <BUILTINS>/node.js:1131
  Member 3:
  1132:     listen(port?: number, hostname?: string, callback?: Function): Server;
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ function type. See lib: <BUILTINS>/node.js:1132
  Error:
   70: server.listen({}, function() {}, 'localhost', 123);
                     ^^ object literal. This type is incompatible with the expected param type of
  1132:     listen(port?: number, hostname?: string, callback?: Function): Server;
                          ^^^^^^ number. See lib: <BUILTINS>/node.js:1132
  Member 4:
  1133:     listen(port?: number, callback?: Function): Server;
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ function type. See lib: <BUILTINS>/node.js:1133
  Error:
   70: server.listen({}, function() {}, 'localhost', 123);
                     ^^ object literal. This type is incompatible with the expected param type of
  1133:     listen(port?: number, callback?: Function): Server;
                          ^^^^^^ number. See lib: <BUILTINS>/node.js:1133
  Member 5:
  1134:     listen(path: string, callback?: Function): Server;
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ function type. See lib: <BUILTINS>/node.js:1134
  Error:
   70: server.listen({}, function() {}, 'localhost', 123);
                     ^^ object literal. This type is incompatible with the expected param type of
  1134:     listen(path: string, callback?: Function): Server;
                         ^^^^^^ string. See lib: <BUILTINS>/node.js:1134
  Member 6:
  1135:     listen(handle: Object, callback?: Function): Server;
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ function type. See lib: <BUILTINS>/node.js:1135
  Error:
   70: server.listen({}, function() {}, 'localhost', 123);
                                        ^^^^^^^^^^^ unused function argument
    1135:     listen(handle: Object, callback?: Function): Server;
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ function type expects no more than 2 arguments. See lib: <BUILTINS>/node.js:1135

Error: https/server.js:71
 71: server.listen({}, () => {}, 123);
     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ call of method `listen`. Function cannot be called on any member of intersection type
 71: server.listen({}, () => {}, 123);
     ^^^^^^^^^^^^^ intersection
  Member 1:
  1129:     listen(port?: number, hostname?: string, backlog?: number, callback?: Function): Server;
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ function type. See lib: <BUILTINS>/node.js:1129
  Error:
   71: server.listen({}, () => {}, 123);
                     ^^ object literal. This type is incompatible with the expected param type of
  1129:     listen(port?: number, hostname?: string, backlog?: number, callback?: Function): Server;
                          ^^^^^^ number. See lib: <BUILTINS>/node.js:1129
  Member 2:
  1131:     listen(port?: number, backlog?: number, callback?: Function): Server;
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ function type. See lib: <BUILTINS>/node.js:1131
  Error:
   71: server.listen({}, () => {}, 123);
                     ^^ object literal. This type is incompatible with the expected param type of
  1131:     listen(port?: number, backlog?: number, callback?: Function): Server;
                          ^^^^^^ number. See lib: <BUILTINS>/node.js:1131
  Member 3:
  1132:     listen(port?: number, hostname?: string, callback?: Function): Server;
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ function type. See lib: <BUILTINS>/node.js:1132
  Error:
   71: server.listen({}, () => {}, 123);
                     ^^ object literal. This type is incompatible with the expected param type of
  1132:     listen(port?: number, hostname?: string, callback?: Function): Server;
                          ^^^^^^ number. See lib: <BUILTINS>/node.js:1132
  Member 4:
  1133:     listen(port?: number, callback?: Function): Server;
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ function type. See lib: <BUILTINS>/node.js:1133
  Error:
   71: server.listen({}, () => {}, 123);
                     ^^ object literal. This type is incompatible with the expected param type of
  1133:     listen(port?: number, callback?: Function): Server;
                          ^^^^^^ number. See lib: <BUILTINS>/node.js:1133
  Member 5:
  1134:     listen(path: string, callback?: Function): Server;
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ function type. See lib: <BUILTINS>/node.js:1134
  Error:
   71: server.listen({}, () => {}, 123);
                     ^^ object literal. This type is incompatible with the expected param type of
  1134:     listen(path: string, callback?: Function): Server;
                         ^^^^^^ string. See lib: <BUILTINS>/node.js:1134
  Member 6:
  1135:     listen(handle: Object, callback?: Function): Server;
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ function type. See lib: <BUILTINS>/node.js:1135
  Error:
   71: server.listen({}, () => {}, 123);
                                   ^^^ unused function argument
    1135:     listen(handle: Object, callback?: Function): Server;
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ function type expects no more than 2 arguments. See lib: <BUILTINS>/node.js:1135

Error: https/server.js:72
 72: server.listen({}, function() {}, 123);
     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ call of method `listen`. Function cannot be called on any member of intersection type
 72: server.listen({}, function() {}, 123);
     ^^^^^^^^^^^^^ intersection
  Member 1:
  1129:     listen(port?: number, hostname?: string, backlog?: number, callback?: Function): Server;
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ function type. See lib: <BUILTINS>/node.js:1129
  Error:
   72: server.listen({}, function() {}, 123);
                     ^^ object literal. This type is incompatible with the expected param type of
  1129:     listen(port?: number, hostname?: string, backlog?: number, callback?: Function): Server;
                          ^^^^^^ number. See lib: <BUILTINS>/node.js:1129
  Member 2:
  1131:     listen(port?: number, backlog?: number, callback?: Function): Server;
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ function type. See lib: <BUILTINS>/node.js:1131
  Error:
   72: server.listen({}, function() {}, 123);
                     ^^ object literal. This type is incompatible with the expected param type of
  1131:     listen(port?: number, backlog?: number, callback?: Function): Server;
                          ^^^^^^ number. See lib: <BUILTINS>/node.js:1131
  Member 3:
  1132:     listen(port?: number, hostname?: string, callback?: Function): Server;
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ function type. See lib: <BUILTINS>/node.js:1132
  Error:
   72: server.listen({}, function() {}, 123);
                     ^^ object literal. This type is incompatible with the expected param type of
  1132:     listen(port?: number, hostname?: string, callback?: Function): Server;
                          ^^^^^^ number. See lib: <BUILTINS>/node.js:1132
  Member 4:
  1133:     listen(port?: number, callback?: Function): Server;
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ function type. See lib: <BUILTINS>/node.js:1133
  Error:
   72: server.listen({}, function() {}, 123);
                     ^^ object literal. This type is incompatible with the expected param type of
  1133:     listen(port?: number, callback?: Function): Server;
                          ^^^^^^ number. See lib: <BUILTINS>/node.js:1133
  Member 5:
  1134:     listen(path: string, callback?: Function): Server;
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ function type. See lib: <BUILTINS>/node.js:1134
  Error:
   72: server.listen({}, function() {}, 123);
                     ^^ object literal. This type is incompatible with the expected param type of
  1134:     listen(path: string, callback?: Function): Server;
                         ^^^^^^ string. See lib: <BUILTINS>/node.js:1134
  Member 6:
  1135:     listen(handle: Object, callback?: Function): Server;
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ function type. See lib: <BUILTINS>/node.js:1135
  Error:
   72: server.listen({}, function() {}, 123);
                                        ^^^ unused function argument
    1135:     listen(handle: Object, callback?: Function): Server;
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ function type expects no more than 2 arguments. See lib: <BUILTINS>/node.js:1135

Error: https/server.js:73
 73: server.listen(() => {}, 123);
     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^ call of method `listen`. Function cannot be called on any member of intersection type
 73: server.listen(() => {}, 123);
     ^^^^^^^^^^^^^ intersection
  Member 1:
  1129:     listen(port?: number, hostname?: string, backlog?: number, callback?: Function): Server;
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ function type. See lib: <BUILTINS>/node.js:1129
  Error:
   73: server.listen(() => {}, 123);
                     ^^^^^^^^ function. This type is incompatible with the expected param type of
  1129:     listen(port?: number, hostname?: string, backlog?: number, callback?: Function): Server;
                          ^^^^^^ number. See lib: <BUILTINS>/node.js:1129
  Member 2:
  1131:     listen(port?: number, backlog?: number, callback?: Function): Server;
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ function type. See lib: <BUILTINS>/node.js:1131
  Error:
   73: server.listen(() => {}, 123);
                     ^^^^^^^^ function. This type is incompatible with the expected param type of
  1131:     listen(port?: number, backlog?: number, callback?: Function): Server;
                          ^^^^^^ number. See lib: <BUILTINS>/node.js:1131
  Member 3:
  1132:     listen(port?: number, hostname?: string, callback?: Function): Server;
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ function type. See lib: <BUILTINS>/node.js:1132
  Error:
   73: server.listen(() => {}, 123);
                     ^^^^^^^^ function. This type is incompatible with the expected param type of
  1132:     listen(port?: number, hostname?: string, callback?: Function): Server;
                          ^^^^^^ number. See lib: <BUILTINS>/node.js:1132
  Member 4:
  1133:     listen(port?: number, callback?: Function): Server;
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ function type. See lib: <BUILTINS>/node.js:1133
  Error:
   73: server.listen(() => {}, 123);
                     ^^^^^^^^ function. This type is incompatible with the expected param type of
  1133:     listen(port?: number, callback?: Function): Server;
                          ^^^^^^ number. See lib: <BUILTINS>/node.js:1133
  Member 5:
  1134:     listen(path: string, callback?: Function): Server;
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ function type. See lib: <BUILTINS>/node.js:1134
  Error:
   73: server.listen(() => {}, 123);
                     ^^^^^^^^ function. This type is incompatible with the expected param type of
  1134:     listen(path: string, callback?: Function): Server;
                         ^^^^^^ string. See lib: <BUILTINS>/node.js:1134
  Member 6:
  1135:     listen(handle: Object, callback?: Function): Server;
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ function type. See lib: <BUILTINS>/node.js:1135
  Error:
   73: server.listen(() => {}, 123);
                               ^^^ number. This type is incompatible with the expected param type of
  1135:     listen(handle: Object, callback?: Function): Server;
                                              ^^^^^^^^ function type. See lib: <BUILTINS>/node.js:1135

Error: https/server.js:74
 74: server.listen(function() {}, 123);
     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ call of method `listen`. Function cannot be called on any member of intersection type
 74: server.listen(function() {}, 123);
     ^^^^^^^^^^^^^ intersection
  Member 1:
  1129:     listen(port?: number, hostname?: string, backlog?: number, callback?: Function): Server;
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ function type. See lib: <BUILTINS>/node.js:1129
  Error:
   74: server.listen(function() {}, 123);
                     ^^^^^^^^^^ function. This type is incompatible with the expected param type of
  1129:     listen(port?: number, hostname?: string, backlog?: number, callback?: Function): Server;
                          ^^^^^^ number. See lib: <BUILTINS>/node.js:1129
  Member 2:
  1131:     listen(port?: number, backlog?: number, callback?: Function): Server;
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ function type. See lib: <BUILTINS>/node.js:1131
  Error:
   74: server.listen(function() {}, 123);
                     ^^^^^^^^^^ function. This type is incompatible with the expected param type of
  1131:     listen(port?: number, backlog?: number, callback?: Function): Server;
                          ^^^^^^ number. See lib: <BUILTINS>/node.js:1131
  Member 3:
  1132:     listen(port?: number, hostname?: string, callback?: Function): Server;
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ function type. See lib: <BUILTINS>/node.js:1132
  Error:
   74: server.listen(function() {}, 123);
                     ^^^^^^^^^^ function. This type is incompatible with the expected param type of
  1132:     listen(port?: number, hostname?: string, callback?: Function): Server;
                          ^^^^^^ number. See lib: <BUILTINS>/node.js:1132
  Member 4:
  1133:     listen(port?: number, callback?: Function): Server;
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ function type. See lib: <BUILTINS>/node.js:1133
  Error:
   74: server.listen(function() {}, 123);
                     ^^^^^^^^^^ function. This type is incompatible with the expected param type of
  1133:     listen(port?: number, callback?: Function): Server;
                          ^^^^^^ number. See lib: <BUILTINS>/node.js:1133
  Member 5:
  1134:     listen(path: string, callback?: Function): Server;
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ function type. See lib: <BUILTINS>/node.js:1134
  Error:
   74: server.listen(function() {}, 123);
                     ^^^^^^^^^^ function. This type is incompatible with the expected param type of
  1134:     listen(path: string, callback?: Function): Server;
                         ^^^^^^ string. See lib: <BUILTINS>/node.js:1134
  Member 6:
  1135:     listen(handle: Object, callback?: Function): Server;
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ function type. See lib: <BUILTINS>/node.js:1135
  Error:
   74: server.listen(function() {}, 123);
                                    ^^^ number. This type is incompatible with the expected param type of
  1135:     listen(handle: Object, callback?: Function): Server;
                                              ^^^^^^^^ function type. See lib: <BUILTINS>/node.js:1135

Error: https/server.js:75
 75: server.listen(() => {}, 'localhost', 123);
     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ call of method `listen`. Function cannot be called on any member of intersection type
 75: server.listen(() => {}, 'localhost', 123);
     ^^^^^^^^^^^^^ intersection
  Member 1:
  1129:     listen(port?: number, hostname?: string, backlog?: number, callback?: Function): Server;
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ function type. See lib: <BUILTINS>/node.js:1129
  Error:
   75: server.listen(() => {}, 'localhost', 123);
                     ^^^^^^^^ function. This type is incompatible with the expected param type of
  1129:     listen(port?: number, hostname?: string, backlog?: number, callback?: Function): Server;
                          ^^^^^^ number. See lib: <BUILTINS>/node.js:1129
  Member 2:
  1131:     listen(port?: number, backlog?: number, callback?: Function): Server;
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ function type. See lib: <BUILTINS>/node.js:1131
  Error:
   75: server.listen(() => {}, 'localhost', 123);
                     ^^^^^^^^ function. This type is incompatible with the expected param type of
  1131:     listen(port?: number, backlog?: number, callback?: Function): Server;
                          ^^^^^^ number. See lib: <BUILTINS>/node.js:1131
  Member 3:
  1132:     listen(port?: number, hostname?: string, callback?: Function): Server;
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ function type. See lib: <BUILTINS>/node.js:1132
  Error:
   75: server.listen(() => {}, 'localhost', 123);
                     ^^^^^^^^ function. This type is incompatible with the expected param type of
  1132:     listen(port?: number, hostname?: string, callback?: Function): Server;
                          ^^^^^^ number. See lib: <BUILTINS>/node.js:1132
  Member 4:
  1133:     listen(port?: number, callback?: Function): Server;
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ function type. See lib: <BUILTINS>/node.js:1133
  Error:
   75: server.listen(() => {}, 'localhost', 123);
                     ^^^^^^^^ function. This type is incompatible with the expected param type of
  1133:     listen(port?: number, callback?: Function): Server;
                          ^^^^^^ number. See lib: <BUILTINS>/node.js:1133
  Member 5:
  1134:     listen(path: string, callback?: Function): Server;
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ function type. See lib: <BUILTINS>/node.js:1134
  Error:
   75: server.listen(() => {}, 'localhost', 123);
                     ^^^^^^^^ function. This type is incompatible with the expected param type of
  1134:     listen(path: string, callback?: Function): Server;
                         ^^^^^^ string. See lib: <BUILTINS>/node.js:1134
  Member 6:
  1135:     listen(handle: Object, callback?: Function): Server;
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ function type. See lib: <BUILTINS>/node.js:1135
  Error:
   75: server.listen(() => {}, 'localhost', 123);
                               ^^^^^^^^^^^ string. This type is incompatible with the expected param type of
  1135:     listen(handle: Object, callback?: Function): Server;
                                              ^^^^^^^^ function type. See lib: <BUILTINS>/node.js:1135

Error: https/server.js:76
 76: server.listen(function() {}, 'localhost', 123);
     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ call of method `listen`. Function cannot be called on any member of intersection type
 76: server.listen(function() {}, 'localhost', 123);
     ^^^^^^^^^^^^^ intersection
  Member 1:
  1129:     listen(port?: number, hostname?: string, backlog?: number, callback?: Function): Server;
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ function type. See lib: <BUILTINS>/node.js:1129
  Error:
   76: server.listen(function() {}, 'localhost', 123);
                     ^^^^^^^^^^ function. This type is incompatible with the expected param type of
  1129:     listen(port?: number, hostname?: string, backlog?: number, callback?: Function): Server;
                          ^^^^^^ number. See lib: <BUILTINS>/node.js:1129
  Member 2:
  1131:     listen(port?: number, backlog?: number, callback?: Function): Server;
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ function type. See lib: <BUILTINS>/node.js:1131
  Error:
   76: server.listen(function() {}, 'localhost', 123);
                     ^^^^^^^^^^ function. This type is incompatible with the expected param type of
  1131:     listen(port?: number, backlog?: number, callback?: Function): Server;
                          ^^^^^^ number. See lib: <BUILTINS>/node.js:1131
  Member 3:
  1132:     listen(port?: number, hostname?: string, callback?: Function): Server;
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ function type. See lib: <BUILTINS>/node.js:1132
  Error:
   76: server.listen(function() {}, 'localhost', 123);
                     ^^^^^^^^^^ function. This type is incompatible with the expected param type of
  1132:     listen(port?: number, hostname?: string, callback?: Function): Server;
                          ^^^^^^ number. See lib: <BUILTINS>/node.js:1132
  Member 4:
  1133:     listen(port?: number, callback?: Function): Server;
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ function type. See lib: <BUILTINS>/node.js:1133
  Error:
   76: server.listen(function() {}, 'localhost', 123);
                     ^^^^^^^^^^ function. This type is incompatible with the expected param type of
  1133:     listen(port?: number, callback?: Function): Server;
                          ^^^^^^ number. See lib: <BUILTINS>/node.js:1133
  Member 5:
  1134:     listen(path: string, callback?: Function): Server;
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ function type. See lib: <BUILTINS>/node.js:1134
  Error:
   76: server.listen(function() {}, 'localhost', 123);
                     ^^^^^^^^^^ function. This type is incompatible with the expected param type of
  1134:     listen(path: string, callback?: Function): Server;
                         ^^^^^^ string. See lib: <BUILTINS>/node.js:1134
  Member 6:
  1135:     listen(handle: Object, callback?: Function): Server;
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ function type. See lib: <BUILTINS>/node.js:1135
  Error:
   76: server.listen(function() {}, 'localhost', 123);
                                    ^^^^^^^^^^^ string. This type is incompatible with the expected param type of
  1135:     listen(handle: Object, callback?: Function): Server;
                                              ^^^^^^^^ function type. See lib: <BUILTINS>/node.js:1135

Error: https/server.js:77
 77: server.listen(() => {}, 'localhost');
     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ call of method `listen`. Function cannot be called on any member of intersection type
 77: server.listen(() => {}, 'localhost');
     ^^^^^^^^^^^^^ intersection
  Member 1:
  1129:     listen(port?: number, hostname?: string, backlog?: number, callback?: Function): Server;
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ function type. See lib: <BUILTINS>/node.js:1129
  Error:
   77: server.listen(() => {}, 'localhost');
                     ^^^^^^^^ function. This type is incompatible with the expected param type of
  1129:     listen(port?: number, hostname?: string, backlog?: number, callback?: Function): Server;
                          ^^^^^^ number. See lib: <BUILTINS>/node.js:1129
  Member 2:
  1131:     listen(port?: number, backlog?: number, callback?: Function): Server;
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ function type. See lib: <BUILTINS>/node.js:1131
  Error:
   77: server.listen(() => {}, 'localhost');
                     ^^^^^^^^ function. This type is incompatible with the expected param type of
  1131:     listen(port?: number, backlog?: number, callback?: Function): Server;
                          ^^^^^^ number. See lib: <BUILTINS>/node.js:1131
  Member 3:
  1132:     listen(port?: number, hostname?: string, callback?: Function): Server;
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ function type. See lib: <BUILTINS>/node.js:1132
  Error:
   77: server.listen(() => {}, 'localhost');
                     ^^^^^^^^ function. This type is incompatible with the expected param type of
  1132:     listen(port?: number, hostname?: string, callback?: Function): Server;
                          ^^^^^^ number. See lib: <BUILTINS>/node.js:1132
  Member 4:
  1133:     listen(port?: number, callback?: Function): Server;
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ function type. See lib: <BUILTINS>/node.js:1133
  Error:
   77: server.listen(() => {}, 'localhost');
                     ^^^^^^^^ function. This type is incompatible with the expected param type of
  1133:     listen(port?: number, callback?: Function): Server;
                          ^^^^^^ number. See lib: <BUILTINS>/node.js:1133
  Member 5:
  1134:     listen(path: string, callback?: Function): Server;
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ function type. See lib: <BUILTINS>/node.js:1134
  Error:
   77: server.listen(() => {}, 'localhost');
                     ^^^^^^^^ function. This type is incompatible with the expected param type of
  1134:     listen(path: string, callback?: Function): Server;
                         ^^^^^^ string. See lib: <BUILTINS>/node.js:1134
  Member 6:
  1135:     listen(handle: Object, callback?: Function): Server;
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ function type. See lib: <BUILTINS>/node.js:1135
  Error:
   77: server.listen(() => {}, 'localhost');
                               ^^^^^^^^^^^ string. This type is incompatible with the expected param type of
  1135:     listen(handle: Object, callback?: Function): Server;
                                              ^^^^^^^^ function type. See lib: <BUILTINS>/node.js:1135

Error: https/server.js:78
 78: server.listen(function() {}, 'localhost');
     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ call of method `listen`. Function cannot be called on any member of intersection type
 78: server.listen(function() {}, 'localhost');
     ^^^^^^^^^^^^^ intersection
  Member 1:
  1129:     listen(port?: number, hostname?: string, backlog?: number, callback?: Function): Server;
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ function type. See lib: <BUILTINS>/node.js:1129
  Error:
   78: server.listen(function() {}, 'localhost');
                     ^^^^^^^^^^ function. This type is incompatible with the expected param type of
  1129:     listen(port?: number, hostname?: string, backlog?: number, callback?: Function): Server;
                          ^^^^^^ number. See lib: <BUILTINS>/node.js:1129
  Member 2:
  1131:     listen(port?: number, backlog?: number, callback?: Function): Server;
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ function type. See lib: <BUILTINS>/node.js:1131
  Error:
   78: server.listen(function() {}, 'localhost');
                     ^^^^^^^^^^ function. This type is incompatible with the expected param type of
  1131:     listen(port?: number, backlog?: number, callback?: Function): Server;
                          ^^^^^^ number. See lib: <BUILTINS>/node.js:1131
  Member 3:
  1132:     listen(port?: number, hostname?: string, callback?: Function): Server;
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ function type. See lib: <BUILTINS>/node.js:1132
  Error:
   78: server.listen(function() {}, 'localhost');
                     ^^^^^^^^^^ function. This type is incompatible with the expected param type of
  1132:     listen(port?: number, hostname?: string, callback?: Function): Server;
                          ^^^^^^ number. See lib: <BUILTINS>/node.js:1132
  Member 4:
  1133:     listen(port?: number, callback?: Function): Server;
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ function type. See lib: <BUILTINS>/node.js:1133
  Error:
   78: server.listen(function() {}, 'localhost');
                     ^^^^^^^^^^ function. This type is incompatible with the expected param type of
  1133:     listen(port?: number, callback?: Function): Server;
                          ^^^^^^ number. See lib: <BUILTINS>/node.js:1133
  Member 5:
  1134:     listen(path: string, callback?: Function): Server;
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ function type. See lib: <BUILTINS>/node.js:1134
  Error:
   78: server.listen(function() {}, 'localhost');
                     ^^^^^^^^^^ function. This type is incompatible with the expected param type of
  1134:     listen(path: string, callback?: Function): Server;
                         ^^^^^^ string. See lib: <BUILTINS>/node.js:1134
  Member 6:
  1135:     listen(handle: Object, callback?: Function): Server;
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ function type. See lib: <BUILTINS>/node.js:1135
  Error:
   78: server.listen(function() {}, 'localhost');
                                    ^^^^^^^^^^^ string. This type is incompatible with the expected param type of
  1135:     listen(handle: Object, callback?: Function): Server;
                                              ^^^^^^^^ function type. See lib: <BUILTINS>/node.js:1135

Error: https/server.js:79
 79: server.listen(8443, () => {}, 'localhost', 123);
     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ call of method `listen`. Function cannot be called on any member of intersection type
 79: server.listen(8443, () => {}, 'localhost', 123);
     ^^^^^^^^^^^^^ intersection
  Member 1:
  1129:     listen(port?: number, hostname?: string, backlog?: number, callback?: Function): Server;
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ function type. See lib: <BUILTINS>/node.js:1129
  Error:
   79: server.listen(8443, () => {}, 'localhost', 123);
                           ^^^^^^^^ function. This type is incompatible with the expected param type of
  1129:     listen(port?: number, hostname?: string, backlog?: number, callback?: Function): Server;
                                             ^^^^^^ string. See lib: <BUILTINS>/node.js:1129
  Member 2:
  1131:     listen(port?: number, backlog?: number, callback?: Function): Server;
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ function type. See lib: <BUILTINS>/node.js:1131
  Error:
   79: server.listen(8443, () => {}, 'localhost', 123);
                           ^^^^^^^^ function. This type is incompatible with the expected param type of
  1131:     listen(port?: number, backlog?: number, callback?: Function): Server;
                                            ^^^^^^ number. See lib: <BUILTINS>/node.js:1131
  Member 3:
  1132:     listen(port?: number, hostname?: string, callback?: Function): Server;
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ function type. See lib: <BUILTINS>/node.js:1132
  Error:
   79: server.listen(8443, () => {}, 'localhost', 123);
                           ^^^^^^^^ function. This type is incompatible with the expected param type of
  1132:     listen(port?: number, hostname?: string, callback?: Function): Server;
                                             ^^^^^^ string. See lib: <BUILTINS>/node.js:1132
  Member 4:
  1133:     listen(port?: number, callback?: Function): Server;
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ function type. See lib: <BUILTINS>/node.js:1133
  Error:
   79: server.listen(8443, () => {}, 'localhost', 123);
                                     ^^^^^^^^^^^ unused function argument
    1133:     listen(port?: number, callback?: Function): Server;
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ function type expects no more than 2 arguments. See lib: <BUILTINS>/node.js:1133
  Member 5:
  1134:     listen(path: string, callback?: Function): Server;
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ function type. See lib: <BUILTINS>/node.js:1134
  Error:
   79: server.listen(8443, () => {}, 'localhost', 123);
                     ^^^^ number. This type is incompatible with the expected param type of
  1134:     listen(path: string, callback?: Function): Server;
                         ^^^^^^ string. See lib: <BUILTINS>/node.js:1134
  Member 6:
  1135:     listen(handle: Object, callback?: Function): Server;
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ function type. See lib: <BUILTINS>/node.js:1135
  Error:
   79: server.listen(8443, () => {}, 'localhost', 123);
                     ^^^^ number. This type is incompatible with the expected param type of
  1135:     listen(handle: Object, callback?: Function): Server;
                           ^^^^^^ object type. See lib: <BUILTINS>/node.js:1135

Error: https/server.js:80
 80: server.listen(8443, function() {}, 'localhost', 123);
     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ call of method `listen`. Function cannot be called on any member of intersection type
 80: server.listen(8443, function() {}, 'localhost', 123);
     ^^^^^^^^^^^^^ intersection
  Member 1:
  1129:     listen(port?: number, hostname?: string, backlog?: number, callback?: Function): Server;
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ function type. See lib: <BUILTINS>/node.js:1129
  Error:
   80: server.listen(8443, function() {}, 'localhost', 123);
                           ^^^^^^^^^^ function. This type is incompatible with the expected param type of
  1129:     listen(port?: number, hostname?: string, backlog?: number, callback?: Function): Server;
                                             ^^^^^^ string. See lib: <BUILTINS>/node.js:1129
  Member 2:
  1131:     listen(port?: number, backlog?: number, callback?: Function): Server;
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ function type. See lib: <BUILTINS>/node.js:1131
  Error:
   80: server.listen(8443, function() {}, 'localhost', 123);
                           ^^^^^^^^^^ function. This type is incompatible with the expected param type of
  1131:     listen(port?: number, backlog?: number, callback?: Function): Server;
                                            ^^^^^^ number. See lib: <BUILTINS>/node.js:1131
  Member 3:
  1132:     listen(port?: number, hostname?: string, callback?: Function): Server;
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ function type. See lib: <BUILTINS>/node.js:1132
  Error:
   80: server.listen(8443, function() {}, 'localhost', 123);
                           ^^^^^^^^^^ function. This type is incompatible with the expected param type of
  1132:     listen(port?: number, hostname?: string, callback?: Function): Server;
                                             ^^^^^^ string. See lib: <BUILTINS>/node.js:1132
  Member 4:
  1133:     listen(port?: number, callback?: Function): Server;
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ function type. See lib: <BUILTINS>/node.js:1133
  Error:
   80: server.listen(8443, function() {}, 'localhost', 123);
                                          ^^^^^^^^^^^ unused function argument
    1133:     listen(port?: number, callback?: Function): Server;
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ function type expects no more than 2 arguments. See lib: <BUILTINS>/node.js:1133
  Member 5:
  1134:     listen(path: string, callback?: Function): Server;
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ function type. See lib: <BUILTINS>/node.js:1134
  Error:
   80: server.listen(8443, function() {}, 'localhost', 123);
                     ^^^^ number. This type is incompatible with the expected param type of
  1134:     listen(path: string, callback?: Function): Server;
                         ^^^^^^ string. See lib: <BUILTINS>/node.js:1134
  Member 6:
  1135:     listen(handle: Object, callback?: Function): Server;
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ function type. See lib: <BUILTINS>/node.js:1135
  Error:
   80: server.listen(8443, function() {}, 'localhost', 123);
                     ^^^^ number. This type is incompatible with the expected param type of
  1135:     listen(handle: Object, callback?: Function): Server;
                           ^^^^^^ object type. See lib: <BUILTINS>/node.js:1135

Error: https/server.js:81
 81: server.listen(8443, () => {}, 123);
     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ call of method `listen`. Function cannot be called on any member of intersection type
 81: server.listen(8443, () => {}, 123);
     ^^^^^^^^^^^^^ intersection
  Member 1:
  1129:     listen(port?: number, hostname?: string, backlog?: number, callback?: Function): Server;
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ function type. See lib: <BUILTINS>/node.js:1129
  Error:
   81: server.listen(8443, () => {}, 123);
                           ^^^^^^^^ function. This type is incompatible with the expected param type of
  1129:     listen(port?: number, hostname?: string, backlog?: number, callback?: Function): Server;
                                             ^^^^^^ string. See lib: <BUILTINS>/node.js:1129
  Member 2:
  1131:     listen(port?: number, backlog?: number, callback?: Function): Server;
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ function type. See lib: <BUILTINS>/node.js:1131
  Error:
   81: server.listen(8443, () => {}, 123);
                           ^^^^^^^^ function. This type is incompatible with the expected param type of
  1131:     listen(port?: number, backlog?: number, callback?: Function): Server;
                                            ^^^^^^ number. See lib: <BUILTINS>/node.js:1131
  Member 3:
  1132:     listen(port?: number, hostname?: string, callback?: Function): Server;
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ function type. See lib: <BUILTINS>/node.js:1132
  Error:
   81: server.listen(8443, () => {}, 123);
                           ^^^^^^^^ function. This type is incompatible with the expected param type of
  1132:     listen(port?: number, hostname?: string, callback?: Function): Server;
                                             ^^^^^^ string. See lib: <BUILTINS>/node.js:1132
  Member 4:
  1133:     listen(port?: number, callback?: Function): Server;
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ function type. See lib: <BUILTINS>/node.js:1133
  Error:
   81: server.listen(8443, () => {}, 123);
                                     ^^^ unused function argument
    1133:     listen(port?: number, callback?: Function): Server;
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ function type expects no more than 2 arguments. See lib: <BUILTINS>/node.js:1133
  Member 5:
  1134:     listen(path: string, callback?: Function): Server;
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ function type. See lib: <BUILTINS>/node.js:1134
  Error:
   81: server.listen(8443, () => {}, 123);
                     ^^^^ number. This type is incompatible with the expected param type of
  1134:     listen(path: string, callback?: Function): Server;
                         ^^^^^^ string. See lib: <BUILTINS>/node.js:1134
  Member 6:
  1135:     listen(handle: Object, callback?: Function): Server;
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ function type. See lib: <BUILTINS>/node.js:1135
  Error:
   81: server.listen(8443, () => {}, 123);
                     ^^^^ number. This type is incompatible with the expected param type of
  1135:     listen(handle: Object, callback?: Function): Server;
                           ^^^^^^ object type. See lib: <BUILTINS>/node.js:1135

Error: https/server.js:82
 82: server.listen(8443, function() {}, 123);
     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ call of method `listen`. Function cannot be called on any member of intersection type
 82: server.listen(8443, function() {}, 123);
     ^^^^^^^^^^^^^ intersection
  Member 1:
  1129:     listen(port?: number, hostname?: string, backlog?: number, callback?: Function): Server;
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ function type. See lib: <BUILTINS>/node.js:1129
  Error:
   82: server.listen(8443, function() {}, 123);
                           ^^^^^^^^^^ function. This type is incompatible with the expected param type of
  1129:     listen(port?: number, hostname?: string, backlog?: number, callback?: Function): Server;
                                             ^^^^^^ string. See lib: <BUILTINS>/node.js:1129
  Member 2:
  1131:     listen(port?: number, backlog?: number, callback?: Function): Server;
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ function type. See lib: <BUILTINS>/node.js:1131
  Error:
   82: server.listen(8443, function() {}, 123);
                           ^^^^^^^^^^ function. This type is incompatible with the expected param type of
  1131:     listen(port?: number, backlog?: number, callback?: Function): Server;
                                            ^^^^^^ number. See lib: <BUILTINS>/node.js:1131
  Member 3:
  1132:     listen(port?: number, hostname?: string, callback?: Function): Server;
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ function type. See lib: <BUILTINS>/node.js:1132
  Error:
   82: server.listen(8443, function() {}, 123);
                           ^^^^^^^^^^ function. This type is incompatible with the expected param type of
  1132:     listen(port?: number, hostname?: string, callback?: Function): Server;
                                             ^^^^^^ string. See lib: <BUILTINS>/node.js:1132
  Member 4:
  1133:     listen(port?: number, callback?: Function): Server;
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ function type. See lib: <BUILTINS>/node.js:1133
  Error:
   82: server.listen(8443, function() {}, 123);
                                          ^^^ unused function argument
    1133:     listen(port?: number, callback?: Function): Server;
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ function type expects no more than 2 arguments. See lib: <BUILTINS>/node.js:1133
  Member 5:
  1134:     listen(path: string, callback?: Function): Server;
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ function type. See lib: <BUILTINS>/node.js:1134
  Error:
   82: server.listen(8443, function() {}, 123);
                     ^^^^ number. This type is incompatible with the expected param type of
  1134:     listen(path: string, callback?: Function): Server;
                         ^^^^^^ string. See lib: <BUILTINS>/node.js:1134
  Member 6:
  1135:     listen(handle: Object, callback?: Function): Server;
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ function type. See lib: <BUILTINS>/node.js:1135
  Error:
   82: server.listen(8443, function() {}, 123);
                     ^^^^ number. This type is incompatible with the expected param type of
  1135:     listen(handle: Object, callback?: Function): Server;
                           ^^^^^^ object type. See lib: <BUILTINS>/node.js:1135

Error: https/server.js:83
 83: server.listen(8443, () => {}, 'localhost');
     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ call of method `listen`. Function cannot be called on any member of intersection type
 83: server.listen(8443, () => {}, 'localhost');
     ^^^^^^^^^^^^^ intersection
  Member 1:
  1129:     listen(port?: number, hostname?: string, backlog?: number, callback?: Function): Server;
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ function type. See lib: <BUILTINS>/node.js:1129
  Error:
   83: server.listen(8443, () => {}, 'localhost');
                           ^^^^^^^^ function. This type is incompatible with the expected param type of
  1129:     listen(port?: number, hostname?: string, backlog?: number, callback?: Function): Server;
                                             ^^^^^^ string. See lib: <BUILTINS>/node.js:1129
  Member 2:
  1131:     listen(port?: number, backlog?: number, callback?: Function): Server;
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ function type. See lib: <BUILTINS>/node.js:1131
  Error:
   83: server.listen(8443, () => {}, 'localhost');
                           ^^^^^^^^ function. This type is incompatible with the expected param type of
  1131:     listen(port?: number, backlog?: number, callback?: Function): Server;
                                            ^^^^^^ number. See lib: <BUILTINS>/node.js:1131
  Member 3:
  1132:     listen(port?: number, hostname?: string, callback?: Function): Server;
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ function type. See lib: <BUILTINS>/node.js:1132
  Error:
   83: server.listen(8443, () => {}, 'localhost');
                           ^^^^^^^^ function. This type is incompatible with the expected param type of
  1132:     listen(port?: number, hostname?: string, callback?: Function): Server;
                                             ^^^^^^ string. See lib: <BUILTINS>/node.js:1132
  Member 4:
  1133:     listen(port?: number, callback?: Function): Server;
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ function type. See lib: <BUILTINS>/node.js:1133
  Error:
   83: server.listen(8443, () => {}, 'localhost');
                                     ^^^^^^^^^^^ unused function argument
    1133:     listen(port?: number, callback?: Function): Server;
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ function type expects no more than 2 arguments. See lib: <BUILTINS>/node.js:1133
  Member 5:
  1134:     listen(path: string, callback?: Function): Server;
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ function type. See lib: <BUILTINS>/node.js:1134
  Error:
   83: server.listen(8443, () => {}, 'localhost');
                     ^^^^ number. This type is incompatible with the expected param type of
  1134:     listen(path: string, callback?: Function): Server;
                         ^^^^^^ string. See lib: <BUILTINS>/node.js:1134
  Member 6:
  1135:     listen(handle: Object, callback?: Function): Server;
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ function type. See lib: <BUILTINS>/node.js:1135
  Error:
   83: server.listen(8443, () => {}, 'localhost');
                     ^^^^ number. This type is incompatible with the expected param type of
  1135:     listen(handle: Object, callback?: Function): Server;
                           ^^^^^^ object type. See lib: <BUILTINS>/node.js:1135

Error: https/server.js:84
 84: server.listen(8443, function() {}, 'localhost');
     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ call of method `listen`. Function cannot be called on any member of intersection type
 84: server.listen(8443, function() {}, 'localhost');
     ^^^^^^^^^^^^^ intersection
  Member 1:
  1129:     listen(port?: number, hostname?: string, backlog?: number, callback?: Function): Server;
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ function type. See lib: <BUILTINS>/node.js:1129
  Error:
   84: server.listen(8443, function() {}, 'localhost');
                           ^^^^^^^^^^ function. This type is incompatible with the expected param type of
  1129:     listen(port?: number, hostname?: string, backlog?: number, callback?: Function): Server;
                                             ^^^^^^ string. See lib: <BUILTINS>/node.js:1129
  Member 2:
  1131:     listen(port?: number, backlog?: number, callback?: Function): Server;
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ function type. See lib: <BUILTINS>/node.js:1131
  Error:
   84: server.listen(8443, function() {}, 'localhost');
                           ^^^^^^^^^^ function. This type is incompatible with the expected param type of
  1131:     listen(port?: number, backlog?: number, callback?: Function): Server;
                                            ^^^^^^ number. See lib: <BUILTINS>/node.js:1131
  Member 3:
  1132:     listen(port?: number, hostname?: string, callback?: Function): Server;
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ function type. See lib: <BUILTINS>/node.js:1132
  Error:
   84: server.listen(8443, function() {}, 'localhost');
                           ^^^^^^^^^^ function. This type is incompatible with the expected param type of
  1132:     listen(port?: number, hostname?: string, callback?: Function): Server;
                                             ^^^^^^ string. See lib: <BUILTINS>/node.js:1132
  Member 4:
  1133:     listen(port?: number, callback?: Function): Server;
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ function type. See lib: <BUILTINS>/node.js:1133
  Error:
   84: server.listen(8443, function() {}, 'localhost');
                                          ^^^^^^^^^^^ unused function argument
    1133:     listen(port?: number, callback?: Function): Server;
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ function type expects no more than 2 arguments. See lib: <BUILTINS>/node.js:1133
  Member 5:
  1134:     listen(path: string, callback?: Function): Server;
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ function type. See lib: <BUILTINS>/node.js:1134
  Error:
   84: server.listen(8443, function() {}, 'localhost');
                     ^^^^ number. This type is incompatible with the expected param type of
  1134:     listen(path: string, callback?: Function): Server;
                         ^^^^^^ string. See lib: <BUILTINS>/node.js:1134
  Member 6:
  1135:     listen(handle: Object, callback?: Function): Server;
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ function type. See lib: <BUILTINS>/node.js:1135
  Error:
   84: server.listen(8443, function() {}, 'localhost');
                     ^^^^ number. This type is incompatible with the expected param type of
  1135:     listen(handle: Object, callback?: Function): Server;
                           ^^^^^^ object type. See lib: <BUILTINS>/node.js:1135

Error: invalid_package_file/package.json:1
  1: 
     ^ Unexpected end of input

Error: json_file/json_invalid.json:1
  1: :derp
     ^ Unexpected token :

Error: json_file/test.js:4
  4: (data.foo: void); // error, should be object literal
      ^^^^^^^^ object literal. This type is incompatible with
  4: (data.foo: void); // error, should be object literal
                ^^^^ undefined

Error: json_file/test.js:5
  5: (data.foo.bar: void); // error, should be boolean
      ^^^^^^^^^^^^ boolean. This type is incompatible with
  5: (data.foo.bar: void); // error, should be boolean
                    ^^^^ undefined

Error: json_file/test.js:6
  6: (data.abc: boolean); // error, should be ?string
      ^^^^^^^^ null. This type is incompatible with
  6: (data.abc: boolean); // error, should be ?string
                ^^^^^^^ boolean

Error: json_file/test.js:6
  6: (data.abc: boolean); // error, should be ?string
      ^^^^^^^^ string. This type is incompatible with
  6: (data.abc: boolean); // error, should be ?string
                ^^^^^^^ boolean

Error: json_file/test.js:6
  6: (data.abc: boolean); // error, should be ?string
      ^^^^^^^^ undefined. This type is incompatible with
  6: (data.abc: boolean); // error, should be ?string
                ^^^^^^^ boolean

Error: json_file/test.js:9
  9: (data2.baz: void); // error, should be string
      ^^^^^^^^^ string. This type is incompatible with
  9: (data2.baz: void); // error, should be string
                 ^^^^ undefined

Error: json_file/test.js:12
 12: (data3.foo: void); // error, should be number (not string! index.js wins)
      ^^^^^^^^^ number. This type is incompatible with
 12: (data3.foo: void); // error, should be number (not string! index.js wins)
                 ^^^^ undefined

Error: json_file/test.js:16
 16: (data4: void); // error, should be Array<number>
      ^^^^^ array literal. This type is incompatible with
 16: (data4: void); // error, should be Array<number>
             ^^^^ undefined

Error: json_file/test.js:18
 18: (require('./json_string'): void); // error, should be string
      ^^^^^^^^^^^^^^^^^^^^^^^^ string. This type is incompatible with
 18: (require('./json_string'): void); // error, should be string
                                ^^^^ undefined

Error: json_file/test.js:19
 19: (require('./json_number'): void); // error, should be number
      ^^^^^^^^^^^^^^^^^^^^^^^^ number. This type is incompatible with
 19: (require('./json_number'): void); // error, should be number
                                ^^^^ undefined

Error: json_file/test.js:20
 20: (require('./json_true'): void); // error, should be true
      ^^^^^^^^^^^^^^^^^^^^^^ boolean. This type is incompatible with
 20: (require('./json_true'): void); // error, should be true
                              ^^^^ undefined

Error: json_file/test.js:21
 21: (require('./json_false'): void); // error, should be false
      ^^^^^^^^^^^^^^^^^^^^^^^ boolean. This type is incompatible with
 21: (require('./json_false'): void); // error, should be false
                               ^^^^ undefined

Error: json_file/test.js:22
 22: (require('./json_null'): void); // error, should be null
      ^^^^^^^^^^^^^^^^^^^^^^ null. This type is incompatible with
 22: (require('./json_null'): void); // error, should be null
                              ^^^^ undefined

Error: os/userInfo.js:7
  7: (u1.username: Buffer); // error
      ^^^^^^^^^^^ string. This type is incompatible with
  7: (u1.username: Buffer); // error
                   ^^^^^^ Buffer

Error: os/userInfo.js:11
 11: (u2.username: Buffer); // error
      ^^^^^^^^^^^ string. This type is incompatible with
 11: (u2.username: Buffer); // error
                   ^^^^^^ Buffer

Error: os/userInfo.js:14
 14: (u3.username: string); // error
      ^^^^^^^^^^^ Buffer. This type is incompatible with
 14: (u3.username: string); // error
                   ^^^^^^ string

Error: process/nextTick.js:13
 13:   (a: string, b: number, c: boolean) => {},
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ function. This type is incompatible with the expected param type of
1946:   nextTick: <T>(cb: (...T) => mixed, ...T) => void;
                          ^^^^^^^^^^^^^^^ function type. See lib: <BUILTINS>/node.js:1946
  This parameter is incompatible:
     14:   0, // Error: number ~> string
           ^ number. This type is incompatible with
     13:   (a: string, b: number, c: boolean) => {},
               ^^^^^^ string

Error: process/nextTick.js:13
 13:   (a: string, b: number, c: boolean) => {},
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ function. This type is incompatible with the expected param type of
1946:   nextTick: <T>(cb: (...T) => mixed, ...T) => void;
                          ^^^^^^^^^^^^^^^ function type. See lib: <BUILTINS>/node.js:1946
  This parameter is incompatible:
     16:   null // Error: null ~> boolean
           ^^^^ null. This type is incompatible with
     13:   (a: string, b: number, c: boolean) => {},
                                     ^^^^^^^ boolean

Error: process/nextTick.js:20
 20:   (a: string, b: number, c: boolean) => {},
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ function. This type is incompatible with the expected param type of
1946:   nextTick: <T>(cb: (...T) => mixed, ...T) => void;
                          ^^^^^^^^^^^^^^^ function type. See lib: <BUILTINS>/node.js:1946
  This parameter is incompatible:
     22:   'y', // Error: string ~> number
           ^^^ string. This type is incompatible with
     20:   (a: string, b: number, c: boolean) => {},
                          ^^^^^^ number

Error: process/nextTick.js:27
 27:   (a: string, b: number, c: boolean) => {} // Error: too few arguments
           ^^^^^^ string. This type is incompatible with
1946:   nextTick: <T>(cb: (...T) => mixed, ...T) => void;
                          ^^^^^^^^^^^^^^^ undefined (too few arguments, expected default/rest parameters). See lib: <BUILTINS>/node.js:1946

Error: process/nextTick.js:27
 27:   (a: string, b: number, c: boolean) => {} // Error: too few arguments
                      ^^^^^^ number. This type is incompatible with
1946:   nextTick: <T>(cb: (...T) => mixed, ...T) => void;
                          ^^^^^^^^^^^^^^^ undefined (too few arguments, expected default/rest parameters). See lib: <BUILTINS>/node.js:1946

Error: process/nextTick.js:27
 27:   (a: string, b: number, c: boolean) => {} // Error: too few arguments
                                 ^^^^^^^ boolean. This type is incompatible with
1946:   nextTick: <T>(cb: (...T) => mixed, ...T) => void;
                          ^^^^^^^^^^^^^^^ undefined (too few arguments, expected default/rest parameters). See lib: <BUILTINS>/node.js:1946


Found 76 errors
