Error -------------------------------------------------------------- test.js:4:2

Cannot create `F` element because property `foo` is missing in props but exists
in object type.


Error -------------------------------------------------------------- test.js:5:9

Cannot create `F` element because in property `foo`, number is incompatible with
string.


Error ------------------------------------------------------------- test.js:9:33

Cannot resolve name `numner`.


Error ------------------------------------------------------------- test.js:13:2

Cannot create `Z` element because number is not a React component.



Found 4 errors
