
test.js:3:7,12: string
This type is incompatible with
[LIB] lib.js:5:20,25: number

test.js:3:9,11: number
This type is incompatible with
[LIB] lib.js:2:32,37: string

test.js:5:7,12: string
This type is incompatible with
[LIB] lib.js:6:20,25: number

test.js:5:9,11: number
This type is incompatible with
[LIB] lib.js:2:32,37: string

test.js:7:7,12: function call
Error:
test.js:7:7,12: string
This type is incompatible with
[LIB] lib.js:7:20,25: number

test.js:7:7,12: function call
Error:
test.js:7:9,11: number
This type is incompatible with
[LIB] lib.js:2:32,37: string

Found 6 errors
