
test.js:1:7,7: A
This type is incompatible with
test.js:48:2,2: B

test.js:2:13,18: number
This type is incompatible with
test.js:10:13,18: string

test.js:4:17,22: number
This type is incompatible with
test.js:11:17,22: string

test.js:7:3,5: property `qux`
Property not found in
test.js:7:1,1: statics of A

test.js:9:7,7: B
This type is incompatible with
test.js:25:23,28: number

test.js:10:13,18: string
This type is incompatible with
test.js:2:13,18: number

test.js:13:5,7: assignment of property `x`
Error:
test.js:13:11,11: number
This type is incompatible with
test.js:10:13,18: string

test.js:15:5,12: call of method `foo`
Error:
test.js:15:11,11: number
This type is incompatible with
test.js:11:17,22: string

test.js:17:5,7: assignment of property `y`
Error:
test.js:17:11,11: number
This type is incompatible with
test.js:3:13,18: string

test.js:18:5,12: call of method `bar`
Error:
test.js:18:11,11: number
This type is incompatible with
test.js:5:17,22: string

test.js:19:7,9: property `qux`
Property not found in
test.js:19:5,5: statics of B

test.js:40:7,9: property `foo`
Property not found in
test.js:40:5,5: statics of D

test.js:42:5,12: call of method `bar`
Error:
test.js:42:11,11: number
This type is incompatible with
test.js:38:19,24: string

test.js:47:6,6: A
This type is incompatible with
test.js:1:7,7: class type: A

test.js:53:5,14: call of method `bar`
Error:
test.js:53:10,12: property `bar`
Property not found in
test.js:50:7,7: statics of E

test.js:54:12,17: number
This type is incompatible with
test.js:52:17,22: string

Found 16 errors
