Error ---------------------------------------------------------------------------------------------- sketchy_null.js:6:5

Sketchy null check on string [1] which is potentially an empty string. Perhaps you meant to check for null or
undefined [2]? [sketchy-null-string]

   sketchy_null.js:6:5
   6| if (x) { } // This should be an error
          ^

References:
   sketchy_null.js:3:17
   3| declare var x: ?string;
                      ^^^^^^ [1]
   sketchy_null.js:3:16
   3| declare var x: ?string;
                     ^^^^^^^ [2]


Warning --------------------------------------------------------------------------------------- deprecated_types.js:3:25

Deprecated type. Use `boolean` instead. [deprecated-type]

   3| function foo(x: mixed): bool {
                              ^^^^


Warning --------------------------------------------------------------------------------------- deprecated_types.js:6:33

Deprecated type. Use `boolean` instead. [deprecated-type]

   6| declare function bar(x: mixed): bool;
                                      ^^^^


Warning ----------------------------------------------------------------------------------------- dynamic-export.js:3:23

Unclear type. Using `any`, `Object`, or `Function` types is not safe! [unclear-type]

   3| module.exports = 3 as any; // should only report unclear type, not dynamic-export
                            ^^^


Warning -------------------------------------------------------------------------------------------- sketchy_null.js:8:5

Sketchy null check on string [1] which is potentially an empty string. Perhaps you meant to check for null or
undefined [2]? [sketchy-null-string]

   sketchy_null.js:8:5
   8| if (x) { } // This should be a warning
          ^

References:
   sketchy_null.js:3:17
   3| declare var x: ?string;
                      ^^^^^^ [1]
   sketchy_null.js:3:16
   3| declare var x: ?string;
                     ^^^^^^^ [2]



Found 1 error and 4 warnings
