
Stop any already-running server.

Quick start.

Expect no errors.
No errors!

The Flow server is currently in lazy mode and is only checking 44/49 files.
To learn more, visit flow.org/en/docs/lang/lazy-modes

"Warm up" a dependency.
No errors!

The Flow server is currently in lazy mode and is only checking 45/49 files.
To learn more, visit flow.org/en/docs/lang/lazy-modes

"Perturb" a dependent that depends on the warmed up, but unchanged dependency.
No errors!

The Flow server is currently in lazy mode and is only checking 47/49 files.
To learn more, visit flow.org/en/docs/lang/lazy-modes

Test that the perturbed dependent is actually known (expecting a crash otherwise).
No errors!

The Flow server is currently in lazy mode and is only checking 48/49 files.
To learn more, visit flow.org/en/docs/lang/lazy-modes

Done!
