Error ------------------------------------- class-extends-and-implements.js:15:6

Cannot extend `A` [1] with `C` because in property `p`, string [2] is
incompatible with number [3].


Error ------------------------------------- class-extends-and-implements.js:19:6

Cannot extend `B` [1] with `D` because in property `p`, string [2] is
incompatible with number [3].


Error ------------------------------------- class-extends-and-implements.js:31:6

Cannot implement `E` [1] with `G` because in property `p`, string [2] is
incompatible with number [3].


Error ------------------------------------- class-extends-and-implements.js:35:6

Cannot implement `F` [1] with `H` because in property `p`, string [2] is
incompatible with number [3].


Error ------------------------------------- class-extends-and-implements.js:47:6

Cannot extend `I` [1] with `K` because in property `p`, string [2] is
incompatible with number [3].


Error ------------------------------------- class-extends-and-implements.js:51:6

Cannot extend `J` [1] with `L` because in property `p`, string [2] is
incompatible with number [3].


Error ------------------------------------- class-extends-and-implements.js:71:7

Cannot extend `M1` [1] with `O` because in property `p1`, string [2] is
incompatible with number [3].


Error ------------------------------------- class-extends-and-implements.js:72:7

Cannot extend `M2` [1] with `O` because in property `p2`, string [2] is
incompatible with number [3].


Error ------------------------------------- class-extends-and-implements.js:76:7

Cannot extend `N1` [1] with `P` because in property `p1`, string [2] is
incompatible with number [3].


Error ------------------------------------- class-extends-and-implements.js:77:7

Cannot extend `N2` [1] with `P` because in property `p2`, string [2] is
incompatible with number [3].


Error ------------------------------------- class-extends-and-implements.js:97:7

Cannot implement `Q1` [1] with `S` because in property `p1`, number [2] is
incompatible with string [3].


Error ------------------------------------- class-extends-and-implements.js:98:7

Cannot implement `Q2` [1] with `S` because in property `p2`, number [2] is
incompatible with string [3].


Error ------------------------------------ class-extends-and-implements.js:102:7

Cannot implement `R1` [1] with `T` because in property `p1`, number [2] is
incompatible with string [3].


Error ------------------------------------ class-extends-and-implements.js:103:7

Cannot implement `R2` [1] with `T` because in property `p2`, number [2] is
incompatible with string [3].


Error --------------------------------------- class-refinement-env-merge.js:12:6

Cannot cast `this.p` to number because:
 - string [1] is incompatible with number [2].
 - string [3] is incompatible with number [2].


Error -------------------------------------------- desc-class-properties.js:16:6

Cannot cast `this.a` to number because string [1] is incompatible with
number [2].


Error -------------------------------------------- desc-class-properties.js:17:6

Cannot cast `super.a` to number because string [1] is incompatible with
number [2].


Error -------------------------------------------- desc-class-properties.js:18:6

Cannot cast `this.b` to number because string [1] is incompatible with
number [2].


Error -------------------------------------------- desc-class-properties.js:19:6

Cannot cast `this.#c` to number because string [1] is incompatible with
number [2].


Error ----------------------------------------- indexer-key-compatibility.js:7:2

Cannot cast `o` to object type because in the indexer property's key, number [1]
is incompatible with string [2].


Error ------------------------------------ loc-primary-for-covariant-ops.js:8:16

Cannot cast `any` to function type because in the first argument and then
property `p`, number [1] is incompatible with string [2].


Error ----------------------------------- loc-primary-for-covariant-ops.js:11:14

Cannot cast `any` to `X` because in type argument `T` and then property `p`,
number [1] is incompatible with string [2].


Error ------------------------------------------------------- loc-primary.js:8:2

Cannot cast `a1` to `A` because in property `p`, number [1] is incompatible with
string [2].


Error ------------------------------------------------------ loc-primary.js:10:6

Cannot cast object literal to `A` because in property `p`, number [1] is
incompatible with string [2].


Error ------------------------------------------------------ loc-primary.js:11:6

Cannot cast object literal to `A` because in property `p`, number [1] is
incompatible with string [2].


Error ------------------------------------------------------ loc-primary.js:15:2

Cannot cast `b1` to `B` because in property `a.b`, number [1] is incompatible
with string [2].


Error ------------------------------------------------------ loc-primary.js:17:6

Cannot cast object literal to `B` because in property `a.b`, number [1] is
incompatible with string [2].


Error ----------------------------------------------------- loc-primary.js:19:10

Cannot cast object literal to `B` because in property `a.b`, number [1] is
incompatible with string [2].


Error ----------------------------------------------------- loc-primary.js:20:10

Cannot cast object literal to `B` because in property `a.b`, number [1] is
incompatible with string [2].


Error ------------------------------------------------------ loc-primary.js:24:2

Cannot cast `c1` to `C` because in property `a.b.c`, number [1] is incompatible
with string [2].


Error ------------------------------------------------------ loc-primary.js:26:6

Cannot cast object literal to `C` because in property `a.b.c`, number [1] is
incompatible with string [2].


Error ----------------------------------------------------- loc-primary.js:28:10

Cannot cast object literal to `C` because in property `a.b.c`, number [1] is
incompatible with string [2].


Error ----------------------------------------------------- loc-primary.js:30:14

Cannot cast object literal to `C` because in property `a.b.c`, number [1] is
incompatible with string [2].


Error ----------------------------------------------------- loc-primary.js:31:14

Cannot cast object literal to `C` because in property `a.b.c`, number [1] is
incompatible with string [2].


Error ------------------------------------------------------ loc-primary.js:35:2

Cannot cast `d1` to `D` because in property `a.b.c.d`, number [1] is
incompatible with string [2].


Error ------------------------------------------------------ loc-primary.js:37:6

Cannot cast object literal to `D` because in property `a.b.c.d`, number [1] is
incompatible with string [2].


Error ----------------------------------------------------- loc-primary.js:39:10

Cannot cast object literal to `D` because in property `a.b.c.d`, number [1] is
incompatible with string [2].


Error ----------------------------------------------------- loc-primary.js:41:14

Cannot cast object literal to `D` because in property `a.b.c.d`, number [1] is
incompatible with string [2].


Error ----------------------------------------------------- loc-primary.js:43:18

Cannot cast object literal to `D` because in property `a.b.c.d`, number [1] is
incompatible with string [2].


Error ----------------------------------------------------- loc-primary.js:44:18

Cannot cast object literal to `D` because in property `a.b.c.d`, number [1] is
incompatible with string [2].


Error ---------------------------------------------------- loc-reference.js:15:2

Cannot cast `x1` to empty because `X` [1] is incompatible with empty [2].


Error ---------------------------------------------------- loc-reference.js:16:2

Cannot cast `x2` to empty because `X` [1] is incompatible with empty [2].


Error ---------------------------------------------------- loc-reference.js:17:2

Cannot cast `x3` to empty because `X` [1] is incompatible with empty [2].


Error ---------------------------------------------------- loc-reference.js:18:2

Cannot cast `x4` to empty because `X` [1] is incompatible with empty [2].


Error ---------------------------------------------------- loc-reference.js:19:2

Cannot cast `x5` to empty because `X` [1] is incompatible with empty [2].


Error ---------------------------------------------------- loc-reference.js:20:2

Cannot cast `x6` to empty because `X` [1] is incompatible with empty [2].


Error ---------------------------------------------------- loc-reference.js:29:2

Cannot cast `y1` to empty because number [1] is incompatible with empty [2].


Error ---------------------------------------------------- loc-reference.js:30:2

Cannot cast `y2` to empty because number [1] is incompatible with empty [2].


Error ---------------------------------------------------- loc-reference.js:31:2

Cannot cast `y3` to empty because number [1] is incompatible with empty [2].


Error ---------------------------------------------------- loc-reference.js:32:2

Cannot cast `y4` to empty because number [1] is incompatible with empty [2].


Error ---------------------------------------------------- loc-reference.js:33:2

Cannot cast `y5` to empty because number [1] is incompatible with empty [2].


Error ---------------------------------------------------- loc-reference.js:34:2

Cannot cast `y6` to empty because number [1] is incompatible with empty [2].


Error ---------------------------------------------------- loc-reference.js:37:4

Cannot cast `x` to number because string [1] is incompatible with number [2].


Error ---------------------------------------------------- loc-reference.js:41:4

Cannot cast `x` to number because `T` [1] is incompatible with number [2].


Error ----------------------------------------------- misc-incompatibles.js:8:24

number [1] is not a class.


Error ---------------------------------------------- misc-incompatibles.js:11:11

Cannot extend `A` [1] with `B` because number [1] is not inheritable.


Error ---------------------------------------------- misc-incompatibles.js:11:21

number [1] is not supported by unclassified use GetStaticsT.


Error ----------------------------------------------- misc-incompatibles.js:14:3

Cannot access computed property using boolean [1].


Error ----------------------------------------------- misc-incompatibles.js:15:3

Cannot assign computed property using boolean [1].


Error ----------------------------------------------- misc-incompatibles.js:17:1

Invalid left-hand side in assignment expression.


Error ------------------------------------------------------------- order.js:8:2

Cannot cast object literal to object type because:
 - in property `a`, number [1] is incompatible with boolean [2].
 - in property `c`, boolean [3] is incompatible with number [4].


Error ------------------------------------------------------------ order.js:10:7

Cannot cast `'foo'` to empty because string [1] is incompatible with empty [2].


Error ---------------------------------------------------- prop-variance.js:12:8

Cannot cast `any` to object type because property `p` is read-only in object
type [1] but writable in object type [2].


Error ---------------------------------------------------- prop-variance.js:14:8

Cannot cast `any` to object type because property `p` is read-only in object
type [1] but write-only in object type [2].


Error ---------------------------------------------------- prop-variance.js:15:8

Cannot cast `any` to object type because property `p` is write-only in object
type [1] but readable in object type [2].


Error ---------------------------------------------------- prop-variance.js:16:8

Cannot cast `any` to object type because property `p` is write-only in object
type [1] but read-only in object type [2].


Error ------------------------------------------------ typeof-unexpected.js:6:15

`typeof` can only be used to get the type of variables.



Found 69 errors
