
switch.js:23:19,20: string
This type is incompatible with
switch.js:28:13,15: number

switch_default_fallthrough.js:9:13,13: number
This type is incompatible with
switch_default_fallthrough.js:5:13,14: string

switch_default_fallthrough.js:11:13,13: number
This type is incompatible with
switch_default_fallthrough.js:6:13,14: string

switch_default_fallthrough.js:23:13,13: number
This type is incompatible with
switch_default_fallthrough.js:32:10,15: string

switch_default_fallthrough.js:28:13,13: number
This type is incompatible with
switch_default_fallthrough.js:33:10,15: string

switch_default_fallthrough.js:35:12,14: string
This type is incompatible with
switch_default_fallthrough.js:17:25,30: number

Found 6 errors
