Error ------------------------------------------------------------ This.js:29:15

Cannot get `this.x` because property `x` is missing in global object [1].


Error ------------------------------------------------------------ This.js:29:10

Cannot return `this.x` because string [1] is incompatible with number [2].


Error ------------------------------------------------------------ This.js:33:21

Cannot assign `f1.bind(...)()` to `f1_2` because number [1] is incompatible with
string [2].


Error ------------------------------------------------------------ This.js:41:15

Cannot get `this.x` because property `x` is missing in global object [1].


Error ------------------------------------------------------------ This.js:48:34

Cannot get `this.x` because property `x` is missing in global object [1].


Error ------------------------------------------------------------ This.js:49:12

Cannot return `a2()` because string [1] is incompatible with number [2].


Error ------------------------------------------------------------ This.js:53:21

Cannot assign `f2.bind(...)()` to `f2_2` because number [1] is incompatible with
string [2].


Error ------------------------------------------------------------- This.js:58:2

Cannot cast `this` to undefined because global object [1] is incompatible with
undefined [2].


Error ----------------------------------------------------------- arrows.js:16:2

Cannot cast `j` to `D` because `C` [1] is incompatible with `D` [2].


Error ---------------------------------------------------------- arrows.js:24:17

Cannot call `super.foo` with empty string bound to `x` because string [1] is
incompatible with number [2].



Found 10 errors
