Error ---------------------------------------------------------------------------------------------------- test.js:36:10

Cannot return `s` because `void` [1] is incompatible with `string` [2]. [incompatible-type]

   test.js:36:10
   36|   return s;
                ^

References:
   test.js:1:48
    1| declare function myAssert(condition: boolean): asserts condition;
                                                      ^^^^^^^^^^^^^^^^^ [1]
   test.js:33:59
   33| function reproNeverReturnsInNestedTernary(level: string): string {
                                                                 ^^^^^^ [2]


Error ----------------------------------------------------------------------------------------------------- test.js:55:5

Cannot cast `object.property` to string because `null` [1] is incompatible with `string` [2]. [incompatible-type]

   test.js:55:5
   55|     object.property as string; // error: expression-position calls are ordinary calls
           ^^^^^^^^^^^^^^^

References:
   test.js:51:65
   51| function expressionPositionHavocsRefinements(object: {property: ?string}) {
                                                                       ^^^^^^^ [1]
   test.js:55:24
   55|     object.property as string; // error: expression-position calls are ordinary calls
                              ^^^^^^ [2]


Error ----------------------------------------------------------------------------------------------------- test.js:55:5

Cannot cast `object.property` to string because `void` [1] is incompatible with `string` [2]. [incompatible-type]

   test.js:55:5
   55|     object.property as string; // error: expression-position calls are ordinary calls
           ^^^^^^^^^^^^^^^

References:
   test.js:51:65
   51| function expressionPositionHavocsRefinements(object: {property: ?string}) {
                                                                       ^^^^^^^ [1]
   test.js:55:24
   55|     object.property as string; // error: expression-position calls are ordinary calls
                              ^^^^^^ [2]



Found 3 errors
