Error ----------------------------------------------------- test_absolute.js:5:2

Cannot cast `B1.fun()` to string because number is incompatible with string.


Error ----------------------------------------------------- test_absolute.js:9:2

Cannot cast `B2.fun()` to string because number is incompatible with string.


Error ---------------------------------------------------- test_absolute.js:12:2

Cannot cast `C.fun()` to string because number is incompatible with string.


Error ---------------------------------------------------- test_absolute.js:15:2

Cannot cast `D.fun()` to string because number is incompatible with string.


Error ---------------------------------------------------- test_absolute.js:18:2

Cannot cast `E.fun()` to string because number is incompatible with string.


Error ---------------------------------------------------- test_absolute.js:21:2

Cannot cast `F.fun()` to string because number is incompatible with string.


Error ----------------------------------------------------- test_relative.js:5:2

Cannot cast `A1.fun()` to string because number is incompatible with string.


Error ----------------------------------------------------- test_relative.js:9:2

Cannot cast `A2.fun()` to string because number is incompatible with string.


Error ---------------------------------------------------- test_relative.js:13:2

Cannot cast `CJS` to number because string is incompatible with number.



Found 9 errors
