>>> file.js (#changes: 1)
// @flow

// In case of infered type size violation, this should be annotated as `any`
function foo(x: any) {}

foo({f: 1, g: 2, h: 3});

>>> Launching report...

Stats:
  Files changed:                            1
  Number of annotations added:              1
  Total size of annotations:                1
  Number of LTI errors:                     1

Errors:
  Missing annot./normalizer error:          0
  Validation Error:                         2
  Import Error:
    Loc source none:                        0
    Parsing heaps get ast error:            0
    Indeterminate module type:              0
    No matching export:                     0
  Serializer error:                         0
  Unsupported error kind:                   0

Warnings:
  Skipping arrow function:                  0
  Large type added:                         0
  Location unhandled:                       0
  Empty NoUpper:                            0
  Empty SomeKnownUpper:                     0

