Error ------------------------------------------------------------- main.js:6:10

Cannot create `div` element because in property `id`, number is incompatible
with string.


Error -------------------------------------------------------------- main.js:9:2

Cannot cast `<div />.props.id` to number because string is incompatible with
number.


Error ----------------------------------------------------------- strings.js:9:2

Cannot create `Div` element because property `id` is missing in props but exists
in object type.


Error ---------------------------------------------------------- strings.js:10:2

Cannot create `bad` element because property `bad` is missing in
`$JSXIntrinsics`.


Error ---------------------------------------------------------- strings.js:11:2

An indexer property is missing in `$JSXIntrinsics`.


Error --------------------------------------------------------- strings.js:13:28

Cannot call `React.createElement` because property `id` is missing in props but
exists in object type.


Error --------------------------------------------------------- strings.js:14:21

Cannot create `bad` element because property `bad` is missing in
`$JSXIntrinsics`.


Error --------------------------------------------------------- strings.js:15:21

An indexer property is missing in `$JSXIntrinsics`.


Error --------------------------------------------------------- strings.js:18:10

Cannot create `Div` element because in property `id`, number is incompatible
with string.



Found 9 errors
