
=== Codemod annotate-exports ===

>>> ./a.js
// @flow

module.exports = ({}: {...});

>>> ./b.js
// @flow

module.exports = { f: ({}: {...}) };

>>> ./c.js
// @flow

const obj = { f: ({}: {...}) };

obj.f = { x: 1 };
obj.f = { x: "a" };

module.exports = obj;

>>> ./d.js
// @flow

const obj: {|f: {|x: number|}, g: {|x: string|}|} = { };

obj.f = { x: 1 };
obj["g"] = { x: "a" };

module.exports = obj;

>>> ./e.js
// @flow

const obj: {|a: number|} = {};
declare function foo(x: { a: number }): void;
foo(obj);
module.exports = obj;

>>> ./f.js
// @flow

const obj: {|f: number|} = {};
(obj.f: number);
module.exports = obj;

>>> ./g.js
// @flow

declare function foo<X: { a: 1 }>(x: X): void;

const obj: {|a: 1|} = {};
foo(obj);
module.exports = obj;

>>> Launching report...

Stats:
  Files changed:                            7
  Number of annotations added:              7
  Total size of annotations:               16
  Number of sig. ver. errors:               7
  Number of annotations required:           7
  Number of annotations skipped:            0

Errors:
  Missing annot./normalizer error:          0
  Validation Error:                         0
  Import Error:
    Loc source none:                        0
    Parsing heaps get ast error:            0
    Indeterminate module type:              0
    No matching export:                     0
  Serializer error:                         0
  Unsupported error kind:                   0

Warnings:
  Skipping arrow function:                  0
  Large type added:                         0
  Location unhandled:                       0
  Empty NoUpper:                            0
  Empty SomeKnownUpper:                     2


=== Autofix exports ===

>>> ./a.js
// @flow

module.exports = ({}: {...});

>>> ./b.js
// @flow

module.exports = { f: ({}: {...}) };

>>> ./c.js
// @flow

const obj = { f: ({}: {...}) };

obj.f = { x: 1 };
obj.f = { x: "a" };

module.exports = obj;

>>> ./d.js
// @flow

const obj: {f: {x: number,...}, g: {x: string,...},...} = { };

obj.f = { x: 1 };
obj["g"] = { x: "a" };

module.exports = obj;

>>> ./e.js
// @flow

const obj: {a: number,...} = {};
declare function foo(x: { a: number }): void;
foo(obj);
module.exports = obj;

>>> ./f.js
// @flow

const obj: {f: number,...} = {};
(obj.f: number);
module.exports = obj;

>>> ./g.js
// @flow

declare function foo<X: { a: 1 }>(x: X): void;

const obj: {a: 1,...} = {};
foo(obj);
module.exports = obj;


=== Diff between codemod-ed & autofix-ed ===
>>> ./d.js
3c3
< const obj: {|f: {|x: number|}, g: {|x: string|}|} = { };
---
> const obj: {f: {x: number,...}, g: {x: string,...},...} = { };

>>> ./e.js
3c3
< const obj: {|a: number|} = {};
---
> const obj: {a: number,...} = {};

>>> ./f.js
3c3
< const obj: {|f: number|} = {};
---
> const obj: {f: number,...} = {};

>>> ./g.js
5c5
< const obj: {|a: 1|} = {};
---
> const obj: {a: 1,...} = {};

