
objects.js:4:4,6: property `foo`
Property not found in
objects.js:4:2,2: object type

objects.js:5:4,8: property `foo`
Property not found in
objects.js:5:2,2: object type

objects.js:7:2,6: string
This type is incompatible with
objects.js:7:9,15: boolean

objects.js:8:2,9: string
This type is incompatible with
objects.js:8:13,19: boolean

objects.js:9:12,16: boolean
This type is incompatible with
objects.js:3:17,22: string

objects.js:14:12,14: number
This type is incompatible with
objects.js:13:15,20: string

objects.js:15:3,7: property `bar`
Property not found in
objects.js:15:1,1: object type

objects.js:17:23,28: string
This type is incompatible with
[LIB] core.js:43:5,38: function type

Found 8 errors
