Library type error:
<BUILTINS>/react.js:265
265:     callback?: () => void,
                    ^^^^^^^^^^ function type. Callable signature not found in
 23: ReactDOM.render(<Example/>, document.querySelector('#site'), {});
                                                                  ^^ object literal. See: render_callback.js:23

Error: createElementRequiredProp_string.js:17
 17:     return (<Cmp/>);
                 ^^^^^^ React element `Cmp`
  4: class Bar extends React.Component<{test: number}> {
                                       ^^^^^^^^^^^^^^ property `test`. Property not found in
 17:     return (<Cmp/>);
                 ^^^^^^ props of React element `Cmp`

Error: create_class.js:7
  7:     (this.props.foo: empty); // error: string ~> empty
          ^^^^^^^^^^^^^^ string. This type is incompatible with
  7:     (this.props.foo: empty); // error: string ~> empty
                          ^^^^^ empty

Error: create_class.js:8
  8:     (this.props.bar: empty); // error: number ~> empty
          ^^^^^^^^^^^^^^ number. This type is incompatible with
  8:     (this.props.bar: empty); // error: number ~> empty
                          ^^^^^ empty

Error: create_class.js:15
 15:     this.p = 0; // error: number ~> string
         ^^^^^^ assignment of property `p`
 15:     this.p = 0; // error: number ~> string
                  ^ number. This type is incompatible with
 15:     this.p = 0; // error: number ~> string
         ^^^^^^ string

Error: create_class.js:48
 48:     (this.foo: string); // error: number ~> string
          ^^^^^^^^ number. This type is incompatible with
 48:     (this.foo: string); // error: number ~> string
                    ^^^^^^ string

Error: create_class.js:71
 71:     (this.mixins: mixed); // error: property `mixins` not found
               ^^^^^^ property `mixins`. Property not found in
 71:     (this.mixins: mixed); // error: property `mixins` not found
          ^^^^ React component

Error: create_class.js:72
 72:     (this.autobind: mixed); // error: property `autobind` not found
               ^^^^^^^^ property `autobind`. Property not found in
 72:     (this.autobind: mixed); // error: property `autobind` not found
          ^^^^ React component

Error: create_class.js:73
 73:     (this.statics: mixed); // error: property `statics` not found
               ^^^^^^^ property `statics`. Property not found in
 73:     (this.statics: mixed); // error: property `statics` not found
          ^^^^ React component

Error: create_class.js:80
 80:     (this.q: empty); // error: number ~> empty
          ^^^^^^ number. This type is incompatible with
 80:     (this.q: empty); // error: number ~> empty
                  ^^^^^ empty

Error: create_class.js:104
104:     (this.state.foo: empty); // number ~> empty
          ^^^^^^^^^^^^^^ number. This type is incompatible with
104:     (this.state.foo: empty); // number ~> empty
                          ^^^^^ empty

Error: create_class.js:117
117:     (this.props.foo: empty); // string ~> empty
          ^^^^^^^^^^^^^^ string. This type is incompatible with
117:     (this.props.foo: empty); // string ~> empty
                          ^^^^^ empty

Error: create_class.js:118
118:     (this.state.foo: empty); // string ~> empty
          ^^^^^^^^^^^^^^ string. This type is incompatible with
118:     (this.state.foo: empty); // string ~> empty
                          ^^^^^ empty

Error: create_class.js:133
133:     (this.props.foo: empty); // string ~> empty
          ^^^^^^^^^^^^^^ string. This type is incompatible with
133:     (this.props.foo: empty); // string ~> empty
                          ^^^^^ empty

Error: create_class.js:134
134:     return 0; // number ~> void
                ^ number. This type is incompatible with
 48:   componentWillMount(): void;
                             ^^^^ undefined. See lib: <BUILTINS>/react.js:48

Error: create_class.js:137
137:     (this.props.foo: empty); // string ~> empty
          ^^^^^^^^^^^^^^ string. This type is incompatible with
137:     (this.props.foo: empty); // string ~> empty
                          ^^^^^ empty

Error: create_class.js:138
138:     return 0; // number ~> void
                ^ number. This type is incompatible with
 49:   componentDidMount(): void;
                            ^^^^ undefined. See lib: <BUILTINS>/react.js:49

Error: create_class.js:141
141:     (this.props.foo: empty); // string ~> empty
          ^^^^^^^^^^^^^^ string. This type is incompatible with
141:     (this.props.foo: empty); // string ~> empty
                          ^^^^^ empty

Error: create_class.js:142
142:     (nextProps.foo: empty); // string ~> empty
          ^^^^^^^^^^^^^ string. This type is incompatible with
142:     (nextProps.foo: empty); // string ~> empty
                         ^^^^^ empty

Error: create_class.js:143
143:     return 0; // number ~> void
                ^ number. This type is incompatible with
 53:   ): void;
          ^^^^ undefined. See lib: <BUILTINS>/react.js:53

Error: create_class.js:146
146:     (this.props.foo: empty); // string ~> empty
          ^^^^^^^^^^^^^^ string. This type is incompatible with
146:     (this.props.foo: empty); // string ~> empty
                          ^^^^^ empty

Error: create_class.js:147
147:     (this.state.bar: empty); // number ~> empty
          ^^^^^^^^^^^^^^ number. This type is incompatible with
147:     (this.state.bar: empty); // number ~> empty
                          ^^^^^ empty

Error: create_class.js:148
148:     (nextProps.foo: empty); // string ~> empty
          ^^^^^^^^^^^^^ string. This type is incompatible with
148:     (nextProps.foo: empty); // string ~> empty
                         ^^^^^ empty

Error: create_class.js:149
149:     (nextState.bar: empty); // number ~> empty
          ^^^^^^^^^^^^^ number. This type is incompatible with
149:     (nextState.bar: empty); // number ~> empty
                         ^^^^^ empty

Error: create_class.js:150
150:     return 0; // number ~> bool
                ^ number. This type is incompatible with
 58:   ): boolean;
          ^^^^^^^ boolean. See lib: <BUILTINS>/react.js:58

Error: create_class.js:153
153:     (this.props.foo: empty); // string ~> empty
          ^^^^^^^^^^^^^^ string. This type is incompatible with
153:     (this.props.foo: empty); // string ~> empty
                          ^^^^^ empty

Error: create_class.js:154
154:     (this.state.bar: empty); // number ~> empty
          ^^^^^^^^^^^^^^ number. This type is incompatible with
154:     (this.state.bar: empty); // number ~> empty
                          ^^^^^ empty

Error: create_class.js:155
155:     (nextProps.foo: empty); // string ~> empty
          ^^^^^^^^^^^^^ string. This type is incompatible with
155:     (nextProps.foo: empty); // string ~> empty
                         ^^^^^ empty

Error: create_class.js:156
156:     (nextState.bar: empty); // number ~> empty
          ^^^^^^^^^^^^^ number. This type is incompatible with
156:     (nextState.bar: empty); // number ~> empty
                         ^^^^^ empty

Error: create_class.js:157
157:     return 0; // number ~> void
                ^ number. This type is incompatible with
 63:   ): void;
          ^^^^ undefined. See lib: <BUILTINS>/react.js:63

Error: create_class.js:160
160:     (this.props.foo: empty); // string ~> empty
          ^^^^^^^^^^^^^^ string. This type is incompatible with
160:     (this.props.foo: empty); // string ~> empty
                          ^^^^^ empty

Error: create_class.js:161
161:     (this.state.bar: empty); // number ~> empty
          ^^^^^^^^^^^^^^ number. This type is incompatible with
161:     (this.state.bar: empty); // number ~> empty
                          ^^^^^ empty

Error: create_class.js:162
162:     (nextProps.foo: empty); // string ~> empty
          ^^^^^^^^^^^^^ string. This type is incompatible with
162:     (nextProps.foo: empty); // string ~> empty
                         ^^^^^ empty

Error: create_class.js:163
163:     (nextState.bar: empty); // number ~> empty
          ^^^^^^^^^^^^^ number. This type is incompatible with
163:     (nextState.bar: empty); // number ~> empty
                         ^^^^^ empty

Error: create_class.js:164
164:     return 0; // number ~> void
                ^ number. This type is incompatible with
 68:   ): void;
          ^^^^ undefined. See lib: <BUILTINS>/react.js:68

Error: create_class.js:167
167:     (this.props.foo: empty); // string ~> empty
          ^^^^^^^^^^^^^^ string. This type is incompatible with
167:     (this.props.foo: empty); // string ~> empty
                          ^^^^^ empty

Error: create_class.js:168
168:     (this.state.bar: empty); // number ~> empty
          ^^^^^^^^^^^^^^ number. This type is incompatible with
168:     (this.state.bar: empty); // number ~> empty
                          ^^^^^ empty

Error: create_class.js:169
169:     return 0; // number ~> void
                ^ number. This type is incompatible with
 69:   componentWillUnmount(): void;
                               ^^^^ undefined. See lib: <BUILTINS>/react.js:69

Error: create_class.js:173
173: React.createClass({}); // error: spec must be [x] exact and [ ] sealed
     ^^^^^^^^^^^^^^^^^^^^^ call of method `createClass`. Expected an exact object instead of
173: React.createClass({}); // error: spec must be [x] exact and [ ] sealed
                       ^^ object literal

Error: create_class.js:174
174: React.createClass(({}: {})); // error: spec must be [ ] exact and [x] sealed
     ^^^^^^^^^^^^^^^^^^^^^^^^^^^ call of method `createClass`. Expected an exact object instead of
174: React.createClass(({}: {})); // error: spec must be [ ] exact and [x] sealed
                            ^^ object type

Error: create_class_initial_state_sealed.js:9
  9:     (this.state.q: empty); // number ~> empty
          ^^^^^^^^^^^^ number. This type is incompatible with
  9:     (this.state.q: empty); // number ~> empty
                        ^^^^^ empty

Error: create_class_initial_state_sealed.js:22
 22:     (this.state.q: empty); // number ~> empty
          ^^^^^^^^^^^^ number. This type is incompatible with
 22:     (this.state.q: empty); // number ~> empty
                        ^^^^^ empty

Error: create_class_initial_state_sealed.js:35
 35:     (this.state.q: empty); // number ~> empty
          ^^^^^^^^^^^^ number. This type is incompatible with
 35:     (this.state.q: empty); // number ~> empty
                        ^^^^^ empty

Error: create_class_initial_state_sealed.js:45
 45:     this.setState({ q: 0 }); // property `q` not found
         ^^^^^^^^^^^^^^^^^^^^^^^ call of method `setState`
 45:     this.setState({ q: 0 }); // property `q` not found
                       ^^^^^^^^ object literal. This type is incompatible with
 38:     partialState: $Shape<State> | ((State, Props) => $Shape<State> | void),
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ union: type parameter `State` of call of method `createClass` | function type. See lib: <BUILTINS>/react.js:38
  Member 1:
       v------------------
   40: React.createClass({
   41:   getInitialState(): { p: number } {
   42:     return { p: 0 };
  ...:
   50: });
       -^ type parameter `State` of call of method `createClass`
  Error:
   45:     this.setState({ q: 0 }); // property `q` not found
                         ^^^^^^^^ property `q` of object literal. Property not found in
                        v------------------
   41:   getInitialState(): { p: number } {
   42:     return { p: 0 };
   43:   },
         ^ object type
  Member 2:
   38:     partialState: $Shape<State> | ((State, Props) => $Shape<State> | void),
                                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ function type. See lib: <BUILTINS>/react.js:38
  Error:
   38:     partialState: $Shape<State> | ((State, Props) => $Shape<State> | void),
                                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ function type. Callable signature not found in. See lib: <BUILTINS>/react.js:38
   45:     this.setState({ q: 0 }); // property `q` not found
                         ^^^^^^^^ object literal

Error: create_class_initial_state_sealed.js:48
 48:     (this.state.q: empty); // property `q` not found
                     ^ property `q`. Property not found in
 48:     (this.state.q: empty); // property `q` not found
          ^^^^^^^^^^ object type

Error: create_class_initial_state_sealed.js:66
 66:     (this.state.baz: empty); // number ~> empty
          ^^^^^^^^^^^^^^ number. This type is incompatible with
 66:     (this.state.baz: empty); // number ~> empty
                          ^^^^^ empty

Error: create_class_initial_state_sealed.js:81
 81:     this.setState({ baz: 0 }); // property `baz`  not found
         ^^^^^^^^^^^^^^^^^^^^^^^^^ call of method `setState`
 81:     this.setState({ baz: 0 }); // property `baz`  not found
                       ^^^^^^^^^^ object literal. This type is incompatible with
 38:     partialState: $Shape<State> | ((State, Props) => $Shape<State> | void),
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ union: type parameter `State` of call of method `createClass` | function type. See lib: <BUILTINS>/react.js:38
  Member 1:
       v------------------
   71: React.createClass({
   72:   mixins: [{
   73:     getInitialState(): { foo: number } {
  ...:
   86: });
       -^ type parameter `State` of call of method `createClass`
  Error:
   81:     this.setState({ baz: 0 }); // property `baz`  not found
                         ^^^^^^^^^^ property `baz` of object literal. Property not found in
                          v--------------------
   73:     getInitialState(): { foo: number } {
   74:       return { foo: 0 };
   75:     },
           ^ object type
  Member 2:
   38:     partialState: $Shape<State> | ((State, Props) => $Shape<State> | void),
                                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ function type. See lib: <BUILTINS>/react.js:38
  Error:
   38:     partialState: $Shape<State> | ((State, Props) => $Shape<State> | void),
                                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ function type. Callable signature not found in. See lib: <BUILTINS>/react.js:38
   81:     this.setState({ baz: 0 }); // property `baz`  not found
                         ^^^^^^^^^^ object literal

Error: create_class_initial_state_sealed.js:84
 84:     (this.state.baz: empty); // property `baz` not found
                     ^^^ property `baz`. Property not found in
 84:     (this.state.baz: empty); // property `baz` not found
          ^^^^^^^^^^ object type

Error: create_class_statics_sealed.js:5
  5: (A.bar: empty); // number ~> empty (inflow below)
      ^^^^^ number. This type is incompatible with
  5: (A.bar: empty); // number ~> empty (inflow below)
             ^^^^^ empty

Error: create_class_statics_sealed.js:12
 12: (B.foo: empty); // number ~> empty
      ^^^^^ number. This type is incompatible with
 12: (B.foo: empty); // number ~> empty
             ^^^^^ empty

Error: create_class_statics_sealed.js:13
 13: (B.bar: empty); // number ~> empty (inflow below)
      ^^^^^ number. This type is incompatible with
 13: (B.bar: empty); // number ~> empty (inflow below)
             ^^^^^ empty

Error: create_class_statics_sealed.js:20
 20: (C.foo: empty); // number ~> empty
      ^^^^^ number. This type is incompatible with
 20: (C.foo: empty); // number ~> empty
             ^^^^^ empty

Error: create_class_statics_sealed.js:21
 21: (C.bar: empty); // number ~> empty (inflow below)
      ^^^^^ number. This type is incompatible with
 21: (C.bar: empty); // number ~> empty (inflow below)
             ^^^^^ empty

Error: create_class_statics_sealed.js:28
 28: (D.foo: empty); // number ~> empty
      ^^^^^ number. This type is incompatible with
 28: (D.foo: empty); // number ~> empty
             ^^^^^ empty

Error: create_class_statics_sealed.js:29
 29: (D.bar: empty); // property `bar` not found
        ^^^ property `bar`. Property not found in
 29: (D.bar: empty); // property `bar` not found
      ^ statics of React class

Error: create_class_statics_sealed.js:30
 30: D.bar = 0; // property `bar` not found
       ^^^ property `bar`. Property not found in
 30: D.bar = 0; // property `bar` not found
     ^ statics of React class

Error: create_class_statics_sealed.js:39
 39: (E.foo: empty); // number ~> empty
      ^^^^^ number. This type is incompatible with
 39: (E.foo: empty); // number ~> empty
             ^^^^^ empty

Error: create_class_statics_sealed.js:40
 40: (E.bar: empty); // number ~> empty
      ^^^^^ number. This type is incompatible with
 40: (E.bar: empty); // number ~> empty
             ^^^^^ empty

Error: create_class_statics_sealed.js:41
 41: (E.baz: empty); // number ~> empty (inflow below)
      ^^^^^ number. This type is incompatible with
 41: (E.baz: empty); // number ~> empty (inflow below)
             ^^^^^ empty

Error: create_class_statics_sealed.js:51
 51: (F.foo: empty); // number ~> empty
      ^^^^^ number. This type is incompatible with
 51: (F.foo: empty); // number ~> empty
             ^^^^^ empty

Error: create_class_statics_sealed.js:52
 52: (F.bar: empty); // number ~> empty
      ^^^^^ number. This type is incompatible with
 52: (F.bar: empty); // number ~> empty
             ^^^^^ empty

Error: create_class_statics_sealed.js:53
 53: (F.baz: empty); // number ~> empty (inflow below)
        ^^^ property `baz`. Property not found in
 53: (F.baz: empty); // number ~> empty (inflow below)
      ^ statics of React class

Error: create_class_statics_sealed.js:54
 54: F.baz = 0;
       ^^^ property `baz`. Property not found in
 54: F.baz = 0;
     ^ statics of React class

Error: default_props_undefined.js:10
 10: <Foo bar="42"/>; // Error
     ^^^^^^^^^^^^^^^ props of React element `Foo`. This type is incompatible with
  5: class Foo extends React.Component<{bar: number}, void> {
                                       ^^^^^^^^^^^^^ object type
  Property `bar` is incompatible:
     10: <Foo bar="42"/>; // Error
                  ^^^^ string. This type is incompatible with
      5: class Foo extends React.Component<{bar: number}, void> {
                                                 ^^^^^^ number

Error: element_with_component_type.js:8
  8: (<Foo a={42}/>: React.Element<React.ComponentType<{b: number}>>); // Error
      ^^^^^^^^^^^^^ React element `Foo`
161:   +props: React$ElementProps<ElementType>,
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ property `b`. Property not found in. See lib: <BUILTINS>/react.js:161
  5: class Foo extends React.Component<{a: number}> {}
                                       ^^^^^^^^^^^ object type

Error: element_with_component_type.js:8
  8: (<Foo a={42}/>: React.Element<React.ComponentType<{b: number}>>); // Error
      ^^^^^^^^^^^^^ React element `Foo`
  5: class Foo extends React.Component<{a: number}> {}
           ^^^ class type: Foo. This type is incompatible with
  8: (<Foo a={42}/>: React.Element<React.ComponentType<{b: number}>>); // Error
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ union: type application of polymorphic type: type `React$StatelessFunctionalComponent` | class type: type application of polymorphic type: class type: React$Component
  Member 1:
  140:   | React$StatelessFunctionalComponent<Props>
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ type application of polymorphic type: type `React$StatelessFunctionalComponent`. See lib: <BUILTINS>/react.js:140
  Error:
  140:   | React$StatelessFunctionalComponent<Props>
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ property `$call`. Callable signature not found in. See lib: <BUILTINS>/react.js:140
    5: class Foo extends React.Component<{a: number}> {}
             ^^^ statics of Foo
  Member 2:
  141:   | Class<React$Component<Props, any>>;
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ class type: type application of polymorphic type: class type: React$Component. See lib: <BUILTINS>/react.js:141
  Error:
    8: (<Foo a={42}/>: React.Element<React.ComponentType<{b: number}>>); // Error
                                                         ^^^^^^^^^^^ property `b`. Property not found in
    5: class Foo extends React.Component<{a: number}> {}
                                         ^^^^^^^^^^^ object type

Error: hoc.js:11
 11:       <Component />; // Error: `foo` is required.
           ^^^^^^^^^^^^^ React element `Component`
  6:   Component: React$ComponentType<{foo: number, bar: number}>,
                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^ property `bar`. Property not found in
 11:       <Component />; // Error: `foo` is required.
           ^^^^^^^^^^^^^ props of React element `Component`

Error: hoc.js:11
 11:       <Component />; // Error: `foo` is required.
           ^^^^^^^^^^^^^ React element `Component`
  6:   Component: React$ComponentType<{foo: number, bar: number}>,
                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^ property `foo`. Property not found in
 11:       <Component />; // Error: `foo` is required.
           ^^^^^^^^^^^^^ props of React element `Component`

Error: hoc.js:12
 12:       <Component foo={42} />; // Error: `bar` is required.
           ^^^^^^^^^^^^^^^^^^^^^^ React element `Component`
  6:   Component: React$ComponentType<{foo: number, bar: number}>,
                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^ property `bar`. Property not found in
 12:       <Component foo={42} />; // Error: `bar` is required.
           ^^^^^^^^^^^^^^^^^^^^^^ props of React element `Component`

Error: hoc.js:35
 35: myHOC(class Empty extends React.Component<{foo: string}, void> {}); // Error
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ class type: class expr `Empty`. This type is incompatible with
  6:   Component: React$ComponentType<{foo: number, bar: number}>,
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ union: type application of polymorphic type: type `React$StatelessFunctionalComponent` | class type: type application of polymorphic type: class type: React$Component
  Member 1:
  140:   | React$StatelessFunctionalComponent<Props>
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ type application of polymorphic type: type `React$StatelessFunctionalComponent`. See lib: <BUILTINS>/react.js:140
  Error:
  140:   | React$StatelessFunctionalComponent<Props>
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ property `$call`. Callable signature not found in. See lib: <BUILTINS>/react.js:140
   35: myHOC(class Empty extends React.Component<{foo: string}, void> {}); // Error
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ statics of class expr `Empty`
  Member 2:
  141:   | Class<React$Component<Props, any>>;
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ class type: type application of polymorphic type: class type: React$Component. See lib: <BUILTINS>/react.js:141
  Error:
   35: myHOC(class Empty extends React.Component<{foo: string}, void> {}); // Error
                                                 ^^^^^^^^^^^^^ object type. This type is incompatible with
    6:   Component: React$ComponentType<{foo: number, bar: number}>,
                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^ object type
    Property `foo` is incompatible:
       35: myHOC(class Empty extends React.Component<{foo: string}, void> {}); // Error
                                                           ^^^^^^ string. This type is incompatible with
        6:   Component: React$ComponentType<{foo: number, bar: number}>,
                                                  ^^^^^^ number

Error: hoc.js:36
 36: myHOC(function Empty(props: {foo: string}) {}); // Error
     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ function call
 36: myHOC(function Empty(props: {foo: string}) {}); // Error
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ function. This type is incompatible with
  6:   Component: React$ComponentType<{foo: number, bar: number}>,
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ union: type application of polymorphic type: type `React$StatelessFunctionalComponent` | class type: type application of polymorphic type: class type: React$Component
  Member 1:
  140:   | React$StatelessFunctionalComponent<Props>
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ type application of polymorphic type: type `React$StatelessFunctionalComponent`. See lib: <BUILTINS>/react.js:140
  Error:
    6:   Component: React$ComponentType<{foo: number, bar: number}>,
                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^ object type. This type is incompatible with the expected param type of
   36: myHOC(function Empty(props: {foo: string}) {}); // Error
                                   ^^^^^^^^^^^^^ object type
    Property `foo` is incompatible:
        6:   Component: React$ComponentType<{foo: number, bar: number}>,
                                                  ^^^^^^ number. This type is incompatible with
       36: myHOC(function Empty(props: {foo: string}) {}); // Error
                                             ^^^^^^ string
  Member 2:
  141:   | Class<React$Component<Props, any>>;
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ class type: type application of polymorphic type: class type: React$Component. See lib: <BUILTINS>/react.js:141
  Error:
   36: myHOC(function Empty(props: {foo: string}) {}); // Error
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ property `$call`. Callable signature not found in
  141:   | Class<React$Component<Props, any>>;
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^ statics of React$Component. See lib: <BUILTINS>/react.js:141

Error: hoc.js:41
 41: <Wrapped />; // Error: `foo` is required.
     ^^^^^^^^^^^ React element `Wrapped`
  7: ): React$ComponentType<{foo: number}> {
                            ^^^^^^^^^^^^^ property `foo`. Property not found in
 41: <Wrapped />; // Error: `foo` is required.
     ^^^^^^^^^^^ props of React element `Wrapped`

Error: hoc.js:43
 43: <WrappedFun />; // Error: `foo` is required.
     ^^^^^^^^^^^^^^ React element `WrappedFun`
  7: ): React$ComponentType<{foo: number}> {
                            ^^^^^^^^^^^^^ property `foo`. Property not found in
 43: <WrappedFun />; // Error: `foo` is required.
     ^^^^^^^^^^^^^^ props of React element `WrappedFun`

Error: hoc2.js:6
  6:   Component: React.ComponentType<{|...TProps, prop: number|}>,
                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^ object type. This type is incompatible with
                                               v-
 11: class MyComponent extends React.Component<{|
 12:   a: number,
 13:   b: number,
 14:   prop: number,
 15: |}> {}
     -^ object type
  Property `a` is incompatible:
     12:   a: number,
              ^^^^^^ number. This type is incompatible with
     28: <MyEnhancedComponent a="foo" b={2} />; // Error: string ~> number
                                ^^^^^ string

Error: hoc2.js:6
  6:   Component: React.ComponentType<{|...TProps, prop: number|}>,
                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^ object type. This type is incompatible with
                                               v-
 11: class MyComponent extends React.Component<{|
 12:   a: number,
 13:   b: number,
 14:   prop: number,
 15: |}> {}
     -^ object type
  Property `a` is incompatible:
     28: <MyEnhancedComponent a="foo" b={2} />; // Error: string ~> number
                                ^^^^^ string. This type is incompatible with
     12:   a: number,
              ^^^^^^ number

Error: hoc2.js:6
  6:   Component: React.ComponentType<{|...TProps, prop: number|}>,
                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^ object type. This type is incompatible with
                                         v-
 17: function MyFunctionComponent(props: {|
 18:   a: number,
 19:   b: number,
 20:   prop: number,
 21: |}) {}
     -^ object type
  Property `a` is incompatible:
     18:   a: number,
              ^^^^^^ number. This type is incompatible with
     32: <MyEnhancedFunctionComponent a="foo" b={2} />; // Error: string ~> number
                                        ^^^^^ string

Error: hoc2.js:6
  6:   Component: React.ComponentType<{|...TProps, prop: number|}>,
                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^ object type. This type is incompatible with
                                         v-
 17: function MyFunctionComponent(props: {|
 18:   a: number,
 19:   b: number,
 20:   prop: number,
 21: |}) {}
     -^ object type
  Property `a` is incompatible:
     32: <MyEnhancedFunctionComponent a="foo" b={2} />; // Error: string ~> number
                                        ^^^^^ string. This type is incompatible with
     18:   a: number,
              ^^^^^^ number

Error: hoc2.js:11
                                               v-
 11: class MyComponent extends React.Component<{|
 12:   a: number,
 13:   b: number,
 14:   prop: number,
 15: |}> {}
     -^ object type. This type is incompatible with
  6:   Component: React.ComponentType<{|...TProps, prop: number|}>,
                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^ object type
  Property `a` is incompatible:
     12:   a: number,
              ^^^^^^ number. This type is incompatible with
     28: <MyEnhancedComponent a="foo" b={2} />; // Error: string ~> number
                                ^^^^^ string

Error: hoc2.js:11
                                               v-
 11: class MyComponent extends React.Component<{|
 12:   a: number,
 13:   b: number,
 14:   prop: number,
 15: |}> {}
     -^ object type. This type is incompatible with
  6:   Component: React.ComponentType<{|...TProps, prop: number|}>,
                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^ object type
  Property `a` is incompatible:
     28: <MyEnhancedComponent a="foo" b={2} />; // Error: string ~> number
                                ^^^^^ string. This type is incompatible with
     12:   a: number,
              ^^^^^^ number

Error: hoc2.js:26
 26: <MyEnhancedComponent />; // Error: Needs `a` and `b`.
     ^^^^^^^^^^^^^^^^^^^^^^^ React element `MyEnhancedComponent`
                                               v-
 11: class MyComponent extends React.Component<{|
 12:   a: number,
 13:   b: number,
 14:   prop: number,
 15: |}> {}
     -^ property `a`. Property not found in
  6:   Component: React.ComponentType<{|...TProps, prop: number|}>,
                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^ object type

Error: hoc2.js:26
 26: <MyEnhancedComponent />; // Error: Needs `a` and `b`.
     ^^^^^^^^^^^^^^^^^^^^^^^ React element `MyEnhancedComponent`
                                               v-
 11: class MyComponent extends React.Component<{|
 12:   a: number,
 13:   b: number,
 14:   prop: number,
 15: |}> {}
     -^ property `b`. Property not found in
  6:   Component: React.ComponentType<{|...TProps, prop: number|}>,
                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^ object type

Error: hoc2.js:30
 30: <MyEnhancedFunctionComponent/>; // Error: Needs `a` and `b`.
     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ React element `MyEnhancedFunctionComponent`
                                         v-
 17: function MyFunctionComponent(props: {|
 18:   a: number,
 19:   b: number,
 20:   prop: number,
 21: |}) {}
     -^ property `a`. Property not found in
  6:   Component: React.ComponentType<{|...TProps, prop: number|}>,
                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^ object type

Error: hoc2.js:30
 30: <MyEnhancedFunctionComponent/>; // Error: Needs `a` and `b`.
     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ React element `MyEnhancedFunctionComponent`
                                         v-
 17: function MyFunctionComponent(props: {|
 18:   a: number,
 19:   b: number,
 20:   prop: number,
 21: |}) {}
     -^ property `b`. Property not found in
  6:   Component: React.ComponentType<{|...TProps, prop: number|}>,
                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^ object type

Error: hoc3.js:26
 26: <MyEnhancedComponent />; // Error: Needs `a` and `b`.
     ^^^^^^^^^^^^^^^^^^^^^^^ React element `MyEnhancedComponent`
                                               v
 11: class MyComponent extends React.Component<{
 12:   a: number,
 13:   b: number,
 14:   prop: number,
 15: }> {}
     ^ property `a`. Property not found in
 26: <MyEnhancedComponent />; // Error: Needs `a` and `b`.
     ^^^^^^^^^^^^^^^^^^^^^^^ props of React element `MyEnhancedComponent`

Error: hoc3.js:26
 26: <MyEnhancedComponent />; // Error: Needs `a` and `b`.
     ^^^^^^^^^^^^^^^^^^^^^^^ React element `MyEnhancedComponent`
                                               v
 11: class MyComponent extends React.Component<{
 12:   a: number,
 13:   b: number,
 14:   prop: number,
 15: }> {}
     ^ property `b`. Property not found in
 26: <MyEnhancedComponent />; // Error: Needs `a` and `b`.
     ^^^^^^^^^^^^^^^^^^^^^^^ props of React element `MyEnhancedComponent`

Error: hoc3.js:28
 28: <MyEnhancedComponent a="foo" b={2} />; // Error: string ~> number
     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ props of React element `MyEnhancedComponent`. This type is incompatible with
                                               v
 11: class MyComponent extends React.Component<{
 12:   a: number,
 13:   b: number,
 14:   prop: number,
 15: }> {}
     ^ object type
  Property `a` is incompatible:
     28: <MyEnhancedComponent a="foo" b={2} />; // Error: string ~> number
                                ^^^^^ string. This type is incompatible with
     12:   a: number,
              ^^^^^^ number

Error: hoc3.js:30
 30: <MyEnhancedFunctionComponent/>; // Error: Needs `a` and `b`.
     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ React element `MyEnhancedFunctionComponent`
                                         v
 17: function MyFunctionComponent(props: {
 18:   a: number,
 19:   b: number,
 20:   prop: number,
 21: }) {}
     ^ property `a`. Property not found in
 30: <MyEnhancedFunctionComponent/>; // Error: Needs `a` and `b`.
     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ props of React element `MyEnhancedFunctionComponent`

Error: hoc3.js:30
 30: <MyEnhancedFunctionComponent/>; // Error: Needs `a` and `b`.
     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ React element `MyEnhancedFunctionComponent`
                                         v
 17: function MyFunctionComponent(props: {
 18:   a: number,
 19:   b: number,
 20:   prop: number,
 21: }) {}
     ^ property `b`. Property not found in
 30: <MyEnhancedFunctionComponent/>; // Error: Needs `a` and `b`.
     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ props of React element `MyEnhancedFunctionComponent`

Error: hoc3.js:32
 32: <MyEnhancedFunctionComponent a="foo" b={2} />; // Error: string ~> number
     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ props of React element `MyEnhancedFunctionComponent`. This type is incompatible with the expected param type of
                                         v
 17: function MyFunctionComponent(props: {
 18:   a: number,
 19:   b: number,
 20:   prop: number,
 21: }) {}
     ^ object type
  Property `a` is incompatible:
     32: <MyEnhancedFunctionComponent a="foo" b={2} />; // Error: string ~> number
                                        ^^^^^ string. This type is incompatible with
     18:   a: number,
              ^^^^^^ number

Error: hoc4.js:26
 26: <MyEnhancedComponent />; // Error: Needs `a` and `b`.
     ^^^^^^^^^^^^^^^^^^^^^^^ React element `MyEnhancedComponent`
                                               v
 11: class MyComponent extends React.Component<{
 12:   a: number,
 13:   b: number,
 14:   prop: number,
 15: }> {}
     ^ property `a`. Property not found in
 26: <MyEnhancedComponent />; // Error: Needs `a` and `b`.
     ^^^^^^^^^^^^^^^^^^^^^^^ props of React element `MyEnhancedComponent`

Error: hoc4.js:26
 26: <MyEnhancedComponent />; // Error: Needs `a` and `b`.
     ^^^^^^^^^^^^^^^^^^^^^^^ React element `MyEnhancedComponent`
                                               v
 11: class MyComponent extends React.Component<{
 12:   a: number,
 13:   b: number,
 14:   prop: number,
 15: }> {}
     ^ property `b`. Property not found in
 26: <MyEnhancedComponent />; // Error: Needs `a` and `b`.
     ^^^^^^^^^^^^^^^^^^^^^^^ props of React element `MyEnhancedComponent`

Error: hoc4.js:28
 28: <MyEnhancedComponent a="foo" b={2} />; // Error: string ~> number
     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ props of React element `MyEnhancedComponent`. This type is incompatible with
                                               v
 11: class MyComponent extends React.Component<{
 12:   a: number,
 13:   b: number,
 14:   prop: number,
 15: }> {}
     ^ object type
  Property `a` is incompatible:
     28: <MyEnhancedComponent a="foo" b={2} />; // Error: string ~> number
                                ^^^^^ string. This type is incompatible with
     12:   a: number,
              ^^^^^^ number

Error: hoc4.js:30
 30: <MyEnhancedFunctionComponent/>; // Error: Needs `a` and `b`.
     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ React element `MyEnhancedFunctionComponent`
                                         v
 17: function MyFunctionComponent(props: {
 18:   a: number,
 19:   b: number,
 20:   prop: number,
 21: }) {}
     ^ property `a`. Property not found in
 30: <MyEnhancedFunctionComponent/>; // Error: Needs `a` and `b`.
     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ props of React element `MyEnhancedFunctionComponent`

Error: hoc4.js:30
 30: <MyEnhancedFunctionComponent/>; // Error: Needs `a` and `b`.
     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ React element `MyEnhancedFunctionComponent`
                                         v
 17: function MyFunctionComponent(props: {
 18:   a: number,
 19:   b: number,
 20:   prop: number,
 21: }) {}
     ^ property `b`. Property not found in
 30: <MyEnhancedFunctionComponent/>; // Error: Needs `a` and `b`.
     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ props of React element `MyEnhancedFunctionComponent`

Error: hoc4.js:32
 32: <MyEnhancedFunctionComponent a="foo" b={2} />; // Error: string ~> number
     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ props of React element `MyEnhancedFunctionComponent`. This type is incompatible with the expected param type of
                                         v
 17: function MyFunctionComponent(props: {
 18:   a: number,
 19:   b: number,
 20:   prop: number,
 21: }) {}
     ^ object type
  Property `a` is incompatible:
     32: <MyEnhancedFunctionComponent a="foo" b={2} />; // Error: string ~> number
                                        ^^^^^ string. This type is incompatible with
     18:   a: number,
              ^^^^^^ number

Error: import_react.js:7
  7: var b: number = new react.Component(); // Error: ReactComponent ~> number
                     ^^^^^^^^^^^^^^^^^^^^^ constructor call
  7: var b: number = new react.Component(); // Error: ReactComponent ~> number
                     ^^^^^^^^^^^^^^^^^^^^^ React$Component. This type is incompatible with
  7: var b: number = new react.Component(); // Error: ReactComponent ~> number
            ^^^^^^ number

Error: jsx_spread.js:11
 11: var blah = <Foo {...props} />; // error bar, number given string expected
                ^^^^^^^^^^^^^^^^^^ props of React element `Foo`. This type is incompatible with
                  v
  5:   propTypes: {
  6:     bar: React.PropTypes.string.isRequired,
  7:   },
       ^ propTypes of React component
  Property `bar` is incompatible:
     10: var props = {bar: 42};
                           ^^ number. This type is incompatible with
      6:     bar: React.PropTypes.string.isRequired,
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ string

Error: key.js:12
 12: <Foo key={true} />; // Error
               ^^^^ boolean. This type is incompatible with
 12: <Foo key={true} />; // Error
     ^^^^^^^^^^^^^^^^^^ union: string | number
  Member 1:
  170: declare type React$Key = string | number;
                                ^^^^^^ string. See lib: <BUILTINS>/react.js:170
  Error:
   12: <Foo key={true} />; // Error
                 ^^^^ boolean. This type is incompatible with
  170: declare type React$Key = string | number;
                                ^^^^^^ string. See lib: <BUILTINS>/react.js:170
  Member 2:
  170: declare type React$Key = string | number;
                                         ^^^^^^ number. See lib: <BUILTINS>/react.js:170
  Error:
   12: <Foo key={true} />; // Error
                 ^^^^ boolean. This type is incompatible with
  170: declare type React$Key = string | number;
                                         ^^^^^^ number. See lib: <BUILTINS>/react.js:170

Error: key.js:21
 21: <FooExact key={true} />; // Error
                    ^^^^ boolean. This type is incompatible with
 21: <FooExact key={true} />; // Error
     ^^^^^^^^^^^^^^^^^^^^^^^ union: string | number
  Member 1:
  170: declare type React$Key = string | number;
                                ^^^^^^ string. See lib: <BUILTINS>/react.js:170
  Error:
   21: <FooExact key={true} />; // Error
                      ^^^^ boolean. This type is incompatible with
  170: declare type React$Key = string | number;
                                ^^^^^^ string. See lib: <BUILTINS>/react.js:170
  Member 2:
  170: declare type React$Key = string | number;
                                         ^^^^^^ number. See lib: <BUILTINS>/react.js:170
  Error:
   21: <FooExact key={true} />; // Error
                      ^^^^ boolean. This type is incompatible with
  170: declare type React$Key = string | number;
                                         ^^^^^^ number. See lib: <BUILTINS>/react.js:170

Error: proptype_arrayOf.js:13
 13: var fail_missing = <Example />
                        ^^^^^^^^^^^ React element `Example`
                  v
  5:   propTypes: {
  6:     arr: React.PropTypes.arrayOf(React.PropTypes.number).isRequired,
  7:   },
       ^ property `arr`. Property not found in
 13: var fail_missing = <Example />
                        ^^^^^^^^^^^ props of React element `Example`

Error: proptype_arrayOf.js:14
 14: var fail_not_array = <Example arr={2} />
                          ^^^^^^^^^^^^^^^^^^^ props of React element `Example`. This type is incompatible with
                  v
  5:   propTypes: {
  6:     arr: React.PropTypes.arrayOf(React.PropTypes.number).isRequired,
  7:   },
       ^ propTypes of React component
  Property `arr` is incompatible:
     14: var fail_not_array = <Example arr={2} />
                                            ^ number. This type is incompatible with
      6:     arr: React.PropTypes.arrayOf(React.PropTypes.number).isRequired,
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ array type

Error: proptype_arrayOf.js:15
 15: var fail_mistyped_elems = <Example arr={[1, "foo"]} />
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^ props of React element `Example`. This type is incompatible with
                  v
  5:   propTypes: {
  6:     arr: React.PropTypes.arrayOf(React.PropTypes.number).isRequired,
  7:   },
       ^ propTypes of React component
  Property `arr` is incompatible:
     15: var fail_mistyped_elems = <Example arr={[1, "foo"]} />
                                                 ^^^^^^^^^^ array literal. Has some incompatible type argument with
      6:     arr: React.PropTypes.arrayOf(React.PropTypes.number).isRequired,
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ array type
      Type argument `T` is incompatible:
         15: var fail_mistyped_elems = <Example arr={[1, "foo"]} />
                                                         ^^^^^ string. This type is incompatible with
          6:     arr: React.PropTypes.arrayOf(React.PropTypes.number).isRequired,
                                              ^^^^^^^^^^^^^^^^^^^^^^ number

Error: proptype_arrayOf.js:20
 20: var todo_required = <Example arr={[null]} />
                         ^^^^^^^^^^^^^^^^^^^^^^^^ props of React element `Example`. This type is incompatible with
                  v
  5:   propTypes: {
  6:     arr: React.PropTypes.arrayOf(React.PropTypes.number).isRequired,
  7:   },
       ^ propTypes of React component
  Property `arr` is incompatible:
     20: var todo_required = <Example arr={[null]} />
                                           ^^^^^^ array literal. Has some incompatible type argument with
      6:     arr: React.PropTypes.arrayOf(React.PropTypes.number).isRequired,
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ array type
      Type argument `T` is incompatible:
         20: var todo_required = <Example arr={[null]} />
                                                ^^^^ null. This type is incompatible with
          6:     arr: React.PropTypes.arrayOf(React.PropTypes.number).isRequired,
                                              ^^^^^^^^^^^^^^^^^^^^^^ number

Error: proptype_arrayOf.js:30
 30: (<OptionalExample arr={[""]} />); // error: string ~> number
      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ props of React element `OptionalExample`. This type is incompatible with
                  v
 23:   propTypes: {
 24:     arr: React.PropTypes.arrayOf(React.PropTypes.number),
 25:   }
       ^ propTypes of React component
  Property `arr` is incompatible:
     30: (<OptionalExample arr={[""]} />); // error: string ~> number
                                ^^^^ array literal. Has some incompatible type argument with
     24:     arr: React.PropTypes.arrayOf(React.PropTypes.number),
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ array type
      Type argument `T` is incompatible:
         30: (<OptionalExample arr={[""]} />); // error: string ~> number
                                     ^^ string. This type is incompatible with
         24:     arr: React.PropTypes.arrayOf(React.PropTypes.number),
                                              ^^^^^^^^^^^^^^^^^^^^^^ number

Error: proptype_arrayOf.js:38
 38: (<AnyExample arr={0} />); // error: still needs to be an array
      ^^^^^^^^^^^^^^^^^^^^^^ props of React element `AnyExample`. This type is incompatible with
                  v
 33:   propTypes: {
 34:     arr: React.PropTypes.arrayOf((0:any)), // OK
 35:   },
       ^ propTypes of React component
  Property `arr` is incompatible:
     38: (<AnyExample arr={0} />); // error: still needs to be an array
                           ^ number. This type is incompatible with
     34:     arr: React.PropTypes.arrayOf((0:any)), // OK
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ array type

Error: proptype_arrayOf.js:43
 43:     arr: React.PropTypes.arrayOf(0), // error: number not a prop type
              ^^^^^^^^^^^^^^^^^^^^^^^^^^ call of method `arrayOf`. Expected a React PropType instead of
 43:     arr: React.PropTypes.arrayOf(0), // error: number not a prop type
                                      ^ number

Error: proptype_custom_validator.js:8
  8:       (propName: empty); // error: propName is a string
            ^^^^^^^^ string. This type is incompatible with
  8:       (propName: empty); // error: propName is a string
                      ^^^^^ empty

Error: proptype_custom_validator.js:9
  9:       (componentName: empty); // error: componentName is a string
            ^^^^^^^^^^^^^ string. This type is incompatible with
  9:       (componentName: empty); // error: componentName is a string
                           ^^^^^ empty

Error: proptype_custom_validator.js:10
 10:       (href: empty); // error: href is an optional string
            ^^^^ string. This type is incompatible with
 10:       (href: empty); // error: href is an optional string
                  ^^^^^ empty

Error: proptype_custom_validator.js:10
 10:       (href: empty); // error: href is an optional string
            ^^^^ undefined. This type is incompatible with
 10:       (href: empty); // error: href is an optional string
                  ^^^^^ empty

Error: proptype_custom_validator.js:11
 11:       return (0: mixed); // error: should return ?Error
                      ^^^^^ mixed. This type is incompatible with
298:   href?: string) => ?Error;
                          ^^^^^ Error. See lib: <BUILTINS>/react.js:298

Error: proptype_func.js:14
 14: var fail_mistyped = <Example func={2} />
                         ^^^^^^^^^^^^^^^^^^^^ props of React element `Example`. This type is incompatible with
                  v
  5:   propTypes: {
  6:     func: React.PropTypes.func.isRequired
  7:   },
       ^ propTypes of React component
  Property `func` is incompatible:
     14: var fail_mistyped = <Example func={2} />
                                            ^ number. This type is incompatible with
      6:     func: React.PropTypes.func.isRequired
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ function type

Error: proptype_incompatible.js:3
                   v------------------
  3: var Example = React.createClass({
  4:   propTypes: {
  5:     foo: 0, // error: `0` is not a prop type
  6:   },
  7: });
     -^ call of method `createClass`. Expected a React PropType instead of
  5:     foo: 0, // error: `0` is not a prop type
              ^ number

Error: proptype_instanceOf.js:14
 14: (<Example x={new A} />); // error: A ~> B
      ^^^^^^^^^^^^^^^^^^^^^ props of React element `Example`. This type is incompatible with
                  v
  9:   propTypes: {
 10:     x: React.PropTypes.instanceOf(B),
 11:   }
       ^ propTypes of React component
  Property `x` is incompatible:
     14: (<Example x={new A} />); // error: A ~> B
                      ^^^^^ A. This type is incompatible with
     10:     x: React.PropTypes.instanceOf(B),
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ B

Error: proptype_instanceOf.js:17
 17: (<Example x="wrong" />); // error: string ~> B
      ^^^^^^^^^^^^^^^^^^^^^ props of React element `Example`. This type is incompatible with
                  v
  9:   propTypes: {
 10:     x: React.PropTypes.instanceOf(B),
 11:   }
       ^ propTypes of React component
  Property `x` is incompatible:
     17: (<Example x="wrong" />); // error: string ~> B
                     ^^^^^^^ string. This type is incompatible with
     10:     x: React.PropTypes.instanceOf(B),
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ B

Error: proptype_object.js:13
 13: var fail_mistyped = <Example object={2} />
                         ^^^^^^^^^^^^^^^^^^^^^^ props of React element `Example`. This type is incompatible with
                  v
  5:   propTypes: {
  6:     object: React.PropTypes.object.isRequired
  7:   },
       ^ propTypes of React component
  Property `object` is incompatible:
     13: var fail_mistyped = <Example object={2} />
                                              ^ number. This type is incompatible with
      6:     object: React.PropTypes.object.isRequired
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ object type

Error: proptype_objectOf.js:13
 13: var fail_missing = <Example />
                        ^^^^^^^^^^^ React element `Example`
                  v
  5:   propTypes: {
  6:     obj: React.PropTypes.objectOf(React.PropTypes.number).isRequired
  7:   },
       ^ property `obj`. Property not found in
 13: var fail_missing = <Example />
                        ^^^^^^^^^^^ props of React element `Example`

Error: proptype_objectOf.js:14
 14: var fail_not_object = <Example obj={2} />
                           ^^^^^^^^^^^^^^^^^^^ props of React element `Example`. This type is incompatible with
                  v
  5:   propTypes: {
  6:     obj: React.PropTypes.objectOf(React.PropTypes.number).isRequired
  7:   },
       ^ propTypes of React component
  Property `obj` is incompatible:
     14: var fail_not_object = <Example obj={2} />
                                             ^ number. This type is incompatible with
      6:     obj: React.PropTypes.objectOf(React.PropTypes.number).isRequired
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ object type

Error: proptype_objectOf.js:15
 15: var fail_mistyped_props = <Example obj={{foo: "foo"}} />
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ props of React element `Example`. This type is incompatible with
                  v
  5:   propTypes: {
  6:     obj: React.PropTypes.objectOf(React.PropTypes.number).isRequired
  7:   },
       ^ propTypes of React component
  Property `obj` is incompatible:
     15: var fail_mistyped_props = <Example obj={{foo: "foo"}} />
                                                       ^^^^^ string. This type is incompatible with
      6:     obj: React.PropTypes.objectOf(React.PropTypes.number).isRequired
                                           ^^^^^^^^^^^^^^^^^^^^^^ number

Error: proptype_objectOf.js:20
 20: var todo_required = <Example obj={{p:null}} />
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^ props of React element `Example`. This type is incompatible with
                  v
  5:   propTypes: {
  6:     obj: React.PropTypes.objectOf(React.PropTypes.number).isRequired
  7:   },
       ^ propTypes of React component
  Property `obj` is incompatible:
     20: var todo_required = <Example obj={{p:null}} />
                                              ^^^^ null. This type is incompatible with
      6:     obj: React.PropTypes.objectOf(React.PropTypes.number).isRequired
                                           ^^^^^^^^^^^^^^^^^^^^^^ number

Error: proptype_objectOf.js:30
 30: (<OptionalExample obj={{p:""}} />); // error: string ~> number
      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ props of React element `OptionalExample`. This type is incompatible with
                  v
 23:   propTypes: {
 24:     obj: React.PropTypes.objectOf(React.PropTypes.number),
 25:   }
       ^ propTypes of React component
  Property `obj` is incompatible:
     30: (<OptionalExample obj={{p:""}} />); // error: string ~> number
                                   ^^ string. This type is incompatible with
     24:     obj: React.PropTypes.objectOf(React.PropTypes.number),
                                           ^^^^^^^^^^^^^^^^^^^^^^ number

Error: proptype_objectOf.js:38
 38: (<AnyExample obj={0} />); // error: still needs to be an object
      ^^^^^^^^^^^^^^^^^^^^^^ props of React element `AnyExample`. This type is incompatible with
                  v
 33:   propTypes: {
 34:     obj: React.PropTypes.objectOf((0:any)), // OK
 35:   },
       ^ propTypes of React component
  Property `obj` is incompatible:
     38: (<AnyExample obj={0} />); // error: still needs to be an object
                           ^ number. This type is incompatible with
     34:     obj: React.PropTypes.objectOf((0:any)), // OK
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ object type

Error: proptype_objectOf.js:43
 43:     obj: React.PropTypes.objectOf(0), // error: number not a prop type
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^ call of method `objectOf`. Expected a React PropType instead of
 43:     obj: React.PropTypes.objectOf(0), // error: number not a prop type
                                       ^ number

Error: proptype_oneOf.js:14
 14: (<Example str="baz" />); // error: 'baz' not in enum
      ^^^^^^^^^^^^^^^^^^^^^ props of React element `Example`. This type is incompatible with
                  v
  5:   propTypes: {
  6:     str: React.PropTypes.oneOf(["foo", "bar"]),
  7:     num: React.PropTypes.oneOf([0, 1, 2]),
...:
 10:   },
       ^ propTypes of React component
  Property `str` is incompatible:
     14: (<Example str="baz" />); // error: 'baz' not in enum
                       ^^^^^ string. This type is incompatible with
      6:     str: React.PropTypes.oneOf(["foo", "bar"]),
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ string enum

Error: proptype_oneOf.js:17
 17: (<Example num={3} />); // error: 3 not in enum
      ^^^^^^^^^^^^^^^^^^^ props of React element `Example`. This type is incompatible with
                  v
  5:   propTypes: {
  6:     str: React.PropTypes.oneOf(["foo", "bar"]),
  7:     num: React.PropTypes.oneOf([0, 1, 2]),
...:
 10:   },
       ^ propTypes of React component
  Property `num` is incompatible:
     17: (<Example num={3} />); // error: 3 not in enum
                        ^ number. This type is incompatible with
      7:     num: React.PropTypes.oneOf([0, 1, 2]),
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ number enum

Error: proptype_oneOf.js:20
 20: (<Example bool={false} />); // error: false ~> true
      ^^^^^^^^^^^^^^^^^^^^^^^^ React element `Example`
 20: (<Example bool={false} />); // error: false ~> true
                     ^^^^^ boolean. Expected boolean literal `true`, got `false` instead
  8:     bool: React.PropTypes.oneOf([true]),
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ boolean literal `true`

Error: proptype_oneOf.js:24
 24: (<Example mixed={"baz"} />); // error: 'baz' not in enum
      ^^^^^^^^^^^^^^^^^^^^^^^^^ React element `Example`
 24: (<Example mixed={"baz"} />); // error: 'baz' not in enum
                      ^^^^^ string. This type is incompatible with
  9:     mixed: React.PropTypes.oneOf(["foo", 0, true]),
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ union: string literal `foo` | number literal `0` | boolean literal `true`
  Member 1:
    9:     mixed: React.PropTypes.oneOf(["foo", 0, true]),
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ string literal `foo`
  Error:
   24: (<Example mixed={"baz"} />); // error: 'baz' not in enum
                        ^^^^^ string. Expected string literal `foo`, got `baz` instead
    9:     mixed: React.PropTypes.oneOf(["foo", 0, true]),
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ string literal `foo`
  Member 2:
    9:     mixed: React.PropTypes.oneOf(["foo", 0, true]),
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ number literal `0`
  Error:
   24: (<Example mixed={"baz"} />); // error: 'baz' not in enum
                        ^^^^^ string. This type is incompatible with
    9:     mixed: React.PropTypes.oneOf(["foo", 0, true]),
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ number literal `0`
  Member 3:
    9:     mixed: React.PropTypes.oneOf(["foo", 0, true]),
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ boolean literal `true`
  Error:
   24: (<Example mixed={"baz"} />); // error: 'baz' not in enum
                        ^^^^^ string. This type is incompatible with
    9:     mixed: React.PropTypes.oneOf(["foo", 0, true]),
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ boolean literal `true`

Error: proptype_oneOf.js:32
 32: (<RequiredExample />); // error: `p` not found
      ^^^^^^^^^^^^^^^^^^^ React element `RequiredExample`
                  v
 27:   propTypes: {
 28:     p: React.PropTypes.oneOf([]).isRequired,
 29:   },
       ^ property `p`. Property not found in
 32: (<RequiredExample />); // error: `p` not found
      ^^^^^^^^^^^^^^^^^^^ props of React element `RequiredExample`

Error: proptype_oneOf.js:40
 40: (<EmptyExample nil={0} />); // number ~> empty
      ^^^^^^^^^^^^^^^^^^^^^^^^ props of React element `EmptyExample`. This type is incompatible with
                  v
 35:   propTypes: {
 36:     nil: React.PropTypes.oneOf([]), // i.e., `empty`
 37:   },
       ^ propTypes of React component
  Property `nil` is incompatible:
     40: (<EmptyExample nil={0} />); // number ~> empty
                             ^ number. This type is incompatible with
     36:     nil: React.PropTypes.oneOf([]), // i.e., `empty`
                  ^^^^^^^^^^^^^^^^^^^^^^^^^ empty

Error: proptype_oneOf.js:76
 76:     p: React.PropTypes.oneOf(0), // error: expected array, got 0
            ^^^^^^^^^^^^^^^^^^^^^^^^ call of method `oneOf`. Expected an array instead of
 76:     p: React.PropTypes.oneOf(0), // error: expected array, got 0
                                  ^ number

Error: proptype_oneOfType.js:23
 23: var fail_missing = <Example />;
                        ^^^^^^^^^^^ React element `Example`
                  v
  5:   propTypes: {
  6:     prop: React.PropTypes.oneOfType([
  7:       React.PropTypes.string,
...:
 10:   },
       ^ property `prop`. Property not found in
 23: var fail_missing = <Example />;
                        ^^^^^^^^^^^ props of React element `Example`

Error: proptype_oneOfType.js:24
 24: var fail_bool = <Example prop={true} />;
                     ^^^^^^^^^^^^^^^^^^^^^^^ React element `Example`
 24: var fail_bool = <Example prop={true} />;
                                    ^^^^ boolean. This type is incompatible with
               v--------------------------
  6:     prop: React.PropTypes.oneOfType([
  7:       React.PropTypes.string,
  8:       React.PropTypes.number
  9:     ]).isRequired
         ------------^ union: string | number
  Member 1:
                 v--------------------------
    6:     prop: React.PropTypes.oneOfType([
    7:       React.PropTypes.string,
    8:       React.PropTypes.number
    9:     ]).isRequired
           ------------^ string
  Error:
   24: var fail_bool = <Example prop={true} />;
                                      ^^^^ boolean. This type is incompatible with
                 v--------------------------
    6:     prop: React.PropTypes.oneOfType([
    7:       React.PropTypes.string,
    8:       React.PropTypes.number
    9:     ]).isRequired
           ------------^ string
  Member 2:
                 v--------------------------
    6:     prop: React.PropTypes.oneOfType([
    7:       React.PropTypes.string,
    8:       React.PropTypes.number
    9:     ]).isRequired
           ------------^ number
  Error:
   24: var fail_bool = <Example prop={true} />;
                                      ^^^^ boolean. This type is incompatible with
                 v--------------------------
    6:     prop: React.PropTypes.oneOfType([
    7:       React.PropTypes.string,
    8:       React.PropTypes.number
    9:     ]).isRequired
           ------------^ number

Error: proptype_oneOfType.js:29
 29: var todo_required = <Example prop={null} />;
                         ^^^^^^^^^^^^^^^^^^^^^^^ React element `Example`
 29: var todo_required = <Example prop={null} />;
                                        ^^^^ null. This type is incompatible with
               v--------------------------
  6:     prop: React.PropTypes.oneOfType([
  7:       React.PropTypes.string,
  8:       React.PropTypes.number
  9:     ]).isRequired
         ------------^ union: string | number
  Member 1:
                 v--------------------------
    6:     prop: React.PropTypes.oneOfType([
    7:       React.PropTypes.string,
    8:       React.PropTypes.number
    9:     ]).isRequired
           ------------^ string
  Error:
   29: var todo_required = <Example prop={null} />;
                                          ^^^^ null. This type is incompatible with
                 v--------------------------
    6:     prop: React.PropTypes.oneOfType([
    7:       React.PropTypes.string,
    8:       React.PropTypes.number
    9:     ]).isRequired
           ------------^ string
  Member 2:
                 v--------------------------
    6:     prop: React.PropTypes.oneOfType([
    7:       React.PropTypes.string,
    8:       React.PropTypes.number
    9:     ]).isRequired
           ------------^ number
  Error:
   29: var todo_required = <Example prop={null} />;
                                          ^^^^ null. This type is incompatible with
                 v--------------------------
    6:     prop: React.PropTypes.oneOfType([
    7:       React.PropTypes.string,
    8:       React.PropTypes.number
    9:     ]).isRequired
           ------------^ number

Error: proptype_oneOfType.js:41
 41: (<OptionalExample p={0} />); // error: number ~> string
      ^^^^^^^^^^^^^^^^^^^^^^^^^ props of React element `OptionalExample`. This type is incompatible with
                  v
 32:   propTypes: {
 33:     p: React.PropTypes.oneOfType([
 34:       React.PropTypes.string,
 35:     ]),
 36:   },
       ^ propTypes of React component
  Property `p` is incompatible:
     41: (<OptionalExample p={0} />); // error: number ~> string
                              ^ number. This type is incompatible with
                v--------------------------
     33:     p: React.PropTypes.oneOfType([
     34:       React.PropTypes.string,
     35:     ]),
             -^ string

Error: proptype_oneOfType.js:49
 49: (<EmptyExample nil={0} />); // number ~> empty
      ^^^^^^^^^^^^^^^^^^^^^^^^ props of React element `EmptyExample`. This type is incompatible with
                  v
 44:   propTypes: {
 45:     nil: React.PropTypes.oneOfType([]), // i.e., `empty`
 46:   },
       ^ propTypes of React component
  Property `nil` is incompatible:
     49: (<EmptyExample nil={0} />); // number ~> empty
                             ^ number. This type is incompatible with
     45:     nil: React.PropTypes.oneOfType([]), // i.e., `empty`
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ empty

Error: proptype_oneOfType.js:91
 91:     p: React.PropTypes.oneOfType(0), // error: expected array, got 0
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^ call of method `oneOfType`. Expected an array instead of
 91:     p: React.PropTypes.oneOfType(0), // error: expected array, got 0
                                      ^ number

Error: proptype_oneOfType.js:99
 99:     p: React.PropTypes.oneOfType([{}]), // error: expected prop type, got {}
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ call of method `oneOfType`. Expected a React PropType instead of
 99:     p: React.PropTypes.oneOfType([{}]), // error: expected prop type, got {}
                                       ^^ object literal

Error: proptype_shape.js:20
 20:     (this.props.foo.baz: string);
                         ^^^ property `baz`. Property not found in
 20:     (this.props.foo.baz: string);
          ^^^^^^^^^^^^^^ object type

Error: proptype_shape.js:24
 24:     this.props.foo.baz = 0;
                        ^^^ property `baz`. Property not found in
 24:     this.props.foo.baz = 0;
         ^^^^^^^^^^^^^^ object type

Error: proptypes_builtins.js:3
  3: type NoFun = mixed => empty;
                  ^^^^^ mixed. This type is incompatible with the expected param type of
306:   (typeChecker: ReactPropsCheckType) => ReactPropsChainableTypeChecker;
                     ^^^^^^^^^^^^^^^^^^^ function type. See lib: <BUILTINS>/react.js:306

Error: proptypes_builtins.js:3
  3: type NoFun = mixed => empty;
                  ^^^^^ mixed. This type is incompatible with the expected param type of
310:   (typeChecker: ReactPropsCheckType) => ReactPropsChainableTypeChecker;
                     ^^^^^^^^^^^^^^^^^^^ function type. See lib: <BUILTINS>/react.js:310

Error: proptypes_builtins.js:3
  3: type NoFun = mixed => empty;
                  ^^^^^ mixed. This type is incompatible with the expected param type of
312:   (expectedValues: Array<any>) => ReactPropsChainableTypeChecker;
                        ^^^^^^^^^^ array type. See lib: <BUILTINS>/react.js:312

Error: proptypes_builtins.js:3
  3: type NoFun = mixed => empty;
                  ^^^^^ mixed. This type is incompatible with the expected param type of
314:   (arrayOfTypeCheckers: Array<ReactPropsCheckType>) =>
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^ array type. See lib: <BUILTINS>/react.js:314

Error: proptypes_builtins.js:3
  3: type NoFun = mixed => empty;
                  ^^^^^ mixed. This type is incompatible with the expected param type of
317:   (shapeTypes: { [key: string]: ReactPropsCheckType }) =>
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ object type. See lib: <BUILTINS>/react.js:317

Error: proptypes_builtins.js:3
  3: type NoFun = mixed => empty;
                           ^^^^^ empty. This type is incompatible with
306:   (typeChecker: ReactPropsCheckType) => ReactPropsChainableTypeChecker;
                                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ object type. See lib: <BUILTINS>/react.js:306

Error: proptypes_builtins.js:3
  3: type NoFun = mixed => empty;
                           ^^^^^ empty. This type is incompatible with
308:   (expectedClass: any) => ReactPropsChainableTypeChecker;
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ object type. See lib: <BUILTINS>/react.js:308

Error: proptypes_builtins.js:3
  3: type NoFun = mixed => empty;
                           ^^^^^ empty. This type is incompatible with
310:   (typeChecker: ReactPropsCheckType) => ReactPropsChainableTypeChecker;
                                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ object type. See lib: <BUILTINS>/react.js:310

Error: proptypes_builtins.js:3
  3: type NoFun = mixed => empty;
                           ^^^^^ empty. This type is incompatible with
312:   (expectedValues: Array<any>) => ReactPropsChainableTypeChecker;
                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ object type. See lib: <BUILTINS>/react.js:312

Error: proptypes_builtins.js:3
  3: type NoFun = mixed => empty;
                           ^^^^^ empty. This type is incompatible with
315:     ReactPropsChainableTypeChecker;
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ object type. See lib: <BUILTINS>/react.js:315

Error: proptypes_builtins.js:3
  3: type NoFun = mixed => empty;
                           ^^^^^ empty. This type is incompatible with
318:     ReactPropsChainableTypeChecker;
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ object type. See lib: <BUILTINS>/react.js:318

Error: proptypes_sealed.js:18
 18:     (this.props.baz: string);
                     ^^^ property `baz`. Property not found in
 18:     (this.props.baz: string);
          ^^^^^^^^^^ propTypes of React component

Error: proptypes_sealed.js:22
 22:     this.props.baz = 0;
                    ^^^ property `baz`. Property not found in
 22:     this.props.baz = 0;
         ^^^^^^^^^^ propTypes of React component

Error: ref.js:12
 12: <Foo ref={(foo: number) => {}} />; // Error: `Foo` is not a `number`.
               ^^^^^^^^^^^^^^^^^^^ function. This type is incompatible with
 12: <Foo ref={(foo: number) => {}} />; // Error: `Foo` is not a `number`.
     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ union: function type | string
  Member 1:
  176:   | ((React$ElementRef<ElementType> | null) => mixed)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ function type. See lib: <BUILTINS>/react.js:176
  Error:
   12: <Foo ref={(foo: number) => {}} />; // Error: `Foo` is not a `number`.
                       ^^^^^^ number. This type is incompatible with an argument type of
  176:   | ((React$ElementRef<ElementType> | null) => mixed)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ Foo. See lib: <BUILTINS>/react.js:176
  Member 2:
  177:   | string;
           ^^^^^^ string. See lib: <BUILTINS>/react.js:177
  Error:
   12: <Foo ref={(foo: number) => {}} />; // Error: `Foo` is not a `number`.
                 ^^^^^^^^^^^^^^^^^^^ function. This type is incompatible with
  177:   | string;
           ^^^^^^ string. See lib: <BUILTINS>/react.js:177

Error: ref.js:13
 13: <Foo ref={foo => (foo: Foo)} />; // Error: `Foo` may be null.
                       ^^^ null. This type is incompatible with
 13: <Foo ref={foo => (foo: Foo)} />; // Error: `Foo` may be null.
                            ^^^ Foo

Error: ref.js:15
 15: <Foo ref={foo => (foo: Bar | null)} />; // Error: `Foo` is not `Bar`.
                       ^^^ Foo. This type is incompatible with
 15: <Foo ref={foo => (foo: Bar | null)} />; // Error: `Foo` is not `Bar`.
                            ^^^^^^^^^^ union: Bar | null
  Member 1:
   15: <Foo ref={foo => (foo: Bar | null)} />; // Error: `Foo` is not `Bar`.
                              ^^^ Bar
  Error:
   15: <Foo ref={foo => (foo: Bar | null)} />; // Error: `Foo` is not `Bar`.
                         ^^^ Foo. This type is incompatible with
   15: <Foo ref={foo => (foo: Bar | null)} />; // Error: `Foo` is not `Bar`.
                              ^^^ Bar
  Member 2:
   15: <Foo ref={foo => (foo: Bar | null)} />; // Error: `Foo` is not `Bar`.
                                    ^^^^ null
  Error:
   15: <Foo ref={foo => (foo: Bar | null)} />; // Error: `Foo` is not `Bar`.
                         ^^^ Foo. This type is incompatible with
   15: <Foo ref={foo => (foo: Bar | null)} />; // Error: `Foo` is not `Bar`.
                                    ^^^^ null

Error: ref.js:23
 23: <FooExact ref={(foo: number) => {}} />; // Error: `FooExact` is not a `number`.
                    ^^^^^^^^^^^^^^^^^^^ function. This type is incompatible with
 23: <FooExact ref={(foo: number) => {}} />; // Error: `FooExact` is not a `number`.
     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ union: function type | string
  Member 1:
  176:   | ((React$ElementRef<ElementType> | null) => mixed)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ function type. See lib: <BUILTINS>/react.js:176
  Error:
   23: <FooExact ref={(foo: number) => {}} />; // Error: `FooExact` is not a `number`.
                            ^^^^^^ number. This type is incompatible with an argument type of
  176:   | ((React$ElementRef<ElementType> | null) => mixed)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ FooExact. See lib: <BUILTINS>/react.js:176
  Member 2:
  177:   | string;
           ^^^^^^ string. See lib: <BUILTINS>/react.js:177
  Error:
   23: <FooExact ref={(foo: number) => {}} />; // Error: `FooExact` is not a `number`.
                      ^^^^^^^^^^^^^^^^^^^ function. This type is incompatible with
  177:   | string;
           ^^^^^^ string. See lib: <BUILTINS>/react.js:177

Error: ref.js:24
 24: <FooExact ref={foo => (foo: FooExact)} />; // Error: `FooExact` may be null.
                            ^^^ null. This type is incompatible with
 24: <FooExact ref={foo => (foo: FooExact)} />; // Error: `FooExact` may be null.
                                 ^^^^^^^^ FooExact

Error: ref.js:26
 26: <FooExact ref={foo => (foo: Bar | null)} />; // Error: `FooExact` is not `Bar`.
                            ^^^ FooExact. This type is incompatible with
 26: <FooExact ref={foo => (foo: Bar | null)} />; // Error: `FooExact` is not `Bar`.
                                 ^^^^^^^^^^ union: Bar | null
  Member 1:
   26: <FooExact ref={foo => (foo: Bar | null)} />; // Error: `FooExact` is not `Bar`.
                                   ^^^ Bar
  Error:
   26: <FooExact ref={foo => (foo: Bar | null)} />; // Error: `FooExact` is not `Bar`.
                              ^^^ FooExact. This type is incompatible with
   26: <FooExact ref={foo => (foo: Bar | null)} />; // Error: `FooExact` is not `Bar`.
                                   ^^^ Bar
  Member 2:
   26: <FooExact ref={foo => (foo: Bar | null)} />; // Error: `FooExact` is not `Bar`.
                                         ^^^^ null
  Error:
   26: <FooExact ref={foo => (foo: Bar | null)} />; // Error: `FooExact` is not `Bar`.
                              ^^^ FooExact. This type is incompatible with
   26: <FooExact ref={foo => (foo: Bar | null)} />; // Error: `FooExact` is not `Bar`.
                                         ^^^^ null

Error: render_callback.js:22
 22: ReactDOM.render(<Example/>, document.querySelector('#site'), 1);
                                                                  ^ number. This type is incompatible with the expected param type of
265:     callback?: () => void,
                    ^^^^^^^^^^ function type. See lib: <BUILTINS>/react.js:265

Error: render_callback.js:24
 24: ReactDOM.render(<Example/>, document.querySelector('#site'), '');
                                                                  ^^ string. This type is incompatible with the expected param type of
265:     callback?: () => void,
                    ^^^^^^^^^^ function type. See lib: <BUILTINS>/react.js:265

Error: render_callback.js:25
 25: ReactDOM.render(<Example/>, document.querySelector('#site'), null);
                                                                  ^^^^ null. This type is incompatible with the expected param type of
265:     callback?: () => void,
                    ^^^^^^^^^^ function type. See lib: <BUILTINS>/react.js:265

Error: undefined_prop.js:7
  7: <MyComponent title={undefined} />;
     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ props of React element `MyComponent`. This type is incompatible with
  5: class MyComponent extends React.Component<{title: string}> {}
                                               ^^^^^^^^^^^^^^^ object type
  Property `title` is incompatible:
      7: <MyComponent title={undefined} />;
                             ^^^^^^^^^ undefined. This type is incompatible with
      5: class MyComponent extends React.Component<{title: string}> {}
                                                           ^^^^^^ string


Found 162 errors
