Error ---------------------------------------------------------------------------------- <BUILTINS>/lib.dom.d.ts:14164:5

Multiple indexers are not supported. [unsupported-syntax]

   14164|     [name: string]: any;
              ^^^^^^^^^^^^^^^^^^^


Error --------------------------------------------------------------------------------- <BUILTINS>/lib.dom.d.ts:37956:13

This name declaration overrides an existing binding `console` [1]. Overriding in library definitions can lead to
surprising behaviors. [libdef-override]

   <BUILTINS>/lib.dom.d.ts:37956:13
   37956| declare var console: Console;
                      ^^^^^^^

References:
   <BUILTINS>/core.js:3134:13
    3134| declare var console: {
                      ^^^^^^^ [1]


Error ------------------------------------------------------------------------------------------------------ test.js:7:1

Cannot cast `element.align` to number because `string` [1] is incompatible with `number` [2]. [incompatible-type]

   test.js:7:1
       7| element.align as number; // ERROR
          ^^^^^^^^^^^^^

References:
   <BUILTINS>/lib.dom.d.ts:13651:12
   13651|     align: string;
                     ^^^^^^ [1]
   test.js:7:18
       7| element.align as number; // ERROR
                           ^^^^^^ [2]


Error ------------------------------------------------------------------------------------------------------ test.js:8:1

Cannot cast `promise` to `Promise` because in type argument `R` [1]: `HTMLDivElement` [2] is incompatible with
`string` [3]. [incompatible-type]

   test.js:8:1
      8| promise as Promise<string>; // ERROR
         ^^^^^^^

References:
   <BUILTINS>/core.js:2300:27
   2300| declare class Promise<out R = unknown> {
                                   ^ [1]
   test.js:2:24
      2| const promise: Promise<HTMLDivElement> = Promise.resolve(element);
                                ^^^^^^^^^^^^^^ [2]
   test.js:8:20
      8| promise as Promise<string>; // ERROR
                            ^^^^^^ [3]



Found 4 errors
