Error ----------------------------------------------------- import_type.js:13:18

Cannot assign `foo1Inst` to `a2` because `ClassFoo1` is incompatible with
number.


Error ------------------------------------------------------ import_type.js:14:5

Cannot reference type `ClassFoo1` from a value position.


Error ----------------------------------------------------- import_type.js:24:18

Cannot assign `foo2Inst` to `b2` because `ClassFoo2` is incompatible with
number.


Error ------------------------------------------------------ import_type.js:25:5

Cannot reference type `ClassFoo2` from a value position.


Error ------------------------------------------------------ import_type.js:34:5

Cannot reference type `ClassFoo3T` from a value position.


Error ----------------------------------------------------- import_type.js:44:18

Cannot assign `foo4Inst` to `d2` because `ClassFoo4` is incompatible with
number.


Error ------------------------------------------------------ import_type.js:45:5

Cannot reference type `ClassFoo4` from a value position.


Error ----------------------------------------------------- import_type.js:47:16

Cannot reference type `ClassFoo5` from a value position.


Error ----------------------------------------------------- import_type.js:56:18

Cannot assign `givesAFoo3Obj()` to `e2` because `AliasFoo3` is incompatible with
number.


Error ----------------------------------------------------- import_type.js:57:16

Cannot reference type `AliasFoo3` from a value position.


Error ----------------------------------------------------- import_type.js:71:14

Cannot import the value `numValue` as a type. `import type` only works on type
exports. Like type aliases, interfaces, and classes. If you intended to import
the type of a value use `import typeof` instead.


Error ------------------------------------------------------ import_type.js:81:3

Cannot reference type `ClassFoo6` from a value position.



Found 12 errors
