Error ----------------------------------------------------- embedded_ltgt.js:4:1

Unexpected token ILLEGAL


Error ------------------------------------------------ incorrect_token_lt.js:3:4

Unexpected token <


Error -------------------------------------- nonmatching_closing_element.js:3:17

Expected corresponding JSX closing tag for JSX fragment


Error -------------------------------------- nonmatching_opening_element.js:3:17

Expected corresponding JSX closing tag for elementName



Found 4 errors
