Error -------------------------------------------------------------- 1/f.js:3:27

Cannot perform arithmetic operation because null is not a number.


Error -------------------------------------------------------------- 2/A.js:5:15

Missing type annotation for `x`.


Error -------------------------------------------------------------- 2/A.js:9:10

Missing type annotation for `callback`.


Error ------------------------------------------------------------- 2/A.js:10:21

Cannot call `callback` with `this.getX()` bound to `x` because number is
incompatible with string.



Found 4 errors
