
overload.js:1:27,27: number
This type is incompatible with
  [LIB] core.js:155:19,24: string

overload.js:1:27,27: number
This type is incompatible with
  [LIB] core.js:173:1,183:1: RegExp

[LIB] core.js:155:43,48: string
This type is incompatible with
  overload.js:1:9,14: number

[LIB] core.js:155:43,48: string
This type is incompatible with
  overload.js:2:9,14: number

[LIB] core.js:160:62,67: string
This type is incompatible with
  overload.js:4:9,14: number

Found 5 errors
