CanvasRenderingContext2D.js:11
 11:     ctx.moveTo('0', '1');  // error: should be numbers
         ^^^^^^^^^^^^^^^^^^^^ call of method `moveTo`
 11:     ctx.moveTo('0', '1');  // error: should be numbers
                    ^^^ string. This type is incompatible with
number. See lib: dom.js:1125

CanvasRenderingContext2D.js:11
 11:     ctx.moveTo('0', '1');  // error: should be numbers
         ^^^^^^^^^^^^^^^^^^^^ call of method `moveTo`
 11:     ctx.moveTo('0', '1');  // error: should be numbers
                         ^^^ string. This type is incompatible with
number. See lib: dom.js:1125

Element.js:14
 14:     element.scrollIntoView({ behavior: 'invalid' });
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ call of method `scrollIntoView`
 14:     element.scrollIntoView({ behavior: 'invalid' });
                                ^^^^^^^^^^^^^^^^^^^^^^^ object literal. This type is incompatible with
union: boolean | object type. See lib: dom.js:808
  Member 1:
  boolean. See lib: dom.js:808
  Error:
   14:     element.scrollIntoView({ behavior: 'invalid' });
                                  ^^^^^^^^^^^^^^^^^^^^^^^ object literal. This type is incompatible with
  boolean. See lib: dom.js:808
  Member 2:
  object type. See lib: dom.js:808
  Error:
   14:     element.scrollIntoView({ behavior: 'invalid' });
                                              ^^^^^^^^^ string. This type is incompatible with
  string enum. See lib: dom.js:808

Element.js:15
 15:     element.scrollIntoView({ block: 'invalid' });
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ call of method `scrollIntoView`
 15:     element.scrollIntoView({ block: 'invalid' });
                                ^^^^^^^^^^^^^^^^^^^^ object literal. This type is incompatible with
union: boolean | object type. See lib: dom.js:808
  Member 1:
  boolean. See lib: dom.js:808
  Error:
   15:     element.scrollIntoView({ block: 'invalid' });
                                  ^^^^^^^^^^^^^^^^^^^^ object literal. This type is incompatible with
  boolean. See lib: dom.js:808
  Member 2:
  object type. See lib: dom.js:808
  Error:
   15:     element.scrollIntoView({ block: 'invalid' });
                                           ^^^^^^^^^ string. This type is incompatible with
  string enum. See lib: dom.js:808

Element.js:16
 16:     element.scrollIntoView(1);
         ^^^^^^^^^^^^^^^^^^^^^^^^^ call of method `scrollIntoView`
 16:     element.scrollIntoView(1);
                                ^ number. This type is incompatible with
union: boolean | object type. See lib: dom.js:808
  Member 1:
  boolean. See lib: dom.js:808
  Error:
   16:     element.scrollIntoView(1);
                                  ^ number. This type is incompatible with
  boolean. See lib: dom.js:808
  Member 2:
  object type. See lib: dom.js:808
  Error:
   16:     element.scrollIntoView(1);
                                  ^ number. This type is incompatible with
  object type. See lib: dom.js:808

HTMLElement.js:14
 14:     element.scrollIntoView({ behavior: 'invalid' });
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ call of method `scrollIntoView`
 14:     element.scrollIntoView({ behavior: 'invalid' });
                                ^^^^^^^^^^^^^^^^^^^^^^^ object literal. This type is incompatible with
union: boolean | object type. See lib: dom.js:808
  Member 1:
  boolean. See lib: dom.js:808
  Error:
   14:     element.scrollIntoView({ behavior: 'invalid' });
                                  ^^^^^^^^^^^^^^^^^^^^^^^ object literal. This type is incompatible with
  boolean. See lib: dom.js:808
  Member 2:
  object type. See lib: dom.js:808
  Error:
   14:     element.scrollIntoView({ behavior: 'invalid' });
                                              ^^^^^^^^^ string. This type is incompatible with
  string enum. See lib: dom.js:808

HTMLElement.js:15
 15:     element.scrollIntoView({ block: 'invalid' });
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ call of method `scrollIntoView`
 15:     element.scrollIntoView({ block: 'invalid' });
                                ^^^^^^^^^^^^^^^^^^^^ object literal. This type is incompatible with
union: boolean | object type. See lib: dom.js:808
  Member 1:
  boolean. See lib: dom.js:808
  Error:
   15:     element.scrollIntoView({ block: 'invalid' });
                                  ^^^^^^^^^^^^^^^^^^^^ object literal. This type is incompatible with
  boolean. See lib: dom.js:808
  Member 2:
  object type. See lib: dom.js:808
  Error:
   15:     element.scrollIntoView({ block: 'invalid' });
                                           ^^^^^^^^^ string. This type is incompatible with
  string enum. See lib: dom.js:808

HTMLElement.js:16
 16:     element.scrollIntoView(1);
         ^^^^^^^^^^^^^^^^^^^^^^^^^ call of method `scrollIntoView`
 16:     element.scrollIntoView(1);
                                ^ number. This type is incompatible with
union: boolean | object type. See lib: dom.js:808
  Member 1:
  boolean. See lib: dom.js:808
  Error:
   16:     element.scrollIntoView(1);
                                  ^ number. This type is incompatible with
  boolean. See lib: dom.js:808
  Member 2:
  object type. See lib: dom.js:808
  Error:
   16:     element.scrollIntoView(1);
                                  ^ number. This type is incompatible with
  object type. See lib: dom.js:808

eventtarget.js:9
  9:     (target.attachEvent('foo', listener): void); // invalid, may be undefined
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ call of method `attachEvent`. Function cannot be called on possibly undefined value
  9:     (target.attachEvent('foo', listener): void); // invalid, may be undefined
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ undefined

eventtarget.js:16
 16:     (target.detachEvent('foo', listener): void); // invalid, may be undefined
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ call of method `detachEvent`. Function cannot be called on possibly undefined value
 16:     (target.detachEvent('foo', listener): void); // invalid, may be undefined
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ undefined

path2d.js:9
  9:     (path.arcTo(0, 0, 0, 0, 10, '20', 5): void); // invalid
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ call of method `arcTo`. Function cannot be called on any member of intersection type
  9:     (path.arcTo(0, 0, 0, 0, 10, '20', 5): void); // invalid
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ intersection
  Member 1:
  function type. See lib: dom.js:999
  Error:
    9:     (path.arcTo(0, 0, 0, 0, 10, '20', 5): void); // invalid
                                       ^^^^ string. This type is incompatible with
  undefined. See lib: dom.js:999
  Member 2:
  function type. See lib: dom.js:1000
  Error:
    9:     (path.arcTo(0, 0, 0, 0, 10, '20', 5): void); // invalid
                                       ^^^^ string. This type is incompatible with
  number. See lib: dom.js:1000

registerElement.js:48
 48:     document.registerElement('custom-element', {
         ^ call of method `registerElement`
 52:           oldVal: string, // Error: This might be null
                       ^^^^^^ string. This type is incompatible with
null. See lib: dom.js:354

registerElement.js:48
 48:     document.registerElement('custom-element', {
         ^ call of method `registerElement`
 53:           newVal: string, // Error: This might be null
                       ^^^^^^ string. This type is incompatible with
null. See lib: dom.js:369

traversal.js:26
 26:     document.createNodeIterator({}); // invalid
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ call of method `createNodeIterator`. Function cannot be called on any member of intersection type
 26:     document.createNodeIterator({}); // invalid
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ intersection
  Member 1:
  polymorphic type: function type. See lib: dom.js:527
  Error:
   26:     document.createNodeIterator({}); // invalid
                                       ^^ object literal. This type is incompatible with
  Attr. See lib: dom.js:527
  Member 2:
  polymorphic type: function type. See lib: dom.js:535
  Error:
   26:     document.createNodeIterator({}); // invalid
                                       ^^ object literal. This type is incompatible with
  Document. See lib: dom.js:535
  Member 3:
  polymorphic type: function type. See lib: dom.js:536
  Error:
   26:     document.createNodeIterator({}); // invalid
                                       ^^ object literal. This type is incompatible with
  Document. See lib: dom.js:536
  Member 4:
  polymorphic type: function type. See lib: dom.js:537
  Error:
   26:     document.createNodeIterator({}); // invalid
                                       ^^ object literal. This type is incompatible with
  Document. See lib: dom.js:537
  Member 5:
  polymorphic type: function type. See lib: dom.js:538
  Error:
   26:     document.createNodeIterator({}); // invalid
                                       ^^ object literal. This type is incompatible with
  Document. See lib: dom.js:538
  Member 6:
  polymorphic type: function type. See lib: dom.js:539
  Error:
   26:     document.createNodeIterator({}); // invalid
                                       ^^ object literal. This type is incompatible with
  Document. See lib: dom.js:539
  Member 7:
  polymorphic type: function type. See lib: dom.js:540
  Error:
   26:     document.createNodeIterator({}); // invalid
                                       ^^ object literal. This type is incompatible with
  Document. See lib: dom.js:540
  Member 8:
  polymorphic type: function type. See lib: dom.js:541
  Error:
   26:     document.createNodeIterator({}); // invalid
                                       ^^ object literal. This type is incompatible with
  Document. See lib: dom.js:541
  Member 9:
  polymorphic type: function type. See lib: dom.js:542
  Error:
   26:     document.createNodeIterator({}); // invalid
                                       ^^ object literal. This type is incompatible with
  Document. See lib: dom.js:542
  Member 10:
  polymorphic type: function type. See lib: dom.js:543
  Error:
   26:     document.createNodeIterator({}); // invalid
                                       ^^ object literal. This type is incompatible with
  Document. See lib: dom.js:543
  Member 11:
  polymorphic type: function type. See lib: dom.js:544
  Error:
   26:     document.createNodeIterator({}); // invalid
                                       ^^ object literal. This type is incompatible with
  Document. See lib: dom.js:544
  Member 12:
  polymorphic type: function type. See lib: dom.js:545
  Error:
   26:     document.createNodeIterator({}); // invalid
                                       ^^ object literal. This type is incompatible with
  Document. See lib: dom.js:545
  Member 13:
  polymorphic type: function type. See lib: dom.js:546
  Error:
   26:     document.createNodeIterator({}); // invalid
                                       ^^ object literal. This type is incompatible with
  Document. See lib: dom.js:546
  Member 14:
  polymorphic type: function type. See lib: dom.js:547
  Error:
   26:     document.createNodeIterator({}); // invalid
                                       ^^ object literal. This type is incompatible with
  Document. See lib: dom.js:547
  Member 15:
  polymorphic type: function type. See lib: dom.js:548
  Error:
   26:     document.createNodeIterator({}); // invalid
                                       ^^ object literal. This type is incompatible with
  Document. See lib: dom.js:548
  Member 16:
  polymorphic type: function type. See lib: dom.js:549
  Error:
   26:     document.createNodeIterator({}); // invalid
                                       ^^ object literal. This type is incompatible with
  Document. See lib: dom.js:549
  Member 17:
  polymorphic type: function type. See lib: dom.js:550
  Error:
   26:     document.createNodeIterator({}); // invalid
                                       ^^ object literal. This type is incompatible with
  Document. See lib: dom.js:550
  Member 18:
  polymorphic type: function type. See lib: dom.js:551
  Error:
   26:     document.createNodeIterator({}); // invalid
                                       ^^ object literal. This type is incompatible with
  Document. See lib: dom.js:551
  Member 19:
  polymorphic type: function type. See lib: dom.js:552
  Error:
   26:     document.createNodeIterator({}); // invalid
                                       ^^ object literal. This type is incompatible with
  Document. See lib: dom.js:552
  Member 20:
  polymorphic type: function type. See lib: dom.js:553
  Error:
   26:     document.createNodeIterator({}); // invalid
                                       ^^ object literal. This type is incompatible with
  Document. See lib: dom.js:553
  Member 21:
  polymorphic type: function type. See lib: dom.js:554
  Error:
   26:     document.createNodeIterator({}); // invalid
                                       ^^ object literal. This type is incompatible with
  Document. See lib: dom.js:554
  Member 22:
  polymorphic type: function type. See lib: dom.js:555
  Error:
   26:     document.createNodeIterator({}); // invalid
                                       ^^ object literal. This type is incompatible with
  Document. See lib: dom.js:555
  Member 23:
  polymorphic type: function type. See lib: dom.js:556
  Error:
   26:     document.createNodeIterator({}); // invalid
                                       ^^ object literal. This type is incompatible with
  Document. See lib: dom.js:556
  Member 24:
  polymorphic type: function type. See lib: dom.js:557
  Error:
   26:     document.createNodeIterator({}); // invalid
                                       ^^ object literal. This type is incompatible with
  Document. See lib: dom.js:557
  Member 25:
  polymorphic type: function type. See lib: dom.js:558
  Error:
   26:     document.createNodeIterator({}); // invalid
                                       ^^ object literal. This type is incompatible with
  Document. See lib: dom.js:558
  Member 26:
  polymorphic type: function type. See lib: dom.js:586
  Error:
   26:     document.createNodeIterator({}); // invalid
                                       ^^ object literal. This type is incompatible with
  DocumentFragment. See lib: dom.js:586
  Member 27:
  polymorphic type: function type. See lib: dom.js:587
  Error:
   26:     document.createNodeIterator({}); // invalid
                                       ^^ object literal. This type is incompatible with
  DocumentFragment. See lib: dom.js:587
  Member 28:
  polymorphic type: function type. See lib: dom.js:588
  Error:
   26:     document.createNodeIterator({}); // invalid
                                       ^^ object literal. This type is incompatible with
  DocumentFragment. See lib: dom.js:588
  Member 29:
  polymorphic type: function type. See lib: dom.js:589
  Error:
   26:     document.createNodeIterator({}); // invalid
                                       ^^ object literal. This type is incompatible with
  DocumentFragment. See lib: dom.js:589
  Member 30:
  polymorphic type: function type. See lib: dom.js:590
  Error:
   26:     document.createNodeIterator({}); // invalid
                                       ^^ object literal. This type is incompatible with
  DocumentFragment. See lib: dom.js:590
  Member 31:
  polymorphic type: function type. See lib: dom.js:591
  Error:
   26:     document.createNodeIterator({}); // invalid
                                       ^^ object literal. This type is incompatible with
  DocumentFragment. See lib: dom.js:591
  Member 32:
  polymorphic type: function type. See lib: dom.js:592
  Error:
   26:     document.createNodeIterator({}); // invalid
                                       ^^ object literal. This type is incompatible with
  DocumentFragment. See lib: dom.js:592
  Member 33:
  polymorphic type: function type. See lib: dom.js:593
  Error:
   26:     document.createNodeIterator({}); // invalid
                                       ^^ object literal. This type is incompatible with
  DocumentFragment. See lib: dom.js:593
  Member 34:
  polymorphic type: function type. See lib: dom.js:606
  Error:
   26:     document.createNodeIterator({}); // invalid
                                       ^^ object literal. This type is incompatible with
  Node. See lib: dom.js:606
  Member 35:
  polymorphic type: function type. See lib: dom.js:607
  Error:
   26:     document.createNodeIterator({}); // invalid
                                       ^^ object literal. This type is incompatible with
  Node. See lib: dom.js:607
  Member 36:
  polymorphic type: function type. See lib: dom.js:608
  Error:
   26:     document.createNodeIterator({}); // invalid
                                       ^^ object literal. This type is incompatible with
  Node. See lib: dom.js:608
  Member 37:
  polymorphic type: function type. See lib: dom.js:609
  Error:
   26:     document.createNodeIterator({}); // invalid
                                       ^^ object literal. This type is incompatible with
  Node. See lib: dom.js:609
  Member 38:
  polymorphic type: function type. See lib: dom.js:610
  Error:
   26:     document.createNodeIterator({}); // invalid
                                       ^^ object literal. This type is incompatible with
  Node. See lib: dom.js:610
  Member 39:
  polymorphic type: function type. See lib: dom.js:611
  Error:
   26:     document.createNodeIterator({}); // invalid
                                       ^^ object literal. This type is incompatible with
  Node. See lib: dom.js:611
  Member 40:
  polymorphic type: function type. See lib: dom.js:612
  Error:
   26:     document.createNodeIterator({}); // invalid
                                       ^^ object literal. This type is incompatible with
  Node. See lib: dom.js:612
  Member 41:
  polymorphic type: function type. See lib: dom.js:613
  Error:
   26:     document.createNodeIterator({}); // invalid
                                       ^^ object literal. This type is incompatible with
  Node. See lib: dom.js:613
  Member 42:
  polymorphic type: function type. See lib: dom.js:624
  Error:
   26:     document.createNodeIterator({}); // invalid
                                       ^^ object literal. This type is incompatible with
  Document. See lib: dom.js:624
  Member 43:
  polymorphic type: function type. See lib: dom.js:628
  Error:
   26:     document.createNodeIterator({}); // invalid
                                       ^^ object literal. This type is incompatible with
  Node. See lib: dom.js:628

traversal.js:30
 30:     document.createTreeWalker({}); // invalid
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ call of method `createTreeWalker`. Function cannot be called on any member of intersection type
 30:     document.createTreeWalker({}); // invalid
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ intersection
  Member 1:
  polymorphic type: function type. See lib: dom.js:528
  Error:
   30:     document.createTreeWalker({}); // invalid
                                     ^^ object literal. This type is incompatible with
  Attr. See lib: dom.js:528
  Member 2:
  polymorphic type: function type. See lib: dom.js:559
  Error:
   30:     document.createTreeWalker({}); // invalid
                                     ^^ object literal. This type is incompatible with
  Document. See lib: dom.js:559
  Member 3:
  polymorphic type: function type. See lib: dom.js:560
  Error:
   30:     document.createTreeWalker({}); // invalid
                                     ^^ object literal. This type is incompatible with
  Document. See lib: dom.js:560
  Member 4:
  polymorphic type: function type. See lib: dom.js:561
  Error:
   30:     document.createTreeWalker({}); // invalid
                                     ^^ object literal. This type is incompatible with
  Document. See lib: dom.js:561
  Member 5:
  polymorphic type: function type. See lib: dom.js:562
  Error:
   30:     document.createTreeWalker({}); // invalid
                                     ^^ object literal. This type is incompatible with
  Document. See lib: dom.js:562
  Member 6:
  polymorphic type: function type. See lib: dom.js:563
  Error:
   30:     document.createTreeWalker({}); // invalid
                                     ^^ object literal. This type is incompatible with
  Document. See lib: dom.js:563
  Member 7:
  polymorphic type: function type. See lib: dom.js:564
  Error:
   30:     document.createTreeWalker({}); // invalid
                                     ^^ object literal. This type is incompatible with
  Document. See lib: dom.js:564
  Member 8:
  polymorphic type: function type. See lib: dom.js:565
  Error:
   30:     document.createTreeWalker({}); // invalid
                                     ^^ object literal. This type is incompatible with
  Document. See lib: dom.js:565
  Member 9:
  polymorphic type: function type. See lib: dom.js:566
  Error:
   30:     document.createTreeWalker({}); // invalid
                                     ^^ object literal. This type is incompatible with
  Document. See lib: dom.js:566
  Member 10:
  polymorphic type: function type. See lib: dom.js:567
  Error:
   30:     document.createTreeWalker({}); // invalid
                                     ^^ object literal. This type is incompatible with
  Document. See lib: dom.js:567
  Member 11:
  polymorphic type: function type. See lib: dom.js:568
  Error:
   30:     document.createTreeWalker({}); // invalid
                                     ^^ object literal. This type is incompatible with
  Document. See lib: dom.js:568
  Member 12:
  polymorphic type: function type. See lib: dom.js:569
  Error:
   30:     document.createTreeWalker({}); // invalid
                                     ^^ object literal. This type is incompatible with
  Document. See lib: dom.js:569
  Member 13:
  polymorphic type: function type. See lib: dom.js:570
  Error:
   30:     document.createTreeWalker({}); // invalid
                                     ^^ object literal. This type is incompatible with
  Document. See lib: dom.js:570
  Member 14:
  polymorphic type: function type. See lib: dom.js:571
  Error:
   30:     document.createTreeWalker({}); // invalid
                                     ^^ object literal. This type is incompatible with
  Document. See lib: dom.js:571
  Member 15:
  polymorphic type: function type. See lib: dom.js:572
  Error:
   30:     document.createTreeWalker({}); // invalid
                                     ^^ object literal. This type is incompatible with
  Document. See lib: dom.js:572
  Member 16:
  polymorphic type: function type. See lib: dom.js:573
  Error:
   30:     document.createTreeWalker({}); // invalid
                                     ^^ object literal. This type is incompatible with
  Document. See lib: dom.js:573
  Member 17:
  polymorphic type: function type. See lib: dom.js:574
  Error:
   30:     document.createTreeWalker({}); // invalid
                                     ^^ object literal. This type is incompatible with
  Document. See lib: dom.js:574
  Member 18:
  polymorphic type: function type. See lib: dom.js:575
  Error:
   30:     document.createTreeWalker({}); // invalid
                                     ^^ object literal. This type is incompatible with
  Document. See lib: dom.js:575
  Member 19:
  polymorphic type: function type. See lib: dom.js:576
  Error:
   30:     document.createTreeWalker({}); // invalid
                                     ^^ object literal. This type is incompatible with
  Document. See lib: dom.js:576
  Member 20:
  polymorphic type: function type. See lib: dom.js:577
  Error:
   30:     document.createTreeWalker({}); // invalid
                                     ^^ object literal. This type is incompatible with
  Document. See lib: dom.js:577
  Member 21:
  polymorphic type: function type. See lib: dom.js:578
  Error:
   30:     document.createTreeWalker({}); // invalid
                                     ^^ object literal. This type is incompatible with
  Document. See lib: dom.js:578
  Member 22:
  polymorphic type: function type. See lib: dom.js:579
  Error:
   30:     document.createTreeWalker({}); // invalid
                                     ^^ object literal. This type is incompatible with
  Document. See lib: dom.js:579
  Member 23:
  polymorphic type: function type. See lib: dom.js:580
  Error:
   30:     document.createTreeWalker({}); // invalid
                                     ^^ object literal. This type is incompatible with
  Document. See lib: dom.js:580
  Member 24:
  polymorphic type: function type. See lib: dom.js:581
  Error:
   30:     document.createTreeWalker({}); // invalid
                                     ^^ object literal. This type is incompatible with
  Document. See lib: dom.js:581
  Member 25:
  polymorphic type: function type. See lib: dom.js:582
  Error:
   30:     document.createTreeWalker({}); // invalid
                                     ^^ object literal. This type is incompatible with
  Document. See lib: dom.js:582
  Member 26:
  polymorphic type: function type. See lib: dom.js:594
  Error:
   30:     document.createTreeWalker({}); // invalid
                                     ^^ object literal. This type is incompatible with
  DocumentFragment. See lib: dom.js:594
  Member 27:
  polymorphic type: function type. See lib: dom.js:595
  Error:
   30:     document.createTreeWalker({}); // invalid
                                     ^^ object literal. This type is incompatible with
  DocumentFragment. See lib: dom.js:595
  Member 28:
  polymorphic type: function type. See lib: dom.js:596
  Error:
   30:     document.createTreeWalker({}); // invalid
                                     ^^ object literal. This type is incompatible with
  DocumentFragment. See lib: dom.js:596
  Member 29:
  polymorphic type: function type. See lib: dom.js:597
  Error:
   30:     document.createTreeWalker({}); // invalid
                                     ^^ object literal. This type is incompatible with
  DocumentFragment. See lib: dom.js:597
  Member 30:
  polymorphic type: function type. See lib: dom.js:598
  Error:
   30:     document.createTreeWalker({}); // invalid
                                     ^^ object literal. This type is incompatible with
  DocumentFragment. See lib: dom.js:598
  Member 31:
  polymorphic type: function type. See lib: dom.js:599
  Error:
   30:     document.createTreeWalker({}); // invalid
                                     ^^ object literal. This type is incompatible with
  DocumentFragment. See lib: dom.js:599
  Member 32:
  polymorphic type: function type. See lib: dom.js:600
  Error:
   30:     document.createTreeWalker({}); // invalid
                                     ^^ object literal. This type is incompatible with
  DocumentFragment. See lib: dom.js:600
  Member 33:
  polymorphic type: function type. See lib: dom.js:601
  Error:
   30:     document.createTreeWalker({}); // invalid
                                     ^^ object literal. This type is incompatible with
  DocumentFragment. See lib: dom.js:601
  Member 34:
  polymorphic type: function type. See lib: dom.js:614
  Error:
   30:     document.createTreeWalker({}); // invalid
                                     ^^ object literal. This type is incompatible with
  Node. See lib: dom.js:614
  Member 35:
  polymorphic type: function type. See lib: dom.js:615
  Error:
   30:     document.createTreeWalker({}); // invalid
                                     ^^ object literal. This type is incompatible with
  Node. See lib: dom.js:615
  Member 36:
  polymorphic type: function type. See lib: dom.js:616
  Error:
   30:     document.createTreeWalker({}); // invalid
                                     ^^ object literal. This type is incompatible with
  Node. See lib: dom.js:616
  Member 37:
  polymorphic type: function type. See lib: dom.js:617
  Error:
   30:     document.createTreeWalker({}); // invalid
                                     ^^ object literal. This type is incompatible with
  Node. See lib: dom.js:617
  Member 38:
  polymorphic type: function type. See lib: dom.js:618
  Error:
   30:     document.createTreeWalker({}); // invalid
                                     ^^ object literal. This type is incompatible with
  Node. See lib: dom.js:618
  Member 39:
  polymorphic type: function type. See lib: dom.js:619
  Error:
   30:     document.createTreeWalker({}); // invalid
                                     ^^ object literal. This type is incompatible with
  Node. See lib: dom.js:619
  Member 40:
  polymorphic type: function type. See lib: dom.js:620
  Error:
   30:     document.createTreeWalker({}); // invalid
                                     ^^ object literal. This type is incompatible with
  Node. See lib: dom.js:620
  Member 41:
  polymorphic type: function type. See lib: dom.js:621
  Error:
   30:     document.createTreeWalker({}); // invalid
                                     ^^ object literal. This type is incompatible with
  Node. See lib: dom.js:621
  Member 42:
  polymorphic type: function type. See lib: dom.js:625
  Error:
   30:     document.createTreeWalker({}); // invalid
                                     ^^ object literal. This type is incompatible with
  Node. See lib: dom.js:625
  Member 43:
  polymorphic type: function type. See lib: dom.js:629
  Error:
   30:     document.createTreeWalker({}); // invalid
                                     ^^ object literal. This type is incompatible with
  Node. See lib: dom.js:629

traversal.js:183
183:     document.createNodeIterator(document.body, -1, node => 'accept'); // invalid
                                                                ^^^^^^^^ string. This type is incompatible with
union: typeof typeof-annotation '<<object>>.FILTER_ACCEPT') | typeof typeof-annotation '<<object>>.FILTER_REJECT') | typeof typeof-annotation '<<object>>.FILTER_SKIP'). See lib: dom.js:1751
  Member 1:
  typeof typeof-annotation '<<object>>.FILTER_ACCEPT'). See lib: dom.js:1751
  Error:
  183:     document.createNodeIterator(document.body, -1, node => 'accept'); // invalid
                                                                  ^^^^^^^^ string. This type is incompatible with
  number literal `1`. See lib: dom.js:1751
  Member 2:
  typeof typeof-annotation '<<object>>.FILTER_REJECT'). See lib: dom.js:1752
  Error:
  183:     document.createNodeIterator(document.body, -1, node => 'accept'); // invalid
                                                                  ^^^^^^^^ string. This type is incompatible with
  number literal `2`. See lib: dom.js:1752
  Member 3:
  typeof typeof-annotation '<<object>>.FILTER_SKIP'). See lib: dom.js:1753
  Error:
  183:     document.createNodeIterator(document.body, -1, node => 'accept'); // invalid
                                                                  ^^^^^^^^ string. This type is incompatible with
  number literal `3`. See lib: dom.js:1753

traversal.js:185
185:     document.createNodeIterator(document.body, -1, { accept: node => 'accept' }); // invalid
                                                                          ^^^^^^^^ string. This type is incompatible with
union: typeof typeof-annotation '<<object>>.FILTER_ACCEPT') | typeof typeof-annotation '<<object>>.FILTER_REJECT') | typeof typeof-annotation '<<object>>.FILTER_SKIP'). See lib: dom.js:1751
  Member 1:
  typeof typeof-annotation '<<object>>.FILTER_ACCEPT'). See lib: dom.js:1751
  Error:
  185:     document.createNodeIterator(document.body, -1, { accept: node => 'accept' }); // invalid
                                                                            ^^^^^^^^ string. This type is incompatible with
  number literal `1`. See lib: dom.js:1751
  Member 2:
  typeof typeof-annotation '<<object>>.FILTER_REJECT'). See lib: dom.js:1752
  Error:
  185:     document.createNodeIterator(document.body, -1, { accept: node => 'accept' }); // invalid
                                                                            ^^^^^^^^ string. This type is incompatible with
  number literal `2`. See lib: dom.js:1752
  Member 3:
  typeof typeof-annotation '<<object>>.FILTER_SKIP'). See lib: dom.js:1753
  Error:
  185:     document.createNodeIterator(document.body, -1, { accept: node => 'accept' }); // invalid
                                                                            ^^^^^^^^ string. This type is incompatible with
  number literal `3`. See lib: dom.js:1753

traversal.js:186
186:     document.createNodeIterator(document.body, -1, {}); // invalid
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ call of method `createNodeIterator`. Function cannot be called on any member of intersection type
186:     document.createNodeIterator(document.body, -1, {}); // invalid
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ intersection
  Member 1:
  polymorphic type: function type. See lib: dom.js:527
  Error:
  186:     document.createNodeIterator(document.body, -1, {}); // invalid
                                       ^^^^^^^^^^^^^ HTMLElement. This type is incompatible with
  Attr. See lib: dom.js:527
  Member 2:
  polymorphic type: function type. See lib: dom.js:535
  Error:
  186:     document.createNodeIterator(document.body, -1, {}); // invalid
                                       ^^^^^^^^^^^^^ HTMLElement. This type is incompatible with
  Document. See lib: dom.js:535
  Member 3:
  polymorphic type: function type. See lib: dom.js:536
  Error:
  186:     document.createNodeIterator(document.body, -1, {}); // invalid
                                       ^^^^^^^^^^^^^ HTMLElement. This type is incompatible with
  Document. See lib: dom.js:536
  Member 4:
  polymorphic type: function type. See lib: dom.js:537
  Error:
  186:     document.createNodeIterator(document.body, -1, {}); // invalid
                                       ^^^^^^^^^^^^^ HTMLElement. This type is incompatible with
  Document. See lib: dom.js:537
  Member 5:
  polymorphic type: function type. See lib: dom.js:538
  Error:
  186:     document.createNodeIterator(document.body, -1, {}); // invalid
                                       ^^^^^^^^^^^^^ HTMLElement. This type is incompatible with
  Document. See lib: dom.js:538
  Member 6:
  polymorphic type: function type. See lib: dom.js:539
  Error:
  186:     document.createNodeIterator(document.body, -1, {}); // invalid
                                       ^^^^^^^^^^^^^ HTMLElement. This type is incompatible with
  Document. See lib: dom.js:539
  Member 7:
  polymorphic type: function type. See lib: dom.js:540
  Error:
  186:     document.createNodeIterator(document.body, -1, {}); // invalid
                                       ^^^^^^^^^^^^^ HTMLElement. This type is incompatible with
  Document. See lib: dom.js:540
  Member 8:
  polymorphic type: function type. See lib: dom.js:541
  Error:
  186:     document.createNodeIterator(document.body, -1, {}); // invalid
                                       ^^^^^^^^^^^^^ HTMLElement. This type is incompatible with
  Document. See lib: dom.js:541
  Member 9:
  polymorphic type: function type. See lib: dom.js:542
  Error:
  186:     document.createNodeIterator(document.body, -1, {}); // invalid
                                       ^^^^^^^^^^^^^ HTMLElement. This type is incompatible with
  Document. See lib: dom.js:542
  Member 10:
  polymorphic type: function type. See lib: dom.js:543
  Error:
  186:     document.createNodeIterator(document.body, -1, {}); // invalid
                                       ^^^^^^^^^^^^^ HTMLElement. This type is incompatible with
  Document. See lib: dom.js:543
  Member 11:
  polymorphic type: function type. See lib: dom.js:544
  Error:
  186:     document.createNodeIterator(document.body, -1, {}); // invalid
                                       ^^^^^^^^^^^^^ HTMLElement. This type is incompatible with
  Document. See lib: dom.js:544
  Member 12:
  polymorphic type: function type. See lib: dom.js:545
  Error:
  186:     document.createNodeIterator(document.body, -1, {}); // invalid
                                       ^^^^^^^^^^^^^ HTMLElement. This type is incompatible with
  Document. See lib: dom.js:545
  Member 13:
  polymorphic type: function type. See lib: dom.js:546
  Error:
  186:     document.createNodeIterator(document.body, -1, {}); // invalid
                                       ^^^^^^^^^^^^^ HTMLElement. This type is incompatible with
  Document. See lib: dom.js:546
  Member 14:
  polymorphic type: function type. See lib: dom.js:547
  Error:
  186:     document.createNodeIterator(document.body, -1, {}); // invalid
                                       ^^^^^^^^^^^^^ HTMLElement. This type is incompatible with
  Document. See lib: dom.js:547
  Member 15:
  polymorphic type: function type. See lib: dom.js:548
  Error:
  186:     document.createNodeIterator(document.body, -1, {}); // invalid
                                       ^^^^^^^^^^^^^ HTMLElement. This type is incompatible with
  Document. See lib: dom.js:548
  Member 16:
  polymorphic type: function type. See lib: dom.js:549
  Error:
  186:     document.createNodeIterator(document.body, -1, {}); // invalid
                                       ^^^^^^^^^^^^^ HTMLElement. This type is incompatible with
  Document. See lib: dom.js:549
  Member 17:
  polymorphic type: function type. See lib: dom.js:550
  Error:
  186:     document.createNodeIterator(document.body, -1, {}); // invalid
                                       ^^^^^^^^^^^^^ HTMLElement. This type is incompatible with
  Document. See lib: dom.js:550
  Member 18:
  polymorphic type: function type. See lib: dom.js:551
  Error:
  186:     document.createNodeIterator(document.body, -1, {}); // invalid
                                       ^^^^^^^^^^^^^ HTMLElement. This type is incompatible with
  Document. See lib: dom.js:551
  Member 19:
  polymorphic type: function type. See lib: dom.js:552
  Error:
  186:     document.createNodeIterator(document.body, -1, {}); // invalid
                                       ^^^^^^^^^^^^^ HTMLElement. This type is incompatible with
  Document. See lib: dom.js:552
  Member 20:
  polymorphic type: function type. See lib: dom.js:553
  Error:
  186:     document.createNodeIterator(document.body, -1, {}); // invalid
                                       ^^^^^^^^^^^^^ HTMLElement. This type is incompatible with
  Document. See lib: dom.js:553
  Member 21:
  polymorphic type: function type. See lib: dom.js:554
  Error:
  186:     document.createNodeIterator(document.body, -1, {}); // invalid
                                       ^^^^^^^^^^^^^ HTMLElement. This type is incompatible with
  Document. See lib: dom.js:554
  Member 22:
  polymorphic type: function type. See lib: dom.js:555
  Error:
  186:     document.createNodeIterator(document.body, -1, {}); // invalid
                                       ^^^^^^^^^^^^^ HTMLElement. This type is incompatible with
  Document. See lib: dom.js:555
  Member 23:
  polymorphic type: function type. See lib: dom.js:556
  Error:
  186:     document.createNodeIterator(document.body, -1, {}); // invalid
                                       ^^^^^^^^^^^^^ HTMLElement. This type is incompatible with
  Document. See lib: dom.js:556
  Member 24:
  polymorphic type: function type. See lib: dom.js:557
  Error:
  186:     document.createNodeIterator(document.body, -1, {}); // invalid
                                       ^^^^^^^^^^^^^ HTMLElement. This type is incompatible with
  Document. See lib: dom.js:557
  Member 25:
  polymorphic type: function type. See lib: dom.js:558
  Error:
  186:     document.createNodeIterator(document.body, -1, {}); // invalid
                                       ^^^^^^^^^^^^^ HTMLElement. This type is incompatible with
  Document. See lib: dom.js:558
  Member 26:
  polymorphic type: function type. See lib: dom.js:586
  Error:
  186:     document.createNodeIterator(document.body, -1, {}); // invalid
                                       ^^^^^^^^^^^^^ HTMLElement. This type is incompatible with
  DocumentFragment. See lib: dom.js:586
  Member 27:
  polymorphic type: function type. See lib: dom.js:587
  Error:
  186:     document.createNodeIterator(document.body, -1, {}); // invalid
                                       ^^^^^^^^^^^^^ HTMLElement. This type is incompatible with
  DocumentFragment. See lib: dom.js:587
  Member 28:
  polymorphic type: function type. See lib: dom.js:588
  Error:
  186:     document.createNodeIterator(document.body, -1, {}); // invalid
                                       ^^^^^^^^^^^^^ HTMLElement. This type is incompatible with
  DocumentFragment. See lib: dom.js:588
  Member 29:
  polymorphic type: function type. See lib: dom.js:589
  Error:
  186:     document.createNodeIterator(document.body, -1, {}); // invalid
                                       ^^^^^^^^^^^^^ HTMLElement. This type is incompatible with
  DocumentFragment. See lib: dom.js:589
  Member 30:
  polymorphic type: function type. See lib: dom.js:590
  Error:
  186:     document.createNodeIterator(document.body, -1, {}); // invalid
                                       ^^^^^^^^^^^^^ HTMLElement. This type is incompatible with
  DocumentFragment. See lib: dom.js:590
  Member 31:
  polymorphic type: function type. See lib: dom.js:591
  Error:
  186:     document.createNodeIterator(document.body, -1, {}); // invalid
                                       ^^^^^^^^^^^^^ HTMLElement. This type is incompatible with
  DocumentFragment. See lib: dom.js:591
  Member 32:
  polymorphic type: function type. See lib: dom.js:592
  Error:
  186:     document.createNodeIterator(document.body, -1, {}); // invalid
                                       ^^^^^^^^^^^^^ HTMLElement. This type is incompatible with
  DocumentFragment. See lib: dom.js:592
  Member 33:
  polymorphic type: function type. See lib: dom.js:593
  Error:
  186:     document.createNodeIterator(document.body, -1, {}); // invalid
                                       ^^^^^^^^^^^^^ HTMLElement. This type is incompatible with
  DocumentFragment. See lib: dom.js:593
  Member 34:
  polymorphic type: function type. See lib: dom.js:606
  Error:
  186:     document.createNodeIterator(document.body, -1, {}); // invalid
                                                      ^^ number. Expected number literal `1`, got `-1` instead
  number literal `1`. See lib: dom.js:606
  Member 35:
  polymorphic type: function type. See lib: dom.js:607
  Error:
  186:     document.createNodeIterator(document.body, -1, {}); // invalid
                                                      ^^ number. Expected number literal `4`, got `-1` instead
  number literal `4`. See lib: dom.js:607
  Member 36:
  polymorphic type: function type. See lib: dom.js:608
  Error:
  186:     document.createNodeIterator(document.body, -1, {}); // invalid
                                                      ^^ number. Expected number literal `5`, got `-1` instead
  number literal `5`. See lib: dom.js:608
  Member 37:
  polymorphic type: function type. See lib: dom.js:609
  Error:
  186:     document.createNodeIterator(document.body, -1, {}); // invalid
                                                      ^^ number. Expected number literal `128`, got `-1` instead
  number literal `128`. See lib: dom.js:609
  Member 38:
  polymorphic type: function type. See lib: dom.js:610
  Error:
  186:     document.createNodeIterator(document.body, -1, {}); // invalid
                                                      ^^ number. Expected number literal `129`, got `-1` instead
  number literal `129`. See lib: dom.js:610
  Member 39:
  polymorphic type: function type. See lib: dom.js:611
  Error:
  186:     document.createNodeIterator(document.body, -1, {}); // invalid
                                                      ^^ number. Expected number literal `132`, got `-1` instead
  number literal `132`. See lib: dom.js:611
  Member 40:
  polymorphic type: function type. See lib: dom.js:612
  Error:
  186:     document.createNodeIterator(document.body, -1, {}); // invalid
                                                      ^^ number. Expected number literal `133`, got `-1` instead
  number literal `133`. See lib: dom.js:612
  Member 41:
  polymorphic type: function type. See lib: dom.js:613
  Error:
  186:     document.createNodeIterator(document.body, -1, {}); // invalid
                                                          ^^ object literal. This type is incompatible with
  union: NodeFilterCallback | object type. See lib: dom.js:613
    Member 1:
    NodeFilterCallback. See lib: dom.js:1755
    Error:
    function type. Callable signature not found in. See lib: dom.js:1755
    186:     document.createNodeIterator(document.body, -1, {}); // invalid
                                                            ^^ object literal
    Member 2:
    object type. See lib: dom.js:1755
    Error:
    property `accept`. Property not found in. See lib: dom.js:1755
    186:     document.createNodeIterator(document.body, -1, {}); // invalid
                                                            ^^ object literal
  Member 42:
  polymorphic type: function type. See lib: dom.js:624
  Error:
  186:     document.createNodeIterator(document.body, -1, {}); // invalid
                                       ^^^^^^^^^^^^^ HTMLElement. This type is incompatible with
  Document. See lib: dom.js:624
  Member 43:
  polymorphic type: function type. See lib: dom.js:628
  Error:
  186:     document.createNodeIterator(document.body, -1, {}); // invalid
                                                      ^^ number. This type is incompatible with
  undefined. See lib: dom.js:628

traversal.js:190
190:     document.createTreeWalker(document.body, -1, node => 'accept'); // invalid
                                                              ^^^^^^^^ string. This type is incompatible with
union: typeof typeof-annotation '<<object>>.FILTER_ACCEPT') | typeof typeof-annotation '<<object>>.FILTER_REJECT') | typeof typeof-annotation '<<object>>.FILTER_SKIP'). See lib: dom.js:1751
  Member 1:
  typeof typeof-annotation '<<object>>.FILTER_ACCEPT'). See lib: dom.js:1751
  Error:
  190:     document.createTreeWalker(document.body, -1, node => 'accept'); // invalid
                                                                ^^^^^^^^ string. This type is incompatible with
  number literal `1`. See lib: dom.js:1751
  Member 2:
  typeof typeof-annotation '<<object>>.FILTER_REJECT'). See lib: dom.js:1752
  Error:
  190:     document.createTreeWalker(document.body, -1, node => 'accept'); // invalid
                                                                ^^^^^^^^ string. This type is incompatible with
  number literal `2`. See lib: dom.js:1752
  Member 3:
  typeof typeof-annotation '<<object>>.FILTER_SKIP'). See lib: dom.js:1753
  Error:
  190:     document.createTreeWalker(document.body, -1, node => 'accept'); // invalid
                                                                ^^^^^^^^ string. This type is incompatible with
  number literal `3`. See lib: dom.js:1753

traversal.js:192
192:     document.createTreeWalker(document.body, -1, { accept: node => 'accept' }); // invalid
                                                                        ^^^^^^^^ string. This type is incompatible with
union: typeof typeof-annotation '<<object>>.FILTER_ACCEPT') | typeof typeof-annotation '<<object>>.FILTER_REJECT') | typeof typeof-annotation '<<object>>.FILTER_SKIP'). See lib: dom.js:1751
  Member 1:
  typeof typeof-annotation '<<object>>.FILTER_ACCEPT'). See lib: dom.js:1751
  Error:
  192:     document.createTreeWalker(document.body, -1, { accept: node => 'accept' }); // invalid
                                                                          ^^^^^^^^ string. This type is incompatible with
  number literal `1`. See lib: dom.js:1751
  Member 2:
  typeof typeof-annotation '<<object>>.FILTER_REJECT'). See lib: dom.js:1752
  Error:
  192:     document.createTreeWalker(document.body, -1, { accept: node => 'accept' }); // invalid
                                                                          ^^^^^^^^ string. This type is incompatible with
  number literal `2`. See lib: dom.js:1752
  Member 3:
  typeof typeof-annotation '<<object>>.FILTER_SKIP'). See lib: dom.js:1753
  Error:
  192:     document.createTreeWalker(document.body, -1, { accept: node => 'accept' }); // invalid
                                                                          ^^^^^^^^ string. This type is incompatible with
  number literal `3`. See lib: dom.js:1753

traversal.js:193
193:     document.createTreeWalker(document.body, -1, {}); // invalid
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ call of method `createTreeWalker`. Function cannot be called on any member of intersection type
193:     document.createTreeWalker(document.body, -1, {}); // invalid
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ intersection
  Member 1:
  polymorphic type: function type. See lib: dom.js:528
  Error:
  193:     document.createTreeWalker(document.body, -1, {}); // invalid
                                     ^^^^^^^^^^^^^ HTMLElement. This type is incompatible with
  Attr. See lib: dom.js:528
  Member 2:
  polymorphic type: function type. See lib: dom.js:559
  Error:
  193:     document.createTreeWalker(document.body, -1, {}); // invalid
                                     ^^^^^^^^^^^^^ HTMLElement. This type is incompatible with
  Document. See lib: dom.js:559
  Member 3:
  polymorphic type: function type. See lib: dom.js:560
  Error:
  193:     document.createTreeWalker(document.body, -1, {}); // invalid
                                     ^^^^^^^^^^^^^ HTMLElement. This type is incompatible with
  Document. See lib: dom.js:560
  Member 4:
  polymorphic type: function type. See lib: dom.js:561
  Error:
  193:     document.createTreeWalker(document.body, -1, {}); // invalid
                                     ^^^^^^^^^^^^^ HTMLElement. This type is incompatible with
  Document. See lib: dom.js:561
  Member 5:
  polymorphic type: function type. See lib: dom.js:562
  Error:
  193:     document.createTreeWalker(document.body, -1, {}); // invalid
                                     ^^^^^^^^^^^^^ HTMLElement. This type is incompatible with
  Document. See lib: dom.js:562
  Member 6:
  polymorphic type: function type. See lib: dom.js:563
  Error:
  193:     document.createTreeWalker(document.body, -1, {}); // invalid
                                     ^^^^^^^^^^^^^ HTMLElement. This type is incompatible with
  Document. See lib: dom.js:563
  Member 7:
  polymorphic type: function type. See lib: dom.js:564
  Error:
  193:     document.createTreeWalker(document.body, -1, {}); // invalid
                                     ^^^^^^^^^^^^^ HTMLElement. This type is incompatible with
  Document. See lib: dom.js:564
  Member 8:
  polymorphic type: function type. See lib: dom.js:565
  Error:
  193:     document.createTreeWalker(document.body, -1, {}); // invalid
                                     ^^^^^^^^^^^^^ HTMLElement. This type is incompatible with
  Document. See lib: dom.js:565
  Member 9:
  polymorphic type: function type. See lib: dom.js:566
  Error:
  193:     document.createTreeWalker(document.body, -1, {}); // invalid
                                     ^^^^^^^^^^^^^ HTMLElement. This type is incompatible with
  Document. See lib: dom.js:566
  Member 10:
  polymorphic type: function type. See lib: dom.js:567
  Error:
  193:     document.createTreeWalker(document.body, -1, {}); // invalid
                                     ^^^^^^^^^^^^^ HTMLElement. This type is incompatible with
  Document. See lib: dom.js:567
  Member 11:
  polymorphic type: function type. See lib: dom.js:568
  Error:
  193:     document.createTreeWalker(document.body, -1, {}); // invalid
                                     ^^^^^^^^^^^^^ HTMLElement. This type is incompatible with
  Document. See lib: dom.js:568
  Member 12:
  polymorphic type: function type. See lib: dom.js:569
  Error:
  193:     document.createTreeWalker(document.body, -1, {}); // invalid
                                     ^^^^^^^^^^^^^ HTMLElement. This type is incompatible with
  Document. See lib: dom.js:569
  Member 13:
  polymorphic type: function type. See lib: dom.js:570
  Error:
  193:     document.createTreeWalker(document.body, -1, {}); // invalid
                                     ^^^^^^^^^^^^^ HTMLElement. This type is incompatible with
  Document. See lib: dom.js:570
  Member 14:
  polymorphic type: function type. See lib: dom.js:571
  Error:
  193:     document.createTreeWalker(document.body, -1, {}); // invalid
                                     ^^^^^^^^^^^^^ HTMLElement. This type is incompatible with
  Document. See lib: dom.js:571
  Member 15:
  polymorphic type: function type. See lib: dom.js:572
  Error:
  193:     document.createTreeWalker(document.body, -1, {}); // invalid
                                     ^^^^^^^^^^^^^ HTMLElement. This type is incompatible with
  Document. See lib: dom.js:572
  Member 16:
  polymorphic type: function type. See lib: dom.js:573
  Error:
  193:     document.createTreeWalker(document.body, -1, {}); // invalid
                                     ^^^^^^^^^^^^^ HTMLElement. This type is incompatible with
  Document. See lib: dom.js:573
  Member 17:
  polymorphic type: function type. See lib: dom.js:574
  Error:
  193:     document.createTreeWalker(document.body, -1, {}); // invalid
                                     ^^^^^^^^^^^^^ HTMLElement. This type is incompatible with
  Document. See lib: dom.js:574
  Member 18:
  polymorphic type: function type. See lib: dom.js:575
  Error:
  193:     document.createTreeWalker(document.body, -1, {}); // invalid
                                     ^^^^^^^^^^^^^ HTMLElement. This type is incompatible with
  Document. See lib: dom.js:575
  Member 19:
  polymorphic type: function type. See lib: dom.js:576
  Error:
  193:     document.createTreeWalker(document.body, -1, {}); // invalid
                                     ^^^^^^^^^^^^^ HTMLElement. This type is incompatible with
  Document. See lib: dom.js:576
  Member 20:
  polymorphic type: function type. See lib: dom.js:577
  Error:
  193:     document.createTreeWalker(document.body, -1, {}); // invalid
                                     ^^^^^^^^^^^^^ HTMLElement. This type is incompatible with
  Document. See lib: dom.js:577
  Member 21:
  polymorphic type: function type. See lib: dom.js:578
  Error:
  193:     document.createTreeWalker(document.body, -1, {}); // invalid
                                     ^^^^^^^^^^^^^ HTMLElement. This type is incompatible with
  Document. See lib: dom.js:578
  Member 22:
  polymorphic type: function type. See lib: dom.js:579
  Error:
  193:     document.createTreeWalker(document.body, -1, {}); // invalid
                                     ^^^^^^^^^^^^^ HTMLElement. This type is incompatible with
  Document. See lib: dom.js:579
  Member 23:
  polymorphic type: function type. See lib: dom.js:580
  Error:
  193:     document.createTreeWalker(document.body, -1, {}); // invalid
                                     ^^^^^^^^^^^^^ HTMLElement. This type is incompatible with
  Document. See lib: dom.js:580
  Member 24:
  polymorphic type: function type. See lib: dom.js:581
  Error:
  193:     document.createTreeWalker(document.body, -1, {}); // invalid
                                     ^^^^^^^^^^^^^ HTMLElement. This type is incompatible with
  Document. See lib: dom.js:581
  Member 25:
  polymorphic type: function type. See lib: dom.js:582
  Error:
  193:     document.createTreeWalker(document.body, -1, {}); // invalid
                                     ^^^^^^^^^^^^^ HTMLElement. This type is incompatible with
  Document. See lib: dom.js:582
  Member 26:
  polymorphic type: function type. See lib: dom.js:594
  Error:
  193:     document.createTreeWalker(document.body, -1, {}); // invalid
                                     ^^^^^^^^^^^^^ HTMLElement. This type is incompatible with
  DocumentFragment. See lib: dom.js:594
  Member 27:
  polymorphic type: function type. See lib: dom.js:595
  Error:
  193:     document.createTreeWalker(document.body, -1, {}); // invalid
                                     ^^^^^^^^^^^^^ HTMLElement. This type is incompatible with
  DocumentFragment. See lib: dom.js:595
  Member 28:
  polymorphic type: function type. See lib: dom.js:596
  Error:
  193:     document.createTreeWalker(document.body, -1, {}); // invalid
                                     ^^^^^^^^^^^^^ HTMLElement. This type is incompatible with
  DocumentFragment. See lib: dom.js:596
  Member 29:
  polymorphic type: function type. See lib: dom.js:597
  Error:
  193:     document.createTreeWalker(document.body, -1, {}); // invalid
                                     ^^^^^^^^^^^^^ HTMLElement. This type is incompatible with
  DocumentFragment. See lib: dom.js:597
  Member 30:
  polymorphic type: function type. See lib: dom.js:598
  Error:
  193:     document.createTreeWalker(document.body, -1, {}); // invalid
                                     ^^^^^^^^^^^^^ HTMLElement. This type is incompatible with
  DocumentFragment. See lib: dom.js:598
  Member 31:
  polymorphic type: function type. See lib: dom.js:599
  Error:
  193:     document.createTreeWalker(document.body, -1, {}); // invalid
                                     ^^^^^^^^^^^^^ HTMLElement. This type is incompatible with
  DocumentFragment. See lib: dom.js:599
  Member 32:
  polymorphic type: function type. See lib: dom.js:600
  Error:
  193:     document.createTreeWalker(document.body, -1, {}); // invalid
                                     ^^^^^^^^^^^^^ HTMLElement. This type is incompatible with
  DocumentFragment. See lib: dom.js:600
  Member 33:
  polymorphic type: function type. See lib: dom.js:601
  Error:
  193:     document.createTreeWalker(document.body, -1, {}); // invalid
                                     ^^^^^^^^^^^^^ HTMLElement. This type is incompatible with
  DocumentFragment. See lib: dom.js:601
  Member 34:
  polymorphic type: function type. See lib: dom.js:614
  Error:
  193:     document.createTreeWalker(document.body, -1, {}); // invalid
                                                    ^^ number. Expected number literal `1`, got `-1` instead
  number literal `1`. See lib: dom.js:614
  Member 35:
  polymorphic type: function type. See lib: dom.js:615
  Error:
  193:     document.createTreeWalker(document.body, -1, {}); // invalid
                                                    ^^ number. Expected number literal `4`, got `-1` instead
  number literal `4`. See lib: dom.js:615
  Member 36:
  polymorphic type: function type. See lib: dom.js:616
  Error:
  193:     document.createTreeWalker(document.body, -1, {}); // invalid
                                                    ^^ number. Expected number literal `5`, got `-1` instead
  number literal `5`. See lib: dom.js:616
  Member 37:
  polymorphic type: function type. See lib: dom.js:617
  Error:
  193:     document.createTreeWalker(document.body, -1, {}); // invalid
                                                    ^^ number. Expected number literal `128`, got `-1` instead
  number literal `128`. See lib: dom.js:617
  Member 38:
  polymorphic type: function type. See lib: dom.js:618
  Error:
  193:     document.createTreeWalker(document.body, -1, {}); // invalid
                                                    ^^ number. Expected number literal `129`, got `-1` instead
  number literal `129`. See lib: dom.js:618
  Member 39:
  polymorphic type: function type. See lib: dom.js:619
  Error:
  193:     document.createTreeWalker(document.body, -1, {}); // invalid
                                                    ^^ number. Expected number literal `132`, got `-1` instead
  number literal `132`. See lib: dom.js:619
  Member 40:
  polymorphic type: function type. See lib: dom.js:620
  Error:
  193:     document.createTreeWalker(document.body, -1, {}); // invalid
                                                    ^^ number. Expected number literal `133`, got `-1` instead
  number literal `133`. See lib: dom.js:620
  Member 41:
  polymorphic type: function type. See lib: dom.js:621
  Error:
  193:     document.createTreeWalker(document.body, -1, {}); // invalid
                                                        ^^ object literal. This type is incompatible with
  union: NodeFilterCallback | object type. See lib: dom.js:621
    Member 1:
    NodeFilterCallback. See lib: dom.js:1755
    Error:
    function type. Callable signature not found in. See lib: dom.js:1755
    193:     document.createTreeWalker(document.body, -1, {}); // invalid
                                                          ^^ object literal
    Member 2:
    object type. See lib: dom.js:1755
    Error:
    property `accept`. Property not found in. See lib: dom.js:1755
    193:     document.createTreeWalker(document.body, -1, {}); // invalid
                                                          ^^ object literal
  Member 42:
  polymorphic type: function type. See lib: dom.js:625
  Error:
  193:     document.createTreeWalker(document.body, -1, {}); // invalid
                                                        ^^ object literal. This type is incompatible with
  union: NodeFilterCallback | object type. See lib: dom.js:625
    Member 1:
    NodeFilterCallback. See lib: dom.js:1755
    Error:
    function type. Callable signature not found in. See lib: dom.js:1755
    193:     document.createTreeWalker(document.body, -1, {}); // invalid
                                                          ^^ object literal
    Member 2:
    object type. See lib: dom.js:1755
    Error:
    property `accept`. Property not found in. See lib: dom.js:1755
    193:     document.createTreeWalker(document.body, -1, {}); // invalid
                                                          ^^ object literal
  Member 43:
  polymorphic type: function type. See lib: dom.js:629
  Error:
  193:     document.createTreeWalker(document.body, -1, {}); // invalid
                                                    ^^ number. This type is incompatible with
  undefined. See lib: dom.js:629


Found 21 errors
