CanvasRenderingContext2D.js:11
 11:     ctx.moveTo('0', '1');  // error: should be numbers
         ^^^^^^^^^^^^^^^^^^^^ call of method `moveTo`
 11:     ctx.moveTo('0', '1');  // error: should be numbers
                    ^^^ string. This type is incompatible with
number. See lib: dom.js:864

CanvasRenderingContext2D.js:11
 11:     ctx.moveTo('0', '1');  // error: should be numbers
         ^^^^^^^^^^^^^^^^^^^^ call of method `moveTo`
 11:     ctx.moveTo('0', '1');  // error: should be numbers
                         ^^^ string. This type is incompatible with
number. See lib: dom.js:864

Element.js:14
 14:     element.scrollIntoView({ behavior: 'invalid' });
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ call of method `scrollIntoView`
 14:     element.scrollIntoView({ behavior: 'invalid' });
                                ^^^^^^^^^^^^^^^^^^^^^^^ object literal. This type is incompatible with
union: boolean | object type. See lib: dom.js:601
  Member 1:
  boolean. See lib: dom.js:601
  Error:
   14:     element.scrollIntoView({ behavior: 'invalid' });
                                  ^^^^^^^^^^^^^^^^^^^^^^^ object literal. This type is incompatible with
  boolean. See lib: dom.js:601
  Member 2:
  object type. See lib: dom.js:601
  Error:
   14:     element.scrollIntoView({ behavior: 'invalid' });
                                              ^^^^^^^^^ string. This type is incompatible with
  string enum. See lib: dom.js:601

Element.js:15
 15:     element.scrollIntoView({ block: 'invalid' });
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ call of method `scrollIntoView`
 15:     element.scrollIntoView({ block: 'invalid' });
                                ^^^^^^^^^^^^^^^^^^^^ object literal. This type is incompatible with
union: boolean | object type. See lib: dom.js:601
  Member 1:
  boolean. See lib: dom.js:601
  Error:
   15:     element.scrollIntoView({ block: 'invalid' });
                                  ^^^^^^^^^^^^^^^^^^^^ object literal. This type is incompatible with
  boolean. See lib: dom.js:601
  Member 2:
  object type. See lib: dom.js:601
  Error:
   15:     element.scrollIntoView({ block: 'invalid' });
                                           ^^^^^^^^^ string. This type is incompatible with
  string enum. See lib: dom.js:601

Element.js:16
 16:     element.scrollIntoView(1);
         ^^^^^^^^^^^^^^^^^^^^^^^^^ call of method `scrollIntoView`
 16:     element.scrollIntoView(1);
                                ^ number. This type is incompatible with
union: boolean | object type. See lib: dom.js:601
  Member 1:
  boolean. See lib: dom.js:601
  Error:
   16:     element.scrollIntoView(1);
                                  ^ number. This type is incompatible with
  boolean. See lib: dom.js:601
  Member 2:
  object type. See lib: dom.js:601
  Error:
   16:     element.scrollIntoView(1);
                                  ^ number. This type is incompatible with
  object type. See lib: dom.js:601

HTMLElement.js:14
 14:     element.scrollIntoView({ behavior: 'invalid' });
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ call of method `scrollIntoView`
 14:     element.scrollIntoView({ behavior: 'invalid' });
                                ^^^^^^^^^^^^^^^^^^^^^^^ object literal. This type is incompatible with
union: boolean | object type. See lib: dom.js:601
  Member 1:
  boolean. See lib: dom.js:601
  Error:
   14:     element.scrollIntoView({ behavior: 'invalid' });
                                  ^^^^^^^^^^^^^^^^^^^^^^^ object literal. This type is incompatible with
  boolean. See lib: dom.js:601
  Member 2:
  object type. See lib: dom.js:601
  Error:
   14:     element.scrollIntoView({ behavior: 'invalid' });
                                              ^^^^^^^^^ string. This type is incompatible with
  string enum. See lib: dom.js:601

HTMLElement.js:15
 15:     element.scrollIntoView({ block: 'invalid' });
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ call of method `scrollIntoView`
 15:     element.scrollIntoView({ block: 'invalid' });
                                ^^^^^^^^^^^^^^^^^^^^ object literal. This type is incompatible with
union: boolean | object type. See lib: dom.js:601
  Member 1:
  boolean. See lib: dom.js:601
  Error:
   15:     element.scrollIntoView({ block: 'invalid' });
                                  ^^^^^^^^^^^^^^^^^^^^ object literal. This type is incompatible with
  boolean. See lib: dom.js:601
  Member 2:
  object type. See lib: dom.js:601
  Error:
   15:     element.scrollIntoView({ block: 'invalid' });
                                           ^^^^^^^^^ string. This type is incompatible with
  string enum. See lib: dom.js:601

HTMLElement.js:16
 16:     element.scrollIntoView(1);
         ^^^^^^^^^^^^^^^^^^^^^^^^^ call of method `scrollIntoView`
 16:     element.scrollIntoView(1);
                                ^ number. This type is incompatible with
union: boolean | object type. See lib: dom.js:601
  Member 1:
  boolean. See lib: dom.js:601
  Error:
   16:     element.scrollIntoView(1);
                                  ^ number. This type is incompatible with
  boolean. See lib: dom.js:601
  Member 2:
  object type. See lib: dom.js:601
  Error:
   16:     element.scrollIntoView(1);
                                  ^ number. This type is incompatible with
  object type. See lib: dom.js:601

eventtarget.js:9
  9:     (target.attachEvent('foo', listener): void); // invalid, may be undefined
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ call of method `attachEvent`. Function cannot be called on possibly undefined value
  9:     (target.attachEvent('foo', listener): void); // invalid, may be undefined
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ undefined

eventtarget.js:16
 16:     (target.detachEvent('foo', listener): void); // invalid, may be undefined
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ call of method `detachEvent`. Function cannot be called on possibly undefined value
 16:     (target.detachEvent('foo', listener): void); // invalid, may be undefined
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ undefined

path2d.js:9
  9:     (path.arcTo(0, 0, 0, 0, 10, '20', 5): void); // invalid
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ call of method `arcTo`
  9:     (path.arcTo(0, 0, 0, 0, 10, '20', 5): void); // invalid
                                     ^^^^ string. This type is incompatible with
union: number | undefined. See lib: dom.js:739
  Member 1:
  number. See lib: dom.js:739
  Error:
    9:     (path.arcTo(0, 0, 0, 0, 10, '20', 5): void); // invalid
                                       ^^^^ string. This type is incompatible with
  number. See lib: dom.js:739
  Member 2:
  undefined. See lib: dom.js:738
  Error:
    9:     (path.arcTo(0, 0, 0, 0, 10, '20', 5): void); // invalid
                                       ^^^^ string. This type is incompatible with
  undefined. See lib: dom.js:738

traversal.js:26
 26:     document.createNodeIterator({}); // invalid
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ call of method `createNodeIterator`. Function cannot be called on any member of intersection type
 26:     document.createNodeIterator({}); // invalid
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ intersection
  Member 1:
  polymorphic type: function type. See lib: dom.js:379
  Error:
   26:     document.createNodeIterator({}); // invalid
                                       ^^ object literal. This type is incompatible with
  Attr. See lib: dom.js:379
  Member 2:
  polymorphic type: function type. See lib: dom.js:387
  Error:
   26:     document.createNodeIterator({}); // invalid
                                       ^^ object literal. This type is incompatible with
  Document. See lib: dom.js:387
  Member 3:
  polymorphic type: function type. See lib: dom.js:388
  Error:
   26:     document.createNodeIterator({}); // invalid
                                       ^^ object literal. This type is incompatible with
  Document. See lib: dom.js:388
  Member 4:
  polymorphic type: function type. See lib: dom.js:389
  Error:
   26:     document.createNodeIterator({}); // invalid
                                       ^^ object literal. This type is incompatible with
  Document. See lib: dom.js:389
  Member 5:
  polymorphic type: function type. See lib: dom.js:390
  Error:
   26:     document.createNodeIterator({}); // invalid
                                       ^^ object literal. This type is incompatible with
  Document. See lib: dom.js:390
  Member 6:
  polymorphic type: function type. See lib: dom.js:391
  Error:
   26:     document.createNodeIterator({}); // invalid
                                       ^^ object literal. This type is incompatible with
  Document. See lib: dom.js:391
  Member 7:
  polymorphic type: function type. See lib: dom.js:392
  Error:
   26:     document.createNodeIterator({}); // invalid
                                       ^^ object literal. This type is incompatible with
  Document. See lib: dom.js:392
  Member 8:
  polymorphic type: function type. See lib: dom.js:393
  Error:
   26:     document.createNodeIterator({}); // invalid
                                       ^^ object literal. This type is incompatible with
  Document. See lib: dom.js:393
  Member 9:
  polymorphic type: function type. See lib: dom.js:394
  Error:
   26:     document.createNodeIterator({}); // invalid
                                       ^^ object literal. This type is incompatible with
  Document. See lib: dom.js:394
  Member 10:
  polymorphic type: function type. See lib: dom.js:395
  Error:
   26:     document.createNodeIterator({}); // invalid
                                       ^^ object literal. This type is incompatible with
  Document. See lib: dom.js:395
  Member 11:
  polymorphic type: function type. See lib: dom.js:396
  Error:
   26:     document.createNodeIterator({}); // invalid
                                       ^^ object literal. This type is incompatible with
  Document. See lib: dom.js:396
  Member 12:
  polymorphic type: function type. See lib: dom.js:397
  Error:
   26:     document.createNodeIterator({}); // invalid
                                       ^^ object literal. This type is incompatible with
  Document. See lib: dom.js:397
  Member 13:
  polymorphic type: function type. See lib: dom.js:398
  Error:
   26:     document.createNodeIterator({}); // invalid
                                       ^^ object literal. This type is incompatible with
  Document. See lib: dom.js:398
  Member 14:
  polymorphic type: function type. See lib: dom.js:399
  Error:
   26:     document.createNodeIterator({}); // invalid
                                       ^^ object literal. This type is incompatible with
  Document. See lib: dom.js:399
  Member 15:
  polymorphic type: function type. See lib: dom.js:400
  Error:
   26:     document.createNodeIterator({}); // invalid
                                       ^^ object literal. This type is incompatible with
  Document. See lib: dom.js:400
  Member 16:
  polymorphic type: function type. See lib: dom.js:401
  Error:
   26:     document.createNodeIterator({}); // invalid
                                       ^^ object literal. This type is incompatible with
  Document. See lib: dom.js:401
  Member 17:
  polymorphic type: function type. See lib: dom.js:402
  Error:
   26:     document.createNodeIterator({}); // invalid
                                       ^^ object literal. This type is incompatible with
  Document. See lib: dom.js:402
  Member 18:
  polymorphic type: function type. See lib: dom.js:403
  Error:
   26:     document.createNodeIterator({}); // invalid
                                       ^^ object literal. This type is incompatible with
  Document. See lib: dom.js:403
  Member 19:
  polymorphic type: function type. See lib: dom.js:404
  Error:
   26:     document.createNodeIterator({}); // invalid
                                       ^^ object literal. This type is incompatible with
  Document. See lib: dom.js:404
  Member 20:
  polymorphic type: function type. See lib: dom.js:405
  Error:
   26:     document.createNodeIterator({}); // invalid
                                       ^^ object literal. This type is incompatible with
  Document. See lib: dom.js:405
  Member 21:
  polymorphic type: function type. See lib: dom.js:406
  Error:
   26:     document.createNodeIterator({}); // invalid
                                       ^^ object literal. This type is incompatible with
  Document. See lib: dom.js:406
  Member 22:
  polymorphic type: function type. See lib: dom.js:407
  Error:
   26:     document.createNodeIterator({}); // invalid
                                       ^^ object literal. This type is incompatible with
  Document. See lib: dom.js:407
  Member 23:
  polymorphic type: function type. See lib: dom.js:408
  Error:
   26:     document.createNodeIterator({}); // invalid
                                       ^^ object literal. This type is incompatible with
  Document. See lib: dom.js:408
  Member 24:
  polymorphic type: function type. See lib: dom.js:409
  Error:
   26:     document.createNodeIterator({}); // invalid
                                       ^^ object literal. This type is incompatible with
  Document. See lib: dom.js:409
  Member 25:
  polymorphic type: function type. See lib: dom.js:410
  Error:
   26:     document.createNodeIterator({}); // invalid
                                       ^^ object literal. This type is incompatible with
  Document. See lib: dom.js:410
  Member 26:
  polymorphic type: function type. See lib: dom.js:438
  Error:
   26:     document.createNodeIterator({}); // invalid
                                       ^^ object literal. This type is incompatible with
  DocumentFragment. See lib: dom.js:438
  Member 27:
  polymorphic type: function type. See lib: dom.js:439
  Error:
   26:     document.createNodeIterator({}); // invalid
                                       ^^ object literal. This type is incompatible with
  DocumentFragment. See lib: dom.js:439
  Member 28:
  polymorphic type: function type. See lib: dom.js:440
  Error:
   26:     document.createNodeIterator({}); // invalid
                                       ^^ object literal. This type is incompatible with
  DocumentFragment. See lib: dom.js:440
  Member 29:
  polymorphic type: function type. See lib: dom.js:441
  Error:
   26:     document.createNodeIterator({}); // invalid
                                       ^^ object literal. This type is incompatible with
  DocumentFragment. See lib: dom.js:441
  Member 30:
  polymorphic type: function type. See lib: dom.js:442
  Error:
   26:     document.createNodeIterator({}); // invalid
                                       ^^ object literal. This type is incompatible with
  DocumentFragment. See lib: dom.js:442
  Member 31:
  polymorphic type: function type. See lib: dom.js:443
  Error:
   26:     document.createNodeIterator({}); // invalid
                                       ^^ object literal. This type is incompatible with
  DocumentFragment. See lib: dom.js:443
  Member 32:
  polymorphic type: function type. See lib: dom.js:444
  Error:
   26:     document.createNodeIterator({}); // invalid
                                       ^^ object literal. This type is incompatible with
  DocumentFragment. See lib: dom.js:444
  Member 33:
  polymorphic type: function type. See lib: dom.js:445
  Error:
   26:     document.createNodeIterator({}); // invalid
                                       ^^ object literal. This type is incompatible with
  DocumentFragment. See lib: dom.js:445
  Member 34:
  polymorphic type: function type. See lib: dom.js:458
  Error:
   26:     document.createNodeIterator({}); // invalid
                                       ^^ object literal. This type is incompatible with
  Node. See lib: dom.js:458
  Member 35:
  polymorphic type: function type. See lib: dom.js:459
  Error:
   26:     document.createNodeIterator({}); // invalid
                                       ^^ object literal. This type is incompatible with
  Node. See lib: dom.js:459
  Member 36:
  polymorphic type: function type. See lib: dom.js:460
  Error:
   26:     document.createNodeIterator({}); // invalid
                                       ^^ object literal. This type is incompatible with
  Node. See lib: dom.js:460
  Member 37:
  polymorphic type: function type. See lib: dom.js:461
  Error:
   26:     document.createNodeIterator({}); // invalid
                                       ^^ object literal. This type is incompatible with
  Node. See lib: dom.js:461
  Member 38:
  polymorphic type: function type. See lib: dom.js:462
  Error:
   26:     document.createNodeIterator({}); // invalid
                                       ^^ object literal. This type is incompatible with
  Node. See lib: dom.js:462
  Member 39:
  polymorphic type: function type. See lib: dom.js:463
  Error:
   26:     document.createNodeIterator({}); // invalid
                                       ^^ object literal. This type is incompatible with
  Node. See lib: dom.js:463
  Member 40:
  polymorphic type: function type. See lib: dom.js:464
  Error:
   26:     document.createNodeIterator({}); // invalid
                                       ^^ object literal. This type is incompatible with
  Node. See lib: dom.js:464
  Member 41:
  polymorphic type: function type. See lib: dom.js:465
  Error:
   26:     document.createNodeIterator({}); // invalid
                                       ^^ object literal. This type is incompatible with
  Node. See lib: dom.js:465
  Member 42:
  polymorphic type: function type. See lib: dom.js:476
  Error:
   26:     document.createNodeIterator({}); // invalid
                                       ^^ object literal. This type is incompatible with
  Document. See lib: dom.js:476
  Member 43:
  polymorphic type: function type. See lib: dom.js:480
  Error:
   26:     document.createNodeIterator({}); // invalid
                                       ^^ object literal. This type is incompatible with
  Node. See lib: dom.js:480

traversal.js:30
 30:     document.createTreeWalker({}); // invalid
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ call of method `createTreeWalker`. Function cannot be called on any member of intersection type
 30:     document.createTreeWalker({}); // invalid
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ intersection
  Member 1:
  polymorphic type: function type. See lib: dom.js:380
  Error:
   30:     document.createTreeWalker({}); // invalid
                                     ^^ object literal. This type is incompatible with
  Attr. See lib: dom.js:380
  Member 2:
  polymorphic type: function type. See lib: dom.js:411
  Error:
   30:     document.createTreeWalker({}); // invalid
                                     ^^ object literal. This type is incompatible with
  Document. See lib: dom.js:411
  Member 3:
  polymorphic type: function type. See lib: dom.js:412
  Error:
   30:     document.createTreeWalker({}); // invalid
                                     ^^ object literal. This type is incompatible with
  Document. See lib: dom.js:412
  Member 4:
  polymorphic type: function type. See lib: dom.js:413
  Error:
   30:     document.createTreeWalker({}); // invalid
                                     ^^ object literal. This type is incompatible with
  Document. See lib: dom.js:413
  Member 5:
  polymorphic type: function type. See lib: dom.js:414
  Error:
   30:     document.createTreeWalker({}); // invalid
                                     ^^ object literal. This type is incompatible with
  Document. See lib: dom.js:414
  Member 6:
  polymorphic type: function type. See lib: dom.js:415
  Error:
   30:     document.createTreeWalker({}); // invalid
                                     ^^ object literal. This type is incompatible with
  Document. See lib: dom.js:415
  Member 7:
  polymorphic type: function type. See lib: dom.js:416
  Error:
   30:     document.createTreeWalker({}); // invalid
                                     ^^ object literal. This type is incompatible with
  Document. See lib: dom.js:416
  Member 8:
  polymorphic type: function type. See lib: dom.js:417
  Error:
   30:     document.createTreeWalker({}); // invalid
                                     ^^ object literal. This type is incompatible with
  Document. See lib: dom.js:417
  Member 9:
  polymorphic type: function type. See lib: dom.js:418
  Error:
   30:     document.createTreeWalker({}); // invalid
                                     ^^ object literal. This type is incompatible with
  Document. See lib: dom.js:418
  Member 10:
  polymorphic type: function type. See lib: dom.js:419
  Error:
   30:     document.createTreeWalker({}); // invalid
                                     ^^ object literal. This type is incompatible with
  Document. See lib: dom.js:419
  Member 11:
  polymorphic type: function type. See lib: dom.js:420
  Error:
   30:     document.createTreeWalker({}); // invalid
                                     ^^ object literal. This type is incompatible with
  Document. See lib: dom.js:420
  Member 12:
  polymorphic type: function type. See lib: dom.js:421
  Error:
   30:     document.createTreeWalker({}); // invalid
                                     ^^ object literal. This type is incompatible with
  Document. See lib: dom.js:421
  Member 13:
  polymorphic type: function type. See lib: dom.js:422
  Error:
   30:     document.createTreeWalker({}); // invalid
                                     ^^ object literal. This type is incompatible with
  Document. See lib: dom.js:422
  Member 14:
  polymorphic type: function type. See lib: dom.js:423
  Error:
   30:     document.createTreeWalker({}); // invalid
                                     ^^ object literal. This type is incompatible with
  Document. See lib: dom.js:423
  Member 15:
  polymorphic type: function type. See lib: dom.js:424
  Error:
   30:     document.createTreeWalker({}); // invalid
                                     ^^ object literal. This type is incompatible with
  Document. See lib: dom.js:424
  Member 16:
  polymorphic type: function type. See lib: dom.js:425
  Error:
   30:     document.createTreeWalker({}); // invalid
                                     ^^ object literal. This type is incompatible with
  Document. See lib: dom.js:425
  Member 17:
  polymorphic type: function type. See lib: dom.js:426
  Error:
   30:     document.createTreeWalker({}); // invalid
                                     ^^ object literal. This type is incompatible with
  Document. See lib: dom.js:426
  Member 18:
  polymorphic type: function type. See lib: dom.js:427
  Error:
   30:     document.createTreeWalker({}); // invalid
                                     ^^ object literal. This type is incompatible with
  Document. See lib: dom.js:427
  Member 19:
  polymorphic type: function type. See lib: dom.js:428
  Error:
   30:     document.createTreeWalker({}); // invalid
                                     ^^ object literal. This type is incompatible with
  Document. See lib: dom.js:428
  Member 20:
  polymorphic type: function type. See lib: dom.js:429
  Error:
   30:     document.createTreeWalker({}); // invalid
                                     ^^ object literal. This type is incompatible with
  Document. See lib: dom.js:429
  Member 21:
  polymorphic type: function type. See lib: dom.js:430
  Error:
   30:     document.createTreeWalker({}); // invalid
                                     ^^ object literal. This type is incompatible with
  Document. See lib: dom.js:430
  Member 22:
  polymorphic type: function type. See lib: dom.js:431
  Error:
   30:     document.createTreeWalker({}); // invalid
                                     ^^ object literal. This type is incompatible with
  Document. See lib: dom.js:431
  Member 23:
  polymorphic type: function type. See lib: dom.js:432
  Error:
   30:     document.createTreeWalker({}); // invalid
                                     ^^ object literal. This type is incompatible with
  Document. See lib: dom.js:432
  Member 24:
  polymorphic type: function type. See lib: dom.js:433
  Error:
   30:     document.createTreeWalker({}); // invalid
                                     ^^ object literal. This type is incompatible with
  Document. See lib: dom.js:433
  Member 25:
  polymorphic type: function type. See lib: dom.js:434
  Error:
   30:     document.createTreeWalker({}); // invalid
                                     ^^ object literal. This type is incompatible with
  Document. See lib: dom.js:434
  Member 26:
  polymorphic type: function type. See lib: dom.js:446
  Error:
   30:     document.createTreeWalker({}); // invalid
                                     ^^ object literal. This type is incompatible with
  DocumentFragment. See lib: dom.js:446
  Member 27:
  polymorphic type: function type. See lib: dom.js:447
  Error:
   30:     document.createTreeWalker({}); // invalid
                                     ^^ object literal. This type is incompatible with
  DocumentFragment. See lib: dom.js:447
  Member 28:
  polymorphic type: function type. See lib: dom.js:448
  Error:
   30:     document.createTreeWalker({}); // invalid
                                     ^^ object literal. This type is incompatible with
  DocumentFragment. See lib: dom.js:448
  Member 29:
  polymorphic type: function type. See lib: dom.js:449
  Error:
   30:     document.createTreeWalker({}); // invalid
                                     ^^ object literal. This type is incompatible with
  DocumentFragment. See lib: dom.js:449
  Member 30:
  polymorphic type: function type. See lib: dom.js:450
  Error:
   30:     document.createTreeWalker({}); // invalid
                                     ^^ object literal. This type is incompatible with
  DocumentFragment. See lib: dom.js:450
  Member 31:
  polymorphic type: function type. See lib: dom.js:451
  Error:
   30:     document.createTreeWalker({}); // invalid
                                     ^^ object literal. This type is incompatible with
  DocumentFragment. See lib: dom.js:451
  Member 32:
  polymorphic type: function type. See lib: dom.js:452
  Error:
   30:     document.createTreeWalker({}); // invalid
                                     ^^ object literal. This type is incompatible with
  DocumentFragment. See lib: dom.js:452
  Member 33:
  polymorphic type: function type. See lib: dom.js:453
  Error:
   30:     document.createTreeWalker({}); // invalid
                                     ^^ object literal. This type is incompatible with
  DocumentFragment. See lib: dom.js:453
  Member 34:
  polymorphic type: function type. See lib: dom.js:466
  Error:
   30:     document.createTreeWalker({}); // invalid
                                     ^^ object literal. This type is incompatible with
  Node. See lib: dom.js:466
  Member 35:
  polymorphic type: function type. See lib: dom.js:467
  Error:
   30:     document.createTreeWalker({}); // invalid
                                     ^^ object literal. This type is incompatible with
  Node. See lib: dom.js:467
  Member 36:
  polymorphic type: function type. See lib: dom.js:468
  Error:
   30:     document.createTreeWalker({}); // invalid
                                     ^^ object literal. This type is incompatible with
  Node. See lib: dom.js:468
  Member 37:
  polymorphic type: function type. See lib: dom.js:469
  Error:
   30:     document.createTreeWalker({}); // invalid
                                     ^^ object literal. This type is incompatible with
  Node. See lib: dom.js:469
  Member 38:
  polymorphic type: function type. See lib: dom.js:470
  Error:
   30:     document.createTreeWalker({}); // invalid
                                     ^^ object literal. This type is incompatible with
  Node. See lib: dom.js:470
  Member 39:
  polymorphic type: function type. See lib: dom.js:471
  Error:
   30:     document.createTreeWalker({}); // invalid
                                     ^^ object literal. This type is incompatible with
  Node. See lib: dom.js:471
  Member 40:
  polymorphic type: function type. See lib: dom.js:472
  Error:
   30:     document.createTreeWalker({}); // invalid
                                     ^^ object literal. This type is incompatible with
  Node. See lib: dom.js:472
  Member 41:
  polymorphic type: function type. See lib: dom.js:473
  Error:
   30:     document.createTreeWalker({}); // invalid
                                     ^^ object literal. This type is incompatible with
  Node. See lib: dom.js:473
  Member 42:
  polymorphic type: function type. See lib: dom.js:477
  Error:
   30:     document.createTreeWalker({}); // invalid
                                     ^^ object literal. This type is incompatible with
  Node. See lib: dom.js:477
  Member 43:
  polymorphic type: function type. See lib: dom.js:481
  Error:
   30:     document.createTreeWalker({}); // invalid
                                     ^^ object literal. This type is incompatible with
  Node. See lib: dom.js:481

traversal.js:183
183:     document.createNodeIterator(document.body, -1, node => 'accept'); // invalid
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ call of method `createNodeIterator`. Function cannot be called on any member of intersection type
183:     document.createNodeIterator(document.body, -1, node => 'accept'); // invalid
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ intersection
  Member 1:
  polymorphic type: function type. See lib: dom.js:379
  Error:
  183:     document.createNodeIterator(document.body, -1, node => 'accept'); // invalid
                                       ^^^^^^^^^^^^^ HTMLElement. This type is incompatible with
  Attr. See lib: dom.js:379
  Member 2:
  polymorphic type: function type. See lib: dom.js:387
  Error:
  183:     document.createNodeIterator(document.body, -1, node => 'accept'); // invalid
                                       ^^^^^^^^^^^^^ HTMLElement. This type is incompatible with
  Document. See lib: dom.js:387
  Member 3:
  polymorphic type: function type. See lib: dom.js:388
  Error:
  183:     document.createNodeIterator(document.body, -1, node => 'accept'); // invalid
                                       ^^^^^^^^^^^^^ HTMLElement. This type is incompatible with
  Document. See lib: dom.js:388
  Member 4:
  polymorphic type: function type. See lib: dom.js:389
  Error:
  183:     document.createNodeIterator(document.body, -1, node => 'accept'); // invalid
                                       ^^^^^^^^^^^^^ HTMLElement. This type is incompatible with
  Document. See lib: dom.js:389
  Member 5:
  polymorphic type: function type. See lib: dom.js:390
  Error:
  183:     document.createNodeIterator(document.body, -1, node => 'accept'); // invalid
                                       ^^^^^^^^^^^^^ HTMLElement. This type is incompatible with
  Document. See lib: dom.js:390
  Member 6:
  polymorphic type: function type. See lib: dom.js:391
  Error:
  183:     document.createNodeIterator(document.body, -1, node => 'accept'); // invalid
                                       ^^^^^^^^^^^^^ HTMLElement. This type is incompatible with
  Document. See lib: dom.js:391
  Member 7:
  polymorphic type: function type. See lib: dom.js:392
  Error:
  183:     document.createNodeIterator(document.body, -1, node => 'accept'); // invalid
                                       ^^^^^^^^^^^^^ HTMLElement. This type is incompatible with
  Document. See lib: dom.js:392
  Member 8:
  polymorphic type: function type. See lib: dom.js:393
  Error:
  183:     document.createNodeIterator(document.body, -1, node => 'accept'); // invalid
                                       ^^^^^^^^^^^^^ HTMLElement. This type is incompatible with
  Document. See lib: dom.js:393
  Member 9:
  polymorphic type: function type. See lib: dom.js:394
  Error:
  183:     document.createNodeIterator(document.body, -1, node => 'accept'); // invalid
                                       ^^^^^^^^^^^^^ HTMLElement. This type is incompatible with
  Document. See lib: dom.js:394
  Member 10:
  polymorphic type: function type. See lib: dom.js:395
  Error:
  183:     document.createNodeIterator(document.body, -1, node => 'accept'); // invalid
                                       ^^^^^^^^^^^^^ HTMLElement. This type is incompatible with
  Document. See lib: dom.js:395
  Member 11:
  polymorphic type: function type. See lib: dom.js:396
  Error:
  183:     document.createNodeIterator(document.body, -1, node => 'accept'); // invalid
                                       ^^^^^^^^^^^^^ HTMLElement. This type is incompatible with
  Document. See lib: dom.js:396
  Member 12:
  polymorphic type: function type. See lib: dom.js:397
  Error:
  183:     document.createNodeIterator(document.body, -1, node => 'accept'); // invalid
                                       ^^^^^^^^^^^^^ HTMLElement. This type is incompatible with
  Document. See lib: dom.js:397
  Member 13:
  polymorphic type: function type. See lib: dom.js:398
  Error:
  183:     document.createNodeIterator(document.body, -1, node => 'accept'); // invalid
                                       ^^^^^^^^^^^^^ HTMLElement. This type is incompatible with
  Document. See lib: dom.js:398
  Member 14:
  polymorphic type: function type. See lib: dom.js:399
  Error:
  183:     document.createNodeIterator(document.body, -1, node => 'accept'); // invalid
                                       ^^^^^^^^^^^^^ HTMLElement. This type is incompatible with
  Document. See lib: dom.js:399
  Member 15:
  polymorphic type: function type. See lib: dom.js:400
  Error:
  183:     document.createNodeIterator(document.body, -1, node => 'accept'); // invalid
                                       ^^^^^^^^^^^^^ HTMLElement. This type is incompatible with
  Document. See lib: dom.js:400
  Member 16:
  polymorphic type: function type. See lib: dom.js:401
  Error:
  183:     document.createNodeIterator(document.body, -1, node => 'accept'); // invalid
                                       ^^^^^^^^^^^^^ HTMLElement. This type is incompatible with
  Document. See lib: dom.js:401
  Member 17:
  polymorphic type: function type. See lib: dom.js:402
  Error:
  183:     document.createNodeIterator(document.body, -1, node => 'accept'); // invalid
                                       ^^^^^^^^^^^^^ HTMLElement. This type is incompatible with
  Document. See lib: dom.js:402
  Member 18:
  polymorphic type: function type. See lib: dom.js:403
  Error:
  183:     document.createNodeIterator(document.body, -1, node => 'accept'); // invalid
                                       ^^^^^^^^^^^^^ HTMLElement. This type is incompatible with
  Document. See lib: dom.js:403
  Member 19:
  polymorphic type: function type. See lib: dom.js:404
  Error:
  183:     document.createNodeIterator(document.body, -1, node => 'accept'); // invalid
                                       ^^^^^^^^^^^^^ HTMLElement. This type is incompatible with
  Document. See lib: dom.js:404
  Member 20:
  polymorphic type: function type. See lib: dom.js:405
  Error:
  183:     document.createNodeIterator(document.body, -1, node => 'accept'); // invalid
                                       ^^^^^^^^^^^^^ HTMLElement. This type is incompatible with
  Document. See lib: dom.js:405
  Member 21:
  polymorphic type: function type. See lib: dom.js:406
  Error:
  183:     document.createNodeIterator(document.body, -1, node => 'accept'); // invalid
                                       ^^^^^^^^^^^^^ HTMLElement. This type is incompatible with
  Document. See lib: dom.js:406
  Member 22:
  polymorphic type: function type. See lib: dom.js:407
  Error:
  183:     document.createNodeIterator(document.body, -1, node => 'accept'); // invalid
                                       ^^^^^^^^^^^^^ HTMLElement. This type is incompatible with
  Document. See lib: dom.js:407
  Member 23:
  polymorphic type: function type. See lib: dom.js:408
  Error:
  183:     document.createNodeIterator(document.body, -1, node => 'accept'); // invalid
                                       ^^^^^^^^^^^^^ HTMLElement. This type is incompatible with
  Document. See lib: dom.js:408
  Member 24:
  polymorphic type: function type. See lib: dom.js:409
  Error:
  183:     document.createNodeIterator(document.body, -1, node => 'accept'); // invalid
                                       ^^^^^^^^^^^^^ HTMLElement. This type is incompatible with
  Document. See lib: dom.js:409
  Member 25:
  polymorphic type: function type. See lib: dom.js:410
  Error:
  183:     document.createNodeIterator(document.body, -1, node => 'accept'); // invalid
                                       ^^^^^^^^^^^^^ HTMLElement. This type is incompatible with
  Document. See lib: dom.js:410
  Member 26:
  polymorphic type: function type. See lib: dom.js:438
  Error:
  183:     document.createNodeIterator(document.body, -1, node => 'accept'); // invalid
                                       ^^^^^^^^^^^^^ HTMLElement. This type is incompatible with
  DocumentFragment. See lib: dom.js:438
  Member 27:
  polymorphic type: function type. See lib: dom.js:439
  Error:
  183:     document.createNodeIterator(document.body, -1, node => 'accept'); // invalid
                                       ^^^^^^^^^^^^^ HTMLElement. This type is incompatible with
  DocumentFragment. See lib: dom.js:439
  Member 28:
  polymorphic type: function type. See lib: dom.js:440
  Error:
  183:     document.createNodeIterator(document.body, -1, node => 'accept'); // invalid
                                       ^^^^^^^^^^^^^ HTMLElement. This type is incompatible with
  DocumentFragment. See lib: dom.js:440
  Member 29:
  polymorphic type: function type. See lib: dom.js:441
  Error:
  183:     document.createNodeIterator(document.body, -1, node => 'accept'); // invalid
                                       ^^^^^^^^^^^^^ HTMLElement. This type is incompatible with
  DocumentFragment. See lib: dom.js:441
  Member 30:
  polymorphic type: function type. See lib: dom.js:442
  Error:
  183:     document.createNodeIterator(document.body, -1, node => 'accept'); // invalid
                                       ^^^^^^^^^^^^^ HTMLElement. This type is incompatible with
  DocumentFragment. See lib: dom.js:442
  Member 31:
  polymorphic type: function type. See lib: dom.js:443
  Error:
  183:     document.createNodeIterator(document.body, -1, node => 'accept'); // invalid
                                       ^^^^^^^^^^^^^ HTMLElement. This type is incompatible with
  DocumentFragment. See lib: dom.js:443
  Member 32:
  polymorphic type: function type. See lib: dom.js:444
  Error:
  183:     document.createNodeIterator(document.body, -1, node => 'accept'); // invalid
                                       ^^^^^^^^^^^^^ HTMLElement. This type is incompatible with
  DocumentFragment. See lib: dom.js:444
  Member 33:
  polymorphic type: function type. See lib: dom.js:445
  Error:
  183:     document.createNodeIterator(document.body, -1, node => 'accept'); // invalid
                                       ^^^^^^^^^^^^^ HTMLElement. This type is incompatible with
  DocumentFragment. See lib: dom.js:445
  Member 34:
  polymorphic type: function type. See lib: dom.js:458
  Error:
  183:     document.createNodeIterator(document.body, -1, node => 'accept'); // invalid
                                                      ^^ number. Expected number literal `1`, got `-1` instead
  number literal `1`. See lib: dom.js:458
  Member 35:
  polymorphic type: function type. See lib: dom.js:459
  Error:
  183:     document.createNodeIterator(document.body, -1, node => 'accept'); // invalid
                                                      ^^ number. Expected number literal `4`, got `-1` instead
  number literal `4`. See lib: dom.js:459
  Member 36:
  polymorphic type: function type. See lib: dom.js:460
  Error:
  183:     document.createNodeIterator(document.body, -1, node => 'accept'); // invalid
                                                      ^^ number. Expected number literal `5`, got `-1` instead
  number literal `5`. See lib: dom.js:460
  Member 37:
  polymorphic type: function type. See lib: dom.js:461
  Error:
  183:     document.createNodeIterator(document.body, -1, node => 'accept'); // invalid
                                                      ^^ number. Expected number literal `128`, got `-1` instead
  number literal `128`. See lib: dom.js:461
  Member 38:
  polymorphic type: function type. See lib: dom.js:462
  Error:
  183:     document.createNodeIterator(document.body, -1, node => 'accept'); // invalid
                                                      ^^ number. Expected number literal `129`, got `-1` instead
  number literal `129`. See lib: dom.js:462
  Member 39:
  polymorphic type: function type. See lib: dom.js:463
  Error:
  183:     document.createNodeIterator(document.body, -1, node => 'accept'); // invalid
                                                      ^^ number. Expected number literal `132`, got `-1` instead
  number literal `132`. See lib: dom.js:463
  Member 40:
  polymorphic type: function type. See lib: dom.js:464
  Error:
  183:     document.createNodeIterator(document.body, -1, node => 'accept'); // invalid
                                                      ^^ number. Expected number literal `133`, got `-1` instead
  number literal `133`. See lib: dom.js:464
  Member 41:
  polymorphic type: function type. See lib: dom.js:465
  Error:
  183:     document.createNodeIterator(document.body, -1, node => 'accept'); // invalid
                                                          ^^^^^^^^^^^^^^^^ arrow function. This type is incompatible with
  union: NodeFilterCallback | object type. See lib: dom.js:465
    Member 1:
    NodeFilterCallback. See lib: dom.js:1476
    Error:
    183:     document.createNodeIterator(document.body, -1, node => 'accept'); // invalid
                                                                    ^^^^^^^^ string. This type is incompatible with
    union: typeof typeof-annotation '<<object>>.FILTER_ACCEPT') | typeof typeof-annotation '<<object>>.FILTER_REJECT') | typeof typeof-annotation '<<object>>.FILTER_SKIP'). See lib: dom.js:1472
      Member 1:
      typeof typeof-annotation '<<object>>.FILTER_ACCEPT'). See lib: dom.js:1472
      Error:
      183:     document.createNodeIterator(document.body, -1, node => 'accept'); // invalid
                                                                      ^^^^^^^^ string. This type is incompatible with
      number literal `1`. See lib: dom.js:1472
      Member 2:
      typeof typeof-annotation '<<object>>.FILTER_REJECT'). See lib: dom.js:1473
      Error:
      183:     document.createNodeIterator(document.body, -1, node => 'accept'); // invalid
                                                                      ^^^^^^^^ string. This type is incompatible with
      number literal `2`. See lib: dom.js:1473
      Member 3:
      typeof typeof-annotation '<<object>>.FILTER_SKIP'). See lib: dom.js:1474
      Error:
      183:     document.createNodeIterator(document.body, -1, node => 'accept'); // invalid
                                                                      ^^^^^^^^ string. This type is incompatible with
      number literal `3`. See lib: dom.js:1474
    Member 2:
    object type. See lib: dom.js:1476
    Error:
    property `accept`. Property not found in. See lib: dom.js:1476
    183:     document.createNodeIterator(document.body, -1, node => 'accept'); // invalid
                                                            ^^^^^^^^^^^^^^^^ arrow function
  Member 42:
  polymorphic type: function type. See lib: dom.js:476
  Error:
  183:     document.createNodeIterator(document.body, -1, node => 'accept'); // invalid
                                       ^^^^^^^^^^^^^ HTMLElement. This type is incompatible with
  Document. See lib: dom.js:476
  Member 43:
  polymorphic type: function type. See lib: dom.js:480
  Error:
  183:     document.createNodeIterator(document.body, -1, node => 'accept'); // invalid
                                                      ^^ number. This type is incompatible with
  undefined. See lib: dom.js:480

traversal.js:185
185:     document.createNodeIterator(document.body, -1, { accept: node => 'accept' }); // invalid
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ call of method `createNodeIterator`. Function cannot be called on any member of intersection type
185:     document.createNodeIterator(document.body, -1, { accept: node => 'accept' }); // invalid
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ intersection
  Member 1:
  polymorphic type: function type. See lib: dom.js:379
  Error:
  185:     document.createNodeIterator(document.body, -1, { accept: node => 'accept' }); // invalid
                                       ^^^^^^^^^^^^^ HTMLElement. This type is incompatible with
  Attr. See lib: dom.js:379
  Member 2:
  polymorphic type: function type. See lib: dom.js:387
  Error:
  185:     document.createNodeIterator(document.body, -1, { accept: node => 'accept' }); // invalid
                                       ^^^^^^^^^^^^^ HTMLElement. This type is incompatible with
  Document. See lib: dom.js:387
  Member 3:
  polymorphic type: function type. See lib: dom.js:388
  Error:
  185:     document.createNodeIterator(document.body, -1, { accept: node => 'accept' }); // invalid
                                       ^^^^^^^^^^^^^ HTMLElement. This type is incompatible with
  Document. See lib: dom.js:388
  Member 4:
  polymorphic type: function type. See lib: dom.js:389
  Error:
  185:     document.createNodeIterator(document.body, -1, { accept: node => 'accept' }); // invalid
                                       ^^^^^^^^^^^^^ HTMLElement. This type is incompatible with
  Document. See lib: dom.js:389
  Member 5:
  polymorphic type: function type. See lib: dom.js:390
  Error:
  185:     document.createNodeIterator(document.body, -1, { accept: node => 'accept' }); // invalid
                                       ^^^^^^^^^^^^^ HTMLElement. This type is incompatible with
  Document. See lib: dom.js:390
  Member 6:
  polymorphic type: function type. See lib: dom.js:391
  Error:
  185:     document.createNodeIterator(document.body, -1, { accept: node => 'accept' }); // invalid
                                       ^^^^^^^^^^^^^ HTMLElement. This type is incompatible with
  Document. See lib: dom.js:391
  Member 7:
  polymorphic type: function type. See lib: dom.js:392
  Error:
  185:     document.createNodeIterator(document.body, -1, { accept: node => 'accept' }); // invalid
                                       ^^^^^^^^^^^^^ HTMLElement. This type is incompatible with
  Document. See lib: dom.js:392
  Member 8:
  polymorphic type: function type. See lib: dom.js:393
  Error:
  185:     document.createNodeIterator(document.body, -1, { accept: node => 'accept' }); // invalid
                                       ^^^^^^^^^^^^^ HTMLElement. This type is incompatible with
  Document. See lib: dom.js:393
  Member 9:
  polymorphic type: function type. See lib: dom.js:394
  Error:
  185:     document.createNodeIterator(document.body, -1, { accept: node => 'accept' }); // invalid
                                       ^^^^^^^^^^^^^ HTMLElement. This type is incompatible with
  Document. See lib: dom.js:394
  Member 10:
  polymorphic type: function type. See lib: dom.js:395
  Error:
  185:     document.createNodeIterator(document.body, -1, { accept: node => 'accept' }); // invalid
                                       ^^^^^^^^^^^^^ HTMLElement. This type is incompatible with
  Document. See lib: dom.js:395
  Member 11:
  polymorphic type: function type. See lib: dom.js:396
  Error:
  185:     document.createNodeIterator(document.body, -1, { accept: node => 'accept' }); // invalid
                                       ^^^^^^^^^^^^^ HTMLElement. This type is incompatible with
  Document. See lib: dom.js:396
  Member 12:
  polymorphic type: function type. See lib: dom.js:397
  Error:
  185:     document.createNodeIterator(document.body, -1, { accept: node => 'accept' }); // invalid
                                       ^^^^^^^^^^^^^ HTMLElement. This type is incompatible with
  Document. See lib: dom.js:397
  Member 13:
  polymorphic type: function type. See lib: dom.js:398
  Error:
  185:     document.createNodeIterator(document.body, -1, { accept: node => 'accept' }); // invalid
                                       ^^^^^^^^^^^^^ HTMLElement. This type is incompatible with
  Document. See lib: dom.js:398
  Member 14:
  polymorphic type: function type. See lib: dom.js:399
  Error:
  185:     document.createNodeIterator(document.body, -1, { accept: node => 'accept' }); // invalid
                                       ^^^^^^^^^^^^^ HTMLElement. This type is incompatible with
  Document. See lib: dom.js:399
  Member 15:
  polymorphic type: function type. See lib: dom.js:400
  Error:
  185:     document.createNodeIterator(document.body, -1, { accept: node => 'accept' }); // invalid
                                       ^^^^^^^^^^^^^ HTMLElement. This type is incompatible with
  Document. See lib: dom.js:400
  Member 16:
  polymorphic type: function type. See lib: dom.js:401
  Error:
  185:     document.createNodeIterator(document.body, -1, { accept: node => 'accept' }); // invalid
                                       ^^^^^^^^^^^^^ HTMLElement. This type is incompatible with
  Document. See lib: dom.js:401
  Member 17:
  polymorphic type: function type. See lib: dom.js:402
  Error:
  185:     document.createNodeIterator(document.body, -1, { accept: node => 'accept' }); // invalid
                                       ^^^^^^^^^^^^^ HTMLElement. This type is incompatible with
  Document. See lib: dom.js:402
  Member 18:
  polymorphic type: function type. See lib: dom.js:403
  Error:
  185:     document.createNodeIterator(document.body, -1, { accept: node => 'accept' }); // invalid
                                       ^^^^^^^^^^^^^ HTMLElement. This type is incompatible with
  Document. See lib: dom.js:403
  Member 19:
  polymorphic type: function type. See lib: dom.js:404
  Error:
  185:     document.createNodeIterator(document.body, -1, { accept: node => 'accept' }); // invalid
                                       ^^^^^^^^^^^^^ HTMLElement. This type is incompatible with
  Document. See lib: dom.js:404
  Member 20:
  polymorphic type: function type. See lib: dom.js:405
  Error:
  185:     document.createNodeIterator(document.body, -1, { accept: node => 'accept' }); // invalid
                                       ^^^^^^^^^^^^^ HTMLElement. This type is incompatible with
  Document. See lib: dom.js:405
  Member 21:
  polymorphic type: function type. See lib: dom.js:406
  Error:
  185:     document.createNodeIterator(document.body, -1, { accept: node => 'accept' }); // invalid
                                       ^^^^^^^^^^^^^ HTMLElement. This type is incompatible with
  Document. See lib: dom.js:406
  Member 22:
  polymorphic type: function type. See lib: dom.js:407
  Error:
  185:     document.createNodeIterator(document.body, -1, { accept: node => 'accept' }); // invalid
                                       ^^^^^^^^^^^^^ HTMLElement. This type is incompatible with
  Document. See lib: dom.js:407
  Member 23:
  polymorphic type: function type. See lib: dom.js:408
  Error:
  185:     document.createNodeIterator(document.body, -1, { accept: node => 'accept' }); // invalid
                                       ^^^^^^^^^^^^^ HTMLElement. This type is incompatible with
  Document. See lib: dom.js:408
  Member 24:
  polymorphic type: function type. See lib: dom.js:409
  Error:
  185:     document.createNodeIterator(document.body, -1, { accept: node => 'accept' }); // invalid
                                       ^^^^^^^^^^^^^ HTMLElement. This type is incompatible with
  Document. See lib: dom.js:409
  Member 25:
  polymorphic type: function type. See lib: dom.js:410
  Error:
  185:     document.createNodeIterator(document.body, -1, { accept: node => 'accept' }); // invalid
                                       ^^^^^^^^^^^^^ HTMLElement. This type is incompatible with
  Document. See lib: dom.js:410
  Member 26:
  polymorphic type: function type. See lib: dom.js:438
  Error:
  185:     document.createNodeIterator(document.body, -1, { accept: node => 'accept' }); // invalid
                                       ^^^^^^^^^^^^^ HTMLElement. This type is incompatible with
  DocumentFragment. See lib: dom.js:438
  Member 27:
  polymorphic type: function type. See lib: dom.js:439
  Error:
  185:     document.createNodeIterator(document.body, -1, { accept: node => 'accept' }); // invalid
                                       ^^^^^^^^^^^^^ HTMLElement. This type is incompatible with
  DocumentFragment. See lib: dom.js:439
  Member 28:
  polymorphic type: function type. See lib: dom.js:440
  Error:
  185:     document.createNodeIterator(document.body, -1, { accept: node => 'accept' }); // invalid
                                       ^^^^^^^^^^^^^ HTMLElement. This type is incompatible with
  DocumentFragment. See lib: dom.js:440
  Member 29:
  polymorphic type: function type. See lib: dom.js:441
  Error:
  185:     document.createNodeIterator(document.body, -1, { accept: node => 'accept' }); // invalid
                                       ^^^^^^^^^^^^^ HTMLElement. This type is incompatible with
  DocumentFragment. See lib: dom.js:441
  Member 30:
  polymorphic type: function type. See lib: dom.js:442
  Error:
  185:     document.createNodeIterator(document.body, -1, { accept: node => 'accept' }); // invalid
                                       ^^^^^^^^^^^^^ HTMLElement. This type is incompatible with
  DocumentFragment. See lib: dom.js:442
  Member 31:
  polymorphic type: function type. See lib: dom.js:443
  Error:
  185:     document.createNodeIterator(document.body, -1, { accept: node => 'accept' }); // invalid
                                       ^^^^^^^^^^^^^ HTMLElement. This type is incompatible with
  DocumentFragment. See lib: dom.js:443
  Member 32:
  polymorphic type: function type. See lib: dom.js:444
  Error:
  185:     document.createNodeIterator(document.body, -1, { accept: node => 'accept' }); // invalid
                                       ^^^^^^^^^^^^^ HTMLElement. This type is incompatible with
  DocumentFragment. See lib: dom.js:444
  Member 33:
  polymorphic type: function type. See lib: dom.js:445
  Error:
  185:     document.createNodeIterator(document.body, -1, { accept: node => 'accept' }); // invalid
                                       ^^^^^^^^^^^^^ HTMLElement. This type is incompatible with
  DocumentFragment. See lib: dom.js:445
  Member 34:
  polymorphic type: function type. See lib: dom.js:458
  Error:
  185:     document.createNodeIterator(document.body, -1, { accept: node => 'accept' }); // invalid
                                                      ^^ number. Expected number literal `1`, got `-1` instead
  number literal `1`. See lib: dom.js:458
  Member 35:
  polymorphic type: function type. See lib: dom.js:459
  Error:
  185:     document.createNodeIterator(document.body, -1, { accept: node => 'accept' }); // invalid
                                                      ^^ number. Expected number literal `4`, got `-1` instead
  number literal `4`. See lib: dom.js:459
  Member 36:
  polymorphic type: function type. See lib: dom.js:460
  Error:
  185:     document.createNodeIterator(document.body, -1, { accept: node => 'accept' }); // invalid
                                                      ^^ number. Expected number literal `5`, got `-1` instead
  number literal `5`. See lib: dom.js:460
  Member 37:
  polymorphic type: function type. See lib: dom.js:461
  Error:
  185:     document.createNodeIterator(document.body, -1, { accept: node => 'accept' }); // invalid
                                                      ^^ number. Expected number literal `128`, got `-1` instead
  number literal `128`. See lib: dom.js:461
  Member 38:
  polymorphic type: function type. See lib: dom.js:462
  Error:
  185:     document.createNodeIterator(document.body, -1, { accept: node => 'accept' }); // invalid
                                                      ^^ number. Expected number literal `129`, got `-1` instead
  number literal `129`. See lib: dom.js:462
  Member 39:
  polymorphic type: function type. See lib: dom.js:463
  Error:
  185:     document.createNodeIterator(document.body, -1, { accept: node => 'accept' }); // invalid
                                                      ^^ number. Expected number literal `132`, got `-1` instead
  number literal `132`. See lib: dom.js:463
  Member 40:
  polymorphic type: function type. See lib: dom.js:464
  Error:
  185:     document.createNodeIterator(document.body, -1, { accept: node => 'accept' }); // invalid
                                                      ^^ number. Expected number literal `133`, got `-1` instead
  number literal `133`. See lib: dom.js:464
  Member 41:
  polymorphic type: function type. See lib: dom.js:465
  Error:
  185:     document.createNodeIterator(document.body, -1, { accept: node => 'accept' }); // invalid
                                                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^ object literal. This type is incompatible with
  union: NodeFilterCallback | object type. See lib: dom.js:465
    Member 1:
    NodeFilterCallback. See lib: dom.js:1476
    Error:
    function type. Callable signature not found in. See lib: dom.js:1476
    185:     document.createNodeIterator(document.body, -1, { accept: node => 'accept' }); // invalid
                                                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^ object literal
    Member 2:
    object type. See lib: dom.js:1476
    Error:
    185:     document.createNodeIterator(document.body, -1, { accept: node => 'accept' }); // invalid
                                                                              ^^^^^^^^ string. This type is incompatible with
    union: typeof typeof-annotation '<<object>>.FILTER_ACCEPT') | typeof typeof-annotation '<<object>>.FILTER_REJECT') | typeof typeof-annotation '<<object>>.FILTER_SKIP'). See lib: dom.js:1472
      Member 1:
      typeof typeof-annotation '<<object>>.FILTER_ACCEPT'). See lib: dom.js:1472
      Error:
      185:     document.createNodeIterator(document.body, -1, { accept: node => 'accept' }); // invalid
                                                                                ^^^^^^^^ string. This type is incompatible with
      number literal `1`. See lib: dom.js:1472
      Member 2:
      typeof typeof-annotation '<<object>>.FILTER_REJECT'). See lib: dom.js:1473
      Error:
      185:     document.createNodeIterator(document.body, -1, { accept: node => 'accept' }); // invalid
                                                                                ^^^^^^^^ string. This type is incompatible with
      number literal `2`. See lib: dom.js:1473
      Member 3:
      typeof typeof-annotation '<<object>>.FILTER_SKIP'). See lib: dom.js:1474
      Error:
      185:     document.createNodeIterator(document.body, -1, { accept: node => 'accept' }); // invalid
                                                                                ^^^^^^^^ string. This type is incompatible with
      number literal `3`. See lib: dom.js:1474
  Member 42:
  polymorphic type: function type. See lib: dom.js:476
  Error:
  185:     document.createNodeIterator(document.body, -1, { accept: node => 'accept' }); // invalid
                                       ^^^^^^^^^^^^^ HTMLElement. This type is incompatible with
  Document. See lib: dom.js:476
  Member 43:
  polymorphic type: function type. See lib: dom.js:480
  Error:
  185:     document.createNodeIterator(document.body, -1, { accept: node => 'accept' }); // invalid
                                                      ^^ number. This type is incompatible with
  undefined. See lib: dom.js:480

traversal.js:186
186:     document.createNodeIterator(document.body, -1, {}); // invalid
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ call of method `createNodeIterator`. Function cannot be called on any member of intersection type
186:     document.createNodeIterator(document.body, -1, {}); // invalid
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ intersection
  Member 1:
  polymorphic type: function type. See lib: dom.js:379
  Error:
  186:     document.createNodeIterator(document.body, -1, {}); // invalid
                                       ^^^^^^^^^^^^^ HTMLElement. This type is incompatible with
  Attr. See lib: dom.js:379
  Member 2:
  polymorphic type: function type. See lib: dom.js:387
  Error:
  186:     document.createNodeIterator(document.body, -1, {}); // invalid
                                       ^^^^^^^^^^^^^ HTMLElement. This type is incompatible with
  Document. See lib: dom.js:387
  Member 3:
  polymorphic type: function type. See lib: dom.js:388
  Error:
  186:     document.createNodeIterator(document.body, -1, {}); // invalid
                                       ^^^^^^^^^^^^^ HTMLElement. This type is incompatible with
  Document. See lib: dom.js:388
  Member 4:
  polymorphic type: function type. See lib: dom.js:389
  Error:
  186:     document.createNodeIterator(document.body, -1, {}); // invalid
                                       ^^^^^^^^^^^^^ HTMLElement. This type is incompatible with
  Document. See lib: dom.js:389
  Member 5:
  polymorphic type: function type. See lib: dom.js:390
  Error:
  186:     document.createNodeIterator(document.body, -1, {}); // invalid
                                       ^^^^^^^^^^^^^ HTMLElement. This type is incompatible with
  Document. See lib: dom.js:390
  Member 6:
  polymorphic type: function type. See lib: dom.js:391
  Error:
  186:     document.createNodeIterator(document.body, -1, {}); // invalid
                                       ^^^^^^^^^^^^^ HTMLElement. This type is incompatible with
  Document. See lib: dom.js:391
  Member 7:
  polymorphic type: function type. See lib: dom.js:392
  Error:
  186:     document.createNodeIterator(document.body, -1, {}); // invalid
                                       ^^^^^^^^^^^^^ HTMLElement. This type is incompatible with
  Document. See lib: dom.js:392
  Member 8:
  polymorphic type: function type. See lib: dom.js:393
  Error:
  186:     document.createNodeIterator(document.body, -1, {}); // invalid
                                       ^^^^^^^^^^^^^ HTMLElement. This type is incompatible with
  Document. See lib: dom.js:393
  Member 9:
  polymorphic type: function type. See lib: dom.js:394
  Error:
  186:     document.createNodeIterator(document.body, -1, {}); // invalid
                                       ^^^^^^^^^^^^^ HTMLElement. This type is incompatible with
  Document. See lib: dom.js:394
  Member 10:
  polymorphic type: function type. See lib: dom.js:395
  Error:
  186:     document.createNodeIterator(document.body, -1, {}); // invalid
                                       ^^^^^^^^^^^^^ HTMLElement. This type is incompatible with
  Document. See lib: dom.js:395
  Member 11:
  polymorphic type: function type. See lib: dom.js:396
  Error:
  186:     document.createNodeIterator(document.body, -1, {}); // invalid
                                       ^^^^^^^^^^^^^ HTMLElement. This type is incompatible with
  Document. See lib: dom.js:396
  Member 12:
  polymorphic type: function type. See lib: dom.js:397
  Error:
  186:     document.createNodeIterator(document.body, -1, {}); // invalid
                                       ^^^^^^^^^^^^^ HTMLElement. This type is incompatible with
  Document. See lib: dom.js:397
  Member 13:
  polymorphic type: function type. See lib: dom.js:398
  Error:
  186:     document.createNodeIterator(document.body, -1, {}); // invalid
                                       ^^^^^^^^^^^^^ HTMLElement. This type is incompatible with
  Document. See lib: dom.js:398
  Member 14:
  polymorphic type: function type. See lib: dom.js:399
  Error:
  186:     document.createNodeIterator(document.body, -1, {}); // invalid
                                       ^^^^^^^^^^^^^ HTMLElement. This type is incompatible with
  Document. See lib: dom.js:399
  Member 15:
  polymorphic type: function type. See lib: dom.js:400
  Error:
  186:     document.createNodeIterator(document.body, -1, {}); // invalid
                                       ^^^^^^^^^^^^^ HTMLElement. This type is incompatible with
  Document. See lib: dom.js:400
  Member 16:
  polymorphic type: function type. See lib: dom.js:401
  Error:
  186:     document.createNodeIterator(document.body, -1, {}); // invalid
                                       ^^^^^^^^^^^^^ HTMLElement. This type is incompatible with
  Document. See lib: dom.js:401
  Member 17:
  polymorphic type: function type. See lib: dom.js:402
  Error:
  186:     document.createNodeIterator(document.body, -1, {}); // invalid
                                       ^^^^^^^^^^^^^ HTMLElement. This type is incompatible with
  Document. See lib: dom.js:402
  Member 18:
  polymorphic type: function type. See lib: dom.js:403
  Error:
  186:     document.createNodeIterator(document.body, -1, {}); // invalid
                                       ^^^^^^^^^^^^^ HTMLElement. This type is incompatible with
  Document. See lib: dom.js:403
  Member 19:
  polymorphic type: function type. See lib: dom.js:404
  Error:
  186:     document.createNodeIterator(document.body, -1, {}); // invalid
                                       ^^^^^^^^^^^^^ HTMLElement. This type is incompatible with
  Document. See lib: dom.js:404
  Member 20:
  polymorphic type: function type. See lib: dom.js:405
  Error:
  186:     document.createNodeIterator(document.body, -1, {}); // invalid
                                       ^^^^^^^^^^^^^ HTMLElement. This type is incompatible with
  Document. See lib: dom.js:405
  Member 21:
  polymorphic type: function type. See lib: dom.js:406
  Error:
  186:     document.createNodeIterator(document.body, -1, {}); // invalid
                                       ^^^^^^^^^^^^^ HTMLElement. This type is incompatible with
  Document. See lib: dom.js:406
  Member 22:
  polymorphic type: function type. See lib: dom.js:407
  Error:
  186:     document.createNodeIterator(document.body, -1, {}); // invalid
                                       ^^^^^^^^^^^^^ HTMLElement. This type is incompatible with
  Document. See lib: dom.js:407
  Member 23:
  polymorphic type: function type. See lib: dom.js:408
  Error:
  186:     document.createNodeIterator(document.body, -1, {}); // invalid
                                       ^^^^^^^^^^^^^ HTMLElement. This type is incompatible with
  Document. See lib: dom.js:408
  Member 24:
  polymorphic type: function type. See lib: dom.js:409
  Error:
  186:     document.createNodeIterator(document.body, -1, {}); // invalid
                                       ^^^^^^^^^^^^^ HTMLElement. This type is incompatible with
  Document. See lib: dom.js:409
  Member 25:
  polymorphic type: function type. See lib: dom.js:410
  Error:
  186:     document.createNodeIterator(document.body, -1, {}); // invalid
                                       ^^^^^^^^^^^^^ HTMLElement. This type is incompatible with
  Document. See lib: dom.js:410
  Member 26:
  polymorphic type: function type. See lib: dom.js:438
  Error:
  186:     document.createNodeIterator(document.body, -1, {}); // invalid
                                       ^^^^^^^^^^^^^ HTMLElement. This type is incompatible with
  DocumentFragment. See lib: dom.js:438
  Member 27:
  polymorphic type: function type. See lib: dom.js:439
  Error:
  186:     document.createNodeIterator(document.body, -1, {}); // invalid
                                       ^^^^^^^^^^^^^ HTMLElement. This type is incompatible with
  DocumentFragment. See lib: dom.js:439
  Member 28:
  polymorphic type: function type. See lib: dom.js:440
  Error:
  186:     document.createNodeIterator(document.body, -1, {}); // invalid
                                       ^^^^^^^^^^^^^ HTMLElement. This type is incompatible with
  DocumentFragment. See lib: dom.js:440
  Member 29:
  polymorphic type: function type. See lib: dom.js:441
  Error:
  186:     document.createNodeIterator(document.body, -1, {}); // invalid
                                       ^^^^^^^^^^^^^ HTMLElement. This type is incompatible with
  DocumentFragment. See lib: dom.js:441
  Member 30:
  polymorphic type: function type. See lib: dom.js:442
  Error:
  186:     document.createNodeIterator(document.body, -1, {}); // invalid
                                       ^^^^^^^^^^^^^ HTMLElement. This type is incompatible with
  DocumentFragment. See lib: dom.js:442
  Member 31:
  polymorphic type: function type. See lib: dom.js:443
  Error:
  186:     document.createNodeIterator(document.body, -1, {}); // invalid
                                       ^^^^^^^^^^^^^ HTMLElement. This type is incompatible with
  DocumentFragment. See lib: dom.js:443
  Member 32:
  polymorphic type: function type. See lib: dom.js:444
  Error:
  186:     document.createNodeIterator(document.body, -1, {}); // invalid
                                       ^^^^^^^^^^^^^ HTMLElement. This type is incompatible with
  DocumentFragment. See lib: dom.js:444
  Member 33:
  polymorphic type: function type. See lib: dom.js:445
  Error:
  186:     document.createNodeIterator(document.body, -1, {}); // invalid
                                       ^^^^^^^^^^^^^ HTMLElement. This type is incompatible with
  DocumentFragment. See lib: dom.js:445
  Member 34:
  polymorphic type: function type. See lib: dom.js:458
  Error:
  186:     document.createNodeIterator(document.body, -1, {}); // invalid
                                                      ^^ number. Expected number literal `1`, got `-1` instead
  number literal `1`. See lib: dom.js:458
  Member 35:
  polymorphic type: function type. See lib: dom.js:459
  Error:
  186:     document.createNodeIterator(document.body, -1, {}); // invalid
                                                      ^^ number. Expected number literal `4`, got `-1` instead
  number literal `4`. See lib: dom.js:459
  Member 36:
  polymorphic type: function type. See lib: dom.js:460
  Error:
  186:     document.createNodeIterator(document.body, -1, {}); // invalid
                                                      ^^ number. Expected number literal `5`, got `-1` instead
  number literal `5`. See lib: dom.js:460
  Member 37:
  polymorphic type: function type. See lib: dom.js:461
  Error:
  186:     document.createNodeIterator(document.body, -1, {}); // invalid
                                                      ^^ number. Expected number literal `128`, got `-1` instead
  number literal `128`. See lib: dom.js:461
  Member 38:
  polymorphic type: function type. See lib: dom.js:462
  Error:
  186:     document.createNodeIterator(document.body, -1, {}); // invalid
                                                      ^^ number. Expected number literal `129`, got `-1` instead
  number literal `129`. See lib: dom.js:462
  Member 39:
  polymorphic type: function type. See lib: dom.js:463
  Error:
  186:     document.createNodeIterator(document.body, -1, {}); // invalid
                                                      ^^ number. Expected number literal `132`, got `-1` instead
  number literal `132`. See lib: dom.js:463
  Member 40:
  polymorphic type: function type. See lib: dom.js:464
  Error:
  186:     document.createNodeIterator(document.body, -1, {}); // invalid
                                                      ^^ number. Expected number literal `133`, got `-1` instead
  number literal `133`. See lib: dom.js:464
  Member 41:
  polymorphic type: function type. See lib: dom.js:465
  Error:
  186:     document.createNodeIterator(document.body, -1, {}); // invalid
                                                          ^^ object literal. This type is incompatible with
  union: NodeFilterCallback | object type. See lib: dom.js:465
    Member 1:
    NodeFilterCallback. See lib: dom.js:1476
    Error:
    function type. Callable signature not found in. See lib: dom.js:1476
    186:     document.createNodeIterator(document.body, -1, {}); // invalid
                                                            ^^ object literal
    Member 2:
    object type. See lib: dom.js:1476
    Error:
    property `accept`. Property not found in. See lib: dom.js:1476
    186:     document.createNodeIterator(document.body, -1, {}); // invalid
                                                            ^^ object literal
  Member 42:
  polymorphic type: function type. See lib: dom.js:476
  Error:
  186:     document.createNodeIterator(document.body, -1, {}); // invalid
                                       ^^^^^^^^^^^^^ HTMLElement. This type is incompatible with
  Document. See lib: dom.js:476
  Member 43:
  polymorphic type: function type. See lib: dom.js:480
  Error:
  186:     document.createNodeIterator(document.body, -1, {}); // invalid
                                                      ^^ number. This type is incompatible with
  undefined. See lib: dom.js:480


Found 16 errors
