source 'https://rubygems.org'
ruby RUBY_VERSION

gem 'jekyll'
gem 'jekyll-redirect-from'
gem 'jekyll-paginate'
gem 'crowdin-cli'
gem 'kramdown', '~>1.11' # _plugins/jekyll_ext.rb messes with internals
gem 'rouge', '<2' # rouge2 will require changes in _plugins/jekyll_ext.rb
gem 'wdm', '>= 0.1.0' if Gem.win_platform?
