After start:
No errors!

After introducing a lint error:
Error: test.js:5
  5: if (x) { /* sketchy */ }
         ^ sketchy-null-number: Sketchy null check on number value. Perhaps you meant to check for null instead of for existence?
    3: var x: ?number = 0;
              ^^^^^^^ Potentially null/undefined value.
    3: var x: ?number = 0;
               ^^^^^^ Potentially 0 value.


Found 1 error

After suppressing the lint error:
No errors!

After fixing the lint error, leaving the suppression:
Warning: test.js:4
  4: //flowlint-next-line sketchy-null:off
                          ^^^^^^^^^^^^^^^^ Error suppressing comment. Unused suppression


Found 1 warning

After removing the unused suppression:
No errors!
