Error ------------------------------------------------------- enum_client.js:6:5

Property `LOCATION` is missing in object literal.


Error ------------------------------------------------------ enum_client.js:10:5

Property `name` is missing in object type.


Error ----------------------------------------------------- enum_client.js:17:19

Cannot assign `object[APIKeys.NAME]` to `name` because string is incompatible
with number.


Error ----------------------------------------------------- enum_client.js:21:18

Cannot assign `tuple[indices.red]` to `red` because number is incompatible with
string.


Error ----------------------------------------------------------- number.js:6:10

string is not a number.



Found 5 errors
