/**
 * Copyright (c) Meta Platforms, Inc. and affiliates.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 *
 * @format
 */

'use strict';

const FlowParserDeserializer = require('./FlowParserDeserializer');
const FlowParserWASMModule = require('./FlowParserWASM');

let FlowParserWASM;
let flowParse;
let flowParseResult_free;
let flowParseResult_getError;
let flowParseResult_getErrorLine;
let flowParseResult_getErrorColumn;
let flowParseResult_getProgramBuffer;
let flowParseResult_getPositionBuffer;
let flowParseResult_getPositionBufferSize;
let flowParseResult_getStringBuffer;

/**
 * Init the WASM wrapper code generated by `emscripten` for the
 * Flow Rust parser WASM binary.
 */
function initFlowParserWASM() {
  if (FlowParserWASM != null) {
    return;
  }

  FlowParserWASM = FlowParserWASMModule({
    quit(_status, toThrow) {
      throw toThrow;
    },
  });

  // The Flow Rust WASM binary exports an extended C ABI: the original
  // Hermes signature plus a (sourceFilename, sourceFilenameSize) pair that
  // lets the parser switch on file extension (.flow / .d.ts / .d.cts /
  // .d.mts) for ambient-context handling, plus an explicit
  // `enableDecorators` flag (Stage-1 decorator syntax) so fixtures that
  // disable decorators can exercise the unexpected-`@` error path, an
  // `assertOperator` flag to enable Flow's `expr!` non-null assertion,
  // `enableEnums` / `enableRecords` flags that mirror OCaml's
  // `default_parse_options` (both off by default; fixtures that use enum
  // or record syntax opt in via their `.options.json`), an `enableTypes`
  // flag that mirrors OCaml's `types` option (on by default; fixtures that
  // need to exercise the no-type-grammar path opt out via `types: false`),
  // and a `sourceType` integer (0=unspecified/detect, 1=script, 2=module)
  // that mirrors the JS-level `options.sourceType` so the parser can switch
  // between script and module modes (and detect via @flow pragma when 0).
  flowParse = FlowParserWASM.cwrap('hermesParse', 'number', [
    'number',
    'number',
    'number',
    'number',
    'number',
    'number',
    'number',
    'number',
    'number',
    'number',
    'number',
    'number',
    'number',
    'number',
    'number',
  ]);

  flowParseResult_free = FlowParserWASM.cwrap(
    'hermesParseResult_free',
    'void',
    ['number'],
  );

  flowParseResult_getError = FlowParserWASM.cwrap(
    'hermesParseResult_getError',
    'string',
    ['number'],
  );

  flowParseResult_getErrorLine = FlowParserWASM.cwrap(
    'hermesParseResult_getErrorLine',
    'number',
    ['number'],
  );

  flowParseResult_getErrorColumn = FlowParserWASM.cwrap(
    'hermesParseResult_getErrorColumn',
    'number',
    ['number'],
  );

  flowParseResult_getProgramBuffer = FlowParserWASM.cwrap(
    'hermesParseResult_getProgramBuffer',
    'number',
    ['number'],
  );

  flowParseResult_getPositionBuffer = FlowParserWASM.cwrap(
    'hermesParseResult_getPositionBuffer',
    'number',
    ['number'],
  );

  flowParseResult_getPositionBufferSize = FlowParserWASM.cwrap(
    'hermesParseResult_getPositionBufferSize',
    'number',
    ['number'],
  );

  flowParseResult_getStringBuffer = FlowParserWASM.cwrap(
    'hermesParseResult_getStringBuffer',
    'number',
    ['number'],
  );
}

// Copy a string into the WASM heap and null-terminate
function copyToHeap(buffer, addr) {
  FlowParserWASM.HEAP8.set(buffer, addr);
  FlowParserWASM.HEAP8[addr + buffer.length] = 0;
}

// Coerce any option value to the 0/1 expected by the C ABI. Anything other
// than the literal boolean `true` is treated as `false` so callers can't
// accidentally pass `undefined`/`null`/strings and get NaN at the cwrap
// boundary.
function flag(v) {
  return v === true ? 1 : 0;
}

function parse(source, options) {
  initFlowParserWASM();

  const sourceBuffer = Buffer.from(source, 'utf8');
  // Plumb the source filename into WASM so the parser can inspect file
  // extensions (.flow / .d.ts / .d.cts / .d.mts) for ambient context. When
  // no filename is provided we pass NULL/0 — the parser falls back to its
  // non-ambient defaults.
  const filename =
    typeof options.sourceFilename === 'string' ? options.sourceFilename : '';
  const filenameBuffer =
    filename.length > 0 ? Buffer.from(filename, 'utf8') : null;

  // All wasm allocations live inside a single try/finally so a throw from
  // any malloc, copyToHeap, or the parse call itself frees everything we
  // managed to allocate. Earlier versions allocated and partially populated
  // before entering the try, so a throw from copyToHeap leaked the wasm
  // address back to the heap.
  let sourceAddr = 0;
  let filenameAddr = 0;
  let filenameLen = 0;
  let parseResult = 0;
  try {
    sourceAddr = FlowParserWASM._malloc(sourceBuffer.length + 1);
    if (!sourceAddr) {
      throw new Error('Parser out of memory');
    }
    if (filenameBuffer != null) {
      filenameAddr = FlowParserWASM._malloc(filenameBuffer.length + 1);
      if (!filenameAddr) {
        throw new Error('Parser out of memory');
      }
      copyToHeap(filenameBuffer, filenameAddr);
      filenameLen = filenameBuffer.length + 1;
    }
    copyToHeap(sourceBuffer, sourceAddr);

    // `enableTypes` mirrors OCaml's `types` option, which defaults to true.
    // Fixtures opt out via `types: false` to exercise the no-type-grammar
    // path (e.g. ts_syntax fixtures testing that `as`/`satisfies` are not
    // parsed when types are disabled).
    const enableTypes = options.enableTypes === false ? 0 : 1;
    // `sourceType` is sent to Rust as an integer code:
    //   0 = unspecified / parser default
    //   1 = 'script' (script-with-import/export toleration)
    //   2 = 'module' — currently unsupported by flow_parser (no top-level
    //       await; see parser_env.rs:392-393), so this *intentionally*
    //       trips the Rust-side panic at lib.rs:128-147. Callers who want
    //       parser-default behaviour should pass `sourceType: 'unambiguous'`
    //       (which index.js deletes → undefined → 0) or omit `sourceType`.
    //       Silently collapsing 'module' onto 0 would mis-parse module-only
    //       syntax (top-level await) under script semantics — better to
    //       fail loud than silently produce a wrong AST.
    const sourceTypeCode =
      options.sourceType === 'script'
        ? 1
        : options.sourceType === 'module'
          ? 2
          : 0;
    parseResult = flowParse(
      sourceAddr,
      sourceBuffer.length + 1,
      filenameAddr,
      filenameLen,
      flag(options.flow === 'detect'),
      flag(options.enableExperimentalComponentSyntax),
      flag(options.enableExperimentalFlowMatchSyntax),
      // Decorators default to disabled — OCaml's `default_parse_options`
      // sets `esproposal_decorators = false`. Opt in via
      // `enableExperimentalDecorators: true`.
      flag(options.enableExperimentalDecorators),
      flag(options.tokens),
      flag(options.allowReturnOutsideFunction),
      // `assertOperator` enables Flow's `expr!` non-null assertion.
      flag(options.assertOperator),
      // `enableEnums` / `enableRecords` mirror OCaml's `default_parse_options`
      // (both default to false; fixtures opt in via their `.options.json`).
      flag(options.enableEnums),
      flag(options.enableRecords),
      enableTypes,
      sourceTypeCode,
    );

    // The Rust parser always returns a (possibly partial) AST plus an
    // error list, mirroring the OCaml behaviour. Errors are surfaced as
    // `program.errors` by the deserializer; only fall back to throwing if
    // we got back no program buffer at all (e.g. invalid UTF-8).
    const programBuffer = flowParseResult_getProgramBuffer(parseResult);
    if (!programBuffer) {
      const err = flowParseResult_getError(parseResult);
      const syntaxError = new SyntaxError(err || 'unknown parse error');
      syntaxError.loc = {
        line: flowParseResult_getErrorLine(parseResult),
        column: flowParseResult_getErrorColumn(parseResult),
      };
      throw syntaxError;
    }

    const deserializer = new FlowParserDeserializer(
      programBuffer,
      flowParseResult_getPositionBuffer(parseResult),
      flowParseResult_getPositionBufferSize(parseResult),
      flowParseResult_getStringBuffer(parseResult),
      FlowParserWASM,
      options,
    );
    return deserializer.deserialize();
  } finally {
    if (parseResult !== 0) {
      flowParseResult_free(parseResult);
    }
    if (sourceAddr !== 0) {
      FlowParserWASM._free(sourceAddr);
    }
    if (filenameAddr !== 0) {
      FlowParserWASM._free(filenameAddr);
    }
  }
}

module.exports = {parse};
