/**
 * @format
 * @flow
 */

import {foo1, foo2} from './foo';

foo1 as empty;
// intentionally empty line
// intentionally empty line
// intentionally empty line
// intentionally empty line
// intentionally empty line
// intentionally empty line
// intentionally empty line
// intentionally empty line
// intentionally empty line
// intentionally empty line
// intentionally empty line
// intentionally empty line
// intentionally empty line
// intentionally empty line
// intentionally empty line
// intentionally empty line
// intentionally empty line
// intentionally empty line
// intentionally empty line
// intentionally empty line
// intentionally empty line
// intentionally empty line
// intentionally empty line
// intentionally empty line
// intentionally empty line
// intentionally empty line
// intentionally empty line
// intentionally empty line
// intentionally empty line
// intentionally empty line
// intentionally empty line
// intentionally empty line
// intentionally empty line
// intentionally empty line
// intentionally empty line
// intentionally empty line
// intentionally empty line
// intentionally empty line
// intentionally empty line
// intentionally empty line
// intentionally empty line
// intentionally empty line
// intentionally empty line
// intentionally empty line
// intentionally empty line
// intentionally empty line
// intentionally empty line
// intentionally empty line
// intentionally empty line
// intentionally empty line
// intentionally empty line
// intentionally empty line
// intentionally empty line
// intentionally empty line
// intentionally empty line
// intentionally empty line
// intentionally empty line
// intentionally empty line
// intentionally empty line
// intentionally empty line
// intentionally empty line
// intentionally empty line
// intentionally empty line
// intentionally empty line
// intentionally empty line
// intentionally empty line
// intentionally empty line
// intentionally empty line
// intentionally empty line
// intentionally empty line
// intentionally empty line
// intentionally empty line
// intentionally empty line
// intentionally empty line
// intentionally empty line
// intentionally empty line
// intentionally empty line
// intentionally empty line
// intentionally empty line
// intentionally empty line
// intentionally empty line
// intentionally empty line
// intentionally empty line
// intentionally empty line
// intentionally empty line
// intentionally empty line
// intentionally empty line
// intentionally empty line
// intentionally empty line
// intentionally empty line
// intentionally empty line
// intentionally empty line
// intentionally empty line
foo2 as empty;
