// flow-typed signature: 70608f6f191453b7b77ad5be23512600
// flow-typed version: <<STUB>>/chalk_v^2.0.1/flow_v0.50.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'chalk'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'chalk' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'chalk/templates' {
  declare module.exports: any;
}

// Filename aliases
declare module 'chalk/index' {
  declare module.exports: $Exports<'chalk'>;
}
declare module 'chalk/index.js' {
  declare module.exports: $Exports<'chalk'>;
}
declare module 'chalk/templates.js' {
  declare module.exports: $Exports<'chalk/templates'>;
}
