// flow-typed signature: d3a9153742c3864b61ec9b80d605a1e3
// flow-typed version: <<STUB>>/jscodeshift_vcalebmer/jscodeshift#patch-1/flow_v0.50.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'jscodeshift'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'jscodeshift' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'jscodeshift/bin/__tests__/jscodeshift-test' {
  declare module.exports: any;
}

declare module 'jscodeshift/docs/scripts/linenumber' {
  declare module.exports: any;
}

declare module 'jscodeshift/docs/scripts/prettify/lang-css' {
  declare module.exports: any;
}

declare module 'jscodeshift/docs/scripts/prettify/prettify' {
  declare module.exports: any;
}

declare module 'jscodeshift/parser/babylon' {
  declare module.exports: any;
}

declare module 'jscodeshift/parser/flow' {
  declare module.exports: any;
}

declare module 'jscodeshift/sample/__testfixtures__/reverse-identifiers.input' {
  declare module.exports: any;
}

declare module 'jscodeshift/sample/__testfixtures__/reverse-identifiers.output' {
  declare module.exports: any;
}

declare module 'jscodeshift/sample/__tests__/reverse-identifiers-test' {
  declare module.exports: any;
}

declare module 'jscodeshift/sample/reverse-identifiers' {
  declare module.exports: any;
}

declare module 'jscodeshift/src/Collection' {
  declare module.exports: any;
}

declare module 'jscodeshift/src/Runner' {
  declare module.exports: any;
}

declare module 'jscodeshift/src/Worker' {
  declare module.exports: any;
}

declare module 'jscodeshift/src/__tests__/Collection-test' {
  declare module.exports: any;
}

declare module 'jscodeshift/src/__tests__/Worker-test' {
  declare module.exports: any;
}

declare module 'jscodeshift/src/__tests__/core-test' {
  declare module.exports: any;
}

declare module 'jscodeshift/src/__tests__/matchNode-test' {
  declare module.exports: any;
}

declare module 'jscodeshift/src/__tests__/template-test' {
  declare module.exports: any;
}

declare module 'jscodeshift/src/collections/JSXElement' {
  declare module.exports: any;
}

declare module 'jscodeshift/src/collections/Node' {
  declare module.exports: any;
}

declare module 'jscodeshift/src/collections/VariableDeclarator' {
  declare module.exports: any;
}

declare module 'jscodeshift/src/collections/__tests__/JSXElement-test' {
  declare module.exports: any;
}

declare module 'jscodeshift/src/collections/__tests__/Node-test' {
  declare module.exports: any;
}

declare module 'jscodeshift/src/collections/__tests__/VariableDeclarator-test' {
  declare module.exports: any;
}

declare module 'jscodeshift/src/collections/index' {
  declare module.exports: any;
}

declare module 'jscodeshift/src/core' {
  declare module.exports: any;
}

declare module 'jscodeshift/src/getParser' {
  declare module.exports: any;
}

declare module 'jscodeshift/src/ignoreFiles' {
  declare module.exports: any;
}

declare module 'jscodeshift/src/matchNode' {
  declare module.exports: any;
}

declare module 'jscodeshift/src/template' {
  declare module.exports: any;
}

declare module 'jscodeshift/src/testUtils' {
  declare module.exports: any;
}

declare module 'jscodeshift/utils/requirePackage' {
  declare module.exports: any;
}

declare module 'jscodeshift/utils/testUtils' {
  declare module.exports: any;
}

// Filename aliases
declare module 'jscodeshift/bin/__tests__/jscodeshift-test.js' {
  declare module.exports: $Exports<'jscodeshift/bin/__tests__/jscodeshift-test'>;
}
declare module 'jscodeshift/docs/scripts/linenumber.js' {
  declare module.exports: $Exports<'jscodeshift/docs/scripts/linenumber'>;
}
declare module 'jscodeshift/docs/scripts/prettify/lang-css.js' {
  declare module.exports: $Exports<'jscodeshift/docs/scripts/prettify/lang-css'>;
}
declare module 'jscodeshift/docs/scripts/prettify/prettify.js' {
  declare module.exports: $Exports<'jscodeshift/docs/scripts/prettify/prettify'>;
}
declare module 'jscodeshift/index' {
  declare module.exports: $Exports<'jscodeshift'>;
}
declare module 'jscodeshift/index.js' {
  declare module.exports: $Exports<'jscodeshift'>;
}
declare module 'jscodeshift/parser/babylon.js' {
  declare module.exports: $Exports<'jscodeshift/parser/babylon'>;
}
declare module 'jscodeshift/parser/flow.js' {
  declare module.exports: $Exports<'jscodeshift/parser/flow'>;
}
declare module 'jscodeshift/sample/__testfixtures__/reverse-identifiers.input.js' {
  declare module.exports: $Exports<'jscodeshift/sample/__testfixtures__/reverse-identifiers.input'>;
}
declare module 'jscodeshift/sample/__testfixtures__/reverse-identifiers.output.js' {
  declare module.exports: $Exports<'jscodeshift/sample/__testfixtures__/reverse-identifiers.output'>;
}
declare module 'jscodeshift/sample/__tests__/reverse-identifiers-test.js' {
  declare module.exports: $Exports<'jscodeshift/sample/__tests__/reverse-identifiers-test'>;
}
declare module 'jscodeshift/sample/reverse-identifiers.js' {
  declare module.exports: $Exports<'jscodeshift/sample/reverse-identifiers'>;
}
declare module 'jscodeshift/src/Collection.js' {
  declare module.exports: $Exports<'jscodeshift/src/Collection'>;
}
declare module 'jscodeshift/src/Runner.js' {
  declare module.exports: $Exports<'jscodeshift/src/Runner'>;
}
declare module 'jscodeshift/src/Worker.js' {
  declare module.exports: $Exports<'jscodeshift/src/Worker'>;
}
declare module 'jscodeshift/src/__tests__/Collection-test.js' {
  declare module.exports: $Exports<'jscodeshift/src/__tests__/Collection-test'>;
}
declare module 'jscodeshift/src/__tests__/Worker-test.js' {
  declare module.exports: $Exports<'jscodeshift/src/__tests__/Worker-test'>;
}
declare module 'jscodeshift/src/__tests__/core-test.js' {
  declare module.exports: $Exports<'jscodeshift/src/__tests__/core-test'>;
}
declare module 'jscodeshift/src/__tests__/matchNode-test.js' {
  declare module.exports: $Exports<'jscodeshift/src/__tests__/matchNode-test'>;
}
declare module 'jscodeshift/src/__tests__/template-test.js' {
  declare module.exports: $Exports<'jscodeshift/src/__tests__/template-test'>;
}
declare module 'jscodeshift/src/collections/JSXElement.js' {
  declare module.exports: $Exports<'jscodeshift/src/collections/JSXElement'>;
}
declare module 'jscodeshift/src/collections/Node.js' {
  declare module.exports: $Exports<'jscodeshift/src/collections/Node'>;
}
declare module 'jscodeshift/src/collections/VariableDeclarator.js' {
  declare module.exports: $Exports<'jscodeshift/src/collections/VariableDeclarator'>;
}
declare module 'jscodeshift/src/collections/__tests__/JSXElement-test.js' {
  declare module.exports: $Exports<'jscodeshift/src/collections/__tests__/JSXElement-test'>;
}
declare module 'jscodeshift/src/collections/__tests__/Node-test.js' {
  declare module.exports: $Exports<'jscodeshift/src/collections/__tests__/Node-test'>;
}
declare module 'jscodeshift/src/collections/__tests__/VariableDeclarator-test.js' {
  declare module.exports: $Exports<'jscodeshift/src/collections/__tests__/VariableDeclarator-test'>;
}
declare module 'jscodeshift/src/collections/index.js' {
  declare module.exports: $Exports<'jscodeshift/src/collections/index'>;
}
declare module 'jscodeshift/src/core.js' {
  declare module.exports: $Exports<'jscodeshift/src/core'>;
}
declare module 'jscodeshift/src/getParser.js' {
  declare module.exports: $Exports<'jscodeshift/src/getParser'>;
}
declare module 'jscodeshift/src/ignoreFiles.js' {
  declare module.exports: $Exports<'jscodeshift/src/ignoreFiles'>;
}
declare module 'jscodeshift/src/matchNode.js' {
  declare module.exports: $Exports<'jscodeshift/src/matchNode'>;
}
declare module 'jscodeshift/src/template.js' {
  declare module.exports: $Exports<'jscodeshift/src/template'>;
}
declare module 'jscodeshift/src/testUtils.js' {
  declare module.exports: $Exports<'jscodeshift/src/testUtils'>;
}
declare module 'jscodeshift/utils/requirePackage.js' {
  declare module.exports: $Exports<'jscodeshift/utils/requirePackage'>;
}
declare module 'jscodeshift/utils/testUtils.js' {
  declare module.exports: $Exports<'jscodeshift/utils/testUtils'>;
}
