// flow-typed signature: cc6a2269a70ee08a2b104a1555b07069
// flow-typed version: <<STUB>>/prompt-confirm_v^1.2.0/flow_v0.50.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'prompt-confirm'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'prompt-confirm' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'prompt-confirm/index' {
  declare module.exports: $Exports<'prompt-confirm'>;
}
declare module 'prompt-confirm/index.js' {
  declare module.exports: $Exports<'prompt-confirm'>;
}
