Error ----------------------------------------------------------------------------------------------------- test.js:27:2

Cannot create `ClassExact_NoProps` element because property `foo` is missing in `Props_NoProps` [1] but exists in
props [2]. [prop-missing]

   test.js:27:2
   27| <ClassExact_NoProps foo={42} />; // Error: Exact type does not have `foo`.
        ^^^^^^^^^^^^^^^^^^

References:
   test.js:25:57
   25| class ClassExact_NoProps extends React.Component<$Exact<Props_NoProps>> {}
                                                               ^^^^^^^^^^^^^ [1]
   test.js:27:1
   27| <ClassExact_NoProps foo={42} />; // Error: Exact type does not have `foo`.
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ [2]


Error ----------------------------------------------------------------------------------------------------- test.js:39:2

Cannot create `FunctionExact_NoProps` element because property `foo` is missing in `Props_NoProps` [1] but exists in
props [2]. [prop-missing]

   test.js:39:2
   39| <FunctionExact_NoProps foo={42} />; // Error: Exact type does not have `foo`.
        ^^^^^^^^^^^^^^^^^^^^^

References:
   test.js:37:46
   37| const FunctionExact_NoProps = (props: $Exact<Props_NoProps>) => any;
                                                    ^^^^^^^^^^^^^ [1]
   test.js:39:1
   39| <FunctionExact_NoProps foo={42} />; // Error: Exact type does not have `foo`.
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ [2]


Error ----------------------------------------------------------------------------------------------------- test.js:47:2

Cannot create `AbstractExact_NoProps` element because property `foo` is missing in `Props_NoProps` [1] but exists in
props [2]. [prop-missing]

   test.js:47:2
   47| <AbstractExact_NoProps foo={42} />; // Error: Exact type does not have `foo`.
        ^^^^^^^^^^^^^^^^^^^^^

References:
   test.js:45:57
   45| const AbstractExact_NoProps: React.ComponentType<$Exact<Props_NoProps>> = any;
                                                               ^^^^^^^^^^^^^ [1]
   test.js:47:1
   47| <AbstractExact_NoProps foo={42} />; // Error: Exact type does not have `foo`.
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ [2]


Error ----------------------------------------------------------------------------------------------------- test.js:74:2

Cannot create `Class_ManyProps` element because property `boolean1` is missing in props [1] but exists in
`Props_ManyProps` [2]. [prop-missing]

   test.js:74:2
   74| <Class_ManyProps />; // Error: There are no props.
        ^^^^^^^^^^^^^^^

References:
   test.js:74:1
   74| <Class_ManyProps />; // Error: There are no props.
       ^^^^^^^^^^^^^^^^^^^ [1]
   test.js:73:47
   73| class Class_ManyProps extends React.Component<Props_ManyProps> {}
                                                     ^^^^^^^^^^^^^^^ [2]


Error ----------------------------------------------------------------------------------------------------- test.js:74:2

Cannot create `Class_ManyProps` element because property `boolean2` is missing in props [1] but exists in
`Props_ManyProps` [2]. [prop-missing]

   test.js:74:2
   74| <Class_ManyProps />; // Error: There are no props.
        ^^^^^^^^^^^^^^^

References:
   test.js:74:1
   74| <Class_ManyProps />; // Error: There are no props.
       ^^^^^^^^^^^^^^^^^^^ [1]
   test.js:73:47
   73| class Class_ManyProps extends React.Component<Props_ManyProps> {}
                                                     ^^^^^^^^^^^^^^^ [2]


Error ----------------------------------------------------------------------------------------------------- test.js:74:2

Cannot create `Class_ManyProps` element because property `number` is missing in props [1] but exists in
`Props_ManyProps` [2]. [prop-missing]

   test.js:74:2
   74| <Class_ManyProps />; // Error: There are no props.
        ^^^^^^^^^^^^^^^

References:
   test.js:74:1
   74| <Class_ManyProps />; // Error: There are no props.
       ^^^^^^^^^^^^^^^^^^^ [1]
   test.js:73:47
   73| class Class_ManyProps extends React.Component<Props_ManyProps> {}
                                                     ^^^^^^^^^^^^^^^ [2]


Error ----------------------------------------------------------------------------------------------------- test.js:74:2

Cannot create `Class_ManyProps` element because property `string1` is missing in props [1] but exists in
`Props_ManyProps` [2]. [prop-missing]

   test.js:74:2
   74| <Class_ManyProps />; // Error: There are no props.
        ^^^^^^^^^^^^^^^

References:
   test.js:74:1
   74| <Class_ManyProps />; // Error: There are no props.
       ^^^^^^^^^^^^^^^^^^^ [1]
   test.js:73:47
   73| class Class_ManyProps extends React.Component<Props_ManyProps> {}
                                                     ^^^^^^^^^^^^^^^ [2]


Error ----------------------------------------------------------------------------------------------------- test.js:74:2

Cannot create `Class_ManyProps` element because property `string2` is missing in props [1] but exists in
`Props_ManyProps` [2]. [prop-missing]

   test.js:74:2
   74| <Class_ManyProps />; // Error: There are no props.
        ^^^^^^^^^^^^^^^

References:
   test.js:74:1
   74| <Class_ManyProps />; // Error: There are no props.
       ^^^^^^^^^^^^^^^^^^^ [1]
   test.js:73:47
   73| class Class_ManyProps extends React.Component<Props_ManyProps> {}
                                                     ^^^^^^^^^^^^^^^ [2]


Error ---------------------------------------------------------------------------------------------------- test.js:93:12

Cannot create `Class_ManyProps` element because null [1] is incompatible with string [2] in property `string1`.
[incompatible-type]

   test.js:93:12
   93|   string1={null}
                  ^^^^ [1]

References:
   test.js:66:12
   66|   string1: string,
                  ^^^^^^ [2]


Error ---------------------------------------------------------------------------------------------------- test.js:94:12

Cannot create `Class_ManyProps` element because null [1] is incompatible with string [2] in property `string2`.
[incompatible-type]

   test.js:94:12
   94|   string2={null}
                  ^^^^ [1]

References:
   test.js:67:12
   67|   string2: string,
                  ^^^^^^ [2]


Error ---------------------------------------------------------------------------------------------------- test.js:95:13

Cannot create `Class_ManyProps` element because null [1] is incompatible with boolean [2] in property `boolean1`.
[incompatible-type]

   test.js:95:13
   95|   boolean1={null}
                   ^^^^ [1]

References:
   test.js:68:13
   68|   boolean1: boolean,
                   ^^^^^^^ [2]


Error ---------------------------------------------------------------------------------------------------- test.js:96:13

Cannot create `Class_ManyProps` element because null [1] is incompatible with boolean [2] in property `boolean2`.
[incompatible-type]

   test.js:96:13
   96|   boolean2={null}
                   ^^^^ [1]

References:
   test.js:69:13
   69|   boolean2: boolean,
                   ^^^^^^^ [2]


Error ---------------------------------------------------------------------------------------------------- test.js:97:11

Cannot create `Class_ManyProps` element because null [1] is incompatible with number [2] in property `number`.
[incompatible-type]

   test.js:97:11
   97|   number={null}
                 ^^^^ [1]

References:
   test.js:70:11
   70|   number: number,
                 ^^^^^^ [2]


Error ---------------------------------------------------------------------------------------------------- test.js:111:2

Cannot create `Class_ManyProps` element because property `number` is missing in props [1] but exists in
`Props_ManyProps` [2]. [prop-missing]

   test.js:111:2
   111| <Class_ManyProps // Error: Missing `number`.
         ^^^^^^^^^^^^^^^

References:
   test.js:111:1
        v-------------------------------------------
   111| <Class_ManyProps // Error: Missing `number`.
   112|   {...{string1: 'foo', string2: 'bar'}}
   113|   {...{boolean1: true, boolean2: false}}
   114| />;
        -^ [1]
   test.js:73:47
    73| class Class_ManyProps extends React.Component<Props_ManyProps> {}
                                                      ^^^^^^^^^^^^^^^ [2]


Error --------------------------------------------------------------------------------------------------- test.js:132:54

Cannot create `Class_ManyProps` element because null or undefined [1] is incompatible with number [2] in property
`number`. [incompatible-type]

   test.js:132:54
   132|   {...{string1: 'foo', string2: 'bar', number: (any: ?number)}}
                                                             ^^^^^^^ [1]

References:
   test.js:70:11
    70|   number: number,
                  ^^^^^^ [2]


Error ---------------------------------------------------------------------------------------------------- test.js:136:2

Cannot create `ClassExact_ManyProps` element because property `boolean1` is missing in props [1] but exists in
`Props_ManyProps` [2]. [prop-missing]

   test.js:136:2
   136| <ClassExact_ManyProps />; // Error: There are no props.
         ^^^^^^^^^^^^^^^^^^^^

References:
   test.js:136:1
   136| <ClassExact_ManyProps />; // Error: There are no props.
        ^^^^^^^^^^^^^^^^^^^^^^^^ [1]
   test.js:135:59
   135| class ClassExact_ManyProps extends React.Component<$Exact<Props_ManyProps>> {}
                                                                  ^^^^^^^^^^^^^^^ [2]


Error ---------------------------------------------------------------------------------------------------- test.js:136:2

Cannot create `ClassExact_ManyProps` element because property `boolean2` is missing in props [1] but exists in
`Props_ManyProps` [2]. [prop-missing]

   test.js:136:2
   136| <ClassExact_ManyProps />; // Error: There are no props.
         ^^^^^^^^^^^^^^^^^^^^

References:
   test.js:136:1
   136| <ClassExact_ManyProps />; // Error: There are no props.
        ^^^^^^^^^^^^^^^^^^^^^^^^ [1]
   test.js:135:59
   135| class ClassExact_ManyProps extends React.Component<$Exact<Props_ManyProps>> {}
                                                                  ^^^^^^^^^^^^^^^ [2]


Error ---------------------------------------------------------------------------------------------------- test.js:136:2

Cannot create `ClassExact_ManyProps` element because property `number` is missing in props [1] but exists in
`Props_ManyProps` [2]. [prop-missing]

   test.js:136:2
   136| <ClassExact_ManyProps />; // Error: There are no props.
         ^^^^^^^^^^^^^^^^^^^^

References:
   test.js:136:1
   136| <ClassExact_ManyProps />; // Error: There are no props.
        ^^^^^^^^^^^^^^^^^^^^^^^^ [1]
   test.js:135:59
   135| class ClassExact_ManyProps extends React.Component<$Exact<Props_ManyProps>> {}
                                                                  ^^^^^^^^^^^^^^^ [2]


Error ---------------------------------------------------------------------------------------------------- test.js:136:2

Cannot create `ClassExact_ManyProps` element because property `string1` is missing in props [1] but exists in
`Props_ManyProps` [2]. [prop-missing]

   test.js:136:2
   136| <ClassExact_ManyProps />; // Error: There are no props.
         ^^^^^^^^^^^^^^^^^^^^

References:
   test.js:136:1
   136| <ClassExact_ManyProps />; // Error: There are no props.
        ^^^^^^^^^^^^^^^^^^^^^^^^ [1]
   test.js:135:59
   135| class ClassExact_ManyProps extends React.Component<$Exact<Props_ManyProps>> {}
                                                                  ^^^^^^^^^^^^^^^ [2]


Error ---------------------------------------------------------------------------------------------------- test.js:136:2

Cannot create `ClassExact_ManyProps` element because property `string2` is missing in props [1] but exists in
`Props_ManyProps` [2]. [prop-missing]

   test.js:136:2
   136| <ClassExact_ManyProps />; // Error: There are no props.
         ^^^^^^^^^^^^^^^^^^^^

References:
   test.js:136:1
   136| <ClassExact_ManyProps />; // Error: There are no props.
        ^^^^^^^^^^^^^^^^^^^^^^^^ [1]
   test.js:135:59
   135| class ClassExact_ManyProps extends React.Component<$Exact<Props_ManyProps>> {}
                                                                  ^^^^^^^^^^^^^^^ [2]


Error ---------------------------------------------------------------------------------------------------- test.js:144:2

Cannot create `ClassExact_ManyProps` element because property `a` is missing in `Props_ManyProps` [1] but exists in
props [2]. [prop-missing]

   test.js:144:2
   144| <ClassExact_ManyProps // Error: Extra props are not allowed.
         ^^^^^^^^^^^^^^^^^^^^

References:
   test.js:135:59
   135| class ClassExact_ManyProps extends React.Component<$Exact<Props_ManyProps>> {}
                                                                  ^^^^^^^^^^^^^^^ [1]
   test.js:144:1
        v-----------------------------------------------------------
   144| <ClassExact_ManyProps // Error: Extra props are not allowed.
   145|   string1="foo"
   146|   string2={'bar'}
   147|   boolean1
   148|   boolean2={false}
   149|   number={42}
   150|   a={1}
   151|   b={2}
   152|   c={3}
   153| />;
        -^ [2]


Error ---------------------------------------------------------------------------------------------------- test.js:144:2

Cannot create `ClassExact_ManyProps` element because property `b` is missing in `Props_ManyProps` [1] but exists in
props [2]. [prop-missing]

   test.js:144:2
   144| <ClassExact_ManyProps // Error: Extra props are not allowed.
         ^^^^^^^^^^^^^^^^^^^^

References:
   test.js:135:59
   135| class ClassExact_ManyProps extends React.Component<$Exact<Props_ManyProps>> {}
                                                                  ^^^^^^^^^^^^^^^ [1]
   test.js:144:1
        v-----------------------------------------------------------
   144| <ClassExact_ManyProps // Error: Extra props are not allowed.
   145|   string1="foo"
   146|   string2={'bar'}
   147|   boolean1
   148|   boolean2={false}
   149|   number={42}
   150|   a={1}
   151|   b={2}
   152|   c={3}
   153| />;
        -^ [2]


Error ---------------------------------------------------------------------------------------------------- test.js:144:2

Cannot create `ClassExact_ManyProps` element because property `c` is missing in `Props_ManyProps` [1] but exists in
props [2]. [prop-missing]

   test.js:144:2
   144| <ClassExact_ManyProps // Error: Extra props are not allowed.
         ^^^^^^^^^^^^^^^^^^^^

References:
   test.js:135:59
   135| class ClassExact_ManyProps extends React.Component<$Exact<Props_ManyProps>> {}
                                                                  ^^^^^^^^^^^^^^^ [1]
   test.js:144:1
        v-----------------------------------------------------------
   144| <ClassExact_ManyProps // Error: Extra props are not allowed.
   145|   string1="foo"
   146|   string2={'bar'}
   147|   boolean1
   148|   boolean2={false}
   149|   number={42}
   150|   a={1}
   151|   b={2}
   152|   c={3}
   153| />;
        -^ [2]


Error --------------------------------------------------------------------------------------------------- test.js:155:12

Cannot create `ClassExact_ManyProps` element because null [1] is incompatible with string [2] in property `string1`.
[incompatible-type]

   test.js:155:12
   155|   string1={null}
                   ^^^^ [1]

References:
   test.js:66:12
    66|   string1: string,
                   ^^^^^^ [2]


Error --------------------------------------------------------------------------------------------------- test.js:156:12

Cannot create `ClassExact_ManyProps` element because null [1] is incompatible with string [2] in property `string2`.
[incompatible-type]

   test.js:156:12
   156|   string2={null}
                   ^^^^ [1]

References:
   test.js:67:12
    67|   string2: string,
                   ^^^^^^ [2]


Error --------------------------------------------------------------------------------------------------- test.js:157:13

Cannot create `ClassExact_ManyProps` element because null [1] is incompatible with boolean [2] in property `boolean1`.
[incompatible-type]

   test.js:157:13
   157|   boolean1={null}
                    ^^^^ [1]

References:
   test.js:68:13
    68|   boolean1: boolean,
                    ^^^^^^^ [2]


Error --------------------------------------------------------------------------------------------------- test.js:158:13

Cannot create `ClassExact_ManyProps` element because null [1] is incompatible with boolean [2] in property `boolean2`.
[incompatible-type]

   test.js:158:13
   158|   boolean2={null}
                    ^^^^ [1]

References:
   test.js:69:13
    69|   boolean2: boolean,
                    ^^^^^^^ [2]


Error --------------------------------------------------------------------------------------------------- test.js:159:11

Cannot create `ClassExact_ManyProps` element because null [1] is incompatible with number [2] in property `number`.
[incompatible-type]

   test.js:159:11
   159|   number={null}
                  ^^^^ [1]

References:
   test.js:70:11
    70|   number: number,
                  ^^^^^^ [2]


Error ---------------------------------------------------------------------------------------------------- test.js:173:2

Cannot create `ClassExact_ManyProps` element because property `number` is missing in props [1] but exists in
`Props_ManyProps` [2]. [prop-missing]

   test.js:173:2
   173| <ClassExact_ManyProps // Error: Missing `number`.
         ^^^^^^^^^^^^^^^^^^^^

References:
   test.js:173:1
        v------------------------------------------------
   173| <ClassExact_ManyProps // Error: Missing `number`.
   174|   {...{string1: 'foo', string2: 'bar'}}
   175|   {...{boolean1: true, boolean2: false}}
   176| />;
        -^ [1]
   test.js:135:59
   135| class ClassExact_ManyProps extends React.Component<$Exact<Props_ManyProps>> {}
                                                                  ^^^^^^^^^^^^^^^ [2]


Error ---------------------------------------------------------------------------------------------------- test.js:177:2

Cannot create `ClassExact_ManyProps` element because property `a` is missing in `Props_ManyProps` [1] but exists in
props [2]. [prop-missing]

   test.js:177:2
   177| <ClassExact_ManyProps // Error: Extra props are not allowed.
         ^^^^^^^^^^^^^^^^^^^^

References:
   test.js:135:59
   135| class ClassExact_ManyProps extends React.Component<$Exact<Props_ManyProps>> {}
                                                                  ^^^^^^^^^^^^^^^ [1]
   test.js:177:1
        v-----------------------------------------------------------
   177| <ClassExact_ManyProps // Error: Extra props are not allowed.
   178|   string1="foo"
   179|   string2={'bar'}
   180|   boolean1
   181|   boolean2={false}
   182|   {...{number: 42, a: 1, b: 2, c: 3}}
   183| />;
        -^ [2]


Error ---------------------------------------------------------------------------------------------------- test.js:177:2

Cannot create `ClassExact_ManyProps` element because property `b` is missing in `Props_ManyProps` [1] but exists in
props [2]. [prop-missing]

   test.js:177:2
   177| <ClassExact_ManyProps // Error: Extra props are not allowed.
         ^^^^^^^^^^^^^^^^^^^^

References:
   test.js:135:59
   135| class ClassExact_ManyProps extends React.Component<$Exact<Props_ManyProps>> {}
                                                                  ^^^^^^^^^^^^^^^ [1]
   test.js:177:1
        v-----------------------------------------------------------
   177| <ClassExact_ManyProps // Error: Extra props are not allowed.
   178|   string1="foo"
   179|   string2={'bar'}
   180|   boolean1
   181|   boolean2={false}
   182|   {...{number: 42, a: 1, b: 2, c: 3}}
   183| />;
        -^ [2]


Error ---------------------------------------------------------------------------------------------------- test.js:177:2

Cannot create `ClassExact_ManyProps` element because property `c` is missing in `Props_ManyProps` [1] but exists in
props [2]. [prop-missing]

   test.js:177:2
   177| <ClassExact_ManyProps // Error: Extra props are not allowed.
         ^^^^^^^^^^^^^^^^^^^^

References:
   test.js:135:59
   135| class ClassExact_ManyProps extends React.Component<$Exact<Props_ManyProps>> {}
                                                                  ^^^^^^^^^^^^^^^ [1]
   test.js:177:1
        v-----------------------------------------------------------
   177| <ClassExact_ManyProps // Error: Extra props are not allowed.
   178|   string1="foo"
   179|   string2={'bar'}
   180|   boolean1
   181|   boolean2={false}
   182|   {...{number: 42, a: 1, b: 2, c: 3}}
   183| />;
        -^ [2]


Error --------------------------------------------------------------------------------------------------- test.js:194:54

Cannot create `ClassExact_ManyProps` element because null or undefined [1] is incompatible with number [2] in property
`number`. [incompatible-type]

   test.js:194:54
   194|   {...{string1: 'foo', string2: 'bar', number: (any: ?number)}}
                                                             ^^^^^^^ [1]

References:
   test.js:70:11
    70|   number: number,
                  ^^^^^^ [2]


Error ---------------------------------------------------------------------------------------------------- test.js:198:2

Cannot create `ClassPure_ManyProps` element because property `boolean1` is missing in props [1] but exists in
`Props_ManyProps` [2]. [prop-missing]

   test.js:198:2
   198| <ClassPure_ManyProps />; // Error: There are no props.
         ^^^^^^^^^^^^^^^^^^^

References:
   test.js:198:1
   198| <ClassPure_ManyProps />; // Error: There are no props.
        ^^^^^^^^^^^^^^^^^^^^^^^ [1]
   test.js:197:55
   197| class ClassPure_ManyProps extends React.PureComponent<Props_ManyProps> {}
                                                              ^^^^^^^^^^^^^^^ [2]


Error ---------------------------------------------------------------------------------------------------- test.js:198:2

Cannot create `ClassPure_ManyProps` element because property `boolean2` is missing in props [1] but exists in
`Props_ManyProps` [2]. [prop-missing]

   test.js:198:2
   198| <ClassPure_ManyProps />; // Error: There are no props.
         ^^^^^^^^^^^^^^^^^^^

References:
   test.js:198:1
   198| <ClassPure_ManyProps />; // Error: There are no props.
        ^^^^^^^^^^^^^^^^^^^^^^^ [1]
   test.js:197:55
   197| class ClassPure_ManyProps extends React.PureComponent<Props_ManyProps> {}
                                                              ^^^^^^^^^^^^^^^ [2]


Error ---------------------------------------------------------------------------------------------------- test.js:198:2

Cannot create `ClassPure_ManyProps` element because property `number` is missing in props [1] but exists in
`Props_ManyProps` [2]. [prop-missing]

   test.js:198:2
   198| <ClassPure_ManyProps />; // Error: There are no props.
         ^^^^^^^^^^^^^^^^^^^

References:
   test.js:198:1
   198| <ClassPure_ManyProps />; // Error: There are no props.
        ^^^^^^^^^^^^^^^^^^^^^^^ [1]
   test.js:197:55
   197| class ClassPure_ManyProps extends React.PureComponent<Props_ManyProps> {}
                                                              ^^^^^^^^^^^^^^^ [2]


Error ---------------------------------------------------------------------------------------------------- test.js:198:2

Cannot create `ClassPure_ManyProps` element because property `string1` is missing in props [1] but exists in
`Props_ManyProps` [2]. [prop-missing]

   test.js:198:2
   198| <ClassPure_ManyProps />; // Error: There are no props.
         ^^^^^^^^^^^^^^^^^^^

References:
   test.js:198:1
   198| <ClassPure_ManyProps />; // Error: There are no props.
        ^^^^^^^^^^^^^^^^^^^^^^^ [1]
   test.js:197:55
   197| class ClassPure_ManyProps extends React.PureComponent<Props_ManyProps> {}
                                                              ^^^^^^^^^^^^^^^ [2]


Error ---------------------------------------------------------------------------------------------------- test.js:198:2

Cannot create `ClassPure_ManyProps` element because property `string2` is missing in props [1] but exists in
`Props_ManyProps` [2]. [prop-missing]

   test.js:198:2
   198| <ClassPure_ManyProps />; // Error: There are no props.
         ^^^^^^^^^^^^^^^^^^^

References:
   test.js:198:1
   198| <ClassPure_ManyProps />; // Error: There are no props.
        ^^^^^^^^^^^^^^^^^^^^^^^ [1]
   test.js:197:55
   197| class ClassPure_ManyProps extends React.PureComponent<Props_ManyProps> {}
                                                              ^^^^^^^^^^^^^^^ [2]


Error --------------------------------------------------------------------------------------------------- test.js:217:12

Cannot create `ClassPure_ManyProps` element because null [1] is incompatible with string [2] in property `string1`.
[incompatible-type]

   test.js:217:12
   217|   string1={null}
                   ^^^^ [1]

References:
   test.js:66:12
    66|   string1: string,
                   ^^^^^^ [2]


Error --------------------------------------------------------------------------------------------------- test.js:218:12

Cannot create `ClassPure_ManyProps` element because null [1] is incompatible with string [2] in property `string2`.
[incompatible-type]

   test.js:218:12
   218|   string2={null}
                   ^^^^ [1]

References:
   test.js:67:12
    67|   string2: string,
                   ^^^^^^ [2]


Error --------------------------------------------------------------------------------------------------- test.js:219:13

Cannot create `ClassPure_ManyProps` element because null [1] is incompatible with boolean [2] in property `boolean1`.
[incompatible-type]

   test.js:219:13
   219|   boolean1={null}
                    ^^^^ [1]

References:
   test.js:68:13
    68|   boolean1: boolean,
                    ^^^^^^^ [2]


Error --------------------------------------------------------------------------------------------------- test.js:220:13

Cannot create `ClassPure_ManyProps` element because null [1] is incompatible with boolean [2] in property `boolean2`.
[incompatible-type]

   test.js:220:13
   220|   boolean2={null}
                    ^^^^ [1]

References:
   test.js:69:13
    69|   boolean2: boolean,
                    ^^^^^^^ [2]


Error --------------------------------------------------------------------------------------------------- test.js:221:11

Cannot create `ClassPure_ManyProps` element because null [1] is incompatible with number [2] in property `number`.
[incompatible-type]

   test.js:221:11
   221|   number={null}
                  ^^^^ [1]

References:
   test.js:70:11
    70|   number: number,
                  ^^^^^^ [2]


Error ---------------------------------------------------------------------------------------------------- test.js:235:2

Cannot create `ClassPure_ManyProps` element because property `number` is missing in props [1] but exists in
`Props_ManyProps` [2]. [prop-missing]

   test.js:235:2
   235| <ClassPure_ManyProps // Error: Missing `number`.
         ^^^^^^^^^^^^^^^^^^^

References:
   test.js:235:1
        v-----------------------------------------------
   235| <ClassPure_ManyProps // Error: Missing `number`.
   236|   {...{string1: 'foo', string2: 'bar'}}
   237|   {...{boolean1: true, boolean2: false}}
   238| />;
        -^ [1]
   test.js:197:55
   197| class ClassPure_ManyProps extends React.PureComponent<Props_ManyProps> {}
                                                              ^^^^^^^^^^^^^^^ [2]


Error --------------------------------------------------------------------------------------------------- test.js:256:54

Cannot create `ClassPure_ManyProps` element because null or undefined [1] is incompatible with number [2] in property
`number`. [incompatible-type]

   test.js:256:54
   256|   {...{string1: 'foo', string2: 'bar', number: (any: ?number)}}
                                                             ^^^^^^^ [1]

References:
   test.js:70:11
    70|   number: number,
                  ^^^^^^ [2]


Error ---------------------------------------------------------------------------------------------------- test.js:260:2

Cannot create `Function_ManyProps` element because property `boolean1` is missing in props [1] but exists in
`Props_ManyProps` [2]. [prop-missing]

   test.js:260:2
   260| <Function_ManyProps />; // Error: There are no props.
         ^^^^^^^^^^^^^^^^^^

References:
   test.js:260:1
   260| <Function_ManyProps />; // Error: There are no props.
        ^^^^^^^^^^^^^^^^^^^^^^ [1]
   test.js:259:36
   259| const Function_ManyProps = (props: Props_ManyProps) => any;
                                           ^^^^^^^^^^^^^^^ [2]


Error ---------------------------------------------------------------------------------------------------- test.js:260:2

Cannot create `Function_ManyProps` element because property `boolean2` is missing in props [1] but exists in
`Props_ManyProps` [2]. [prop-missing]

   test.js:260:2
   260| <Function_ManyProps />; // Error: There are no props.
         ^^^^^^^^^^^^^^^^^^

References:
   test.js:260:1
   260| <Function_ManyProps />; // Error: There are no props.
        ^^^^^^^^^^^^^^^^^^^^^^ [1]
   test.js:259:36
   259| const Function_ManyProps = (props: Props_ManyProps) => any;
                                           ^^^^^^^^^^^^^^^ [2]


Error ---------------------------------------------------------------------------------------------------- test.js:260:2

Cannot create `Function_ManyProps` element because property `number` is missing in props [1] but exists in
`Props_ManyProps` [2]. [prop-missing]

   test.js:260:2
   260| <Function_ManyProps />; // Error: There are no props.
         ^^^^^^^^^^^^^^^^^^

References:
   test.js:260:1
   260| <Function_ManyProps />; // Error: There are no props.
        ^^^^^^^^^^^^^^^^^^^^^^ [1]
   test.js:259:36
   259| const Function_ManyProps = (props: Props_ManyProps) => any;
                                           ^^^^^^^^^^^^^^^ [2]


Error ---------------------------------------------------------------------------------------------------- test.js:260:2

Cannot create `Function_ManyProps` element because property `string1` is missing in props [1] but exists in
`Props_ManyProps` [2]. [prop-missing]

   test.js:260:2
   260| <Function_ManyProps />; // Error: There are no props.
         ^^^^^^^^^^^^^^^^^^

References:
   test.js:260:1
   260| <Function_ManyProps />; // Error: There are no props.
        ^^^^^^^^^^^^^^^^^^^^^^ [1]
   test.js:259:36
   259| const Function_ManyProps = (props: Props_ManyProps) => any;
                                           ^^^^^^^^^^^^^^^ [2]


Error ---------------------------------------------------------------------------------------------------- test.js:260:2

Cannot create `Function_ManyProps` element because property `string2` is missing in props [1] but exists in
`Props_ManyProps` [2]. [prop-missing]

   test.js:260:2
   260| <Function_ManyProps />; // Error: There are no props.
         ^^^^^^^^^^^^^^^^^^

References:
   test.js:260:1
   260| <Function_ManyProps />; // Error: There are no props.
        ^^^^^^^^^^^^^^^^^^^^^^ [1]
   test.js:259:36
   259| const Function_ManyProps = (props: Props_ManyProps) => any;
                                           ^^^^^^^^^^^^^^^ [2]


Error --------------------------------------------------------------------------------------------------- test.js:279:12

Cannot create `Function_ManyProps` element because null [1] is incompatible with string [2] in property `string1`.
[incompatible-type]

   test.js:279:12
   279|   string1={null}
                   ^^^^ [1]

References:
   test.js:66:12
    66|   string1: string,
                   ^^^^^^ [2]


Error --------------------------------------------------------------------------------------------------- test.js:280:12

Cannot create `Function_ManyProps` element because null [1] is incompatible with string [2] in property `string2`.
[incompatible-type]

   test.js:280:12
   280|   string2={null}
                   ^^^^ [1]

References:
   test.js:67:12
    67|   string2: string,
                   ^^^^^^ [2]


Error --------------------------------------------------------------------------------------------------- test.js:281:13

Cannot create `Function_ManyProps` element because null [1] is incompatible with boolean [2] in property `boolean1`.
[incompatible-type]

   test.js:281:13
   281|   boolean1={null}
                    ^^^^ [1]

References:
   test.js:68:13
    68|   boolean1: boolean,
                    ^^^^^^^ [2]


Error --------------------------------------------------------------------------------------------------- test.js:282:13

Cannot create `Function_ManyProps` element because null [1] is incompatible with boolean [2] in property `boolean2`.
[incompatible-type]

   test.js:282:13
   282|   boolean2={null}
                    ^^^^ [1]

References:
   test.js:69:13
    69|   boolean2: boolean,
                    ^^^^^^^ [2]


Error --------------------------------------------------------------------------------------------------- test.js:283:11

Cannot create `Function_ManyProps` element because null [1] is incompatible with number [2] in property `number`.
[incompatible-type]

   test.js:283:11
   283|   number={null}
                  ^^^^ [1]

References:
   test.js:70:11
    70|   number: number,
                  ^^^^^^ [2]


Error ---------------------------------------------------------------------------------------------------- test.js:297:2

Cannot create `Function_ManyProps` element because property `number` is missing in props [1] but exists in
`Props_ManyProps` [2]. [prop-missing]

   test.js:297:2
   297| <Function_ManyProps // Error: Missing `number`.
         ^^^^^^^^^^^^^^^^^^

References:
   test.js:297:1
        v----------------------------------------------
   297| <Function_ManyProps // Error: Missing `number`.
   298|   {...{string1: 'foo', string2: 'bar'}}
   299|   {...{boolean1: true, boolean2: false}}
   300| />;
        -^ [1]
   test.js:259:36
   259| const Function_ManyProps = (props: Props_ManyProps) => any;
                                           ^^^^^^^^^^^^^^^ [2]


Error --------------------------------------------------------------------------------------------------- test.js:318:54

Cannot create `Function_ManyProps` element because null or undefined [1] is incompatible with number [2] in property
`number`. [incompatible-type]

   test.js:318:54
   318|   {...{string1: 'foo', string2: 'bar', number: (any: ?number)}}
                                                             ^^^^^^^ [1]

References:
   test.js:70:11
    70|   number: number,
                  ^^^^^^ [2]


Error ---------------------------------------------------------------------------------------------------- test.js:322:2

Cannot create `FunctionExact_ManyProps` element because property `boolean1` is missing in props [1] but exists in
`Props_ManyProps` [2]. [prop-missing]

   test.js:322:2
   322| <FunctionExact_ManyProps />; // Error: There are no props.
         ^^^^^^^^^^^^^^^^^^^^^^^

References:
   test.js:322:1
   322| <FunctionExact_ManyProps />; // Error: There are no props.
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^ [1]
   test.js:321:48
   321| const FunctionExact_ManyProps = (props: $Exact<Props_ManyProps>) => any;
                                                       ^^^^^^^^^^^^^^^ [2]


Error ---------------------------------------------------------------------------------------------------- test.js:322:2

Cannot create `FunctionExact_ManyProps` element because property `boolean2` is missing in props [1] but exists in
`Props_ManyProps` [2]. [prop-missing]

   test.js:322:2
   322| <FunctionExact_ManyProps />; // Error: There are no props.
         ^^^^^^^^^^^^^^^^^^^^^^^

References:
   test.js:322:1
   322| <FunctionExact_ManyProps />; // Error: There are no props.
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^ [1]
   test.js:321:48
   321| const FunctionExact_ManyProps = (props: $Exact<Props_ManyProps>) => any;
                                                       ^^^^^^^^^^^^^^^ [2]


Error ---------------------------------------------------------------------------------------------------- test.js:322:2

Cannot create `FunctionExact_ManyProps` element because property `number` is missing in props [1] but exists in
`Props_ManyProps` [2]. [prop-missing]

   test.js:322:2
   322| <FunctionExact_ManyProps />; // Error: There are no props.
         ^^^^^^^^^^^^^^^^^^^^^^^

References:
   test.js:322:1
   322| <FunctionExact_ManyProps />; // Error: There are no props.
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^ [1]
   test.js:321:48
   321| const FunctionExact_ManyProps = (props: $Exact<Props_ManyProps>) => any;
                                                       ^^^^^^^^^^^^^^^ [2]


Error ---------------------------------------------------------------------------------------------------- test.js:322:2

Cannot create `FunctionExact_ManyProps` element because property `string1` is missing in props [1] but exists in
`Props_ManyProps` [2]. [prop-missing]

   test.js:322:2
   322| <FunctionExact_ManyProps />; // Error: There are no props.
         ^^^^^^^^^^^^^^^^^^^^^^^

References:
   test.js:322:1
   322| <FunctionExact_ManyProps />; // Error: There are no props.
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^ [1]
   test.js:321:48
   321| const FunctionExact_ManyProps = (props: $Exact<Props_ManyProps>) => any;
                                                       ^^^^^^^^^^^^^^^ [2]


Error ---------------------------------------------------------------------------------------------------- test.js:322:2

Cannot create `FunctionExact_ManyProps` element because property `string2` is missing in props [1] but exists in
`Props_ManyProps` [2]. [prop-missing]

   test.js:322:2
   322| <FunctionExact_ManyProps />; // Error: There are no props.
         ^^^^^^^^^^^^^^^^^^^^^^^

References:
   test.js:322:1
   322| <FunctionExact_ManyProps />; // Error: There are no props.
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^ [1]
   test.js:321:48
   321| const FunctionExact_ManyProps = (props: $Exact<Props_ManyProps>) => any;
                                                       ^^^^^^^^^^^^^^^ [2]


Error ---------------------------------------------------------------------------------------------------- test.js:330:2

Cannot create `FunctionExact_ManyProps` element because property `a` is missing in `Props_ManyProps` [1] but exists in
props [2]. [prop-missing]

   test.js:330:2
   330| <FunctionExact_ManyProps // OK: Other props are allowed.
         ^^^^^^^^^^^^^^^^^^^^^^^

References:
   test.js:321:48
   321| const FunctionExact_ManyProps = (props: $Exact<Props_ManyProps>) => any;
                                                       ^^^^^^^^^^^^^^^ [1]
   test.js:330:1
        v-------------------------------------------------------
   330| <FunctionExact_ManyProps // OK: Other props are allowed.
   331|   string1="foo"
   332|   string2={'bar'}
   333|   boolean1
   334|   boolean2={false}
   335|   number={42}
   336|   a={1}
   337|   b={2}
   338|   c={3}
   339| />;
        -^ [2]


Error ---------------------------------------------------------------------------------------------------- test.js:330:2

Cannot create `FunctionExact_ManyProps` element because property `b` is missing in `Props_ManyProps` [1] but exists in
props [2]. [prop-missing]

   test.js:330:2
   330| <FunctionExact_ManyProps // OK: Other props are allowed.
         ^^^^^^^^^^^^^^^^^^^^^^^

References:
   test.js:321:48
   321| const FunctionExact_ManyProps = (props: $Exact<Props_ManyProps>) => any;
                                                       ^^^^^^^^^^^^^^^ [1]
   test.js:330:1
        v-------------------------------------------------------
   330| <FunctionExact_ManyProps // OK: Other props are allowed.
   331|   string1="foo"
   332|   string2={'bar'}
   333|   boolean1
   334|   boolean2={false}
   335|   number={42}
   336|   a={1}
   337|   b={2}
   338|   c={3}
   339| />;
        -^ [2]


Error ---------------------------------------------------------------------------------------------------- test.js:330:2

Cannot create `FunctionExact_ManyProps` element because property `c` is missing in `Props_ManyProps` [1] but exists in
props [2]. [prop-missing]

   test.js:330:2
   330| <FunctionExact_ManyProps // OK: Other props are allowed.
         ^^^^^^^^^^^^^^^^^^^^^^^

References:
   test.js:321:48
   321| const FunctionExact_ManyProps = (props: $Exact<Props_ManyProps>) => any;
                                                       ^^^^^^^^^^^^^^^ [1]
   test.js:330:1
        v-------------------------------------------------------
   330| <FunctionExact_ManyProps // OK: Other props are allowed.
   331|   string1="foo"
   332|   string2={'bar'}
   333|   boolean1
   334|   boolean2={false}
   335|   number={42}
   336|   a={1}
   337|   b={2}
   338|   c={3}
   339| />;
        -^ [2]


Error --------------------------------------------------------------------------------------------------- test.js:341:12

Cannot create `FunctionExact_ManyProps` element because null [1] is incompatible with string [2] in property `string1`.
[incompatible-type]

   test.js:341:12
   341|   string1={null}
                   ^^^^ [1]

References:
   test.js:66:12
    66|   string1: string,
                   ^^^^^^ [2]


Error --------------------------------------------------------------------------------------------------- test.js:342:12

Cannot create `FunctionExact_ManyProps` element because null [1] is incompatible with string [2] in property `string2`.
[incompatible-type]

   test.js:342:12
   342|   string2={null}
                   ^^^^ [1]

References:
   test.js:67:12
    67|   string2: string,
                   ^^^^^^ [2]


Error --------------------------------------------------------------------------------------------------- test.js:343:13

Cannot create `FunctionExact_ManyProps` element because null [1] is incompatible with boolean [2] in property
`boolean1`. [incompatible-type]

   test.js:343:13
   343|   boolean1={null}
                    ^^^^ [1]

References:
   test.js:68:13
    68|   boolean1: boolean,
                    ^^^^^^^ [2]


Error --------------------------------------------------------------------------------------------------- test.js:344:13

Cannot create `FunctionExact_ManyProps` element because null [1] is incompatible with boolean [2] in property
`boolean2`. [incompatible-type]

   test.js:344:13
   344|   boolean2={null}
                    ^^^^ [1]

References:
   test.js:69:13
    69|   boolean2: boolean,
                    ^^^^^^^ [2]


Error --------------------------------------------------------------------------------------------------- test.js:345:11

Cannot create `FunctionExact_ManyProps` element because null [1] is incompatible with number [2] in property `number`.
[incompatible-type]

   test.js:345:11
   345|   number={null}
                  ^^^^ [1]

References:
   test.js:70:11
    70|   number: number,
                  ^^^^^^ [2]


Error ---------------------------------------------------------------------------------------------------- test.js:359:2

Cannot create `FunctionExact_ManyProps` element because property `number` is missing in props [1] but exists in
`Props_ManyProps` [2]. [prop-missing]

   test.js:359:2
   359| <FunctionExact_ManyProps // Error: Missing `number`.
         ^^^^^^^^^^^^^^^^^^^^^^^

References:
   test.js:359:1
        v---------------------------------------------------
   359| <FunctionExact_ManyProps // Error: Missing `number`.
   360|   {...{string1: 'foo', string2: 'bar'}}
   361|   {...{boolean1: true, boolean2: false}}
   362| />;
        -^ [1]
   test.js:321:48
   321| const FunctionExact_ManyProps = (props: $Exact<Props_ManyProps>) => any;
                                                       ^^^^^^^^^^^^^^^ [2]


Error ---------------------------------------------------------------------------------------------------- test.js:363:2

Cannot create `FunctionExact_ManyProps` element because property `a` is missing in `Props_ManyProps` [1] but exists in
props [2]. [prop-missing]

   test.js:363:2
   363| <FunctionExact_ManyProps // Error: Extra props are not allowed.
         ^^^^^^^^^^^^^^^^^^^^^^^

References:
   test.js:321:48
   321| const FunctionExact_ManyProps = (props: $Exact<Props_ManyProps>) => any;
                                                       ^^^^^^^^^^^^^^^ [1]
   test.js:363:1
        v--------------------------------------------------------------
   363| <FunctionExact_ManyProps // Error: Extra props are not allowed.
   364|   string1="foo"
   365|   string2={'bar'}
   366|   boolean1
   367|   boolean2={false}
   368|   {...{number: 42, a: 1, b: 2, c: 3}}
   369| />;
        -^ [2]


Error ---------------------------------------------------------------------------------------------------- test.js:363:2

Cannot create `FunctionExact_ManyProps` element because property `b` is missing in `Props_ManyProps` [1] but exists in
props [2]. [prop-missing]

   test.js:363:2
   363| <FunctionExact_ManyProps // Error: Extra props are not allowed.
         ^^^^^^^^^^^^^^^^^^^^^^^

References:
   test.js:321:48
   321| const FunctionExact_ManyProps = (props: $Exact<Props_ManyProps>) => any;
                                                       ^^^^^^^^^^^^^^^ [1]
   test.js:363:1
        v--------------------------------------------------------------
   363| <FunctionExact_ManyProps // Error: Extra props are not allowed.
   364|   string1="foo"
   365|   string2={'bar'}
   366|   boolean1
   367|   boolean2={false}
   368|   {...{number: 42, a: 1, b: 2, c: 3}}
   369| />;
        -^ [2]


Error ---------------------------------------------------------------------------------------------------- test.js:363:2

Cannot create `FunctionExact_ManyProps` element because property `c` is missing in `Props_ManyProps` [1] but exists in
props [2]. [prop-missing]

   test.js:363:2
   363| <FunctionExact_ManyProps // Error: Extra props are not allowed.
         ^^^^^^^^^^^^^^^^^^^^^^^

References:
   test.js:321:48
   321| const FunctionExact_ManyProps = (props: $Exact<Props_ManyProps>) => any;
                                                       ^^^^^^^^^^^^^^^ [1]
   test.js:363:1
        v--------------------------------------------------------------
   363| <FunctionExact_ManyProps // Error: Extra props are not allowed.
   364|   string1="foo"
   365|   string2={'bar'}
   366|   boolean1
   367|   boolean2={false}
   368|   {...{number: 42, a: 1, b: 2, c: 3}}
   369| />;
        -^ [2]


Error --------------------------------------------------------------------------------------------------- test.js:380:54

Cannot create `FunctionExact_ManyProps` element because null or undefined [1] is incompatible with number [2] in
property `number`. [incompatible-type]

   test.js:380:54
   380|   {...{string1: 'foo', string2: 'bar', number: (any: ?number)}}
                                                             ^^^^^^^ [1]

References:
   test.js:70:11
    70|   number: number,
                  ^^^^^^ [2]


Error ---------------------------------------------------------------------------------------------------- test.js:384:2

Cannot create `Abstract_ManyProps` element because property `boolean1` is missing in props [1] but exists in
`Props_ManyProps` [2]. [prop-missing]

   test.js:384:2
   384| <Abstract_ManyProps />; // Error: There are no props.
         ^^^^^^^^^^^^^^^^^^

References:
   test.js:384:1
   384| <Abstract_ManyProps />; // Error: There are no props.
        ^^^^^^^^^^^^^^^^^^^^^^ [1]
   test.js:383:47
   383| const Abstract_ManyProps: React.ComponentType<Props_ManyProps> = any;
                                                      ^^^^^^^^^^^^^^^ [2]


Error ---------------------------------------------------------------------------------------------------- test.js:384:2

Cannot create `Abstract_ManyProps` element because property `boolean2` is missing in props [1] but exists in
`Props_ManyProps` [2]. [prop-missing]

   test.js:384:2
   384| <Abstract_ManyProps />; // Error: There are no props.
         ^^^^^^^^^^^^^^^^^^

References:
   test.js:384:1
   384| <Abstract_ManyProps />; // Error: There are no props.
        ^^^^^^^^^^^^^^^^^^^^^^ [1]
   test.js:383:47
   383| const Abstract_ManyProps: React.ComponentType<Props_ManyProps> = any;
                                                      ^^^^^^^^^^^^^^^ [2]


Error ---------------------------------------------------------------------------------------------------- test.js:384:2

Cannot create `Abstract_ManyProps` element because property `number` is missing in props [1] but exists in
`Props_ManyProps` [2]. [prop-missing]

   test.js:384:2
   384| <Abstract_ManyProps />; // Error: There are no props.
         ^^^^^^^^^^^^^^^^^^

References:
   test.js:384:1
   384| <Abstract_ManyProps />; // Error: There are no props.
        ^^^^^^^^^^^^^^^^^^^^^^ [1]
   test.js:383:47
   383| const Abstract_ManyProps: React.ComponentType<Props_ManyProps> = any;
                                                      ^^^^^^^^^^^^^^^ [2]


Error ---------------------------------------------------------------------------------------------------- test.js:384:2

Cannot create `Abstract_ManyProps` element because property `string1` is missing in props [1] but exists in
`Props_ManyProps` [2]. [prop-missing]

   test.js:384:2
   384| <Abstract_ManyProps />; // Error: There are no props.
         ^^^^^^^^^^^^^^^^^^

References:
   test.js:384:1
   384| <Abstract_ManyProps />; // Error: There are no props.
        ^^^^^^^^^^^^^^^^^^^^^^ [1]
   test.js:383:47
   383| const Abstract_ManyProps: React.ComponentType<Props_ManyProps> = any;
                                                      ^^^^^^^^^^^^^^^ [2]


Error ---------------------------------------------------------------------------------------------------- test.js:384:2

Cannot create `Abstract_ManyProps` element because property `string2` is missing in props [1] but exists in
`Props_ManyProps` [2]. [prop-missing]

   test.js:384:2
   384| <Abstract_ManyProps />; // Error: There are no props.
         ^^^^^^^^^^^^^^^^^^

References:
   test.js:384:1
   384| <Abstract_ManyProps />; // Error: There are no props.
        ^^^^^^^^^^^^^^^^^^^^^^ [1]
   test.js:383:47
   383| const Abstract_ManyProps: React.ComponentType<Props_ManyProps> = any;
                                                      ^^^^^^^^^^^^^^^ [2]


Error --------------------------------------------------------------------------------------------------- test.js:403:12

Cannot create `Abstract_ManyProps` element because null [1] is incompatible with string [2] in property `string1`.
[incompatible-type]

   test.js:403:12
   403|   string1={null}
                   ^^^^ [1]

References:
   test.js:66:12
    66|   string1: string,
                   ^^^^^^ [2]


Error --------------------------------------------------------------------------------------------------- test.js:404:12

Cannot create `Abstract_ManyProps` element because null [1] is incompatible with string [2] in property `string2`.
[incompatible-type]

   test.js:404:12
   404|   string2={null}
                   ^^^^ [1]

References:
   test.js:67:12
    67|   string2: string,
                   ^^^^^^ [2]


Error --------------------------------------------------------------------------------------------------- test.js:405:13

Cannot create `Abstract_ManyProps` element because null [1] is incompatible with boolean [2] in property `boolean1`.
[incompatible-type]

   test.js:405:13
   405|   boolean1={null}
                    ^^^^ [1]

References:
   test.js:68:13
    68|   boolean1: boolean,
                    ^^^^^^^ [2]


Error --------------------------------------------------------------------------------------------------- test.js:406:13

Cannot create `Abstract_ManyProps` element because null [1] is incompatible with boolean [2] in property `boolean2`.
[incompatible-type]

   test.js:406:13
   406|   boolean2={null}
                    ^^^^ [1]

References:
   test.js:69:13
    69|   boolean2: boolean,
                    ^^^^^^^ [2]


Error --------------------------------------------------------------------------------------------------- test.js:407:11

Cannot create `Abstract_ManyProps` element because null [1] is incompatible with number [2] in property `number`.
[incompatible-type]

   test.js:407:11
   407|   number={null}
                  ^^^^ [1]

References:
   test.js:70:11
    70|   number: number,
                  ^^^^^^ [2]


Error ---------------------------------------------------------------------------------------------------- test.js:421:2

Cannot create `Abstract_ManyProps` element because property `number` is missing in props [1] but exists in
`Props_ManyProps` [2]. [prop-missing]

   test.js:421:2
   421| <Abstract_ManyProps // Error: Missing `number`.
         ^^^^^^^^^^^^^^^^^^

References:
   test.js:421:1
        v----------------------------------------------
   421| <Abstract_ManyProps // Error: Missing `number`.
   422|   {...{string1: 'foo', string2: 'bar'}}
   423|   {...{boolean1: true, boolean2: false}}
   424| />;
        -^ [1]
   test.js:383:47
   383| const Abstract_ManyProps: React.ComponentType<Props_ManyProps> = any;
                                                      ^^^^^^^^^^^^^^^ [2]


Error --------------------------------------------------------------------------------------------------- test.js:442:54

Cannot create `Abstract_ManyProps` element because null or undefined [1] is incompatible with number [2] in property
`number`. [incompatible-type]

   test.js:442:54
   442|   {...{string1: 'foo', string2: 'bar', number: (any: ?number)}}
                                                             ^^^^^^^ [1]

References:
   test.js:70:11
    70|   number: number,
                  ^^^^^^ [2]


Error ---------------------------------------------------------------------------------------------------- test.js:447:2

Cannot create `AbstractExact_ManyProps` element because property `boolean1` is missing in props [1] but exists in
`Props_ManyProps` [2]. [prop-missing]

   test.js:447:2
   447| <AbstractExact_ManyProps />; // Error: There are no props.
         ^^^^^^^^^^^^^^^^^^^^^^^

References:
   test.js:447:1
   447| <AbstractExact_ManyProps />; // Error: There are no props.
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^ [1]
   test.js:445:59
   445| const AbstractExact_ManyProps: React.ComponentType<$Exact<Props_ManyProps>>
                                                                  ^^^^^^^^^^^^^^^ [2]


Error ---------------------------------------------------------------------------------------------------- test.js:447:2

Cannot create `AbstractExact_ManyProps` element because property `boolean2` is missing in props [1] but exists in
`Props_ManyProps` [2]. [prop-missing]

   test.js:447:2
   447| <AbstractExact_ManyProps />; // Error: There are no props.
         ^^^^^^^^^^^^^^^^^^^^^^^

References:
   test.js:447:1
   447| <AbstractExact_ManyProps />; // Error: There are no props.
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^ [1]
   test.js:445:59
   445| const AbstractExact_ManyProps: React.ComponentType<$Exact<Props_ManyProps>>
                                                                  ^^^^^^^^^^^^^^^ [2]


Error ---------------------------------------------------------------------------------------------------- test.js:447:2

Cannot create `AbstractExact_ManyProps` element because property `number` is missing in props [1] but exists in
`Props_ManyProps` [2]. [prop-missing]

   test.js:447:2
   447| <AbstractExact_ManyProps />; // Error: There are no props.
         ^^^^^^^^^^^^^^^^^^^^^^^

References:
   test.js:447:1
   447| <AbstractExact_ManyProps />; // Error: There are no props.
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^ [1]
   test.js:445:59
   445| const AbstractExact_ManyProps: React.ComponentType<$Exact<Props_ManyProps>>
                                                                  ^^^^^^^^^^^^^^^ [2]


Error ---------------------------------------------------------------------------------------------------- test.js:447:2

Cannot create `AbstractExact_ManyProps` element because property `string1` is missing in props [1] but exists in
`Props_ManyProps` [2]. [prop-missing]

   test.js:447:2
   447| <AbstractExact_ManyProps />; // Error: There are no props.
         ^^^^^^^^^^^^^^^^^^^^^^^

References:
   test.js:447:1
   447| <AbstractExact_ManyProps />; // Error: There are no props.
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^ [1]
   test.js:445:59
   445| const AbstractExact_ManyProps: React.ComponentType<$Exact<Props_ManyProps>>
                                                                  ^^^^^^^^^^^^^^^ [2]


Error ---------------------------------------------------------------------------------------------------- test.js:447:2

Cannot create `AbstractExact_ManyProps` element because property `string2` is missing in props [1] but exists in
`Props_ManyProps` [2]. [prop-missing]

   test.js:447:2
   447| <AbstractExact_ManyProps />; // Error: There are no props.
         ^^^^^^^^^^^^^^^^^^^^^^^

References:
   test.js:447:1
   447| <AbstractExact_ManyProps />; // Error: There are no props.
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^ [1]
   test.js:445:59
   445| const AbstractExact_ManyProps: React.ComponentType<$Exact<Props_ManyProps>>
                                                                  ^^^^^^^^^^^^^^^ [2]


Error ---------------------------------------------------------------------------------------------------- test.js:455:2

Cannot create `AbstractExact_ManyProps` element because property `a` is missing in `Props_ManyProps` [1] but exists in
props [2]. [prop-missing]

   test.js:455:2
   455| <AbstractExact_ManyProps // Error: Other props are not allowed.
         ^^^^^^^^^^^^^^^^^^^^^^^

References:
   test.js:445:59
   445| const AbstractExact_ManyProps: React.ComponentType<$Exact<Props_ManyProps>>
                                                                  ^^^^^^^^^^^^^^^ [1]
   test.js:455:1
        v--------------------------------------------------------------
   455| <AbstractExact_ManyProps // Error: Other props are not allowed.
   456|   string1="foo"
   457|   string2={'bar'}
   458|   boolean1
   459|   boolean2={false}
   460|   number={42}
   461|   a={1}
   462|   b={2}
   463|   c={3}
   464| />;
        -^ [2]


Error ---------------------------------------------------------------------------------------------------- test.js:455:2

Cannot create `AbstractExact_ManyProps` element because property `b` is missing in `Props_ManyProps` [1] but exists in
props [2]. [prop-missing]

   test.js:455:2
   455| <AbstractExact_ManyProps // Error: Other props are not allowed.
         ^^^^^^^^^^^^^^^^^^^^^^^

References:
   test.js:445:59
   445| const AbstractExact_ManyProps: React.ComponentType<$Exact<Props_ManyProps>>
                                                                  ^^^^^^^^^^^^^^^ [1]
   test.js:455:1
        v--------------------------------------------------------------
   455| <AbstractExact_ManyProps // Error: Other props are not allowed.
   456|   string1="foo"
   457|   string2={'bar'}
   458|   boolean1
   459|   boolean2={false}
   460|   number={42}
   461|   a={1}
   462|   b={2}
   463|   c={3}
   464| />;
        -^ [2]


Error ---------------------------------------------------------------------------------------------------- test.js:455:2

Cannot create `AbstractExact_ManyProps` element because property `c` is missing in `Props_ManyProps` [1] but exists in
props [2]. [prop-missing]

   test.js:455:2
   455| <AbstractExact_ManyProps // Error: Other props are not allowed.
         ^^^^^^^^^^^^^^^^^^^^^^^

References:
   test.js:445:59
   445| const AbstractExact_ManyProps: React.ComponentType<$Exact<Props_ManyProps>>
                                                                  ^^^^^^^^^^^^^^^ [1]
   test.js:455:1
        v--------------------------------------------------------------
   455| <AbstractExact_ManyProps // Error: Other props are not allowed.
   456|   string1="foo"
   457|   string2={'bar'}
   458|   boolean1
   459|   boolean2={false}
   460|   number={42}
   461|   a={1}
   462|   b={2}
   463|   c={3}
   464| />;
        -^ [2]


Error --------------------------------------------------------------------------------------------------- test.js:466:12

Cannot create `AbstractExact_ManyProps` element because null [1] is incompatible with string [2] in property `string1`.
[incompatible-type]

   test.js:466:12
   466|   string1={null}
                   ^^^^ [1]

References:
   test.js:66:12
    66|   string1: string,
                   ^^^^^^ [2]


Error --------------------------------------------------------------------------------------------------- test.js:467:12

Cannot create `AbstractExact_ManyProps` element because null [1] is incompatible with string [2] in property `string2`.
[incompatible-type]

   test.js:467:12
   467|   string2={null}
                   ^^^^ [1]

References:
   test.js:67:12
    67|   string2: string,
                   ^^^^^^ [2]


Error --------------------------------------------------------------------------------------------------- test.js:468:13

Cannot create `AbstractExact_ManyProps` element because null [1] is incompatible with boolean [2] in property
`boolean1`. [incompatible-type]

   test.js:468:13
   468|   boolean1={null}
                    ^^^^ [1]

References:
   test.js:68:13
    68|   boolean1: boolean,
                    ^^^^^^^ [2]


Error --------------------------------------------------------------------------------------------------- test.js:469:13

Cannot create `AbstractExact_ManyProps` element because null [1] is incompatible with boolean [2] in property
`boolean2`. [incompatible-type]

   test.js:469:13
   469|   boolean2={null}
                    ^^^^ [1]

References:
   test.js:69:13
    69|   boolean2: boolean,
                    ^^^^^^^ [2]


Error --------------------------------------------------------------------------------------------------- test.js:470:11

Cannot create `AbstractExact_ManyProps` element because null [1] is incompatible with number [2] in property `number`.
[incompatible-type]

   test.js:470:11
   470|   number={null}
                  ^^^^ [1]

References:
   test.js:70:11
    70|   number: number,
                  ^^^^^^ [2]


Error ---------------------------------------------------------------------------------------------------- test.js:484:2

Cannot create `AbstractExact_ManyProps` element because property `number` is missing in props [1] but exists in
`Props_ManyProps` [2]. [prop-missing]

   test.js:484:2
   484| <AbstractExact_ManyProps // Error: Missing `number`.
         ^^^^^^^^^^^^^^^^^^^^^^^

References:
   test.js:484:1
        v---------------------------------------------------
   484| <AbstractExact_ManyProps // Error: Missing `number`.
   485|   {...{string1: 'foo', string2: 'bar'}}
   486|   {...{boolean1: true, boolean2: false}}
   487| />;
        -^ [1]
   test.js:445:59
   445| const AbstractExact_ManyProps: React.ComponentType<$Exact<Props_ManyProps>>
                                                                  ^^^^^^^^^^^^^^^ [2]


Error ---------------------------------------------------------------------------------------------------- test.js:488:2

Cannot create `AbstractExact_ManyProps` element because property `a` is missing in `Props_ManyProps` [1] but exists in
props [2]. [prop-missing]

   test.js:488:2
   488| <AbstractExact_ManyProps // Error: Extra props are not allowed.
         ^^^^^^^^^^^^^^^^^^^^^^^

References:
   test.js:445:59
   445| const AbstractExact_ManyProps: React.ComponentType<$Exact<Props_ManyProps>>
                                                                  ^^^^^^^^^^^^^^^ [1]
   test.js:488:1
        v--------------------------------------------------------------
   488| <AbstractExact_ManyProps // Error: Extra props are not allowed.
   489|   string1="foo"
   490|   string2={'bar'}
   491|   boolean1
   492|   boolean2={false}
   493|   {...{number: 42, a: 1, b: 2, c: 3}}
   494| />;
        -^ [2]


Error ---------------------------------------------------------------------------------------------------- test.js:488:2

Cannot create `AbstractExact_ManyProps` element because property `b` is missing in `Props_ManyProps` [1] but exists in
props [2]. [prop-missing]

   test.js:488:2
   488| <AbstractExact_ManyProps // Error: Extra props are not allowed.
         ^^^^^^^^^^^^^^^^^^^^^^^

References:
   test.js:445:59
   445| const AbstractExact_ManyProps: React.ComponentType<$Exact<Props_ManyProps>>
                                                                  ^^^^^^^^^^^^^^^ [1]
   test.js:488:1
        v--------------------------------------------------------------
   488| <AbstractExact_ManyProps // Error: Extra props are not allowed.
   489|   string1="foo"
   490|   string2={'bar'}
   491|   boolean1
   492|   boolean2={false}
   493|   {...{number: 42, a: 1, b: 2, c: 3}}
   494| />;
        -^ [2]


Error ---------------------------------------------------------------------------------------------------- test.js:488:2

Cannot create `AbstractExact_ManyProps` element because property `c` is missing in `Props_ManyProps` [1] but exists in
props [2]. [prop-missing]

   test.js:488:2
   488| <AbstractExact_ManyProps // Error: Extra props are not allowed.
         ^^^^^^^^^^^^^^^^^^^^^^^

References:
   test.js:445:59
   445| const AbstractExact_ManyProps: React.ComponentType<$Exact<Props_ManyProps>>
                                                                  ^^^^^^^^^^^^^^^ [1]
   test.js:488:1
        v--------------------------------------------------------------
   488| <AbstractExact_ManyProps // Error: Extra props are not allowed.
   489|   string1="foo"
   490|   string2={'bar'}
   491|   boolean1
   492|   boolean2={false}
   493|   {...{number: 42, a: 1, b: 2, c: 3}}
   494| />;
        -^ [2]


Error --------------------------------------------------------------------------------------------------- test.js:505:54

Cannot create `AbstractExact_ManyProps` element because null or undefined [1] is incompatible with number [2] in
property `number`. [incompatible-type]

   test.js:505:54
   505|   {...{string1: 'foo', string2: 'bar', number: (any: ?number)}}
                                                             ^^^^^^^ [1]

References:
   test.js:70:11
    70|   number: number,
                  ^^^^^^ [2]


Error ---------------------------------------------------------------------------------------------------- test.js:509:2

Cannot create `Member_ManyProps.prop` element because property `boolean1` is missing in props [1] but exists in
`Props_ManyProps` [2]. [prop-missing]

   test.js:509:2
   509| <Member_ManyProps.prop />; // Error: There are no props.
         ^^^^^^^^^^^^^^^^^^^^^

References:
   test.js:509:1
   509| <Member_ManyProps.prop />; // Error: There are no props.
        ^^^^^^^^^^^^^^^^^^^^^^^^^ [1]
   test.js:73:47
    73| class Class_ManyProps extends React.Component<Props_ManyProps> {}
                                                      ^^^^^^^^^^^^^^^ [2]


Error ---------------------------------------------------------------------------------------------------- test.js:509:2

Cannot create `Member_ManyProps.prop` element because property `boolean2` is missing in props [1] but exists in
`Props_ManyProps` [2]. [prop-missing]

   test.js:509:2
   509| <Member_ManyProps.prop />; // Error: There are no props.
         ^^^^^^^^^^^^^^^^^^^^^

References:
   test.js:509:1
   509| <Member_ManyProps.prop />; // Error: There are no props.
        ^^^^^^^^^^^^^^^^^^^^^^^^^ [1]
   test.js:73:47
    73| class Class_ManyProps extends React.Component<Props_ManyProps> {}
                                                      ^^^^^^^^^^^^^^^ [2]


Error ---------------------------------------------------------------------------------------------------- test.js:509:2

Cannot create `Member_ManyProps.prop` element because property `number` is missing in props [1] but exists in
`Props_ManyProps` [2]. [prop-missing]

   test.js:509:2
   509| <Member_ManyProps.prop />; // Error: There are no props.
         ^^^^^^^^^^^^^^^^^^^^^

References:
   test.js:509:1
   509| <Member_ManyProps.prop />; // Error: There are no props.
        ^^^^^^^^^^^^^^^^^^^^^^^^^ [1]
   test.js:73:47
    73| class Class_ManyProps extends React.Component<Props_ManyProps> {}
                                                      ^^^^^^^^^^^^^^^ [2]


Error ---------------------------------------------------------------------------------------------------- test.js:509:2

Cannot create `Member_ManyProps.prop` element because property `string1` is missing in props [1] but exists in
`Props_ManyProps` [2]. [prop-missing]

   test.js:509:2
   509| <Member_ManyProps.prop />; // Error: There are no props.
         ^^^^^^^^^^^^^^^^^^^^^

References:
   test.js:509:1
   509| <Member_ManyProps.prop />; // Error: There are no props.
        ^^^^^^^^^^^^^^^^^^^^^^^^^ [1]
   test.js:73:47
    73| class Class_ManyProps extends React.Component<Props_ManyProps> {}
                                                      ^^^^^^^^^^^^^^^ [2]


Error ---------------------------------------------------------------------------------------------------- test.js:509:2

Cannot create `Member_ManyProps.prop` element because property `string2` is missing in props [1] but exists in
`Props_ManyProps` [2]. [prop-missing]

   test.js:509:2
   509| <Member_ManyProps.prop />; // Error: There are no props.
         ^^^^^^^^^^^^^^^^^^^^^

References:
   test.js:509:1
   509| <Member_ManyProps.prop />; // Error: There are no props.
        ^^^^^^^^^^^^^^^^^^^^^^^^^ [1]
   test.js:73:47
    73| class Class_ManyProps extends React.Component<Props_ManyProps> {}
                                                      ^^^^^^^^^^^^^^^ [2]


Error --------------------------------------------------------------------------------------------------- test.js:528:12

Cannot create `Member_ManyProps.prop` element because null [1] is incompatible with string [2] in property `string1`.
[incompatible-type]

   test.js:528:12
   528|   string1={null}
                   ^^^^ [1]

References:
   test.js:66:12
    66|   string1: string,
                   ^^^^^^ [2]


Error --------------------------------------------------------------------------------------------------- test.js:529:12

Cannot create `Member_ManyProps.prop` element because null [1] is incompatible with string [2] in property `string2`.
[incompatible-type]

   test.js:529:12
   529|   string2={null}
                   ^^^^ [1]

References:
   test.js:67:12
    67|   string2: string,
                   ^^^^^^ [2]


Error --------------------------------------------------------------------------------------------------- test.js:530:13

Cannot create `Member_ManyProps.prop` element because null [1] is incompatible with boolean [2] in property `boolean1`.
[incompatible-type]

   test.js:530:13
   530|   boolean1={null}
                    ^^^^ [1]

References:
   test.js:68:13
    68|   boolean1: boolean,
                    ^^^^^^^ [2]


Error --------------------------------------------------------------------------------------------------- test.js:531:13

Cannot create `Member_ManyProps.prop` element because null [1] is incompatible with boolean [2] in property `boolean2`.
[incompatible-type]

   test.js:531:13
   531|   boolean2={null}
                    ^^^^ [1]

References:
   test.js:69:13
    69|   boolean2: boolean,
                    ^^^^^^^ [2]


Error --------------------------------------------------------------------------------------------------- test.js:532:11

Cannot create `Member_ManyProps.prop` element because null [1] is incompatible with number [2] in property `number`.
[incompatible-type]

   test.js:532:11
   532|   number={null}
                  ^^^^ [1]

References:
   test.js:70:11
    70|   number: number,
                  ^^^^^^ [2]


Error ---------------------------------------------------------------------------------------------------- test.js:546:2

Cannot create `Member_ManyProps.prop` element because property `number` is missing in props [1] but exists in
`Props_ManyProps` [2]. [prop-missing]

   test.js:546:2
   546| <Member_ManyProps.prop // Error: Missing `number`.
         ^^^^^^^^^^^^^^^^^^^^^

References:
   test.js:546:1
        v-------------------------------------------------
   546| <Member_ManyProps.prop // Error: Missing `number`.
   547|   {...{string1: 'foo', string2: 'bar'}}
   548|   {...{boolean1: true, boolean2: false}}
   549| />;
        -^ [1]
   test.js:73:47
    73| class Class_ManyProps extends React.Component<Props_ManyProps> {}
                                                      ^^^^^^^^^^^^^^^ [2]


Error --------------------------------------------------------------------------------------------------- test.js:567:54

Cannot create `Member_ManyProps.prop` element because null or undefined [1] is incompatible with number [2] in property
`number`. [incompatible-type]

   test.js:567:54
   567|   {...{string1: 'foo', string2: 'bar', number: (any: ?number)}}
                                                             ^^^^^^^ [1]

References:
   test.js:70:11
    70|   number: number,
                  ^^^^^^ [2]


Error ---------------------------------------------------------------------------------------------------- test.js:571:2

Cannot create `EnhancedClass_ManyProps` element because property `boolean1` is missing in props [1] but exists in
`Props_ManyProps` [2]. [prop-missing]

   test.js:571:2
   571| <EnhancedClass_ManyProps />; // Error: There are no props.
         ^^^^^^^^^^^^^^^^^^^^^^^

References:
   test.js:571:1
   571| <EnhancedClass_ManyProps />; // Error: There are no props.
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^ [1]
   test.js:11:24
    11| ): React.ComponentType<React.ElementConfig<Component>> {
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ [2]


Error ---------------------------------------------------------------------------------------------------- test.js:571:2

Cannot create `EnhancedClass_ManyProps` element because property `boolean2` is missing in props [1] but exists in
`Props_ManyProps` [2]. [prop-missing]

   test.js:571:2
   571| <EnhancedClass_ManyProps />; // Error: There are no props.
         ^^^^^^^^^^^^^^^^^^^^^^^

References:
   test.js:571:1
   571| <EnhancedClass_ManyProps />; // Error: There are no props.
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^ [1]
   test.js:11:24
    11| ): React.ComponentType<React.ElementConfig<Component>> {
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ [2]


Error ---------------------------------------------------------------------------------------------------- test.js:571:2

Cannot create `EnhancedClass_ManyProps` element because property `number` is missing in props [1] but exists in
`Props_ManyProps` [2]. [prop-missing]

   test.js:571:2
   571| <EnhancedClass_ManyProps />; // Error: There are no props.
         ^^^^^^^^^^^^^^^^^^^^^^^

References:
   test.js:571:1
   571| <EnhancedClass_ManyProps />; // Error: There are no props.
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^ [1]
   test.js:11:24
    11| ): React.ComponentType<React.ElementConfig<Component>> {
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ [2]


Error ---------------------------------------------------------------------------------------------------- test.js:571:2

Cannot create `EnhancedClass_ManyProps` element because property `string1` is missing in props [1] but exists in
`Props_ManyProps` [2]. [prop-missing]

   test.js:571:2
   571| <EnhancedClass_ManyProps />; // Error: There are no props.
         ^^^^^^^^^^^^^^^^^^^^^^^

References:
   test.js:571:1
   571| <EnhancedClass_ManyProps />; // Error: There are no props.
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^ [1]
   test.js:11:24
    11| ): React.ComponentType<React.ElementConfig<Component>> {
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ [2]


Error ---------------------------------------------------------------------------------------------------- test.js:571:2

Cannot create `EnhancedClass_ManyProps` element because property `string2` is missing in props [1] but exists in
`Props_ManyProps` [2]. [prop-missing]

   test.js:571:2
   571| <EnhancedClass_ManyProps />; // Error: There are no props.
         ^^^^^^^^^^^^^^^^^^^^^^^

References:
   test.js:571:1
   571| <EnhancedClass_ManyProps />; // Error: There are no props.
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^ [1]
   test.js:11:24
    11| ): React.ComponentType<React.ElementConfig<Component>> {
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ [2]


Error --------------------------------------------------------------------------------------------------- test.js:590:12

Cannot create `EnhancedClass_ManyProps` element because null [1] is incompatible with string [2] in property `string1`.
[incompatible-type]

   test.js:590:12
   590|   string1={null}
                   ^^^^ [1]

References:
   test.js:66:12
    66|   string1: string,
                   ^^^^^^ [2]


Error --------------------------------------------------------------------------------------------------- test.js:591:12

Cannot create `EnhancedClass_ManyProps` element because null [1] is incompatible with string [2] in property `string2`.
[incompatible-type]

   test.js:591:12
   591|   string2={null}
                   ^^^^ [1]

References:
   test.js:67:12
    67|   string2: string,
                   ^^^^^^ [2]


Error --------------------------------------------------------------------------------------------------- test.js:592:13

Cannot create `EnhancedClass_ManyProps` element because null [1] is incompatible with boolean [2] in property
`boolean1`. [incompatible-type]

   test.js:592:13
   592|   boolean1={null}
                    ^^^^ [1]

References:
   test.js:68:13
    68|   boolean1: boolean,
                    ^^^^^^^ [2]


Error --------------------------------------------------------------------------------------------------- test.js:593:13

Cannot create `EnhancedClass_ManyProps` element because null [1] is incompatible with boolean [2] in property
`boolean2`. [incompatible-type]

   test.js:593:13
   593|   boolean2={null}
                    ^^^^ [1]

References:
   test.js:69:13
    69|   boolean2: boolean,
                    ^^^^^^^ [2]


Error --------------------------------------------------------------------------------------------------- test.js:594:11

Cannot create `EnhancedClass_ManyProps` element because null [1] is incompatible with number [2] in property `number`.
[incompatible-type]

   test.js:594:11
   594|   number={null}
                  ^^^^ [1]

References:
   test.js:70:11
    70|   number: number,
                  ^^^^^^ [2]


Error ---------------------------------------------------------------------------------------------------- test.js:608:2

Cannot create `EnhancedClass_ManyProps` element because property `number` is missing in props [1] but exists in
`Props_ManyProps` [2]. [prop-missing]

   test.js:608:2
   608| <EnhancedClass_ManyProps // Error: Missing `number`.
         ^^^^^^^^^^^^^^^^^^^^^^^

References:
   test.js:608:1
        v---------------------------------------------------
   608| <EnhancedClass_ManyProps // Error: Missing `number`.
   609|   {...{string1: 'foo', string2: 'bar'}}
   610|   {...{boolean1: true, boolean2: false}}
   611| />;
        -^ [1]
   test.js:11:24
    11| ): React.ComponentType<React.ElementConfig<Component>> {
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ [2]


Error --------------------------------------------------------------------------------------------------- test.js:629:54

Cannot create `EnhancedClass_ManyProps` element because null or undefined [1] is incompatible with number [2] in
property `number`. [incompatible-type]

   test.js:629:54
   629|   {...{string1: 'foo', string2: 'bar', number: (any: ?number)}}
                                                             ^^^^^^^ [1]

References:
   test.js:70:11
    70|   number: number,
                  ^^^^^^ [2]


Error ---------------------------------------------------------------------------------------------------- test.js:633:2

Cannot create `EnhancedFunction_ManyProps` element because property `boolean1` is missing in props [1] but exists in
`Props_ManyProps` [2]. [prop-missing]

   test.js:633:2
   633| <EnhancedFunction_ManyProps />; // Error: There are no props.
         ^^^^^^^^^^^^^^^^^^^^^^^^^^

References:
   test.js:633:1
   633| <EnhancedFunction_ManyProps />; // Error: There are no props.
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ [1]
   test.js:11:24
    11| ): React.ComponentType<React.ElementConfig<Component>> {
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ [2]


Error ---------------------------------------------------------------------------------------------------- test.js:633:2

Cannot create `EnhancedFunction_ManyProps` element because property `boolean2` is missing in props [1] but exists in
`Props_ManyProps` [2]. [prop-missing]

   test.js:633:2
   633| <EnhancedFunction_ManyProps />; // Error: There are no props.
         ^^^^^^^^^^^^^^^^^^^^^^^^^^

References:
   test.js:633:1
   633| <EnhancedFunction_ManyProps />; // Error: There are no props.
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ [1]
   test.js:11:24
    11| ): React.ComponentType<React.ElementConfig<Component>> {
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ [2]


Error ---------------------------------------------------------------------------------------------------- test.js:633:2

Cannot create `EnhancedFunction_ManyProps` element because property `number` is missing in props [1] but exists in
`Props_ManyProps` [2]. [prop-missing]

   test.js:633:2
   633| <EnhancedFunction_ManyProps />; // Error: There are no props.
         ^^^^^^^^^^^^^^^^^^^^^^^^^^

References:
   test.js:633:1
   633| <EnhancedFunction_ManyProps />; // Error: There are no props.
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ [1]
   test.js:11:24
    11| ): React.ComponentType<React.ElementConfig<Component>> {
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ [2]


Error ---------------------------------------------------------------------------------------------------- test.js:633:2

Cannot create `EnhancedFunction_ManyProps` element because property `string1` is missing in props [1] but exists in
`Props_ManyProps` [2]. [prop-missing]

   test.js:633:2
   633| <EnhancedFunction_ManyProps />; // Error: There are no props.
         ^^^^^^^^^^^^^^^^^^^^^^^^^^

References:
   test.js:633:1
   633| <EnhancedFunction_ManyProps />; // Error: There are no props.
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ [1]
   test.js:11:24
    11| ): React.ComponentType<React.ElementConfig<Component>> {
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ [2]


Error ---------------------------------------------------------------------------------------------------- test.js:633:2

Cannot create `EnhancedFunction_ManyProps` element because property `string2` is missing in props [1] but exists in
`Props_ManyProps` [2]. [prop-missing]

   test.js:633:2
   633| <EnhancedFunction_ManyProps />; // Error: There are no props.
         ^^^^^^^^^^^^^^^^^^^^^^^^^^

References:
   test.js:633:1
   633| <EnhancedFunction_ManyProps />; // Error: There are no props.
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ [1]
   test.js:11:24
    11| ): React.ComponentType<React.ElementConfig<Component>> {
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ [2]


Error --------------------------------------------------------------------------------------------------- test.js:652:12

Cannot create `EnhancedFunction_ManyProps` element because null [1] is incompatible with string [2] in property
`string1`. [incompatible-type]

   test.js:652:12
   652|   string1={null}
                   ^^^^ [1]

References:
   test.js:66:12
    66|   string1: string,
                   ^^^^^^ [2]


Error --------------------------------------------------------------------------------------------------- test.js:653:12

Cannot create `EnhancedFunction_ManyProps` element because null [1] is incompatible with string [2] in property
`string2`. [incompatible-type]

   test.js:653:12
   653|   string2={null}
                   ^^^^ [1]

References:
   test.js:67:12
    67|   string2: string,
                   ^^^^^^ [2]


Error --------------------------------------------------------------------------------------------------- test.js:654:13

Cannot create `EnhancedFunction_ManyProps` element because null [1] is incompatible with boolean [2] in property
`boolean1`. [incompatible-type]

   test.js:654:13
   654|   boolean1={null}
                    ^^^^ [1]

References:
   test.js:68:13
    68|   boolean1: boolean,
                    ^^^^^^^ [2]


Error --------------------------------------------------------------------------------------------------- test.js:655:13

Cannot create `EnhancedFunction_ManyProps` element because null [1] is incompatible with boolean [2] in property
`boolean2`. [incompatible-type]

   test.js:655:13
   655|   boolean2={null}
                    ^^^^ [1]

References:
   test.js:69:13
    69|   boolean2: boolean,
                    ^^^^^^^ [2]


Error --------------------------------------------------------------------------------------------------- test.js:656:11

Cannot create `EnhancedFunction_ManyProps` element because null [1] is incompatible with number [2] in property
`number`. [incompatible-type]

   test.js:656:11
   656|   number={null}
                  ^^^^ [1]

References:
   test.js:70:11
    70|   number: number,
                  ^^^^^^ [2]


Error ---------------------------------------------------------------------------------------------------- test.js:670:2

Cannot create `EnhancedFunction_ManyProps` element because property `number` is missing in props [1] but exists in
`Props_ManyProps` [2]. [prop-missing]

   test.js:670:2
   670| <EnhancedFunction_ManyProps // Error: Missing `number`.
         ^^^^^^^^^^^^^^^^^^^^^^^^^^

References:
   test.js:670:1
        v------------------------------------------------------
   670| <EnhancedFunction_ManyProps // Error: Missing `number`.
   671|   {...{string1: 'foo', string2: 'bar'}}
   672|   {...{boolean1: true, boolean2: false}}
   673| />;
        -^ [1]
   test.js:11:24
    11| ): React.ComponentType<React.ElementConfig<Component>> {
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ [2]


Error --------------------------------------------------------------------------------------------------- test.js:691:54

Cannot create `EnhancedFunction_ManyProps` element because null or undefined [1] is incompatible with number [2] in
property `number`. [incompatible-type]

   test.js:691:54
   691|   {...{string1: 'foo', string2: 'bar', number: (any: ?number)}}
                                                             ^^^^^^^ [1]

References:
   test.js:70:11
    70|   number: number,
                  ^^^^^^ [2]


Error ---------------------------------------------------------------------------------------------------- test.js:701:2

Cannot create `Class_OptionalProps` element because property `foo` is missing in props [1] but exists in
`Props_OptionalProps` [2]. [prop-missing]

   test.js:701:2
   701| <Class_OptionalProps />; // Error: `foo` is required.
         ^^^^^^^^^^^^^^^^^^^

References:
   test.js:701:1
   701| <Class_OptionalProps />; // Error: `foo` is required.
        ^^^^^^^^^^^^^^^^^^^^^^^ [1]
   test.js:700:51
   700| class Class_OptionalProps extends React.Component<Props_OptionalProps> {}
                                                          ^^^^^^^^^^^^^^^^^^^ [2]


Error ---------------------------------------------------------------------------------------------------- test.js:709:7

Cannot create `Class_OptionalProps` element because string [1] is incompatible with number [2] in property `foo`.
[incompatible-type]

   test.js:709:7
   709|   foo="nope"
              ^^^^^^ [1]

References:
   test.js:698:35
   698| type Props_OptionalProps = {foo: ?number, bar?: number};
                                          ^^^^^^ [2]


Error ---------------------------------------------------------------------------------------------------- test.js:714:7

Cannot create `Class_OptionalProps` element because string [1] is incompatible with number [2] in property `bar`.
[incompatible-type]

   test.js:714:7
   714|   bar="nope"
              ^^^^^^ [1]

References:
   test.js:698:49
   698| type Props_OptionalProps = {foo: ?number, bar?: number};
                                                        ^^^^^^ [2]


Error ---------------------------------------------------------------------------------------------------- test.js:719:2

Cannot create `ClassExact_OptionalProps` element because property `foo` is missing in props [1] but exists in
`Props_OptionalProps` [2]. [prop-missing]

   test.js:719:2
   719| <ClassExact_OptionalProps />; // Error: `foo` is required.
         ^^^^^^^^^^^^^^^^^^^^^^^^

References:
   test.js:719:1
   719| <ClassExact_OptionalProps />; // Error: `foo` is required.
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^ [1]
   test.js:718:34
   718|   extends React.Component<$Exact<Props_OptionalProps>> {}
                                         ^^^^^^^^^^^^^^^^^^^ [2]


Error ---------------------------------------------------------------------------------------------------- test.js:727:7

Cannot create `ClassExact_OptionalProps` element because string [1] is incompatible with number [2] in property `foo`.
[incompatible-type]

   test.js:727:7
   727|   foo="nope"
              ^^^^^^ [1]

References:
   test.js:698:35
   698| type Props_OptionalProps = {foo: ?number, bar?: number};
                                          ^^^^^^ [2]


Error ---------------------------------------------------------------------------------------------------- test.js:732:7

Cannot create `ClassExact_OptionalProps` element because string [1] is incompatible with number [2] in property `bar`.
[incompatible-type]

   test.js:732:7
   732|   bar="nope"
              ^^^^^^ [1]

References:
   test.js:698:49
   698| type Props_OptionalProps = {foo: ?number, bar?: number};
                                                        ^^^^^^ [2]


Error ---------------------------------------------------------------------------------------------------- test.js:737:2

Cannot create `ClassPure_OptionalProps` element because property `foo` is missing in props [1] but exists in
`Props_OptionalProps` [2]. [prop-missing]

   test.js:737:2
   737| <ClassPure_OptionalProps />; // Error: `foo` is required.
         ^^^^^^^^^^^^^^^^^^^^^^^

References:
   test.js:737:1
   737| <ClassPure_OptionalProps />; // Error: `foo` is required.
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^ [1]
   test.js:736:31
   736|   extends React.PureComponent<Props_OptionalProps> {}
                                      ^^^^^^^^^^^^^^^^^^^ [2]


Error ---------------------------------------------------------------------------------------------------- test.js:745:7

Cannot create `ClassPure_OptionalProps` element because string [1] is incompatible with number [2] in property `foo`.
[incompatible-type]

   test.js:745:7
   745|   foo="nope"
              ^^^^^^ [1]

References:
   test.js:698:35
   698| type Props_OptionalProps = {foo: ?number, bar?: number};
                                          ^^^^^^ [2]


Error ---------------------------------------------------------------------------------------------------- test.js:750:7

Cannot create `ClassPure_OptionalProps` element because string [1] is incompatible with number [2] in property `bar`.
[incompatible-type]

   test.js:750:7
   750|   bar="nope"
              ^^^^^^ [1]

References:
   test.js:698:49
   698| type Props_OptionalProps = {foo: ?number, bar?: number};
                                                        ^^^^^^ [2]


Error ---------------------------------------------------------------------------------------------------- test.js:754:2

Cannot create `Function_OptionalProps` element because property `foo` is missing in props [1] but exists in
`Props_OptionalProps` [2]. [prop-missing]

   test.js:754:2
   754| <Function_OptionalProps />; // Error: `foo` is required.
         ^^^^^^^^^^^^^^^^^^^^^^

References:
   test.js:754:1
   754| <Function_OptionalProps />; // Error: `foo` is required.
        ^^^^^^^^^^^^^^^^^^^^^^^^^^ [1]
   test.js:753:40
   753| const Function_OptionalProps = (props: Props_OptionalProps) => any;
                                               ^^^^^^^^^^^^^^^^^^^ [2]


Error ---------------------------------------------------------------------------------------------------- test.js:762:7

Cannot create `Function_OptionalProps` element because string [1] is incompatible with number [2] in property `foo`.
[incompatible-type]

   test.js:762:7
   762|   foo="nope"
              ^^^^^^ [1]

References:
   test.js:698:35
   698| type Props_OptionalProps = {foo: ?number, bar?: number};
                                          ^^^^^^ [2]


Error ---------------------------------------------------------------------------------------------------- test.js:767:7

Cannot create `Function_OptionalProps` element because string [1] is incompatible with number [2] in property `bar`.
[incompatible-type]

   test.js:767:7
   767|   bar="nope"
              ^^^^^^ [1]

References:
   test.js:698:49
   698| type Props_OptionalProps = {foo: ?number, bar?: number};
                                                        ^^^^^^ [2]


Error ---------------------------------------------------------------------------------------------------- test.js:771:2

Cannot create `FunctionExact_OptionalProps` element because property `foo` is missing in props [1] but exists in
`Props_OptionalProps` [2]. [prop-missing]

   test.js:771:2
   771| <FunctionExact_OptionalProps />; // Error: `foo` is required.
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^

References:
   test.js:771:1
   771| <FunctionExact_OptionalProps />; // Error: `foo` is required.
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ [1]
   test.js:770:52
   770| const FunctionExact_OptionalProps = (props: $Exact<Props_OptionalProps>) => any;
                                                           ^^^^^^^^^^^^^^^^^^^ [2]


Error ---------------------------------------------------------------------------------------------------- test.js:779:7

Cannot create `FunctionExact_OptionalProps` element because string [1] is incompatible with number [2] in property
`foo`. [incompatible-type]

   test.js:779:7
   779|   foo="nope"
              ^^^^^^ [1]

References:
   test.js:698:35
   698| type Props_OptionalProps = {foo: ?number, bar?: number};
                                          ^^^^^^ [2]


Error ---------------------------------------------------------------------------------------------------- test.js:784:7

Cannot create `FunctionExact_OptionalProps` element because string [1] is incompatible with number [2] in property
`bar`. [incompatible-type]

   test.js:784:7
   784|   bar="nope"
              ^^^^^^ [1]

References:
   test.js:698:49
   698| type Props_OptionalProps = {foo: ?number, bar?: number};
                                                        ^^^^^^ [2]


Error ---------------------------------------------------------------------------------------------------- test.js:788:2

Cannot create `Abstract_OptionalProps` element because property `foo` is missing in props [1] but exists in
`Props_OptionalProps` [2]. [prop-missing]

   test.js:788:2
   788| <Abstract_OptionalProps />; // Error: `foo` is required.
         ^^^^^^^^^^^^^^^^^^^^^^

References:
   test.js:788:1
   788| <Abstract_OptionalProps />; // Error: `foo` is required.
        ^^^^^^^^^^^^^^^^^^^^^^^^^^ [1]
   test.js:787:51
   787| const Abstract_OptionalProps: React.ComponentType<Props_OptionalProps> = any;
                                                          ^^^^^^^^^^^^^^^^^^^ [2]


Error ---------------------------------------------------------------------------------------------------- test.js:796:7

Cannot create `Abstract_OptionalProps` element because string [1] is incompatible with number [2] in property `foo`.
[incompatible-type]

   test.js:796:7
   796|   foo="nope"
              ^^^^^^ [1]

References:
   test.js:698:35
   698| type Props_OptionalProps = {foo: ?number, bar?: number};
                                          ^^^^^^ [2]


Error ---------------------------------------------------------------------------------------------------- test.js:801:7

Cannot create `Abstract_OptionalProps` element because string [1] is incompatible with number [2] in property `bar`.
[incompatible-type]

   test.js:801:7
   801|   bar="nope"
              ^^^^^^ [1]

References:
   test.js:698:49
   698| type Props_OptionalProps = {foo: ?number, bar?: number};
                                                        ^^^^^^ [2]


Error ---------------------------------------------------------------------------------------------------- test.js:806:2

Cannot create `AbstractExact_OptionalProps` element because property `foo` is missing in props [1] but exists in
`Props_OptionalProps` [2]. [prop-missing]

   test.js:806:2
   806| <AbstractExact_OptionalProps />; // Error: `foo` is required.
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^

References:
   test.js:806:1
   806| <AbstractExact_OptionalProps />; // Error: `foo` is required.
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ [1]
   test.js:805:30
   805|   React.ComponentType<$Exact<Props_OptionalProps>> = any;
                                     ^^^^^^^^^^^^^^^^^^^ [2]


Error ---------------------------------------------------------------------------------------------------- test.js:814:7

Cannot create `AbstractExact_OptionalProps` element because string [1] is incompatible with number [2] in property
`foo`. [incompatible-type]

   test.js:814:7
   814|   foo="nope"
              ^^^^^^ [1]

References:
   test.js:698:35
   698| type Props_OptionalProps = {foo: ?number, bar?: number};
                                          ^^^^^^ [2]


Error ---------------------------------------------------------------------------------------------------- test.js:819:7

Cannot create `AbstractExact_OptionalProps` element because string [1] is incompatible with number [2] in property
`bar`. [incompatible-type]

   test.js:819:7
   819|   bar="nope"
              ^^^^^^ [1]

References:
   test.js:698:49
   698| type Props_OptionalProps = {foo: ?number, bar?: number};
                                                        ^^^^^^ [2]


Error ---------------------------------------------------------------------------------------------------- test.js:823:2

Cannot create `Member_OptionalProps.prop` element because property `foo` is missing in props [1] but exists in
`Props_OptionalProps` [2]. [prop-missing]

   test.js:823:2
   823| <Member_OptionalProps.prop />; // Error: `foo` is required.
         ^^^^^^^^^^^^^^^^^^^^^^^^^

References:
   test.js:823:1
   823| <Member_OptionalProps.prop />; // Error: `foo` is required.
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ [1]
   test.js:700:51
   700| class Class_OptionalProps extends React.Component<Props_OptionalProps> {}
                                                          ^^^^^^^^^^^^^^^^^^^ [2]


Error ---------------------------------------------------------------------------------------------------- test.js:831:7

Cannot create `Member_OptionalProps.prop` element because string [1] is incompatible with number [2] in property `foo`.
[incompatible-type]

   test.js:831:7
   831|   foo="nope"
              ^^^^^^ [1]

References:
   test.js:698:35
   698| type Props_OptionalProps = {foo: ?number, bar?: number};
                                          ^^^^^^ [2]


Error ---------------------------------------------------------------------------------------------------- test.js:836:7

Cannot create `Member_OptionalProps.prop` element because string [1] is incompatible with number [2] in property `bar`.
[incompatible-type]

   test.js:836:7
   836|   bar="nope"
              ^^^^^^ [1]

References:
   test.js:698:49
   698| type Props_OptionalProps = {foo: ?number, bar?: number};
                                                        ^^^^^^ [2]


Error ---------------------------------------------------------------------------------------------------- test.js:840:2

Cannot create `EnhancedClass_OptionalProps` element because property `foo` is missing in props [1] but exists in
`Props_OptionalProps` [2]. [prop-missing]

   test.js:840:2
   840| <EnhancedClass_OptionalProps />; // Error: `foo` is required.
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^

References:
   test.js:840:1
   840| <EnhancedClass_OptionalProps />; // Error: `foo` is required.
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ [1]
   test.js:11:24
    11| ): React.ComponentType<React.ElementConfig<Component>> {
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ [2]


Error ---------------------------------------------------------------------------------------------------- test.js:848:7

Cannot create `EnhancedClass_OptionalProps` element because string [1] is incompatible with number [2] in property
`foo`. [incompatible-type]

   test.js:848:7
   848|   foo="nope"
              ^^^^^^ [1]

References:
   test.js:698:35
   698| type Props_OptionalProps = {foo: ?number, bar?: number};
                                          ^^^^^^ [2]


Error ---------------------------------------------------------------------------------------------------- test.js:853:7

Cannot create `EnhancedClass_OptionalProps` element because string [1] is incompatible with number [2] in property
`bar`. [incompatible-type]

   test.js:853:7
   853|   bar="nope"
              ^^^^^^ [1]

References:
   test.js:698:49
   698| type Props_OptionalProps = {foo: ?number, bar?: number};
                                                        ^^^^^^ [2]


Error ---------------------------------------------------------------------------------------------------- test.js:857:2

Cannot create `EnhancedFunction_OptionalProps` element because property `foo` is missing in props [1] but exists in
`Props_OptionalProps` [2]. [prop-missing]

   test.js:857:2
   857| <EnhancedFunction_OptionalProps />; // Error: `foo` is required.
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

References:
   test.js:857:1
   857| <EnhancedFunction_OptionalProps />; // Error: `foo` is required.
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ [1]
   test.js:11:24
    11| ): React.ComponentType<React.ElementConfig<Component>> {
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ [2]


Error ---------------------------------------------------------------------------------------------------- test.js:865:7

Cannot create `EnhancedFunction_OptionalProps` element because string [1] is incompatible with number [2] in property
`foo`. [incompatible-type]

   test.js:865:7
   865|   foo="nope"
              ^^^^^^ [1]

References:
   test.js:698:35
   698| type Props_OptionalProps = {foo: ?number, bar?: number};
                                          ^^^^^^ [2]


Error ---------------------------------------------------------------------------------------------------- test.js:870:7

Cannot create `EnhancedFunction_OptionalProps` element because string [1] is incompatible with number [2] in property
`bar`. [incompatible-type]

   test.js:870:7
   870|   bar="nope"
              ^^^^^^ [1]

References:
   test.js:698:49
   698| type Props_OptionalProps = {foo: ?number, bar?: number};
                                                        ^^^^^^ [2]


Error ---------------------------------------------------------------------------------------------------- test.js:894:2

Cannot create `Class_DefaultProps` element because property `bar` is missing in props [1] but exists in
`Props_DefaultProps` [2]. [prop-missing]

   test.js:894:2
   894| <Class_DefaultProps // Error: It is missing a required non-default prop.
         ^^^^^^^^^^^^^^^^^^

References:
   test.js:894:1
        v-----------------------------------------------------------------------
   894| <Class_DefaultProps // Error: It is missing a required non-default prop.
   895|   foo={1}
   896| />;
        -^ [1]
   test.js:882:50
   882| class Class_DefaultProps extends React.Component<Props_DefaultProps> {
                                                         ^^^^^^^^^^^^^^^^^^ [2]


Error ---------------------------------------------------------------------------------------------------- test.js:911:2

Cannot create `ClassExact_DefaultProps` element because property `bar` is missing in props [1] but exists in
`Props_DefaultProps` [2]. [prop-missing]

   test.js:911:2
   911| <ClassExact_DefaultProps // Error: It is missing a required non-default prop.
         ^^^^^^^^^^^^^^^^^^^^^^^

References:
   test.js:911:1
        v----------------------------------------------------------------------------
   911| <ClassExact_DefaultProps // Error: It is missing a required non-default prop.
   912|   foo={1}
   913| />;
        -^ [1]
   test.js:899:34
   899|   extends React.Component<$Exact<Props_DefaultProps>> {
                                         ^^^^^^^^^^^^^^^^^^ [2]


Error ---------------------------------------------------------------------------------------------------- test.js:927:2

Cannot create `ClassPure_DefaultProps` element because property `bar` is missing in props [1] but exists in
`Props_DefaultProps` [2]. [prop-missing]

   test.js:927:2
   927| <ClassPure_DefaultProps // Error: It is missing a required non-default prop.
         ^^^^^^^^^^^^^^^^^^^^^^

References:
   test.js:927:1
        v---------------------------------------------------------------------------
   927| <ClassPure_DefaultProps // Error: It is missing a required non-default prop.
   928|   foo={1}
   929| />;
        -^ [1]
   test.js:915:58
   915| class ClassPure_DefaultProps extends React.PureComponent<Props_DefaultProps> {
                                                                 ^^^^^^^^^^^^^^^^^^ [2]


Error ---------------------------------------------------------------------------------------------------- test.js:944:2

Cannot create `Function_DefaultProps` element because property `bar` is missing in props [1] but exists in
`Props_DefaultProps` [2]. [prop-missing]

   test.js:944:2
   944| <Function_DefaultProps // Error: It is missing a required non-default prop.
         ^^^^^^^^^^^^^^^^^^^^^

References:
   test.js:944:1
        v--------------------------------------------------------------------------
   944| <Function_DefaultProps // Error: It is missing a required non-default prop.
   945|   foo={1}
   946| />;
        -^ [1]
   test.js:931:39
   931| function Function_DefaultProps(props: Props_DefaultProps) {
                                              ^^^^^^^^^^^^^^^^^^ [2]


Error ---------------------------------------------------------------------------------------------------- test.js:961:2

Cannot create `FunctionExact_DefaultProps` element because property `bar` is missing in props [1] but exists in
`Props_DefaultProps` [2]. [prop-missing]

   test.js:961:2
   961| <FunctionExact_DefaultProps // Error: It is missing a required non-default prop.
         ^^^^^^^^^^^^^^^^^^^^^^^^^^

References:
   test.js:961:1
        v-------------------------------------------------------------------------------
   961| <FunctionExact_DefaultProps // Error: It is missing a required non-default prop.
   962|   foo={1}
   963| />;
        -^ [1]
   test.js:948:51
   948| function FunctionExact_DefaultProps(props: $Exact<Props_DefaultProps>) {
                                                          ^^^^^^^^^^^^^^^^^^ [2]


Error ---------------------------------------------------------------------------------------------------- test.js:973:2

Cannot create `Member_DefaultProps.prop` element because property `bar` is missing in props [1] but exists in
`Props_DefaultProps` [2]. [prop-missing]

   test.js:973:2
   973| <Member_DefaultProps.prop // Error: It is missing a required non-default prop.
         ^^^^^^^^^^^^^^^^^^^^^^^^

References:
   test.js:973:1
        v-----------------------------------------------------------------------------
   973| <Member_DefaultProps.prop // Error: It is missing a required non-default prop.
   974|   foo={1}
   975| />;
        -^ [1]
   test.js:882:50
   882| class Class_DefaultProps extends React.Component<Props_DefaultProps> {
                                                         ^^^^^^^^^^^^^^^^^^ [2]


Error ---------------------------------------------------------------------------------------------------- test.js:985:2

Cannot create `EnhancedClass_DefaultProps` element because property `bar` is missing in props [1] but exists in
`Props_DefaultProps` [2]. [prop-missing]

   test.js:985:2
   985| <EnhancedClass_DefaultProps // Error: It is missing a required non-default prop.
         ^^^^^^^^^^^^^^^^^^^^^^^^^^

References:
   test.js:985:1
        v-------------------------------------------------------------------------------
   985| <EnhancedClass_DefaultProps // Error: It is missing a required non-default prop.
   986|   foo={1}
   987| />;
        -^ [1]
   test.js:11:24
    11| ): React.ComponentType<React.ElementConfig<Component>> {
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ [2]


Error ---------------------------------------------------------------------------------------------------- test.js:997:2

Cannot create `EnhancedFunction_DefaultProps` element because property `bar` is missing in props [1] but exists in
`Props_DefaultProps` [2]. [prop-missing]

   test.js:997:2
   997| <EnhancedFunction_DefaultProps // Error: It is missing a required non-default prop.
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

References:
   test.js:997:1
        v----------------------------------------------------------------------------------
   997| <EnhancedFunction_DefaultProps // Error: It is missing a required non-default prop.
   998|   foo={1}
   999| />;
        -^ [1]
   test.js:11:24
    11| ): React.ComponentType<React.ElementConfig<Component>> {
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ [2]



Found 179 errors
