Error ---------------------------------------------------------------------------------------------------- index.js:37:3

Unreachable code. [unreachable-code]

   37|   return "default string"; // Error: unreachable
         ^^^^^^^^^^^^^^^^^^^^^^^^


Error --------------------------------------------------------------------------------------------------- index.js:46:20

Cannot return `c ? 'a' : invariant()` because `void` [1] is incompatible with `string` [2]. [incompatible-type]

   index.js:46:20
   46|   return c ? 'a' : invariant(); // Error: invariant must be a top-level statement call
                          ^^^^^^^^^^^

References:
   index.js:3:68
    3| declare function invariant(condition?: unknown, message?: string): asserts condition; // raises
                                                                          ^^^^^^^^^^^^^^^^^ [1]
   index.js:45:28
   45| function foo8(c: boolean): string {
                                  ^^^^^^ [2]


Error --------------------------------------------------------------------------------------------------- index.js:50:14

Cannot return `c ? 1 : invariant()` because `1` [1] is incompatible with `string` [2]. [incompatible-type]

   index.js:50:14
   50|   return c ? 1 : invariant(); // Error: invariant must be a top-level statement call
                    ^ [1]

References:
   index.js:49:28
   49| function foo9(c: boolean): string {
                                  ^^^^^^ [2]


Error --------------------------------------------------------------------------------------------------- index.js:50:18

Cannot return `c ? 1 : invariant()` because `void` [1] is incompatible with `string` [2]. [incompatible-type]

   index.js:50:18
   50|   return c ? 1 : invariant(); // Error: invariant must be a top-level statement call
                        ^^^^^^^^^^^

References:
   index.js:3:68
    3| declare function invariant(condition?: unknown, message?: string): asserts condition; // raises
                                                                          ^^^^^^^^^^^^^^^^^ [1]
   index.js:49:28
   49| function foo9(c: boolean): string {
                                  ^^^^^^ [2]


Error --------------------------------------------------------------------------------------------------- index.js:55:14

Cannot return `c ? invariant() : invariant()` because in at least one member of conditional [1]: `void` [2] is
incompatible with `string` [3]. [incompatible-type]

   index.js:55:14
   55|   return c ? invariant() : invariant(); // Error: invariant must be a top-level statement call
                    ^^^^^^^^^^^

References:
   index.js:55:10
   55|   return c ? invariant() : invariant(); // Error: invariant must be a top-level statement call
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ [1]
   index.js:3:68
    3| declare function invariant(condition?: unknown, message?: string): asserts condition; // raises
                                                                          ^^^^^^^^^^^^^^^^^ [2]
   index.js:54:29
   54| function foo10(c: boolean): string {
                                   ^^^^^^ [3]


Error --------------------------------------------------------------------------------------------------- index.js:59:10

This condition is likely falsy.
[WARNING]: Flow's type inference may be incorrect that it could be null at runtime (due to `any` annotations,
out-of-bounds array accesses, etc.). If the check is valid, you might want to make [1] nullable (`T` -> `?T`).
[constant-condition]

   index.js:59:10
   59|   return invariant() ? 1 : 2; // Error: invariant must be a top-level statement call
                ^^^^^^^^^^^

References:
   index.js:3:68
    3| declare function invariant(condition?: unknown, message?: string): asserts condition; // raises
                                                                          ^^^^^^^^^^^^^^^^^ [1]


Error --------------------------------------------------------------------------------------------------- index.js:59:24

Cannot return `invariant() ? 1 : 2` because `1` [1] is incompatible with `string` [2]. [incompatible-type]

   index.js:59:24
   59|   return invariant() ? 1 : 2; // Error: invariant must be a top-level statement call
                              ^ [1]

References:
   index.js:58:19
   58| function foo11(): string {
                         ^^^^^^ [2]


Error --------------------------------------------------------------------------------------------------- index.js:59:28

Cannot return `invariant() ? 1 : 2` because `2` [1] is incompatible with `string` [2]. [incompatible-type]

   index.js:59:28
   59|   return invariant() ? 1 : 2; // Error: invariant must be a top-level statement call
                                  ^ [1]

References:
   index.js:58:19
   58| function foo11(): string {
                         ^^^^^^ [2]


Error ---------------------------------------------------------------------------------------------------- index.js:74:3

This condition is likely falsy.
[WARNING]: Flow's type inference may be incorrect that it could be null at runtime (due to `any` annotations,
out-of-bounds array accesses, etc.). If the check is valid, you might want to make [1] nullable (`T` -> `?T`).
[constant-condition]

   index.js:74:3
   74|   invariant() || c; // Error: invariant must be a top-level statement call
         ^^^^^^^^^^^

References:
   index.js:3:68
    3| declare function invariant(condition?: unknown, message?: string): asserts condition; // raises
                                                                          ^^^^^^^^^^^^^^^^^ [1]


Error --------------------------------------------------------------------------------------------------- index.js:79:10

Cannot return `c || invariant()` because `true` [1] is incompatible with `string` [2]. [incompatible-type]

   index.js:79:10
   79|   return c || invariant(); // Error: invariant must be a top-level statement call
                ^

References:
   index.js:78:19
   78| function foo15(c: boolean): string {
                         ^^^^^^^ [1]
   index.js:78:29
   78| function foo15(c: boolean): string {
                                   ^^^^^^ [2]


Error --------------------------------------------------------------------------------------------------- index.js:79:15

Cannot return `c || invariant()` because `void` [1] is incompatible with `string` [2]. [incompatible-type]

   index.js:79:15
   79|   return c || invariant(); // Error: invariant must be a top-level statement call
                     ^^^^^^^^^^^

References:
   index.js:3:68
    3| declare function invariant(condition?: unknown, message?: string): asserts condition; // raises
                                                                          ^^^^^^^^^^^^^^^^^ [1]
   index.js:78:29
   78| function foo15(c: boolean): string {
                                   ^^^^^^ [2]


Error --------------------------------------------------------------------------------------------------- index.js:83:10

This condition is likely falsy.
[WARNING]: Flow's type inference may be incorrect that it could be null at runtime (due to `any` annotations,
out-of-bounds array accesses, etc.). If the check is valid, you might want to make [1] nullable (`T` -> `?T`).
[constant-condition]

   index.js:83:10
   83|   return invariant() || invariant(); // Error: invariant must be a top-level statement call
                ^^^^^^^^^^^

References:
   index.js:3:68
    3| declare function invariant(condition?: unknown, message?: string): asserts condition; // raises
                                                                          ^^^^^^^^^^^^^^^^^ [1]


Error --------------------------------------------------------------------------------------------------- index.js:83:25

Cannot return `invariant() || invariant()` because `void` [1] is incompatible with `string` [2]. [incompatible-type]

   index.js:83:25
   83|   return invariant() || invariant(); // Error: invariant must be a top-level statement call
                               ^^^^^^^^^^^

References:
   index.js:3:68
    3| declare function invariant(condition?: unknown, message?: string): asserts condition; // raises
                                                                          ^^^^^^^^^^^^^^^^^ [1]
   index.js:82:29
   82| function foo16(c: boolean): string {
                                   ^^^^^^ [2]


Error ---------------------------------------------------------------------------------------------------- index.js:98:3

This condition is likely falsy.
[WARNING]: Flow's type inference may be incorrect that it could be null at runtime (due to `any` annotations,
out-of-bounds array accesses, etc.). If the check is valid, you might want to make [1] nullable (`T` -> `?T`).
[constant-condition]

   index.js:98:3
   98|   invariant() && c; // Error: invariant must be a top-level statement call
         ^^^^^^^^^^^

References:
   index.js:3:68
    3| declare function invariant(condition?: unknown, message?: string): asserts condition; // raises
                                                                          ^^^^^^^^^^^^^^^^^ [1]


Error -------------------------------------------------------------------------------------------------- index.js:103:10

Cannot return `c && invariant()` because `false` [1] is incompatible with `string` [2]. [incompatible-type]

   index.js:103:10
   103|   return c && invariant(); // Error: invariant must be a top-level statement call
                 ^

References:
   index.js:102:19
   102| function foo20(c: boolean): string {
                          ^^^^^^^ [1]
   index.js:102:29
   102| function foo20(c: boolean): string {
                                    ^^^^^^ [2]


Error -------------------------------------------------------------------------------------------------- index.js:103:15

Cannot return `c && invariant()` because `void` [1] is incompatible with `string` [2]. [incompatible-type]

   index.js:103:15
   103|   return c && invariant(); // Error: invariant must be a top-level statement call
                      ^^^^^^^^^^^

References:
   index.js:3:68
     3| declare function invariant(condition?: unknown, message?: string): asserts condition; // raises
                                                                           ^^^^^^^^^^^^^^^^^ [1]
   index.js:102:29
   102| function foo20(c: boolean): string {
                                    ^^^^^^ [2]


Error -------------------------------------------------------------------------------------------------- index.js:107:10

This condition is likely falsy.
[WARNING]: Flow's type inference may be incorrect that it could be null at runtime (due to `any` annotations,
out-of-bounds array accesses, etc.). If the check is valid, you might want to make [1] nullable (`T` -> `?T`).
[constant-condition]

   index.js:107:10
   107|   return invariant() && invariant(); // Error: invariant must be a top-level statement call
                 ^^^^^^^^^^^

References:
   index.js:3:68
     3| declare function invariant(condition?: unknown, message?: string): asserts condition; // raises
                                                                           ^^^^^^^^^^^^^^^^^ [1]


Error -------------------------------------------------------------------------------------------------- index.js:107:10

Cannot return `invariant() && invariant()` because `void` [1] is incompatible with `string` [2]. [incompatible-type]

   index.js:107:10
   107|   return invariant() && invariant(); // Error: invariant must be a top-level statement call
                 ^^^^^^^^^^^

References:
   index.js:3:68
     3| declare function invariant(condition?: unknown, message?: string): asserts condition; // raises
                                                                           ^^^^^^^^^^^^^^^^^ [1]
   index.js:106:29
   106| function foo21(c: boolean): string {
                                    ^^^^^^ [2]


Error --------------------------------------------------------------------------------------------------- index.js:122:3

This condition is likely falsy.
[WARNING]: Flow's type inference may be incorrect that it could be null at runtime (due to `any` annotations,
out-of-bounds array accesses, etc.). If the check is valid, you might want to make [1] nullable (`T` -> `?T`).
[constant-condition]

   index.js:122:3
   122|   invariant() ?? c; // Error: invariant must be a top-level statement call
          ^^^^^^^^^^^

References:
   index.js:3:68
     3| declare function invariant(condition?: unknown, message?: string): asserts condition; // raises
                                                                           ^^^^^^^^^^^^^^^^^ [1]


Error -------------------------------------------------------------------------------------------------- index.js:127:10

Cannot return `c ?? invariant()` because `boolean` [1] is incompatible with `string` [2]. [incompatible-type]

   index.js:127:10
   127|   return c ?? invariant(); // Error: invariant must be a top-level statement call
                 ^

References:
   index.js:126:20
   126| function foo25(c: ?boolean): string {
                           ^^^^^^^ [1]
   index.js:126:30
   126| function foo25(c: ?boolean): string {
                                     ^^^^^^ [2]


Error -------------------------------------------------------------------------------------------------- index.js:127:15

Cannot return `c ?? invariant()` because `void` [1] is incompatible with `string` [2]. [incompatible-type]

   index.js:127:15
   127|   return c ?? invariant(); // Error: invariant must be a top-level statement call
                      ^^^^^^^^^^^

References:
   index.js:3:68
     3| declare function invariant(condition?: unknown, message?: string): asserts condition; // raises
                                                                           ^^^^^^^^^^^^^^^^^ [1]
   index.js:126:30
   126| function foo25(c: ?boolean): string {
                                     ^^^^^^ [2]


Error -------------------------------------------------------------------------------------------------- index.js:131:15

Cannot return `c ?? invariant()` because `void` [1] is incompatible with `string` [2]. [incompatible-type]

   index.js:131:15
   131|   return c ?? invariant(); // Error: invariant must be a top-level statement call
                      ^^^^^^^^^^^

References:
   index.js:3:68
     3| declare function invariant(condition?: unknown, message?: string): asserts condition; // raises
                                                                           ^^^^^^^^^^^^^^^^^ [1]
   index.js:130:29
   130| function foo26(c: ?string): string {
                                    ^^^^^^ [2]


Error -------------------------------------------------------------------------------------------------- index.js:135:10

This condition is likely falsy.
[WARNING]: Flow's type inference may be incorrect that it could be null at runtime (due to `any` annotations,
out-of-bounds array accesses, etc.). If the check is valid, you might want to make [1] nullable (`T` -> `?T`).
[constant-condition]

   index.js:135:10
   135|   return invariant() && invariant(); // Error: invariant must be a top-level statement call
                 ^^^^^^^^^^^

References:
   index.js:3:68
     3| declare function invariant(condition?: unknown, message?: string): asserts condition; // raises
                                                                           ^^^^^^^^^^^^^^^^^ [1]


Error -------------------------------------------------------------------------------------------------- index.js:135:10

Cannot return `invariant() && invariant()` because `void` [1] is incompatible with `string` [2]. [incompatible-type]

   index.js:135:10
   135|   return invariant() && invariant(); // Error: invariant must be a top-level statement call
                 ^^^^^^^^^^^

References:
   index.js:3:68
     3| declare function invariant(condition?: unknown, message?: string): asserts condition; // raises
                                                                           ^^^^^^^^^^^^^^^^^ [1]
   index.js:134:29
   134| function foo27(c: boolean): string {
                                    ^^^^^^ [2]



Found 24 errors
