Error: clone_element.js:22
 22: React.cloneElement(); // Error: Needs a minimum of two arguments.
     ^^^^^^^^^^^^^^^^^^^^ call of method `cloneElement`. React.cloneElement() must be passed at least 1 arguments.

Error: clone_element.js:23
 23: React.cloneElement('nope'); // Error: Not a valid element type.
                        ^^^^^^ string. Inexact type is incompatible with exact type
 23: React.cloneElement('nope'); // Error: Not a valid element type.
                        ^^^^^^ exact type: object type

Error: clone_element.js:24
 24: React.cloneElement({ type: any }); // Error: Not a valid element type.
                        ^^^^^^^^^^^^^ property `key`. Property not found in
 24: React.cloneElement({ type: any }); // Error: Not a valid element type.
                        ^^^^^^^^^^^^^ object literal

Error: clone_element.js:24
 24: React.cloneElement({ type: any }); // Error: Not a valid element type.
                        ^^^^^^^^^^^^^ property `props`. Property not found in
 24: React.cloneElement({ type: any }); // Error: Not a valid element type.
                        ^^^^^^^^^^^^^ object literal

Error: clone_element.js:24
 24: React.cloneElement({ type: any }); // Error: Not a valid element type.
                        ^^^^^^^^^^^^^ property `ref`. Property not found in
 24: React.cloneElement({ type: any }); // Error: Not a valid element type.
                        ^^^^^^^^^^^^^ object literal

Error: clone_element.js:28
 28: (React.cloneElement(a).type: Class<B>); // Error: `a` has a type of `A`.
      ^^^^^^^^^^^^^^^^^^^^^^^^^^ A. This type is incompatible with
 28: (React.cloneElement(a).type: Class<B>); // Error: `a` has a type of `A`.
                                        ^ B

Error: clone_element.js:30
 30: (React.cloneElement(a).props.bar: empty); // Error: `bar` does not exist.
                                  ^^^ property `bar`. Property not found in
 30: (React.cloneElement(a).props.bar: empty); // Error: `bar` does not exist.
      ^^^^^^^^^^^^^^^^^^^^^^^^^^^ object type

Error: clone_element.js:31
 31: (React.cloneElement(a).props.foo: string); // Error: `foo` is number.
      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ number. This type is incompatible with
 31: (React.cloneElement(a).props.foo: string); // Error: `foo` is number.
                                       ^^^^^^ string

Error: clone_element.js:34
 34: (React.cloneElement(b).props.foo: string); // Error: `foo` is number.
      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ number. This type is incompatible with
 34: (React.cloneElement(b).props.foo: string); // Error: `foo` is number.
                                       ^^^^^^ string

Error: clone_element.js:38
 38: React.cloneElement(a, {foo: 1, bar: 2}); // OK
                           ^^^^^^^^^^^^^^^^ property `bar` of props of React element. Property not found in
  8: class A extends React.Component<{foo: number}, void> {}
                                     ^^^^^^^^^^^^^ object type

Error: clone_element.js:39
 39: React.cloneElement(a, {foo: '1'}); // Error: `foo` is a number.
                                 ^^^ string. This type is incompatible with
  8: class A extends React.Component<{foo: number}, void> {}
                                           ^^^^^^ number

Error: clone_element.js:43
 43: React.cloneElement(b, {foo: '1'}); // Error: `foo` is a number.
                                 ^^^ string. This type is incompatible with
  9: class B extends React.Component<{foo: number, bar: number}, void> {}
                                           ^^^^^^ number

Error: clone_element.js:47
 47: React.cloneElement(c, {children: '42'}); // Error: `children` is a number.
                                      ^^^^ string. This type is incompatible with
 10: class C extends React.Component<{children: number}, void> {}
                                                ^^^^^^ number

Error: clone_element.js:49
 49: React.cloneElement(c, {}, 1, 2, 3); // Error: `children` is not an array.
     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ React children array. This type is incompatible with
 10: class C extends React.Component<{children: number}, void> {}
                                                ^^^^^^ number

Error: clone_element.js:53
 53: React.cloneElement(d, {children: 42}); // Error: `children` is an array.
                                      ^^ number. This type is incompatible with
 11: class D extends React.Component<{children: Array<number>}, void> {}
                                                ^^^^^^^^^^^^^ array type

Error: clone_element.js:55
 55: React.cloneElement(d, {}, 42); // Error: `children` is an array.
                               ^^ number. This type is incompatible with
 11: class D extends React.Component<{children: Array<number>}, void> {}
                                                ^^^^^^^^^^^^^ array type

Error: create_element.js:7
  7: React.createElement(); // Error: Needs a minimum of two arguments.
     ^^^^^^^^^^^^^^^^^^^^^ call of method `createElement`. React.createElement() must be passed at least 1 arguments.

Error: create_element.js:9
  9: React.createElement(42); // Error: Number is not a valid component type.
     ^^^^^^^^^^^^^^^^^^^^^^^ call of method `createElement`. Expected React component instead of
  9: React.createElement(42); // Error: Number is not a valid component type.
                         ^^ number

Error: create_element.js:11
 11: React.createElement(42, {}); // Error: Number is not a valid component type.
     ^^^^^^^^^^^^^^^^^^^^^^^^^^^ call of method `createElement`. Expected React component instead of
 11: React.createElement(42, {}); // Error: Number is not a valid component type.
                         ^^ number

Error: create_element.js:12
 12: React.createElement({}, {}); // Error: Object is not a valid component type.
     ^^^^^^^^^^^^^^^^^^^^^^^^^^^ call of method `createElement`. Expected React component instead of
 12: React.createElement({}, {}); // Error: Object is not a valid component type.
                         ^^ object literal

Error: create_element.js:20
                            v
 20: React.createElement(A, {
 21:   foo: 42,
 22:   bar: 'Hello, world!', // Error: `bar` is a string.
 23: });
     ^ props of React element. This type is incompatible with
 15: class A extends React.Component<{foo: number, bar: number}> {}
                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^ object type
  Property `bar` is incompatible:
     22:   bar: 'Hello, world!', // Error: `bar` is a string.
                ^^^^^^^^^^^^^^^ string. This type is incompatible with
     15: class A extends React.Component<{foo: number, bar: number}> {}
                                                            ^^^^^^ number

Error: create_element.js:24
     v-----------------------
 24: React.createElement(B, {
 25:   foo: 42,
 26:   bar: 'Hello, world!', // Error: `bar` is a string.
 27: });
     -^ props of React element. This type is incompatible with the expected param type of
 16: function B(props: {foo: number, bar: number}) {}
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^ object type
  Property `bar` is incompatible:
     26:   bar: 'Hello, world!', // Error: `bar` is a string.
                ^^^^^^^^^^^^^^^ string. This type is incompatible with
     16: function B(props: {foo: number, bar: number}) {}
                                              ^^^^^^ number

Error: create_element.js:28
 28: React.createElement(A, {foo: 42}); // Error: `bar` is missing.
     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ call of method `createElement`
 15: class A extends React.Component<{foo: number, bar: number}> {}
                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^ property `bar`. Property not found in
 28: React.createElement(A, {foo: 42}); // Error: `bar` is missing.
                            ^^^^^^^^^ props of React element

Error: create_element.js:29
 29: React.createElement(B, {foo: 42}); // Error: `bar` is missing.
     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ call of method `createElement`
 16: function B(props: {foo: number, bar: number}) {}
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^ property `bar`. Property not found in
 29: React.createElement(B, {foo: 42}); // Error: `bar` is missing.
     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ props of React element

Error: create_element.js:34
 34: (React.createElement(A, {foo: 1, bar: 2}).props.foo: boolean); // Error: `foo`
      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ number. This type is incompatible with
 34: (React.createElement(A, {foo: 1, bar: 2}).props.foo: boolean); // Error: `foo`
                                                          ^^^^^^^ boolean

Error: create_element.js:36
 36: (React.createElement(B, {foo: 1, bar: 2}).props.foo: boolean); // Error: `foo`
      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ number. This type is incompatible with
 36: (React.createElement(B, {foo: 1, bar: 2}).props.foo: boolean); // Error: `foo`
                                                          ^^^^^^^ boolean

Error: create_element.js:38
 38: React.createElement(A, {foo: 1, bar: 2}).nope; // Error: `nope` does not exist.
                                              ^^^^ property `nope`. Property not found in
                                                                  v-
158: declare type React$Element<ElementType: React$ElementType> = {|
159:   +type: ElementType,
160:   +props: React$ElementProps<ElementType>,
...:
163: |};
     -^ object type. See lib: <BUILTINS>/react.js:158

Error: create_element.js:39
 39: React.createElement(B, {foo: 1, bar: 2}).nope; // Error: `nope` does not exist.
                                              ^^^^ property `nope`. Property not found in
                                                                  v-
158: declare type React$Element<ElementType: React$ElementType> = {|
159:   +type: ElementType,
160:   +props: React$ElementProps<ElementType>,
...:
163: |};
     -^ object type. See lib: <BUILTINS>/react.js:158

Error: create_element.js:40
 40: React.createElement(A); // Error: Missing `foo` and `bar`.
     ^^^^^^^^^^^^^^^^^^^^^^ call of method `createElement`
 15: class A extends React.Component<{foo: number, bar: number}> {}
                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^ property `bar`. Property not found in
 40: React.createElement(A); // Error: Missing `foo` and `bar`.
     ^^^^^^^^^^^^^^^^^^^^^^ props of React element

Error: create_element.js:40
 40: React.createElement(A); // Error: Missing `foo` and `bar`.
     ^^^^^^^^^^^^^^^^^^^^^^ call of method `createElement`
 15: class A extends React.Component<{foo: number, bar: number}> {}
                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^ property `foo`. Property not found in
 40: React.createElement(A); // Error: Missing `foo` and `bar`.
     ^^^^^^^^^^^^^^^^^^^^^^ props of React element

Error: create_element.js:41
 41: React.createElement(B); // Error: Missing `foo` and `bar`.
     ^^^^^^^^^^^^^^^^^^^^^^ call of method `createElement`
 16: function B(props: {foo: number, bar: number}) {}
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^ property `bar`. Property not found in
 41: React.createElement(B); // Error: Missing `foo` and `bar`.
     ^^^^^^^^^^^^^^^^^^^^^^ props of React element

Error: create_element.js:41
 41: React.createElement(B); // Error: Missing `foo` and `bar`.
     ^^^^^^^^^^^^^^^^^^^^^^ call of method `createElement`
 16: function B(props: {foo: number, bar: number}) {}
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^ property `foo`. Property not found in
 41: React.createElement(B); // Error: Missing `foo` and `bar`.
     ^^^^^^^^^^^^^^^^^^^^^^ props of React element

Error: create_element.js:51
                            v
 51: React.createElement(C, {
 52:   foo: 42,
 53:   bar: 'Hello, world!', // Error: `bar` is a string.
 54: });
     ^ props of React element. This type is incompatible with
 43: class C extends React.Component<{foo: number, bar: number}> {
                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^ object type
  Property `bar` is incompatible:
     53:   bar: 'Hello, world!', // Error: `bar` is a string.
                ^^^^^^^^^^^^^^^ string. This type is incompatible with
     43: class C extends React.Component<{foo: number, bar: number}> {
                                                            ^^^^^^ number

Error: create_element.js:55
     v-----------------------
 55: React.createElement(D, {
 56:   foo: 42,
 57:   bar: 'Hello, world!', // Error: `bar` is a string.
 58: });
     -^ props of React element. This type is incompatible with the expected param type of
 46: function D(props: {foo: number, bar: number}) {}
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^ object type
  Property `bar` is incompatible:
     57:   bar: 'Hello, world!', // Error: `bar` is a string.
                ^^^^^^^^^^^^^^^ string. This type is incompatible with
     46: function D(props: {foo: number, bar: number}) {}
                                              ^^^^^^ number

Error: create_element.js:67
 67: React.createElement(E, {}); // Error
     ^^^^^^^^^^^^^^^^^^^^^^^^^^ call of method `createElement`
 66: class E extends React.Component<{children: number}> {}
                                     ^^^^^^^^^^^^^^^^^^ property `children`. Property not found in
 67: React.createElement(E, {}); // Error
                            ^^ props of React element

Error: create_element.js:69
 69: React.createElement(E, {}, 1, 2); // Error
     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ React element. This type is incompatible with
 66: class E extends React.Component<{children: number}> {}
                                     ^^^^^^^^^^^^^^^^^^ object type
  Property `children` is incompatible:
     69: React.createElement(E, {}, 1, 2); // Error
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ React children array. This type is incompatible with
     66: class E extends React.Component<{children: number}> {}
                                                    ^^^^^^ number

Error: create_element.js:70
 70: React.createElement(E, {}, 1, 2, 3); // Error
     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ React element. This type is incompatible with
 66: class E extends React.Component<{children: number}> {}
                                     ^^^^^^^^^^^^^^^^^^ object type
  Property `children` is incompatible:
     70: React.createElement(E, {}, 1, 2, 3); // Error
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ React children array. This type is incompatible with
     66: class E extends React.Component<{children: number}> {}
                                                    ^^^^^^ number

Error: create_element.js:71
 71: React.createElement(E, {}, [1, 2]); // Error
     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ React element. This type is incompatible with
 66: class E extends React.Component<{children: number}> {}
                                     ^^^^^^^^^^^^^^^^^^ object type
  Property `children` is incompatible:
     71: React.createElement(E, {}, [1, 2]); // Error
                                    ^^^^^^ array literal. This type is incompatible with
     66: class E extends React.Component<{children: number}> {}
                                                    ^^^^^^ number

Error: create_element.js:72
 72: React.createElement(E, {}, [1, 2], [3, 4]); // Error
     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ React element. This type is incompatible with
 66: class E extends React.Component<{children: number}> {}
                                     ^^^^^^^^^^^^^^^^^^ object type
  Property `children` is incompatible:
     72: React.createElement(E, {}, [1, 2], [3, 4]); // Error
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ React children array. This type is incompatible with
     66: class E extends React.Component<{children: number}> {}
                                                    ^^^^^^ number

Error: create_element.js:73
 73: React.createElement(E, {}, ...[]); // Error
     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ call of method `createElement`
 66: class E extends React.Component<{children: number}> {}
                                     ^^^^^^^^^^^^^^^^^^ property `children`. Property not found in
 73: React.createElement(E, {}, ...[]); // Error
                            ^^ props of React element

Error: create_element.js:75
 75: React.createElement(E, {}, ...[1, 2]); // Error
     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ React element. This type is incompatible with
 66: class E extends React.Component<{children: number}> {}
                                     ^^^^^^^^^^^^^^^^^^ object type
  Property `children` is incompatible:
     75: React.createElement(E, {}, ...[1, 2]); // Error
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ React children array. This type is incompatible with
     66: class E extends React.Component<{children: number}> {}
                                                    ^^^^^^ number

Error: create_element.js:76
 76: React.createElement(E, {}, ...(any: Array<number>)); // Error
     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ React element. This type is incompatible with
 66: class E extends React.Component<{children: number}> {}
                                     ^^^^^^^^^^^^^^^^^^ object type
  Property `children` is incompatible:
     76: React.createElement(E, {}, ...(any: Array<number>)); // Error
                                             ^^^^^^^^^^^^^ React children array, undefined, or array. This type is incompatible with
     66: class E extends React.Component<{children: number}> {}
                                                    ^^^^^^ number

Error: create_element.js:76
 76: React.createElement(E, {}, ...(any: Array<number>)); // Error
     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ React element. This type is incompatible with
 66: class E extends React.Component<{children: number}> {}
                                     ^^^^^^^^^^^^^^^^^^ object type
  Property `children` is incompatible:
     76: React.createElement(E, {}, ...(any: Array<number>)); // Error
                                             ^^^^^^^^^^^^^ undefined. This type is incompatible with
     66: class E extends React.Component<{children: number}> {}
                                                    ^^^^^^ number

Error: create_element.js:78
 78: React.createElement(E, {}, 1, ...[2]); // Error
     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ React element. This type is incompatible with
 66: class E extends React.Component<{children: number}> {}
                                     ^^^^^^^^^^^^^^^^^^ object type
  Property `children` is incompatible:
     78: React.createElement(E, {}, 1, ...[2]); // Error
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ React children array. This type is incompatible with
     66: class E extends React.Component<{children: number}> {}
                                                    ^^^^^^ number

Error: create_element.js:79
 79: React.createElement(E, {}, 1, ...(any: Array<number>)); // Error
     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ React element. This type is incompatible with
 66: class E extends React.Component<{children: number}> {}
                                     ^^^^^^^^^^^^^^^^^^ object type
  Property `children` is incompatible:
     79: React.createElement(E, {}, 1, ...(any: Array<number>)); // Error
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ React children array or number. This type is incompatible with
     66: class E extends React.Component<{children: number}> {}
                                                    ^^^^^^ number

Error: create_element.js:82
 82: React.createElement(F, {}); // Error
     ^^^^^^^^^^^^^^^^^^^^^^^^^^ call of method `createElement`
 81: class F extends React.Component<{children: Array<number>}> {}
                                     ^^^^^^^^^^^^^^^^^^^^^^^^^ property `children`. Property not found in
 82: React.createElement(F, {}); // Error
                            ^^ props of React element

Error: create_element.js:83
 83: React.createElement(F, {}, 1); // Error
     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ React element. This type is incompatible with
 81: class F extends React.Component<{children: Array<number>}> {}
                                     ^^^^^^^^^^^^^^^^^^^^^^^^^ object type
  Property `children` is incompatible:
     83: React.createElement(F, {}, 1); // Error
                                    ^ number. This type is incompatible with
     81: class F extends React.Component<{children: Array<number>}> {}
                                                    ^^^^^^^^^^^^^ array type

Error: create_element.js:87
 87: React.createElement(F, {}, [1, 2], [3, 4]); // Error
     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ call of method `createElement`
 87: React.createElement(F, {}, [1, 2], [3, 4]); // Error
                                ^^^^^^ array literal. This type is incompatible with
 81: class F extends React.Component<{children: Array<number>}> {}
                                                      ^^^^^^ number

Error: create_element.js:87
 87: React.createElement(F, {}, [1, 2], [3, 4]); // Error
     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ call of method `createElement`
 87: React.createElement(F, {}, [1, 2], [3, 4]); // Error
                                        ^^^^^^ array literal. This type is incompatible with
 81: class F extends React.Component<{children: Array<number>}> {}
                                                      ^^^^^^ number

Error: create_element.js:88
 88: React.createElement(F, {}, ...[]); // Error
     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ call of method `createElement`
 81: class F extends React.Component<{children: Array<number>}> {}
                                     ^^^^^^^^^^^^^^^^^^^^^^^^^ property `children`. Property not found in
 88: React.createElement(F, {}, ...[]); // Error
                            ^^ props of React element

Error: create_element.js:89
 89: React.createElement(F, {}, ...[1]); // Error
     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ React element. This type is incompatible with
 81: class F extends React.Component<{children: Array<number>}> {}
                                     ^^^^^^^^^^^^^^^^^^^^^^^^^ object type
  Property `children` is incompatible:
     89: React.createElement(F, {}, ...[1]); // Error
                                        ^ number. This type is incompatible with
     81: class F extends React.Component<{children: Array<number>}> {}
                                                    ^^^^^^^^^^^^^ array type

Error: create_element.js:91
 91: React.createElement(F, {}, ...(any: Array<number>)); // Error
     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ React element. This type is incompatible with
 81: class F extends React.Component<{children: Array<number>}> {}
                                     ^^^^^^^^^^^^^^^^^^^^^^^^^ object type
  Property `children` is incompatible:
     81: class F extends React.Component<{children: Array<number>}> {}
                                                          ^^^^^^ number. This type is incompatible with
     81: class F extends React.Component<{children: Array<number>}> {}
                                                    ^^^^^^^^^^^^^ array type

Error: create_element.js:91
 91: React.createElement(F, {}, ...(any: Array<number>)); // Error
     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ React element. This type is incompatible with
 81: class F extends React.Component<{children: Array<number>}> {}
                                     ^^^^^^^^^^^^^^^^^^^^^^^^^ object type
  Property `children` is incompatible:
     91: React.createElement(F, {}, ...(any: Array<number>)); // Error
                                             ^^^^^^^^^^^^^ undefined. This type is incompatible with
     81: class F extends React.Component<{children: Array<number>}> {}
                                                    ^^^^^^^^^^^^^ array type

Error: create_element.js:91
 91: React.createElement(F, {}, ...(any: Array<number>)); // Error
     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ React element. This type is incompatible with
 81: class F extends React.Component<{children: Array<number>}> {}
                                     ^^^^^^^^^^^^^^^^^^^^^^^^^ object type
  Property `children` is incompatible:
     91: React.createElement(F, {}, ...(any: Array<number>)); // Error
                                                   ^^^^^^ number. This type is incompatible with
     81: class F extends React.Component<{children: Array<number>}> {}
                                                    ^^^^^^^^^^^^^ array type

Error: create_element.js:92
 92: React.createElement(F, {}, 1, ...[]); // Error
     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ React element. This type is incompatible with
 81: class F extends React.Component<{children: Array<number>}> {}
                                     ^^^^^^^^^^^^^^^^^^^^^^^^^ object type
  Property `children` is incompatible:
     92: React.createElement(F, {}, 1, ...[]); // Error
                                    ^ number. This type is incompatible with
     81: class F extends React.Component<{children: Array<number>}> {}
                                                    ^^^^^^^^^^^^^ array type

Error: create_element.js:94
 94: React.createElement(F, {}, 1, ...(any: Array<number>)); // Error
     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ React element. This type is incompatible with
 81: class F extends React.Component<{children: Array<number>}> {}
                                     ^^^^^^^^^^^^^^^^^^^^^^^^^ object type
  Property `children` is incompatible:
     94: React.createElement(F, {}, 1, ...(any: Array<number>)); // Error
                                    ^ number. This type is incompatible with
     81: class F extends React.Component<{children: Array<number>}> {}
                                                    ^^^^^^^^^^^^^ array type

Error: create_element.js:97
 97: React.createElement(G, {}); // Error
     ^^^^^^^^^^^^^^^^^^^^^^^^^^ call of method `createElement`
 96: class G extends React.Component<{children: number | Array<number>}> {}
                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ property `children`. Property not found in
 97: React.createElement(G, {}); // Error
                            ^^ props of React element

Error: create_element.js:102
102: React.createElement(G, {}, [1, 2], [3, 4]); // Error
     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ call of method `createElement`
102: React.createElement(G, {}, [1, 2], [3, 4]); // Error
                                ^^^^^^ array literal. This type is incompatible with
 96: class G extends React.Component<{children: number | Array<number>}> {}
                                                               ^^^^^^ number

Error: create_element.js:102
102: React.createElement(G, {}, [1, 2], [3, 4]); // Error
     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ call of method `createElement`
102: React.createElement(G, {}, [1, 2], [3, 4]); // Error
                                        ^^^^^^ array literal. This type is incompatible with
 96: class G extends React.Component<{children: number | Array<number>}> {}
                                                               ^^^^^^ number

Error: create_element.js:103
103: React.createElement(G, {}, ...[]); // Error
     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ call of method `createElement`
 96: class G extends React.Component<{children: number | Array<number>}> {}
                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ property `children`. Property not found in
103: React.createElement(G, {}, ...[]); // Error
                            ^^ props of React element

Error: create_element.js:106
106: React.createElement(G, {}, ...(any: Array<number>)); // Error
     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ call of method `createElement`
106: React.createElement(G, {}, ...(any: Array<number>)); // Error
                                         ^^^^^^^^^^^^^ undefined. This type is incompatible with
 96: class G extends React.Component<{children: number | Array<number>}> {}
                                                ^^^^^^^^^^^^^^^^^^^^^^ union: number | array type
  Member 1:
   96: class G extends React.Component<{children: number | Array<number>}> {}
                                                  ^^^^^^ number
  Error:
  106: React.createElement(G, {}, ...(any: Array<number>)); // Error
                                           ^^^^^^^^^^^^^ undefined. This type is incompatible with
   96: class G extends React.Component<{children: number | Array<number>}> {}
                                                  ^^^^^^ number
  Member 2:
   96: class G extends React.Component<{children: number | Array<number>}> {}
                                                           ^^^^^^^^^^^^^ array type
  Error:
  106: React.createElement(G, {}, ...(any: Array<number>)); // Error
                                           ^^^^^^^^^^^^^ undefined. This type is incompatible with
   96: class G extends React.Component<{children: number | Array<number>}> {}
                                                           ^^^^^^^^^^^^^ array type

Error: create_element.js:117
117: React.createElement(G2, {}, [1, 2], [3, 4]); // Error
     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ call of method `createElement`
117: React.createElement(G2, {}, [1, 2], [3, 4]); // Error
                                 ^^^^^^ array literal. This type is incompatible with
111: class G2 extends React.Component<{children?: number | Array<number>}> {}
                                                                 ^^^^^^ number

Error: create_element.js:117
117: React.createElement(G2, {}, [1, 2], [3, 4]); // Error
     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ call of method `createElement`
117: React.createElement(G2, {}, [1, 2], [3, 4]); // Error
                                         ^^^^^^ array literal. This type is incompatible with
111: class G2 extends React.Component<{children?: number | Array<number>}> {}
                                                                 ^^^^^^ number

Error: create_element.js:128
128: React.createElement(H, {}); // Error
     ^^^^^^^^^^^^^^^^^^^^^^^^^^ call of method `createElement`
127: class H extends React.Component<{children: NumberArrayRecursive}> {}
                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ property `children`. Property not found in
128: React.createElement(H, {}); // Error
                            ^^ props of React element

Error: create_element.js:134
134: React.createElement(H, {}, ...[]); // Error
     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ call of method `createElement`
127: class H extends React.Component<{children: NumberArrayRecursive}> {}
                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ property `children`. Property not found in
134: React.createElement(H, {}, ...[]); // Error
                            ^^ props of React element

Error: create_element.js:137
137: React.createElement(H, {}, ...(any: Array<number>)); // Error
     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ call of method `createElement`
137: React.createElement(H, {}, ...(any: Array<number>)); // Error
                                         ^^^^^^^^^^^^^ undefined. This type is incompatible with
127: class H extends React.Component<{children: NumberArrayRecursive}> {}
                                                ^^^^^^^^^^^^^^^^^^^^ union: number | array type
  Member 1:
  126: type NumberArrayRecursive = number | Array<NumberArrayRecursive>;
                                   ^^^^^^ number
  Error:
  137: React.createElement(H, {}, ...(any: Array<number>)); // Error
                                           ^^^^^^^^^^^^^ undefined. This type is incompatible with
  126: type NumberArrayRecursive = number | Array<NumberArrayRecursive>;
                                   ^^^^^^ number
  Member 2:
  126: type NumberArrayRecursive = number | Array<NumberArrayRecursive>;
                                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^ array type
  Error:
  137: React.createElement(H, {}, ...(any: Array<number>)); // Error
                                           ^^^^^^^^^^^^^ undefined. This type is incompatible with
  126: type NumberArrayRecursive = number | Array<NumberArrayRecursive>;
                                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^ array type

Error: create_element.js:145
145: React.createElement(I, {}, null); // Error
     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ React element. This type is incompatible with
142: class I extends React.Component<{children?: number}> {}
                                     ^^^^^^^^^^^^^^^^^^^ object type
  Property `children` is incompatible:
    145: React.createElement(I, {}, null); // Error
                                    ^^^^ null. This type is incompatible with
    142: class I extends React.Component<{children?: number}> {}
                                                     ^^^^^^ number

Error: create_element.js:147
147: React.createElement(I, {}, 1, 2); // Error
     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ React element. This type is incompatible with
142: class I extends React.Component<{children?: number}> {}
                                     ^^^^^^^^^^^^^^^^^^^ object type
  Property `children` is incompatible:
    147: React.createElement(I, {}, 1, 2); // Error
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ React children array. This type is incompatible with
    142: class I extends React.Component<{children?: number}> {}
                                                     ^^^^^^ number

Error: create_element.js:150
150: React.createElement(I, {}, ...[1, 2]); // Error
     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ React element. This type is incompatible with
142: class I extends React.Component<{children?: number}> {}
                                     ^^^^^^^^^^^^^^^^^^^ object type
  Property `children` is incompatible:
    150: React.createElement(I, {}, ...[1, 2]); // Error
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ React children array. This type is incompatible with
    142: class I extends React.Component<{children?: number}> {}
                                                     ^^^^^^ number

Error: create_element.js:151
151: React.createElement(I, {}, ...(any: Array<number>)); // Error
     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ React element. This type is incompatible with
142: class I extends React.Component<{children?: number}> {}
                                     ^^^^^^^^^^^^^^^^^^^ object type
  Property `children` is incompatible:
    151: React.createElement(I, {}, ...(any: Array<number>)); // Error
                                             ^^^^^^^^^^^^^ React children array, undefined, or array. This type is incompatible with
    142: class I extends React.Component<{children?: number}> {}
                                                     ^^^^^^ number

Error: create_element.js:153
153: React.createElement(I, {}, 1, ...[2]); // Error
     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ React element. This type is incompatible with
142: class I extends React.Component<{children?: number}> {}
                                     ^^^^^^^^^^^^^^^^^^^ object type
  Property `children` is incompatible:
    153: React.createElement(I, {}, 1, ...[2]); // Error
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ React children array. This type is incompatible with
    142: class I extends React.Component<{children?: number}> {}
                                                     ^^^^^^ number

Error: create_element.js:154
154: React.createElement(I, {}, 1, ...(any: Array<number>)); // Error
     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ React element. This type is incompatible with
142: class I extends React.Component<{children?: number}> {}
                                     ^^^^^^^^^^^^^^^^^^^ object type
  Property `children` is incompatible:
    154: React.createElement(I, {}, 1, ...(any: Array<number>)); // Error
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ React children array or number. This type is incompatible with
    142: class I extends React.Component<{children?: number}> {}
                                                     ^^^^^^ number

Error: create_element.js:157
157: React.createElement(J, {}); // Error
     ^^^^^^^^^^^^^^^^^^^^^^^^^^ call of method `createElement`
156: class J extends React.Component<{children: ?number}> {}
                                     ^^^^^^^^^^^^^^^^^^^ property `children`. Property not found in
157: React.createElement(J, {}); // Error
                            ^^ props of React element

Error: create_element.js:161
161: React.createElement(J, {}, 1, 2); // Error
     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ React element. This type is incompatible with
156: class J extends React.Component<{children: ?number}> {}
                                     ^^^^^^^^^^^^^^^^^^^ object type
  Property `children` is incompatible:
    161: React.createElement(J, {}, 1, 2); // Error
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ React children array. This type is incompatible with
    156: class J extends React.Component<{children: ?number}> {}
                                                     ^^^^^^ number

Error: create_element.js:162
162: React.createElement(J, {}, ...[]); // Error
     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ call of method `createElement`
156: class J extends React.Component<{children: ?number}> {}
                                     ^^^^^^^^^^^^^^^^^^^ property `children`. Property not found in
162: React.createElement(J, {}, ...[]); // Error
                            ^^ props of React element

Error: create_element.js:164
164: React.createElement(J, {}, ...[1, 2]); // Error
     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ React element. This type is incompatible with
156: class J extends React.Component<{children: ?number}> {}
                                     ^^^^^^^^^^^^^^^^^^^ object type
  Property `children` is incompatible:
    164: React.createElement(J, {}, ...[1, 2]); // Error
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ React children array. This type is incompatible with
    156: class J extends React.Component<{children: ?number}> {}
                                                     ^^^^^^ number

Error: create_element.js:165
165: React.createElement(J, {}, ...(any: Array<number>)); // Error
     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ React element. This type is incompatible with
156: class J extends React.Component<{children: ?number}> {}
                                     ^^^^^^^^^^^^^^^^^^^ object type
  Property `children` is incompatible:
    165: React.createElement(J, {}, ...(any: Array<number>)); // Error
                                             ^^^^^^^^^^^^^ React children array, undefined, or array. This type is incompatible with
    156: class J extends React.Component<{children: ?number}> {}
                                                     ^^^^^^ number

Error: create_element.js:167
167: React.createElement(J, {}, 1, ...[2]); // Error
     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ React element. This type is incompatible with
156: class J extends React.Component<{children: ?number}> {}
                                     ^^^^^^^^^^^^^^^^^^^ object type
  Property `children` is incompatible:
    167: React.createElement(J, {}, 1, ...[2]); // Error
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ React children array. This type is incompatible with
    156: class J extends React.Component<{children: ?number}> {}
                                                     ^^^^^^ number

Error: create_element.js:168
168: React.createElement(J, {}, 1, ...(any: Array<number>)); // Error
     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ React element. This type is incompatible with
156: class J extends React.Component<{children: ?number}> {}
                                     ^^^^^^^^^^^^^^^^^^^ object type
  Property `children` is incompatible:
    168: React.createElement(J, {}, 1, ...(any: Array<number>)); // Error
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ React children array or number. This type is incompatible with
    156: class J extends React.Component<{children: ?number}> {}
                                                     ^^^^^^ number

Error: create_element.js:174
174: React.createElement(K, {}, '42'); // Error
     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ React element. This type is incompatible with
170: class K extends React.Component<{children: number}> {}
                                     ^^^^^^^^^^^^^^^^^^ object type
  Property `children` is incompatible:
    174: React.createElement(K, {}, '42'); // Error
                                    ^^^^ string. This type is incompatible with
    170: class K extends React.Component<{children: number}> {}
                                                    ^^^^^^ number

Error: create_element.js:175
175: React.createElement(K, {children: '42'}); // Error
                            ^^^^^^^^^^^^^^^^ props of React element. This type is incompatible with
170: class K extends React.Component<{children: number}> {}
                                     ^^^^^^^^^^^^^^^^^^ object type
  Property `children` is incompatible:
    175: React.createElement(K, {children: '42'}); // Error
                                           ^^^^ string. This type is incompatible with
    170: class K extends React.Component<{children: number}> {}
                                                    ^^^^^^ number

Error: create_element.js:176
176: React.createElement(K, {children: '42'}, 42); // Error
     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ React element. This type is incompatible with
170: class K extends React.Component<{children: number}> {}
                                     ^^^^^^^^^^^^^^^^^^ object type
  Property `children` is incompatible:
    176: React.createElement(K, {children: '42'}, 42); // Error
                                           ^^^^ string. This type is incompatible with
    170: class K extends React.Component<{children: number}> {}
                                                    ^^^^^^ number

Error: create_element.js:178
178: React.createElement(K, {children: '42'}, '42'); // Error
     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ React element. This type is incompatible with
170: class K extends React.Component<{children: number}> {}
                                     ^^^^^^^^^^^^^^^^^^ object type
  Property `children` is incompatible:
    178: React.createElement(K, {children: '42'}, '42'); // Error
                                           ^^^^ string. This type is incompatible with
    170: class K extends React.Component<{children: number}> {}
                                                    ^^^^^^ number

Error: create_element.js:191
191: React.createElement(L, {}, 1); // Error
     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ call of method `createElement`
                                     v
180: class L extends React.Component<{
181:   foo: number,
182:   bar: number,
183:   children: number,
184: }> {
     ^ property `foo`. Property not found in
191: React.createElement(L, {}, 1); // Error
     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ React element

Error: create_element.js:192
192: React.createElement(L, {children: 1}); // Error
     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ call of method `createElement`
                                     v
180: class L extends React.Component<{
181:   foo: number,
182:   bar: number,
183:   children: number,
184: }> {
     ^ property `foo`. Property not found in
192: React.createElement(L, {children: 1}); // Error
                            ^^^^^^^^^^^^^ props of React element

Error: create_element.js:193
193: React.createElement(L, {bar: 1}, 2); // Error
     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ call of method `createElement`
                                     v
180: class L extends React.Component<{
181:   foo: number,
182:   bar: number,
183:   children: number,
184: }> {
     ^ property `foo`. Property not found in
193: React.createElement(L, {bar: 1}, 2); // Error
     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ React element

Error: create_element.js:194
194: React.createElement(L, {bar: 1, children: 2}); // Error
     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ call of method `createElement`
                                     v
180: class L extends React.Component<{
181:   foo: number,
182:   bar: number,
183:   children: number,
184: }> {
     ^ property `foo`. Property not found in
194: React.createElement(L, {bar: 1, children: 2}); // Error
                            ^^^^^^^^^^^^^^^^^^^^^ props of React element

Error: create_element.js:195
195: React.createElement(L, {foo: '1', bar: 2}, 3); // Error
     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ React element. This type is incompatible with
                                     v
180: class L extends React.Component<{
181:   foo: number,
182:   bar: number,
183:   children: number,
184: }> {
     ^ object type
  Property `foo` is incompatible:
    195: React.createElement(L, {foo: '1', bar: 2}, 3); // Error
                                      ^^^ string. This type is incompatible with
    181:   foo: number,
                ^^^^^^ number

Error: create_element.js:196
196: React.createElement(L, {foo: '1', bar: 2, children: 3}); // Error
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ props of React element. This type is incompatible with
                                     v
180: class L extends React.Component<{
181:   foo: number,
182:   bar: number,
183:   children: number,
184: }> {
     ^ object type
  Property `foo` is incompatible:
    196: React.createElement(L, {foo: '1', bar: 2, children: 3}); // Error
                                      ^^^ string. This type is incompatible with
    181:   foo: number,
                ^^^^^^ number

Error: create_element.js:197
197: React.createElement(L, {foo: 1, bar: '2'}, 3); // Error
     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ React element. This type is incompatible with
                                     v
180: class L extends React.Component<{
181:   foo: number,
182:   bar: number,
183:   children: number,
184: }> {
     ^ object type
  Property `bar` is incompatible:
    197: React.createElement(L, {foo: 1, bar: '2'}, 3); // Error
                                              ^^^ string. This type is incompatible with
    182:   bar: number,
                ^^^^^^ number

Error: create_element.js:198
198: React.createElement(L, {foo: 1, bar: '2', children: 3}); // Error
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ props of React element. This type is incompatible with
                                     v
180: class L extends React.Component<{
181:   foo: number,
182:   bar: number,
183:   children: number,
184: }> {
     ^ object type
  Property `bar` is incompatible:
    198: React.createElement(L, {foo: 1, bar: '2', children: 3}); // Error
                                              ^^^ string. This type is incompatible with
    182:   bar: number,
                ^^^^^^ number

Error: create_element.js:199
199: React.createElement(L, {foo: 1, bar: 2}, '3'); // Error
     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ React element. This type is incompatible with
                                     v
180: class L extends React.Component<{
181:   foo: number,
182:   bar: number,
183:   children: number,
184: }> {
     ^ object type
  Property `children` is incompatible:
    199: React.createElement(L, {foo: 1, bar: 2}, '3'); // Error
                                                  ^^^ string. This type is incompatible with
    183:   children: number,
                     ^^^^^^ number

Error: create_element.js:200
200: React.createElement(L, {foo: 1, bar: 2, children: '3'}); // Error
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ props of React element. This type is incompatible with
                                     v
180: class L extends React.Component<{
181:   foo: number,
182:   bar: number,
183:   children: number,
184: }> {
     ^ object type
  Property `children` is incompatible:
    200: React.createElement(L, {foo: 1, bar: 2, children: '3'}); // Error
                                                           ^^^ string. This type is incompatible with
    183:   children: number,
                     ^^^^^^ number

Error: create_element.js:205
205: (React.createElement(M).type: typeof N); // Error
      ^^^^^^^^^^^^^^^^^^^^^^^^^^^ M. This type is incompatible with
203: class N extends React.Component<{}> {}
           ^ N

Error: create_factory.js:18
              v
 18: aFactory({
 19:   foo: 42,
 20:   bar: 'Hello, world!', // Error: `bar` is a string.
 21: });
     ^ props of React element. This type is incompatible with
 10: class A extends React.Component<{foo: number, bar: number}, void> {}
                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^ object type
  Property `bar` is incompatible:
     20:   bar: 'Hello, world!', // Error: `bar` is a string.
                ^^^^^^^^^^^^^^^ string. This type is incompatible with
     10: class A extends React.Component<{foo: number, bar: number}, void> {}
                                                            ^^^^^^ number

Error: create_factory.js:22
     v---------
 22: bFactory({
 23:   foo: 42,
 24:   bar: 'Hello, world!', // Error: `bar` is a string.
 25: });
     -^ props of React element. This type is incompatible with the expected param type of
 11: function B(props: {foo: number, bar: number}) {}
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^ object type
  Property `bar` is incompatible:
     24:   bar: 'Hello, world!', // Error: `bar` is a string.
                ^^^^^^^^^^^^^^^ string. This type is incompatible with
     11: function B(props: {foo: number, bar: number}) {}
                                              ^^^^^^ number

Error: create_factory.js:26
 26: aFactory({foo: 42}); // Error: `bar` is missing.
     ^^^^^^^^^^^^^^^^^^^ function call
 10: class A extends React.Component<{foo: number, bar: number}, void> {}
                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^ property `bar`. Property not found in
 26: aFactory({foo: 42}); // Error: `bar` is missing.
              ^^^^^^^^^ props of React element

Error: create_factory.js:27
 27: bFactory({foo: 42}); // Error: `bar` is missing.
     ^^^^^^^^^^^^^^^^^^^ function call
 11: function B(props: {foo: number, bar: number}) {}
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^ property `bar`. Property not found in
 27: bFactory({foo: 42}); // Error: `bar` is missing.
     ^^^^^^^^^^^^^^^^^^^ props of React element

Error: create_factory.js:32
 32: (aFactory({foo: 1, bar: 2}).props.foo: boolean); // Error: `foo` is `number`.
      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ number. This type is incompatible with
 32: (aFactory({foo: 1, bar: 2}).props.foo: boolean); // Error: `foo` is `number`.
                                            ^^^^^^^ boolean

Error: create_factory.js:33
 33: (bFactory({foo: 1, bar: 2}).props.foo: boolean); // Error: `foo` is `number`.
      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ number. This type is incompatible with
 33: (bFactory({foo: 1, bar: 2}).props.foo: boolean); // Error: `foo` is `number`.
                                            ^^^^^^^ boolean

Error: create_factory.js:34
 34: aFactory({foo: 1, bar: 2}).nope; // Error: `nope` does not exist.
                                ^^^^ property `nope`. Property not found in
                                                                  v-
158: declare type React$Element<ElementType: React$ElementType> = {|
159:   +type: ElementType,
160:   +props: React$ElementProps<ElementType>,
...:
163: |};
     -^ object type. See lib: <BUILTINS>/react.js:158

Error: create_factory.js:35
 35: bFactory({foo: 1, bar: 2}).nope; // Error: `nope` does not exist.
                                ^^^^ property `nope`. Property not found in
                                                                  v-
158: declare type React$Element<ElementType: React$ElementType> = {|
159:   +type: ElementType,
160:   +props: React$ElementProps<ElementType>,
...:
163: |};
     -^ object type. See lib: <BUILTINS>/react.js:158

Error: create_factory.js:36
 36: aFactory(); // Error: Missing `foo` and `bar`.
     ^^^^^^^^^^ function call
 10: class A extends React.Component<{foo: number, bar: number}, void> {}
                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^ property `bar`. Property not found in
 36: aFactory(); // Error: Missing `foo` and `bar`.
     ^^^^^^^^^^ props of React element

Error: create_factory.js:36
 36: aFactory(); // Error: Missing `foo` and `bar`.
     ^^^^^^^^^^ function call
 10: class A extends React.Component<{foo: number, bar: number}, void> {}
                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^ property `foo`. Property not found in
 36: aFactory(); // Error: Missing `foo` and `bar`.
     ^^^^^^^^^^ props of React element

Error: create_factory.js:37
 37: bFactory(); // Error: Missing `foo` and `bar`.
     ^^^^^^^^^^ function call
 11: function B(props: {foo: number, bar: number}) {}
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^ property `bar`. Property not found in
 37: bFactory(); // Error: Missing `foo` and `bar`.
     ^^^^^^^^^^ props of React element

Error: create_factory.js:37
 37: bFactory(); // Error: Missing `foo` and `bar`.
     ^^^^^^^^^^ function call
 11: function B(props: {foo: number, bar: number}) {}
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^ property `foo`. Property not found in
 37: bFactory(); // Error: Missing `foo` and `bar`.
     ^^^^^^^^^^ props of React element

Error: create_factory.js:50
              v
 50: cFactory({
 51:   foo: 42,
 52:   bar: 'Hello, world!', // Error: `bar` is a string.
 53: });
     ^ props of React element. This type is incompatible with
 39: class C extends React.Component<{foo: number, bar: number}, void> {
                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^ object type
  Property `bar` is incompatible:
     52:   bar: 'Hello, world!', // Error: `bar` is a string.
                ^^^^^^^^^^^^^^^ string. This type is incompatible with
     39: class C extends React.Component<{foo: number, bar: number}, void> {
                                                            ^^^^^^ number

Error: create_factory.js:54
     v---------
 54: dFactory({
 55:   foo: 42,
 56:   bar: 'Hello, world!', // Error: `bar` is a string.
 57: });
     -^ props of React element. This type is incompatible with the expected param type of
 42: function D(props: {foo: number, bar: number}) {}
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^ object type
  Property `bar` is incompatible:
     56:   bar: 'Hello, world!', // Error: `bar` is a string.
                ^^^^^^^^^^^^^^^ string. This type is incompatible with
     42: function D(props: {foo: number, bar: number}) {}
                                              ^^^^^^ number

Error: create_factory.js:69
 69: eFactory({}); // Error
     ^^^^^^^^^^^^ function call
 67: class E extends React.Component<{children: number}, void> {}
                                     ^^^^^^^^^^^^^^^^^^ property `children`. Property not found in
 69: eFactory({}); // Error
              ^^ props of React element

Error: create_factory.js:71
 71: eFactory({}, 1, 2); // Error
     ^^^^^^^^^^^^^^^^^^ React element. This type is incompatible with
 67: class E extends React.Component<{children: number}, void> {}
                                     ^^^^^^^^^^^^^^^^^^ object type
  Property `children` is incompatible:
     71: eFactory({}, 1, 2); // Error
         ^^^^^^^^^^^^^^^^^^ React children array. This type is incompatible with
     67: class E extends React.Component<{children: number}, void> {}
                                                    ^^^^^^ number

Error: create_factory.js:72
 72: eFactory({}, 1, 2, 3); // Error
     ^^^^^^^^^^^^^^^^^^^^^ React element. This type is incompatible with
 67: class E extends React.Component<{children: number}, void> {}
                                     ^^^^^^^^^^^^^^^^^^ object type
  Property `children` is incompatible:
     72: eFactory({}, 1, 2, 3); // Error
         ^^^^^^^^^^^^^^^^^^^^^ React children array. This type is incompatible with
     67: class E extends React.Component<{children: number}, void> {}
                                                    ^^^^^^ number

Error: create_factory.js:73
 73: eFactory({}, [1, 2]); // Error
     ^^^^^^^^^^^^^^^^^^^^ React element. This type is incompatible with
 67: class E extends React.Component<{children: number}, void> {}
                                     ^^^^^^^^^^^^^^^^^^ object type
  Property `children` is incompatible:
     73: eFactory({}, [1, 2]); // Error
                      ^^^^^^ array literal. This type is incompatible with
     67: class E extends React.Component<{children: number}, void> {}
                                                    ^^^^^^ number

Error: create_factory.js:74
 74: eFactory({}, [1, 2], [3, 4]); // Error
     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^ React element. This type is incompatible with
 67: class E extends React.Component<{children: number}, void> {}
                                     ^^^^^^^^^^^^^^^^^^ object type
  Property `children` is incompatible:
     74: eFactory({}, [1, 2], [3, 4]); // Error
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^ React children array. This type is incompatible with
     67: class E extends React.Component<{children: number}, void> {}
                                                    ^^^^^^ number

Error: create_factory.js:75
 75: eFactory({}, ...[]); // Error
     ^^^^^^^^^^^^^^^^^^^ function call
 67: class E extends React.Component<{children: number}, void> {}
                                     ^^^^^^^^^^^^^^^^^^ property `children`. Property not found in
 75: eFactory({}, ...[]); // Error
              ^^ props of React element

Error: create_factory.js:77
 77: eFactory({}, ...[1, 2]); // Error
     ^^^^^^^^^^^^^^^^^^^^^^^ React element. This type is incompatible with
 67: class E extends React.Component<{children: number}, void> {}
                                     ^^^^^^^^^^^^^^^^^^ object type
  Property `children` is incompatible:
     77: eFactory({}, ...[1, 2]); // Error
         ^^^^^^^^^^^^^^^^^^^^^^^ React children array. This type is incompatible with
     67: class E extends React.Component<{children: number}, void> {}
                                                    ^^^^^^ number

Error: create_factory.js:78
 78: eFactory({}, ...(any: Array<number>)); // Error
     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ React element. This type is incompatible with
 67: class E extends React.Component<{children: number}, void> {}
                                     ^^^^^^^^^^^^^^^^^^ object type
  Property `children` is incompatible:
     78: eFactory({}, ...(any: Array<number>)); // Error
                               ^^^^^^^^^^^^^ React children array, undefined, or array. This type is incompatible with
     67: class E extends React.Component<{children: number}, void> {}
                                                    ^^^^^^ number

Error: create_factory.js:78
 78: eFactory({}, ...(any: Array<number>)); // Error
     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ React element. This type is incompatible with
 67: class E extends React.Component<{children: number}, void> {}
                                     ^^^^^^^^^^^^^^^^^^ object type
  Property `children` is incompatible:
     78: eFactory({}, ...(any: Array<number>)); // Error
                               ^^^^^^^^^^^^^ undefined. This type is incompatible with
     67: class E extends React.Component<{children: number}, void> {}
                                                    ^^^^^^ number

Error: create_factory.js:80
 80: eFactory({}, 1, ...[2]); // Error
     ^^^^^^^^^^^^^^^^^^^^^^^ React element. This type is incompatible with
 67: class E extends React.Component<{children: number}, void> {}
                                     ^^^^^^^^^^^^^^^^^^ object type
  Property `children` is incompatible:
     80: eFactory({}, 1, ...[2]); // Error
         ^^^^^^^^^^^^^^^^^^^^^^^ React children array. This type is incompatible with
     67: class E extends React.Component<{children: number}, void> {}
                                                    ^^^^^^ number

Error: create_factory.js:81
 81: eFactory({}, 1, ...(any: Array<number>)); // Error
     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ React element. This type is incompatible with
 67: class E extends React.Component<{children: number}, void> {}
                                     ^^^^^^^^^^^^^^^^^^ object type
  Property `children` is incompatible:
     81: eFactory({}, 1, ...(any: Array<number>)); // Error
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ React children array or number. This type is incompatible with
     67: class E extends React.Component<{children: number}, void> {}
                                                    ^^^^^^ number

Error: create_factory.js:85
 85: fFactory({}); // Error
     ^^^^^^^^^^^^ function call
 83: class F extends React.Component<{children: Array<number>}, void> {}
                                     ^^^^^^^^^^^^^^^^^^^^^^^^^ property `children`. Property not found in
 85: fFactory({}); // Error
              ^^ props of React element

Error: create_factory.js:86
 86: fFactory({}, 1); // Error
     ^^^^^^^^^^^^^^^ React element. This type is incompatible with
 83: class F extends React.Component<{children: Array<number>}, void> {}
                                     ^^^^^^^^^^^^^^^^^^^^^^^^^ object type
  Property `children` is incompatible:
     86: fFactory({}, 1); // Error
                      ^ number. This type is incompatible with
     83: class F extends React.Component<{children: Array<number>}, void> {}
                                                    ^^^^^^^^^^^^^ array type

Error: create_factory.js:90
 90: fFactory({}, [1, 2], [3, 4]); // Error
     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^ function call
 90: fFactory({}, [1, 2], [3, 4]); // Error
                  ^^^^^^ array literal. This type is incompatible with
 83: class F extends React.Component<{children: Array<number>}, void> {}
                                                      ^^^^^^ number

Error: create_factory.js:90
 90: fFactory({}, [1, 2], [3, 4]); // Error
     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^ function call
 90: fFactory({}, [1, 2], [3, 4]); // Error
                          ^^^^^^ array literal. This type is incompatible with
 83: class F extends React.Component<{children: Array<number>}, void> {}
                                                      ^^^^^^ number

Error: create_factory.js:91
 91: fFactory({}, ...[]); // Error
     ^^^^^^^^^^^^^^^^^^^ function call
 83: class F extends React.Component<{children: Array<number>}, void> {}
                                     ^^^^^^^^^^^^^^^^^^^^^^^^^ property `children`. Property not found in
 91: fFactory({}, ...[]); // Error
              ^^ props of React element

Error: create_factory.js:92
 92: fFactory({}, ...[1]); // Error
     ^^^^^^^^^^^^^^^^^^^^ React element. This type is incompatible with
 83: class F extends React.Component<{children: Array<number>}, void> {}
                                     ^^^^^^^^^^^^^^^^^^^^^^^^^ object type
  Property `children` is incompatible:
     92: fFactory({}, ...[1]); // Error
                          ^ number. This type is incompatible with
     83: class F extends React.Component<{children: Array<number>}, void> {}
                                                    ^^^^^^^^^^^^^ array type

Error: create_factory.js:94
 94: fFactory({}, ...(any: Array<number>)); // Error
     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ React element. This type is incompatible with
 83: class F extends React.Component<{children: Array<number>}, void> {}
                                     ^^^^^^^^^^^^^^^^^^^^^^^^^ object type
  Property `children` is incompatible:
     83: class F extends React.Component<{children: Array<number>}, void> {}
                                                          ^^^^^^ number. This type is incompatible with
     83: class F extends React.Component<{children: Array<number>}, void> {}
                                                    ^^^^^^^^^^^^^ array type

Error: create_factory.js:94
 94: fFactory({}, ...(any: Array<number>)); // Error
     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ React element. This type is incompatible with
 83: class F extends React.Component<{children: Array<number>}, void> {}
                                     ^^^^^^^^^^^^^^^^^^^^^^^^^ object type
  Property `children` is incompatible:
     94: fFactory({}, ...(any: Array<number>)); // Error
                               ^^^^^^^^^^^^^ undefined. This type is incompatible with
     83: class F extends React.Component<{children: Array<number>}, void> {}
                                                    ^^^^^^^^^^^^^ array type

Error: create_factory.js:94
 94: fFactory({}, ...(any: Array<number>)); // Error
     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ React element. This type is incompatible with
 83: class F extends React.Component<{children: Array<number>}, void> {}
                                     ^^^^^^^^^^^^^^^^^^^^^^^^^ object type
  Property `children` is incompatible:
     94: fFactory({}, ...(any: Array<number>)); // Error
                                     ^^^^^^ number. This type is incompatible with
     83: class F extends React.Component<{children: Array<number>}, void> {}
                                                    ^^^^^^^^^^^^^ array type

Error: create_factory.js:95
 95: fFactory({}, 1, ...[]); // Error
     ^^^^^^^^^^^^^^^^^^^^^^ React element. This type is incompatible with
 83: class F extends React.Component<{children: Array<number>}, void> {}
                                     ^^^^^^^^^^^^^^^^^^^^^^^^^ object type
  Property `children` is incompatible:
     95: fFactory({}, 1, ...[]); // Error
                      ^ number. This type is incompatible with
     83: class F extends React.Component<{children: Array<number>}, void> {}
                                                    ^^^^^^^^^^^^^ array type

Error: create_factory.js:97
 97: fFactory({}, 1, ...(any: Array<number>)); // Error
     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ React element. This type is incompatible with
 83: class F extends React.Component<{children: Array<number>}, void> {}
                                     ^^^^^^^^^^^^^^^^^^^^^^^^^ object type
  Property `children` is incompatible:
     97: fFactory({}, 1, ...(any: Array<number>)); // Error
                      ^ number. This type is incompatible with
     83: class F extends React.Component<{children: Array<number>}, void> {}
                                                    ^^^^^^^^^^^^^ array type

Error: create_factory.js:101
101: gFactory({}); // Error
     ^^^^^^^^^^^^ function call
 99: class G extends React.Component<{children: number | Array<number>}, void> {}
                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ property `children`. Property not found in
101: gFactory({}); // Error
              ^^ props of React element

Error: create_factory.js:106
106: gFactory({}, [1, 2], [3, 4]); // Error
     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^ function call
106: gFactory({}, [1, 2], [3, 4]); // Error
                  ^^^^^^ array literal. This type is incompatible with
 99: class G extends React.Component<{children: number | Array<number>}, void> {}
                                                               ^^^^^^ number

Error: create_factory.js:106
106: gFactory({}, [1, 2], [3, 4]); // Error
     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^ function call
106: gFactory({}, [1, 2], [3, 4]); // Error
                          ^^^^^^ array literal. This type is incompatible with
 99: class G extends React.Component<{children: number | Array<number>}, void> {}
                                                               ^^^^^^ number

Error: create_factory.js:107
107: gFactory({}, ...[]); // Error
     ^^^^^^^^^^^^^^^^^^^ function call
 99: class G extends React.Component<{children: number | Array<number>}, void> {}
                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ property `children`. Property not found in
107: gFactory({}, ...[]); // Error
              ^^ props of React element

Error: create_factory.js:110
110: gFactory({}, ...(any: Array<number>)); // Error
     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ function call
110: gFactory({}, ...(any: Array<number>)); // Error
                           ^^^^^^^^^^^^^ undefined. This type is incompatible with
 99: class G extends React.Component<{children: number | Array<number>}, void> {}
                                                ^^^^^^^^^^^^^^^^^^^^^^ union: number | array type
  Member 1:
   99: class G extends React.Component<{children: number | Array<number>}, void> {}
                                                  ^^^^^^ number
  Error:
  110: gFactory({}, ...(any: Array<number>)); // Error
                             ^^^^^^^^^^^^^ undefined. This type is incompatible with
   99: class G extends React.Component<{children: number | Array<number>}, void> {}
                                                  ^^^^^^ number
  Member 2:
   99: class G extends React.Component<{children: number | Array<number>}, void> {}
                                                           ^^^^^^^^^^^^^ array type
  Error:
  110: gFactory({}, ...(any: Array<number>)); // Error
                             ^^^^^^^^^^^^^ undefined. This type is incompatible with
   99: class G extends React.Component<{children: number | Array<number>}, void> {}
                                                           ^^^^^^^^^^^^^ array type

Error: create_factory.js:118
118: hFactory({}); // Error
     ^^^^^^^^^^^^ function call
116: class H extends React.Component<{children: NumberArrayRecursive}, void> {}
                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ property `children`. Property not found in
118: hFactory({}); // Error
              ^^ props of React element

Error: create_factory.js:124
124: hFactory({}, ...[]); // Error
     ^^^^^^^^^^^^^^^^^^^ function call
116: class H extends React.Component<{children: NumberArrayRecursive}, void> {}
                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ property `children`. Property not found in
124: hFactory({}, ...[]); // Error
              ^^ props of React element

Error: create_factory.js:127
127: hFactory({}, ...(any: Array<number>)); // Error
     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ function call
127: hFactory({}, ...(any: Array<number>)); // Error
                           ^^^^^^^^^^^^^ undefined. This type is incompatible with
116: class H extends React.Component<{children: NumberArrayRecursive}, void> {}
                                                ^^^^^^^^^^^^^^^^^^^^ union: number | array type
  Member 1:
  115: type NumberArrayRecursive = number | Array<NumberArrayRecursive>;
                                   ^^^^^^ number
  Error:
  127: hFactory({}, ...(any: Array<number>)); // Error
                             ^^^^^^^^^^^^^ undefined. This type is incompatible with
  115: type NumberArrayRecursive = number | Array<NumberArrayRecursive>;
                                   ^^^^^^ number
  Member 2:
  115: type NumberArrayRecursive = number | Array<NumberArrayRecursive>;
                                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^ array type
  Error:
  127: hFactory({}, ...(any: Array<number>)); // Error
                             ^^^^^^^^^^^^^ undefined. This type is incompatible with
  115: type NumberArrayRecursive = number | Array<NumberArrayRecursive>;
                                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^ array type

Error: create_factory.js:136
136: iFactory({}, null); // Error
     ^^^^^^^^^^^^^^^^^^ React element. This type is incompatible with
132: class I extends React.Component<{children?: number}, void> {}
                                     ^^^^^^^^^^^^^^^^^^^ object type
  Property `children` is incompatible:
    136: iFactory({}, null); // Error
                      ^^^^ null. This type is incompatible with
    132: class I extends React.Component<{children?: number}, void> {}
                                                     ^^^^^^ number

Error: create_factory.js:138
138: iFactory({}, 1, 2); // Error
     ^^^^^^^^^^^^^^^^^^ React element. This type is incompatible with
132: class I extends React.Component<{children?: number}, void> {}
                                     ^^^^^^^^^^^^^^^^^^^ object type
  Property `children` is incompatible:
    138: iFactory({}, 1, 2); // Error
         ^^^^^^^^^^^^^^^^^^ React children array. This type is incompatible with
    132: class I extends React.Component<{children?: number}, void> {}
                                                     ^^^^^^ number

Error: create_factory.js:141
141: iFactory({}, ...[1, 2]); // Error
     ^^^^^^^^^^^^^^^^^^^^^^^ React element. This type is incompatible with
132: class I extends React.Component<{children?: number}, void> {}
                                     ^^^^^^^^^^^^^^^^^^^ object type
  Property `children` is incompatible:
    141: iFactory({}, ...[1, 2]); // Error
         ^^^^^^^^^^^^^^^^^^^^^^^ React children array. This type is incompatible with
    132: class I extends React.Component<{children?: number}, void> {}
                                                     ^^^^^^ number

Error: create_factory.js:142
142: iFactory({}, ...(any: Array<number>)); // Error
     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ React element. This type is incompatible with
132: class I extends React.Component<{children?: number}, void> {}
                                     ^^^^^^^^^^^^^^^^^^^ object type
  Property `children` is incompatible:
    142: iFactory({}, ...(any: Array<number>)); // Error
                               ^^^^^^^^^^^^^ React children array, undefined, or array. This type is incompatible with
    132: class I extends React.Component<{children?: number}, void> {}
                                                     ^^^^^^ number

Error: create_factory.js:144
144: iFactory({}, 1, ...[2]); // Error
     ^^^^^^^^^^^^^^^^^^^^^^^ React element. This type is incompatible with
132: class I extends React.Component<{children?: number}, void> {}
                                     ^^^^^^^^^^^^^^^^^^^ object type
  Property `children` is incompatible:
    144: iFactory({}, 1, ...[2]); // Error
         ^^^^^^^^^^^^^^^^^^^^^^^ React children array. This type is incompatible with
    132: class I extends React.Component<{children?: number}, void> {}
                                                     ^^^^^^ number

Error: create_factory.js:145
145: iFactory({}, 1, ...(any: Array<number>)); // Error
     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ React element. This type is incompatible with
132: class I extends React.Component<{children?: number}, void> {}
                                     ^^^^^^^^^^^^^^^^^^^ object type
  Property `children` is incompatible:
    145: iFactory({}, 1, ...(any: Array<number>)); // Error
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ React children array or number. This type is incompatible with
    132: class I extends React.Component<{children?: number}, void> {}
                                                     ^^^^^^ number

Error: create_factory.js:149
149: jFactory({}); // Error
     ^^^^^^^^^^^^ function call
147: class J extends React.Component<{children: ?number}, void> {}
                                     ^^^^^^^^^^^^^^^^^^^ property `children`. Property not found in
149: jFactory({}); // Error
              ^^ props of React element

Error: create_factory.js:153
153: jFactory({}, 1, 2); // Error
     ^^^^^^^^^^^^^^^^^^ React element. This type is incompatible with
147: class J extends React.Component<{children: ?number}, void> {}
                                     ^^^^^^^^^^^^^^^^^^^ object type
  Property `children` is incompatible:
    153: jFactory({}, 1, 2); // Error
         ^^^^^^^^^^^^^^^^^^ React children array. This type is incompatible with
    147: class J extends React.Component<{children: ?number}, void> {}
                                                     ^^^^^^ number

Error: create_factory.js:154
154: jFactory({}, ...[]); // Error
     ^^^^^^^^^^^^^^^^^^^ function call
147: class J extends React.Component<{children: ?number}, void> {}
                                     ^^^^^^^^^^^^^^^^^^^ property `children`. Property not found in
154: jFactory({}, ...[]); // Error
              ^^ props of React element

Error: create_factory.js:156
156: jFactory({}, ...[1, 2]); // Error
     ^^^^^^^^^^^^^^^^^^^^^^^ React element. This type is incompatible with
147: class J extends React.Component<{children: ?number}, void> {}
                                     ^^^^^^^^^^^^^^^^^^^ object type
  Property `children` is incompatible:
    156: jFactory({}, ...[1, 2]); // Error
         ^^^^^^^^^^^^^^^^^^^^^^^ React children array. This type is incompatible with
    147: class J extends React.Component<{children: ?number}, void> {}
                                                     ^^^^^^ number

Error: create_factory.js:157
157: jFactory({}, ...(any: Array<number>)); // Error
     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ React element. This type is incompatible with
147: class J extends React.Component<{children: ?number}, void> {}
                                     ^^^^^^^^^^^^^^^^^^^ object type
  Property `children` is incompatible:
    157: jFactory({}, ...(any: Array<number>)); // Error
                               ^^^^^^^^^^^^^ React children array, undefined, or array. This type is incompatible with
    147: class J extends React.Component<{children: ?number}, void> {}
                                                     ^^^^^^ number

Error: create_factory.js:159
159: jFactory({}, 1, ...[2]); // Error
     ^^^^^^^^^^^^^^^^^^^^^^^ React element. This type is incompatible with
147: class J extends React.Component<{children: ?number}, void> {}
                                     ^^^^^^^^^^^^^^^^^^^ object type
  Property `children` is incompatible:
    159: jFactory({}, 1, ...[2]); // Error
         ^^^^^^^^^^^^^^^^^^^^^^^ React children array. This type is incompatible with
    147: class J extends React.Component<{children: ?number}, void> {}
                                                     ^^^^^^ number

Error: create_factory.js:160
160: jFactory({}, 1, ...(any: Array<number>)); // Error
     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ React element. This type is incompatible with
147: class J extends React.Component<{children: ?number}, void> {}
                                     ^^^^^^^^^^^^^^^^^^^ object type
  Property `children` is incompatible:
    160: jFactory({}, 1, ...(any: Array<number>)); // Error
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ React children array or number. This type is incompatible with
    147: class J extends React.Component<{children: ?number}, void> {}
                                                     ^^^^^^ number

Error: create_factory.js:167
167: kFactory({}, '42'); // Error
     ^^^^^^^^^^^^^^^^^^ React element. This type is incompatible with
162: class K extends React.Component<{children: number}, void> {}
                                     ^^^^^^^^^^^^^^^^^^ object type
  Property `children` is incompatible:
    167: kFactory({}, '42'); // Error
                      ^^^^ string. This type is incompatible with
    162: class K extends React.Component<{children: number}, void> {}
                                                    ^^^^^^ number

Error: create_factory.js:168
168: kFactory({children: '42'}); // Error
              ^^^^^^^^^^^^^^^^ props of React element. This type is incompatible with
162: class K extends React.Component<{children: number}, void> {}
                                     ^^^^^^^^^^^^^^^^^^ object type
  Property `children` is incompatible:
    168: kFactory({children: '42'}); // Error
                             ^^^^ string. This type is incompatible with
    162: class K extends React.Component<{children: number}, void> {}
                                                    ^^^^^^ number

Error: create_factory.js:169
169: kFactory({children: '42'}, 42); // Error
     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ React element. This type is incompatible with
162: class K extends React.Component<{children: number}, void> {}
                                     ^^^^^^^^^^^^^^^^^^ object type
  Property `children` is incompatible:
    169: kFactory({children: '42'}, 42); // Error
                             ^^^^ string. This type is incompatible with
    162: class K extends React.Component<{children: number}, void> {}
                                                    ^^^^^^ number

Error: create_factory.js:171
171: kFactory({children: '42'}, '42'); // Error
     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ React element. This type is incompatible with
162: class K extends React.Component<{children: number}, void> {}
                                     ^^^^^^^^^^^^^^^^^^ object type
  Property `children` is incompatible:
    171: kFactory({children: '42'}, '42'); // Error
                             ^^^^ string. This type is incompatible with
    162: class K extends React.Component<{children: number}, void> {}
                                                    ^^^^^^ number

Error: create_factory.js:185
185: lFactory({}, 1); // Error
     ^^^^^^^^^^^^^^^ function call
                                     v
173: class L extends React.Component<{
174:   foo: number,
175:   bar: number,
176:   children: number,
177: }, void> {
     ^ property `foo`. Property not found in
185: lFactory({}, 1); // Error
     ^^^^^^^^^^^^^^^ React element

Error: create_factory.js:186
186: lFactory({children: 1}); // Error
     ^^^^^^^^^^^^^^^^^^^^^^^ function call
                                     v
173: class L extends React.Component<{
174:   foo: number,
175:   bar: number,
176:   children: number,
177: }, void> {
     ^ property `foo`. Property not found in
186: lFactory({children: 1}); // Error
              ^^^^^^^^^^^^^ props of React element

Error: create_factory.js:187
187: lFactory({bar: 1}, 2); // Error
     ^^^^^^^^^^^^^^^^^^^^^ function call
                                     v
173: class L extends React.Component<{
174:   foo: number,
175:   bar: number,
176:   children: number,
177: }, void> {
     ^ property `foo`. Property not found in
187: lFactory({bar: 1}, 2); // Error
     ^^^^^^^^^^^^^^^^^^^^^ React element

Error: create_factory.js:188
188: lFactory({bar: 1, children: 2}); // Error
     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ function call
                                     v
173: class L extends React.Component<{
174:   foo: number,
175:   bar: number,
176:   children: number,
177: }, void> {
     ^ property `foo`. Property not found in
188: lFactory({bar: 1, children: 2}); // Error
              ^^^^^^^^^^^^^^^^^^^^^ props of React element

Error: create_factory.js:189
189: lFactory({foo: '1', bar: 2}, 3); // Error
     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ React element. This type is incompatible with
                                     v
173: class L extends React.Component<{
174:   foo: number,
175:   bar: number,
176:   children: number,
177: }, void> {
     ^ object type
  Property `foo` is incompatible:
    189: lFactory({foo: '1', bar: 2}, 3); // Error
                        ^^^ string. This type is incompatible with
    174:   foo: number,
                ^^^^^^ number

Error: create_factory.js:190
190: lFactory({foo: '1', bar: 2, children: 3}); // Error
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ props of React element. This type is incompatible with
                                     v
173: class L extends React.Component<{
174:   foo: number,
175:   bar: number,
176:   children: number,
177: }, void> {
     ^ object type
  Property `foo` is incompatible:
    190: lFactory({foo: '1', bar: 2, children: 3}); // Error
                        ^^^ string. This type is incompatible with
    174:   foo: number,
                ^^^^^^ number

Error: create_factory.js:191
191: lFactory({foo: 1, bar: '2'}, 3); // Error
     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ React element. This type is incompatible with
                                     v
173: class L extends React.Component<{
174:   foo: number,
175:   bar: number,
176:   children: number,
177: }, void> {
     ^ object type
  Property `bar` is incompatible:
    191: lFactory({foo: 1, bar: '2'}, 3); // Error
                                ^^^ string. This type is incompatible with
    175:   bar: number,
                ^^^^^^ number

Error: create_factory.js:192
192: lFactory({foo: 1, bar: '2', children: 3}); // Error
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ props of React element. This type is incompatible with
                                     v
173: class L extends React.Component<{
174:   foo: number,
175:   bar: number,
176:   children: number,
177: }, void> {
     ^ object type
  Property `bar` is incompatible:
    192: lFactory({foo: 1, bar: '2', children: 3}); // Error
                                ^^^ string. This type is incompatible with
    175:   bar: number,
                ^^^^^^ number

Error: create_factory.js:193
193: lFactory({foo: 1, bar: 2}, '3'); // Error
     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ React element. This type is incompatible with
                                     v
173: class L extends React.Component<{
174:   foo: number,
175:   bar: number,
176:   children: number,
177: }, void> {
     ^ object type
  Property `children` is incompatible:
    193: lFactory({foo: 1, bar: 2}, '3'); // Error
                                    ^^^ string. This type is incompatible with
    176:   children: number,
                     ^^^^^^ number

Error: create_factory.js:194
194: lFactory({foo: 1, bar: 2, children: '3'}); // Error
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ props of React element. This type is incompatible with
                                     v
173: class L extends React.Component<{
174:   foo: number,
175:   bar: number,
176:   children: number,
177: }, void> {
     ^ object type
  Property `children` is incompatible:
    194: lFactory({foo: 1, bar: 2, children: '3'}); // Error
                                             ^^^ string. This type is incompatible with
    176:   children: number,
                     ^^^^^^ number

Error: create_factory.js:200
200: (mFactory().type: typeof N); // Error
      ^^^^^^^^^^^^^^^ M. This type is incompatible with
197: class N extends React.Component<{}> {}
           ^ N


Found 166 errors
