dro.js:2:9 = (method) sort(compareFn?: (a: number, b: number) => number): Array<number>
dro.js:2:9,2:12
lazy_ref.js:14:9 = const x: {
  default: component(
    ...{...empty, readonly ref?: RefSetter<{moo(x: string): void}>}
  ) renders null
}

'RefSetter' defined at (lib) react.js:1365:9

lazy_ref.js:14:9,14:9
lazy_ref.js:19:9 = const x: Promise<{readonly default: (x: Props) => MixedElement}>

'MixedElement' defined at (lib) react.js:430:22
'Promise' defined at (lib) core.js:2298:14
'Props' defined at exports-component.js:5:5

lazy_ref.js:19:9,19:9
react_component.js:3:9 = module "react"

'react' defined at react_component.js:3:14

react_component.js:3:7,3:11
react_component.js:13:33 = 
 `Component` lets you define a React component as a JavaScript class.

 We recommend defining components as functions instead of classes.
 [See how to migrate](https://react.dev/reference/react/PureComponent#alternatives).

**@see**  https://react.dev/reference/react/Component
class Component<Props, State = void>

'Component' defined at (lib) react.js:972:18

react_component.js:13:29,13:37
react_component.js:18:17 = (property) state: State

'State' defined at react_component.js:9:5

react_component.js:18:14,18:18
react_component.js:31:7 = 
 `<Fragment>`, often used via `<>...</>` syntax,
 lets you group elements without a wrapper node.

**@see**  https://react.dev/reference/react/Fragment
component Fragment<Renders extends React$Node = void>(children?: Renders) renders Renders

'Fragment' defined at (lib) react.js:1077:4
'React$Node' defined at (lib) react.js:15:13

react_component.js:31:7,31:14
react_component.js:32:15 = const react_ct: component(...number)
react_component.js:32:15,32:22
react_component.js:32:31 = (unknown)
react.js:4:7
Flags:

 `createElement` lets you create a React element.
 It serves as an alternative to writing JSX.

**@see**  https://react.dev/reference/react/createElement
(property) React.createElement: React$CreateElement

'React$CreateElement' defined at (lib) react.js:322:20

react.js:4:7,4:19

react_abstract_component.js:3:15 = (parameter) x: component(...any)
react_abstract_component.js:3:15,3:15
react_abstract_component.js:8:15 = type RendersFoo = renders Foo

'Foo' defined at react_abstract_component.js:7:18
'RendersFoo' defined at react_abstract_component.js:8:5

react_abstract_component.js:8:6,8:15
