lazy_ref.js:14:9 = {|default: React$AbstractComponent<empty, {|moo(x: string): void|}>|}
lazy_ref.js:14:9,14:9
lazy_ref.js:19:9 = Promise<{|+default: (x: Props) => Element<(x: Props) => Node>|}>
lazy_ref.js:19:9,19:9
react_component.js:3:9 = module "react"
react_component.js:3:7,3:11
react_component.js:13:33 = class React$Component<Props, State = void>
react_component.js:13:29,13:37
react_component.js:18:17 = State
react_component.js:18:14,18:18
react_component.js:31:7 = {
  "expanded_type":{
    "kind":"Generic",
    "type":{
      "provenance":{"kind":"Library (Remote)","loc":"[LIB] react.js:214:14-31"},
      "name":"React$FragmentType"
    },
    "generic_kind":"type alias"
  },
  "type":"React$FragmentType",
  "reasons":[],
  "loc":{
    "source":"react_component.js",
    "type":"SourceFile",
    "start":{"line":31,"column":7,"offset":454},
    "end":{"line":31,"column":14,"offset":462}
  },
  "path":"react_component.js",
  "line":31,
  "endline":31,
  "start":7,
  "end":14
}
react_component.js:32:13 = {
  "expanded_type":{
    "kind":"Generic",
    "typeArgs":[{"kind":"Num"}],
    "type":{
      "provenance":{"kind":"Library (Remote)","loc":"[LIB] react.js:248:23-35"},
      "name":"ComponentType"
    },
    "generic_kind":"type alias"
  },
  "type":"ComponentType<number>",
  "reasons":[],
  "loc":{
    "source":"react_component.js",
    "type":"SourceFile",
    "start":{"line":32,"column":13,"offset":475},
    "end":{"line":32,"column":20,"offset":483}
  },
  "path":"react_component.js",
  "line":32,
  "endline":32,
  "start":13,
  "end":20
}
react_component.js:32:29 = {
  "expanded_type":{
    "kind":"TypeAlias",
    "name":{
      "provenance":{"kind":"Library (Remote)","loc":"[LIB] react.js:248:23-35"},
      "name":"ComponentType"
    },
    "typeParams":[{"name":"P","bound":null,"polarity":"Negative"}],
    "body":{
      "kind":"Generic",
      "typeArgs":[{"kind":"Bound","bound":"P"}],
      "type":{
        "provenance":{"kind":"Library (Remote)","loc":"[LIB] react.js:151:14-32"},
        "name":"React$ComponentType"
      },
      "generic_kind":"type alias"
    }
  },
  "type":"type ComponentType<-P> = React$ComponentType<P>",
  "reasons":[],
  "loc":{
    "source":"react_component.js",
    "type":"SourceFile",
    "start":{"line":32,"column":29,"offset":491},
    "end":{"line":32,"column":41,"offset":504}
  },
  "path":"react_component.js",
  "line":32,
  "endline":32,
  "start":29,
  "end":41
}
react.js:4:7
Flags:
React$CreateElement
react.js:4:7,4:19

react_abstract_component.js:3:15 = React$AbstractComponent<any, any>
react_abstract_component.js:3:15,3:15
