Error -------------------------------------------------------------- test.js:5:5

Sketchy null check on boolean [1] which is potentially false. Perhaps you meant
to check for null or undefined [2]? (`sketchy-null-bool`)


Error -------------------------------------------------------------- test.js:5:5

Sketchy null check on mixed [1] which is potentially false. Perhaps you meant to
check for null or undefined [1]? (`sketchy-null-mixed`)


Error -------------------------------------------------------------- test.js:5:5

Sketchy null check on number [1] which is potentially 0. Perhaps you meant to
check for null or undefined [2]? (`sketchy-null-number`)


Error -------------------------------------------------------------- test.js:5:5

Sketchy null check on string [1] which is potentially an empty string. Perhaps
you meant to check for null or undefined [2]? (`sketchy-null-string`)


Error -------------------------------------------------------------- test.js:9:5

Sketchy null check on mixed [1] which is potentially false. Perhaps you meant to
check for null or undefined [1]? (`sketchy-null-mixed`)


Error -------------------------------------------------------------- test.js:9:5

Sketchy null check on number [1] which is potentially 0. Perhaps you meant to
check for null or undefined [2]? (`sketchy-null-number`)


Error -------------------------------------------------------------- test.js:9:5

Sketchy null check on string [1] which is potentially an empty string. Perhaps
you meant to check for null or undefined [2]? (`sketchy-null-string`)


Error ------------------------------------------------------------- test.js:13:5

Sketchy null check on boolean [1] which is potentially false. Perhaps you meant
to check for null or undefined [2]? (`sketchy-null-bool`)


Error ------------------------------------------------------------- test.js:13:5

Sketchy null check on number [1] which is potentially 0. Perhaps you meant to
check for null or undefined [2]? (`sketchy-null-number`)


Error ------------------------------------------------------------- test.js:13:5

Sketchy null check on string [1] which is potentially an empty string. Perhaps
you meant to check for null or undefined [2]? (`sketchy-null-string`)


Error ------------------------------------------------------------- test.js:17:5

Sketchy null check on boolean [1] which is potentially false. Perhaps you meant
to check for null or undefined [2]? (`sketchy-null-bool`)


Error ------------------------------------------------------------- test.js:17:5

Sketchy null check on mixed [1] which is potentially false. Perhaps you meant to
check for null or undefined [1]? (`sketchy-null-mixed`)


Error ------------------------------------------------------------- test.js:17:5

Sketchy null check on string [1] which is potentially an empty string. Perhaps
you meant to check for null or undefined [2]? (`sketchy-null-string`)


Error ------------------------------------------------------------- test.js:21:5

Sketchy null check on boolean [1] which is potentially false. Perhaps you meant
to check for null or undefined [2]? (`sketchy-null-bool`)


Error ------------------------------------------------------------- test.js:21:5

Sketchy null check on mixed [1] which is potentially false. Perhaps you meant to
check for null or undefined [1]? (`sketchy-null-mixed`)


Error ------------------------------------------------------------- test.js:21:5

Sketchy null check on number [1] which is potentially 0. Perhaps you meant to
check for null or undefined [2]? (`sketchy-null-number`)


Error ------------------------------------------------------------- test.js:27:5

Sketchy null check on boolean [1] which is potentially false. Perhaps you meant
to check for null or undefined [2]? (`sketchy-null-bool`)


Error ------------------------------------------------------------- test.js:31:5

Sketchy null check on mixed [1] which is potentially false. Perhaps you meant to
check for null or undefined [1]? (`sketchy-null-mixed`)


Error ------------------------------------------------------------- test.js:35:5

Sketchy null check on number [1] which is potentially 0. Perhaps you meant to
check for null or undefined [2]? (`sketchy-null-number`)


Error ------------------------------------------------------------- test.js:39:5

Sketchy null check on string [1] which is potentially an empty string. Perhaps
you meant to check for null or undefined [2]? (`sketchy-null-string`)



Found 20 errors
